### ISSUE TITLE
clarity-icons does not build in web pack

### ISSUE THREAD

**Issue by tarquinrex** [vmware/clarity#1398] opened 2017-08-31 11:56 UTC
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I expect clarity-icons to get bundled with webpack and then run in angular SPA application.
### Actual behavior

When running webpack script to bundle application I get message:

WARNING in ./node_modules/clarity-icons/clarity-icons.min.js
1:3046-3053 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
WARNING in ./node_modules/clarity-icons/clarity-icons.min.js
1:3110-3117 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

and when I try running the application in Chrome I get exception in console:

webpack-internal:///146:1 Uncaught Error: Cannot find module "."
    at webpackMissingModule (webpack-internal:///146:1)
    at eval (webpack-internal:///146:1)
    at Object.eval (webpack-internal:///146:1)
    at eval (webpack-internal:///146:5)
    at Object.<anonymous> (app.bundle.js:932)
    at __webpack_require__ (polyfills.bundle.js:55)
    at eval (webpack-internal:///90:29)
    at Object.<anonymous> (app.bundle.js:587)
    at __webpack_require__ (polyfills.bundle.js:55)
    at webpackJsonpCallback (polyfills.bundle.js:26)

Section of package json to show versions:

    "@angular/animations": "^4.3.5",
    "@angular/common": "~4.3.5",
    "@angular/compiler": "~4.3.5",
    "@angular/compiler-cli": "~4.3.5",
    "@angular/core": "~4.3.5",
    "@angular/forms": "~4.3.5",
    "@angular/http": "~4.3.5",
    "@angular/platform-browser": "~4.3.5",
    "@angular/platform-browser-dynamic": "~4.3.5",
    "@angular/platform-server": "~4.3.5",
    "@angular/router": "~4.3.5",
    "@angular/upgrade": "~4.3.5",
    "@webcomponents/custom-elements": "^1.0.0",
    "clarity-icons": "^0.10.2",
    "clarity-ui": "^0.10.2",
    "clarity-angular": "^0.10.2",

Vendor.js file to show sequence of import statements that will get bundled by webpack:

import '@webcomponents/custom-elements/custom-elements.min';
import 'clarity-ui/clarity-ui.min.css';
import 'clarity-icons/clarity-icons.min';
import 'clarity-icons/clarity-icons.min.css';

When running in IE it enters debugger in webpack-internal js

var exports = module.exports = function (iterable, entries, fn, that, ITERATOR) {
  var iterFn = ITERATOR ? function () { return iterable; } : getIterFn(iterable);
  var f = ctx(fn, that, entries ? 2 : 1);
  var index = 0;
  var length, step, iterator, result;

{COMMENT: breaks here as iterFn is undefined)

  **# if (typeof iterFn != 'function')** throw TypeError(iterable + ' is not iterable!');

{END COMMENT}
}
  // fast case for arrays with default iterator
  if (isArrayIter(iterFn)) for (length = toLength(iterable.length); length > index; index++) {
    result = entries ? f(anObject(step = iterable[index])[0], step[1]) : f(iterable[index]);
    if (result === BREAK || result === RETURN) return result;
  } else for (iterator = iterFn.call(iterable); !(step = iterator.next()).done;) {
    result = call(iterator, f, step.value, entries);
    if (result === BREAK || result === RETURN) return result;
  }

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome and IE (IE breaks at line)

**Comment by mathisscott** [comment] 2017-08-31 13:15
If you're bringing in `"@webcomponents/custom-elements"` through package.json, how is `import '/custom-elements.min';` expected to work?

Do you have a copy of `custom-elements.min.js` in the root of your project? And are you copying that down into your `/dist` folder when you build?

**Comment by tarquinrex** [comment] 2017-09-01 06:19
The entry point in my webpack configuration is a file that contains this:

import '../polyfills';
import '../vendor';

and then then vendor file contains this:

import '@webcomponents/custom-elements/custom-elements.min';
import 'clarity-ui/clarity-ui.min.css';
import 'clarity-icons/clarity-icons.min';
import 'clarity-icons/clarity-icons.min.css';

so webpack builds them into the bundle as part of the dependency tree. I can see its doing that when I open the bundle file. 

There are two problems:

One is when webpack tries to resolve dependencies in clarity-icons-min and I get this error during the bundle process:

WARNING in ./node_modules/clarity-icons/clarity-icons.min.js
1:3046-3053 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

The syntax in the file is not compatible with how webpack does its stuff, I think you can use the column number from the error message to find the section although not easy to understand in a minified file:

In square braces ->

=[[[[[require.resolve]]]]]&&"undefined"!=typeof process&&process.platform&&

and then problem number two is at runtime when I get the webpack cannot find module error as posted above.

I'm not sure if the two are related but I would think so?

Great project and thanks for help.

**Comment by mathisscott** [comment] 2017-09-01 12:34
`clarity-icons.min.js` isn't a module AFAIK. So maybe use `import "clarity-icons"` or load it as a static file?

**Comment by mathisscott** [comment] 2017-09-01 12:34
@Shijir 
Could you see if you can reproduce this?

**Comment by mathisscott** [comment] 2017-09-01 12:38
Additionally, @tarquinrex, you may need to do something like what is described here with `imports-loader`...

https://webpack.github.io/docs/shimming-modules.html

**Comment by Shijir** [comment] 2017-09-01 16:54
As @mathisscott mentioned, using `import "clarity-icons"` should work. So your vendor.js would look like: 
```
import '@webcomponents/custom-elements'; // polyfill for Custom Elements

import 'clarity-icons'; // Clarity Icons module
import 'clarity-icons/clarity-icons.min.css'; // Clarity Icons style

import 'clarity-ui/clarity-ui.min.css'; // Clarity UI style
```

This `import 'clarity-icons';` will get you the raw clarity-icons module.

Your approach with `import 'clarity-icons/clarity-icons.min';` should have worked, but I think webpack is not being able to read javascript files created with our bundling tool, `systemjs-builder`. I thought the problem was with the `systemjs-builder` tool, but the bundled js was working in all environments except Webpack. Also, I bundled and published `clarity-icons.min.js` file using Webpack builder instead of `systemjs-builder`, and this time Webpack accepts and reads the file with no erroes.

You can check there open issues related to Webpack not being able to statically analyze `require` function in third party libraries and throws warnings such as `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`. For example: https://github.com/webpack/webpack/issues/4290

**Comment by tarquinrex** [comment] 2017-09-01 18:53
You are 100% correct, when I replace 
import 'clarity-icons/clarity-icons.min';
 
with 

import 'clarity-icons'; 

it gets through the webpack bundling. 

But now have another problem in that when the web page is loaded I get:

webpack-internal:///89:1738 Uncaught Error: Template parse errors:
'clr-icon' is not a known element:
1. If 'clr-icon' is an Angular component, then verify that it is part of this module.
2. If 'clr-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  <clr-dropdown>
    <button class="nav-icon" clrDropdownTrigger>
      [ERROR ->]<clr-icon shape="user"></clr-icon>
      <clr-icon shape="caret down"></clr-icon>
    </button>
"): ng:///SharedModule/HeaderComponent.html@10:6

I'm following clarity samples and trying to insert dropdown into header area, my header template looks like this:

<div class="branding">
  <a href="..." class="nav-link">
    <img src="../../../../images/paw_print_white_35.png" width="30" height="30"/>
    <div style="width:10px"></div>
    <span class="title">TrackPlus</span>
  </a>
</div>
<div class="header-actions">
  <clr-dropdown>
    <button class="nav-icon" clrDropdownTrigger>
      <clr-icon shape="user"></clr-icon>
      <clr-icon shape="caret down"></clr-icon>
    </button>
    <clr-dropdown-menu *clrIfOpen clrPosition="bottom-right">
      <a href="..." clrDropdownItem>Profile</a>
      <a href="..." clrDropdownItem>Log out</a>
    </clr-dropdown-menu>
  </clr-dropdown>
  <clr-dropdown>
    <button class="nav-icon" clrDropdownTrigger>
      <clr-icon shape="cog"></clr-icon>
      <clr-icon shape="caret down"></clr-icon>
    </button>
    <clr-dropdown-menu *clrIfOpen clrPosition="bottom-right">
      <a href="..." clrDropdownItem>Settings</a>
     </clr-dropdown-menu>
  </clr-dropdown>
</div>

I have imported icons files as mentioned above and also imported clarity angular in app.module:

import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ClarityModule } from 'clarity-angular';

import { AppComponent } from './app.component';
import { Configuration } from './app.constants';
import { AppRoutes } from './app.routes';
import { HomeComponent } from './home/home.component';
import { SharedModule } from './shared/shared.module';

@NgModule({
    imports: [
      BrowserModule,
      BrowserAnimationsModule,
      ClarityModule.forRoot(),

Is there something Im missing? Do I need to import anything else from icons?
Thanks.

**Comment by Shijir** [comment] 2017-09-01 19:27
@tarquinrex you are receiving an error in `/SharedModule/HeaderComponent.html`, which I assume has its own module looking at the code you posted above. For example, your code includes:

```
import { SharedModule } from './shared/shared.module';
````

And I think you only imported `ClarityIcons` module in your `app.module.ts` which is separate from your `shared.module.ts`. So you need to import it in your shared module as well.

Also, that's an Angular related question now. So I will close this issue as I believe your original question/issue has been solved.

**Closed by Shijir** 2017-09-01 19:27 UTC
Labels: waiting-for-more-info
