### ISSUE TITLE
Sass themes do not work with create-react-app

### ISSUE THREAD

**Issue by marcoamonteiro** [vmware/clarity#6034] opened 2021-06-08 15:25 UTC
## Describe the bug

Clarity css sass imports do not work with create-react-app

## How to reproduce

```
npx create-react-app my-app --template typescript
npm install node-sass --save
npm install @cds/core --save
npm install @cds/react --save

Add these lines to app.scss:
@import '~normalize.css/normalize.css'; // css reset
@import '~@cds/core/global.min'; // clarity global styles
@import '~@cds/core/styles/module.shims.min'; // non-evergreen browser shims
@import '~@cds/city/css/bundles/default.min'; // load base font
@import '~@cds/core/styles/theme.dark.min.css';

npm run build

I see this error:

Creating an optimized production build...
Failed to compile.

./src/App.scss
ParserError: Syntax Error at line: 1, column 120


npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

## Versions

**Clarity project:**

- [ x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ x] v5.x

**Framework:**

- [ ] Angular
- [x ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: React 4.0

**Comment by hippee-lee** [comment] 2021-06-08 18:22
I tried to follow your reproduction steps but was unable to reproduce the issue. 

Here is what I had to do:

1. npx create-react-app my-app --template typescript
2. added ```   "devDependencies": {
    "node-sass": "^6.0.0",
    "sass-loader": "^11.1.1"
  },``` because it seems that create react app has some issues to fix with the underlying webpack config or react-scripts
3. installed
    - npm install node-sass --save
    - npm install @cds/core --save
    - npm install @cds/react --save
4. Added the imports mentioned above
5. Modified App.tsx to use a Clarity alert and the dark theme

As I am unable to reproduce the issue I am going to close this for now. Please feel free to update the reproduction steps or provide a simple reproduction repo that can be used to investigate the issue you are seeing. 

[Here](https://github.com/hippee-lee/cra-test-sass-imports) is a link to the repo of my test.

**Closed as completed by hippee-lee** 2021-06-08 18:22 UTC
Labels: resolution: can't reproduce
