### ISSUE TITLE
clrDgSortOrder and clrDgSortBy server driven not in sync on refresh

### ISSUE THREAD

**Issue by rogerfar** [vmware/clarity#3365] opened 2019-05-17 04:29 UTC
## Describe the bug

If you add [clrDgSortBy] and [(clrDgSortOrder)] on a clr-dg-column when the grid is server driven the clrDgSortOrder isn't updated when refresh is called

## How to reproduce
See stackblitz: https://stackblitz.com/edit/clarity-light-theme-v013-svmfax?file=src%2Fapp%2Fapp.component.ts

1.  Open the console
2.  Click on Field 0 and observe the state on the page, it will show 
```
{ "sort": { "by": "field0", "reverse": false } } 
Sort: [ 1, 0 ]
```
Check the console output, it will show:
```
[0, 0]
```
3.  Click on Field 1 and observe the following state:
```
{ "sort": { "by": "field1", "reverse": false } } 
Sort: [ 0, 1 ]
```
The console output will show:
```
[0, 0]
```
The state in the refresh will always lag 1 behind.

## Expected behavior

When refresh is called the sorted columns should be set correctly on the [(clrDgSortOrder)] property.

## Versions

**App**

* Angular: 7
* Clarity: 1.1.3

**Comment by hippee-lee** [comment] 2019-05-17 17:40
Thanks for providing the stackblitz reproduction. It looks like you were logging the sort array outside of the `setTimeout` function used to approximate an API call. 

https://stackblitz.com/edit/clarity-light-theme-v013-zj9v8f

When I move the log statement inside the setTImeout callback it works as I would expect. 
PLease update if your app is more complicated and the error can be reporduced in a different wayt. Closing for now as invalid.

**Comment by farlock85** [comment] 2019-05-17 17:42
@hippee-lee this is correct and done on purpse. The setTimeout is a workaround but not intended I would think?

**Comment by hippee-lee** [comment] 2019-05-17 18:06
In the original example, sorting state is logged out before the datagrid items have been updated. 

How can we expect it to accurately reflect the new state wrt `[(clrDgSortOrder)]="sort[0]"` which gets updated as part of 2-way binding _after_ the datagrid gets a new state in the `setTimeout`?

**Comment by farlock85** [comment] 2019-05-17 18:10
But shouldn't the sorting state of the column be updated first before it tries to refresh the data? Because the State that gets passed in the refresh event does reflect the change in sorting.

**Comment by hippee-lee** [comment] 2019-05-17 19:37
I'm not sure so I'll re-open this for further investigation. Whats happening here is that the parent (ClrDatagrid) @Output is emitting before the child (ClrDatagridColumn) @Output. 

The timeout is only making it look correct because it delays long enough for sort to update. 
We will need to investigate and see if we can/should change the order of @Output emissions from the datagrid. 

Demonstration of the order for emission: https://stackblitz.com/edit/clarity-light-theme-v013-zj9v8f

**Closed** 2022-05-03 13:45 UTC
Labels: status: needs investigation, component: datagrid
