### ISSUE TITLE
ClrTimeline 4 Angular 11 not working with clrState value as string as depicted in example

### ISSUE THREAD

**Issue by AlicePain** [vmware/clarity#5473] opened 2021-01-21 15:01 UTC
TypeScript error occurs 
error TS2322: Type '"success"' is not assignable to type 'ClrTimelineStepState'.

This error shows in the Terminal window of VS Code. If I comment the below code application compiles, if I then uncomment the code below and save, the timeline shows, but the errors still show, one for each clrState.

`<clr-timeline>
  <clr-timeline-step clrState="success">
    <clr-timeline-step-title><a routerLinkActive="disabled" routerLink="personal-info">Create your account</a></clr-timeline-step-title>
  </clr-timeline-step>
  <clr-timeline-step clrState="current">
    <clr-timeline-step-title><a [routerLink]="['/business-info']">Business details</a></clr-timeline-step-title>
  </clr-timeline-step>
  <clr-timeline-step clrState="not-started">
    <clr-timeline-step-title><a [routerLink]="['/documents']">Documents</a></clr-timeline-step-title>
  </clr-timeline-step>
  <clr-timeline-step clrState="not-started">
    <clr-timeline-step-title><a [routerLink]="['/review']">Review</a></clr-timeline-step-title>
  </clr-timeline-step>
 </clr-timeline>`
 
This is the only code in my app.component.html

Creating a brand new project I get this warning trying to install Clarity
Unable to find compatible package.  Using 'latest'.
Package has unmet peer dependencies. Adding the package may not succeed.

**Comment by AlicePain** [comment] 2021-01-21 19:39
I'm able to successfully reproduce this issue. 
Create an angular 11 application, set strict to yes, and add routing yes.
Add Clarity ng add @clr/angular

create a route
const routes: Routes = [
  { path: '', component: FrameworkComponent }];
  
  in app.component.html add the timeline using angular syntax and set a clrState="success"  You can use the example timeline code above.
  
Serve the project and your browser should show failed to compile with the errors described above.

MORE: I have pinned it down the setting STRICT to yes.

**Comment by AlicePain** [comment] 2021-01-21 20:08
tsconfig.json  The following will fix the errors

 "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": false,
    "strictInputAccessModifiers": true,
    "strictTemplates": false
  }

**Comment by gnomeontherun** [comment] 2021-01-21 23:28
We have an open PR to help with some of these issues, it might address this case. https://github.com/vmware/clarity/pull/5448

**Comment by dorthrithil** [comment] 2021-03-08 12:32
Same issue in Clarity 5.0.3. Can either be fixed by passing a state variable like `errorState = ClrTimelineStepState.ERROR;` to `clrState` or disabling `strictTemplates`.

**Comment by gnomeontherun** [comment] 2021-03-10 19:17
@bdryanovski did you address this case with strict?

**Comment by bdryanovski** [comment] 2021-05-25 13:01
Like @dorthrithil mention above - the correct way of passing is to use the `ClrTimelineStepState` enum to pass the value or disabled `strictTemplate` check.

The issue is that the `ClrTimelineStep` expect to have one of already defined `ClrTimelineStepState` values.
```ts
export class ClrTimelineStep {
   @Input('clrState') state: ClrTimelineStepState = ClrTimelineStepState.NOT_STARTED;
   //...
```

You could import it from the `@clr/angular` package like that and use one of his states.
```ts
import { ClrTimelineStepState } from '@clr/angular';
```

**Closed as completed by bdryanovski** 2021-05-25 13:01 UTC
Labels: type: support, @clr/angular, component: timeline
