### ISSUE TITLE
[Accessibility] On modal close focus doesn't return to element which opens the modal

### ISSUE THREAD

**Issue by Tushar2098** [vmware/clarity#4294] opened 2020-02-19 07:00 UTC
## Describe the bug

Focus doesn't return to element which opens the modal instead focus moves to the `body` element on modal close

## How to reproduce

1.  Go to provided Stackblitz setup [here](https://stackblitz.com/edit/clarity-dialog?file=src%2Fapp%2Fapp.component.html)
2.  Click on "Show Modal" button
3.  Close the modal by tabbing the button
4.  See focus doesn't return to "Show Modal" button. For further verification, see the browser console to know the current active element

## Expected behavior

Focus should move to element which opened the modal in this case "Show Modal" button

## Versions
This issue is also reproducible to the latest clarity version

**Comment by gnomeontherun** [comment] 2020-02-21 17:41
Looks like an issue with the focus trap logic, we are tracking the last active element but it doesn't get refocused on close.

**Comment by gnomeontherun** [comment] 2020-02-21 17:42
Apps can workaround this by manually moving focus where they want to on modal close.

**Comment by gnomeontherun** [comment] 2021-02-01 22:49
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:49 UTC
Labels: @clr/angular, component: modal, flag: has workaround, status: backlog, type: accessibility
