### ISSUE TITLE
Unable to install latest version - v3

### ISSUE THREAD

**Issue by iamnaveenpaul** [vmware/clarity#4500] opened 2020-04-22 21:40 UTC
## Describe the bug
I'm trying to add the latest version of clarity to my angular app and I'm getting the No matching version found for @clr/ui@NaN error.
 
_A clear and concise description of what the bug is, and the conditions when it occurs._
I'm running this command - `ng add @clr/angular`
npm ERR! notarget No matching version found for @clr/ui@NaN
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget

## Versions

**App**

* Angular: 9
* Node: 10.12
* Clarity: 3

**Device:**

* Type: Lenovo
* OS: Windows 10

**Comment by arn-the-long-beard** [comment] 2020-04-23 10:01
Hi, I am new to clarity and I just got the issue too.

## Describe the bug
I'm trying to add the latest version of clarity to my angular app and I'm getting the No matching version found for @clr/ui@NaN error.

_A clear and concise description of what the bug is, and the conditions when it occurs._
I'm running this command - `ng add @clr/angular`
npm ERR! notarget No matching version found for @clr/ui@NaN
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget

The error also comes with 


`npm install @clr/core @clr/icons @clr/angular @clr/ui @webcomponents/webcomponentsjs --save`

the bug also appears for the icons

## Versions
**App**

* Angular: 9
* Node: 10.12
* Clarity: 3

 **Device:**

 * Type: Lenovo
 * OS: Linux Mint

**Comment by nmcbride** [comment] 2020-04-23 14:55
Same issue here. I'll go delete my other issue about it.

```
bash-3.2$ ng add @clr/angular
Skipping installation: Package already installed
⠸ Installing packages...npm ERR! code ETARGET
npm ERR! notarget No matching version found for @clr/ui@NaN
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'test-app'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-04-23T04_35_38_800Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
bash-3.2$
```

**Comment by gnomeontherun** [comment] 2020-04-23 15:18
This is a duplicate of #4444 and has been resolved in this week's release, available now. It works as expected now. Closing as fixed.

**Closed by gnomeontherun** 2020-04-23 15:18 UTC
