### ISSUE TITLE
Looping progress bar has incorrect height of the animated strip

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#2564] opened 2018-08-20 10:30 UTC
## Describe the bug

I noticed that height of the background strip and height of the animated strip are not equal. I stopped the animation and made a screenshot to demonstrate it.

![2018-08-20_13-28-52](https://user-images.githubusercontent.com/1847303/44335427-141b4980-a47d-11e8-9dcf-310d766302ca.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v012-mpjy6h

## Expected behavior

The height of the animated strip is the same as that of the background strip.

## Versions

**App**

* Angular: 6.0.1
* Node: 8.11.3
* Clarity: 0.12.5

**Device:**

* Type: Desktop
* OS: Windows 10
* Browser: Chrome
* Version 67.0.3396.99

## Additional notes

I fixed this issue on my side with the following CSS code:
```css
.progress.loop > progress {
  vertical-align: top;
}
```

**Comment by Shijir** [comment] 2018-08-20 22:45
The issue is due to the fact that we set height and width to the `<progress>` element even though it's not a block type element. A potential fix could be applying `display: inline-block` to the `<progress>` element.

**Comment by belyan** [comment] 2018-08-21 10:32
@Shijir , you are right, this solution also works.

I researched styles for progress bar and I don't understand one thing. Why for element with class `progress` applied property `height` and then this property redefined with `max-height`? Why not set the correct height value at once?

**Comment by Shijir** [comment] 2018-08-21 17:25
@belyan I believe this basic progress bar height is the largest possible height for a progress component. From there on, we also offer multiple different styles that have smaller heights. 

Btw, this is issue is fixed in https://github.com/vmware/clarity/pull/2567

**Closed by Shijir** 2018-08-21 17:25 UTC
Labels: Accepted, Bug, In Review
