### ISSUE TITLE
Horizontal navigation through the wizard

### ISSUE THREAD

**Issue by guntisravani** [vmware/clarity#2633] opened 2018-09-09 23:59 UTC
* What is the change?
Currently, the wizard navigation is vertical.

* Why should it go in Clarity?
Users require horizontal navigation option as well.
* Does this change impact existing behaviors? If so how?
N/A
* If this change introduces a new behavior, is this behavior accessible?
N/A

Please let me know if you require any information further

**Comment by mathisscott** [comment] 2018-09-10 15:28
@guntisravani 
What is the use case driving this request?

**Comment by mathisscott** [comment] 2018-09-19 15:28
Barring new information on the use case, I'm closing this as a duplicate of #1633 which is a component that seems more applicable to the use case as I understand it.

**Closed by mathisscott** 2018-09-19 15:28 UTC
Labels: Awaiting More Info, Watchlist
