### ISSUE TITLE
Links on Forms doc page are broken

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1874] opened 2018-01-18 22:12 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Links should go to pages

### Actual behavior
Links go to 404

### Reproduction of behavior
Go to https://vmware.github.io/clarity/documentation/v0.11/forms
Scroll to bottom
Click any link in Usage section

### Environment details
Seeing this in Chrome on Mac, but issue seems fundamental to the link.

**Comment by joshjohnson72** [comment] 2018-01-18 22:13
Links should likely be relative rather than fixed.

**Comment by adityarb88** [comment] 2018-01-18 22:13
@joshjohnson72: Looks like a duplicate of #1873

**Comment by gnomeontherun** [comment] 2018-01-18 22:13
Indeed, and due to Angular bug https://github.com/angular/angular/issues/13011

**Comment by adityarb88** [comment] 2018-01-18 22:15
I am going to close this issue. Please subscribe to #1873 for more updates. Thanks!

**Closed by adityarb88** 2018-01-18 22:15 UTC
Labels: duplicate
