### ISSUE TITLE
cds-icon in button misaligned when placed in clr-dropdown

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#6448] opened 2021-11-02 14:38 UTC
## Describe the bug

The icons are not centered vertically.

![Screenshot 2021-11-02 at 15 37 07](https://user-images.githubusercontent.com/3655915/139868509-337150fc-d236-4466-b302-3b6f0b8fed5c.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-of9ull

## Expected behavior

Centered icons

## Versions

**Clarity project:**

- [x] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [X] v5.6.0

**Framework:**

- [X] Angular

**Framework version:**
_ie: Angular 12.0.2

**Comment by dorthrithil** [comment] 2021-11-02 15:08
The `.dropdown-toggle` style overrides margins, you can hotfix this bug using these styles:

```scss
.dropdown .dropdown-toggle.btn cds-icon{
  margin-top: -.14rem;

  &[shape=angle]{
    margin-top: -.1rem;
  }

}
```

**Comment by bdryanovski** [comment] 2021-11-08 07:07
@dorthrithil thanks for reporting this and for the hotfix :)

**Comment by steve-haar** [comment] 2022-01-07 22:15
After investigating, looks like this is caused by this line: https://github.com/vmware/clarity/blob/e074c2329eac008499b73602cc477c96a2669353/projects/angular/src/popover/dropdown/_dropdown.clarity.scss#L28. Apparently, we set margin to 0 for all immediate children of the dropdown toggle. Looks like this has existing all the way since "commit 0" of v1. Removing this line would fix this issue. I can't think of why we would have this line. @bdryanovski can you weigh in on why we might have added this line?

**Comment by mathisscott** [comment] 2022-01-07 23:02
> Apparently, we set margin to 0 for all immediate children of the dropdown toggle. Looks like this has existing all the way since "commit 0" of v1. Removing this line would fix this issue. I can't think of why we would have this line. @bdryanovski can you weigh in on why we might have added this line?

I'm drawing a bit of a blank on why that is there. I'm sure it was put there for a reason. Since the code goes all the way back to `commit0`, the code predates open-source and it is very likely that the code is from our Bootstrap days and is no longer applicable.

**Comment by mathisscott** [comment] 2022-01-07 23:04
Note also that, back in the `commit0` days, a lot of our icons were `base64` svg. Clarity Icons was still just POC back then. So this might also be related to those old base64 icons we had...

**Comment by steve-haar** [comment] 2022-01-11 15:22
closing this as it was fixed with https://github.com/vmware/clarity/commit/0cb5c3b6d1c41cb1fd57f84088db47481d15d698

**Closed as completed** 2022-01-12 22:35 UTC
Labels: type: bug, flag: has workaround, @clr/angular, component: dropdown, v5
