### ISSUE TITLE
Show unexpected title under Firefox and Safari browsers with tooltip component.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#678] opened 2017-04-05 07:52 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[] feature request
[] enhancement
```
Releated issue  vmware/harbor#1737

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** 0.8.7

* **OS and version:** 10.12.4

* **Browser:** [ Firefox 52 | Safari 10 ]

**Comment by Jinnie** [comment] 2017-04-05 08:55
This tooltip is coming from the `<title>` tag inside of the icon svg, which is probably used for accessibility purposes. You can reproduce this with any icon in the iconography doc page.
The Clarity team has to respond if this is intended or not, but as a quick workaround you should be able to manually force a `pointer-events: none;` CSS to the svg element, and attach the real tooltip, or any other mouse interactions to a container around it.

**Comment by mathisscott** [comment] 2017-04-05 14:06
@wknet : @jinnie is correct. Those titles are intentional. I'm closing this broad issue. 

If you can think of components that use icons in Clarity where the title doesn't seem like it belongs, please open an issue for them so we can take it back to the UX team for further discussion. 

Thanks.

**Closed by mathisscott** 2017-04-05 14:06 UTC
