### ISSUE TITLE
Modals Theme Issues: Close Icon Doesn't Support a Hover Property, Black Box

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3038] opened 2019-01-14 22:38 UTC
## Describe the bug

In the Dark Theme, it's possible to set the Modal's Close Icon color. That's cool. 

$clr-modal-close-color: #DE0063; //Pink. No separate hover property.

However, there is no way to set a hover property on the close icon. What I'd like to do is set the Close Icon's regular and hover color properties to the global ones specified higher up on the page. 

//Global properties that are picked up by the Close icons in other controls, such as Alerts.
$close-color--normal: #000;  //black
$close-color--hover: #687173; //gray

//IDEAL: I could set the default and hover colors to match the global properties. 
$clr-modal-close-color: $close-color--normal;
$clr-modal-close-hover-color: $close-color--hover;  //Possible new property

## BONUS ISSUE
It should be noted that there's this ugly black box around the Close icon on mouse down. Is this intentional? 

## How to reproduce

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

1. Change the values in the dark theme file as noted above.
2. Run the Clarity Kitchen Sink app.
3. View the Modal section of the demo.
4. Observe the effects as noted. There is no hover effect on the Close icon in Modals. 

## Expected behavior

Because the Close icon in most other controls support a hover effect, it would be ideal if the Modal's did, too. 

## Versions

**App**

Kitchen Sink app as downloaded from Github on Friday, Jan. 11, 2019.

Clarity: v1.0.4
Chrome

![image](https://user-images.githubusercontent.com/11655671/51145464-c971e380-1808-11e9-9a01-bf11f959d039.png)

![image](https://user-images.githubusercontent.com/11655671/51145812-d7743400-1809-11e9-99de-f2df4f774a8d.png)

**Comment by gnomeontherun** [comment] 2019-01-14 22:47
@ahand Can you please provide us with a reproduction of all of these theme issues you are reporting? Screenshots do not help us triage the issues and we can't reproduce your exact scenarios to determine what is happening. Before we get more issues like this, check the message I've sent in Slack about how we can get an interactive demonstration.

Also, some things may not have variables to control and then you're on your own to write selectors to change those behaviors.

**Comment by gnomeontherun** [comment] 2019-01-16 22:11
The 'ugly black box' is the focus state, which is picked up from the `$clr-outline-color-inverse` property when we're in a dark theme mode or `$clr-outline-color` in light theme.

You're right, we don't have a `:hover` style applied for the modal close, but it exists on the alert close. I think that is an inconsistency and I'm not entirely sure which way we should go there. For now, the workaround is to write your own CSS selector to add a hover to the modal close icon, if that is your desire. I'll put this in the queue for UX to review.

**Comment by colinreedmiller** [comment] 2019-02-08 18:48
To enable control of color / hover / focus on modal close I recommend the following:

Light theme modal to expose 3 variables:
modal-dismiss-button-color
modal-dismiss-button-hover-color
modal-dismiss-button-focus-color

The values will match those in signposts:
modal-dismiss-button-color #747474
modal-dismiss-button-hover-color #000
modal-dismiss-button-focus-color - only used in few places - (usually uses the components hover color)

For the dark theme these will be overridden with:
dark-modal-dismiss-button-color #ADBBC4
dark-modal-dismiss-button-hover-color  #FFF
dark-modal-dismiss-button-focus-color #49AFD9

/* re: customizing the focus color: Be sure to pay attention to a11y - best practice is to allow the browser to supply focus and only override when necessary. Once you customize a single focus state you may find a consistency issue that leads to the domino effect of customizing them all. */

**Comment by gnomeontherun** [comment] 2021-01-29 22:27
I don't see the issue currently, and this is reflective of an older issue.

**Comment by gnomeontherun** [comment] 2021-01-29 22:28
There is a workaround to address this, but also a different implementation available. Consider using the Clarity Core version of the component for your application which should not have this concern. In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by  implementations in Clarity Core.

**Closed by gnomeontherun** 2021-01-29 22:28 UTC
Labels: Dev, Help Wanted, flag: has workaround, priority: 1 low, type: enhancement, ux: ready
