### ISSUE TITLE
programmatic selection with clrDgSingleSelected not working

### ISSUE THREAD

**Issue by maglkp** [vmware/clarity#2635] opened 2018-09-10 10:44 UTC
## Describe the bug

As in title - [(clrDgSingleSelected)]="variable" on a clr-datagrid to programatically select a row is not working (eg. to select a row on page load).

There is no complete example on how that would exactly be done so it's possible but unlikely I've not been using it right (what type the variable in controller should be, maybe some annotations needed like @Input). Tried loads of things though. Exact same behavior for multi select clrDgSelected works fine - I'm able to set this bound variable in the controller and see the row/-s selected.

## How to reproduce

Create a simple data grid with static data 

controller ts file:
export class SomeComponent 
...
selectedRows;
 ngOnInit() {
this.items = [{id: '1', name: 'n1'}, {id: '2', name: 'n2'}];
this.selectedRow = [items[0]]; 
...

controller html file:
<clr-datagrid [(clrDgSingleSelected)]="selectedRow" [clDgRowSelection]="true">

<clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>

          <clr-dg-row *clrDgItems="let item of items" [clrDgItem]="item">
            <clr-dg-cell>{{item.name}}</clr-dg-cell>
             ....

(I've no time to create full plnkr or something else but basically any simple grid should work)

## Expected behavior

Two way binding should work and UI should reflect the selection.

## Versions

**App**

* Angular: 6.1.3
* Node: 6.1.0
* Clarity: 0.12.4

**Device:**

* Type: MacBook Pro retina 2016
* Browser chrome 

## Additional notes

[(clrDgSelected)]="item.selected" binding as described in https://vmware.github.io/clarity/documentation/v0.11/datagrid/selection doesn't seem to work on single selection either

**Comment by youdz** [comment] 2018-09-10 21:32
Looks like a duplicate of #2500, it was fixed in 0.12.9. Just upgrading to latest 0.12 should fix it. 👍

**Closed by youdz** 2018-09-10 21:32 UTC
