### ISSUE TITLE
Datagrid PageUp/Down key page navigation

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#3637] opened 2019-07-19 00:03 UTC
## Summary

Thinking it would be quite useful froma navigation perspective to be abel to enable PageUp/Down key navigation of the datagrid pages.
Perhaps some attribute in the clr-dg-pagination element clrKeyboardPageKeyBinding that if present would page back and forward through the datagrid.
Pagedown would go to next page.
Possibly also bind Home/End key to first and last page, but that may be more problematic as they are more likely to be used within the context of field editing.
While not a high priority item, I think nthis would give nice UI nagivation ability.
Currently cnavigation through pages requires clickgin the netx nav button which can move around depending on the page so have to focus on the nav bar rather than the grid content, which a user should be doing.
Only the first showing datagrid on a page with this set will get the action.

* What is the change?
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

All above

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

Could add in separate listeners or even a generic component that wires the mapping up to a specified datagrid.

**Comment by gnomeontherun** [comment] 2019-07-23 00:39
This is a duplicate of the more ambitious #2356. Follow that ticket for updates on this and I'll close this.

**Closed by gnomeontherun** 2019-07-23 00:39 UTC
