### ISSUE TITLE
Unnecessary scroll bar in Datagrid with paging

### ISSUE THREAD

**Issue by hughanderson4** [vmware/clarity#2690] opened 2018-09-27 13:13 UTC
## Describe the bug

If I use the paging feature of Datagrid, a vertical scrollbar appears that is not needed and does not function to do anything.

## How to reproduce

You can observe the bug in the Clarity documentation.

1.  Go to https://vmware.github.io/clarity/documentation/v0.13/datagrid/pagination
2.  Observe the Datagrid in step 1 has an unnecessary scroll bar
3.  Compare to https://vmware.github.io/clarity/documentation/v0.13/datagrid/structure
4.  Notice the Datagrid in step 3 doesn't have an unnecessary scroll bar (because it isn't using paging)

## Expected behavior

Scroll bar should not be visible if content is not overflowing.

## Versions

**App**

* Angular: 6.1
* Node: 8.10
* Clarity: 0.13.2

**Device:**

* Type: PC
* OS: Windows 10
* Browser: Chrome

**Comment by youdz** [comment] 2018-09-27 13:33
This is a known issue that should be fixed with #2670. I'm keeping this open for now so we can double-check it's fixed, now that I've linked it.

**Comment by hippee-lee** [comment] 2018-09-27 16:00
#2670 won't fix the scroll bar in the `datagrid/pagination` demo. That demo has a fixed height on the datagrid itself. That is what causes the scrollbar in the pagination demo. I'm not sure why we kept a fixed height on that demo but when it is removed, so is the scrollbar. 

I'm closing this as `invalid`. If you do have a datagrid, with pagination and no fixed height that has a scrollbar please reproduce that issue in a StackBlitz and paste it here.

**Comment by hippee-lee** [comment] 2018-09-27 17:45
Here is a simple datagrid with pagination. As you can see there is no height set for the datagrid and no scrollbar in the y-axis. 

Can you add things one at a time, that reflect your enterprise app, to see whats causing the scrollbar? 
https://stackblitz.com/edit/datagrid-with-pagination

**Comment by hippee-lee** [comment] 2018-09-27 17:47
Actually, you are correct. there is a scrollbar. @youdz is correct this should be fixed by the referenced PR. Re-opening for tracking.

**Comment by hughanderson4** [comment] 2018-09-27 19:01
I noticed it is not a problem with compact Datagrid
`<clr-datagrid class="datagrid-compact">`

**Comment by asachan2707** [comment] 2018-09-28 06:40
@hippee-lee @mathisscott , In datagrid body we have an unwanted property, **overflow**, that is causing the problem. Will anyone check once.

**Comment by youdz** [comment] 2018-10-18 17:12
This seems to not have been fixed as part of #2670, I'm putting it back into our backlog.

**Comment by youdz** [comment] 2018-10-18 17:53
Actually, this is a duplicate of #2351, please follow the linked issue for further updates.

**Closed by youdz** 2018-10-18 17:53 UTC
Labels: Bug, Dev, Needs Investigation, Watchlist
