### ISSUE TITLE
Hiding a data grid column produces an unecessary horizontal scrollbar

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2697] opened 2018-09-30 06:43 UTC
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._
![image](https://user-images.githubusercontent.com/1977391/46254262-fa7b1200-c4be-11e8-84be-65029fdfb997.png)

## How to reproduce

Open the link and hide the Tenant Id column.

https://stackblitz.com/edit/clarity-dark-theme-v013-5p45lh
## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by asachan2707** [comment] 2018-10-01 04:59
Following changes required to resolve the issue,
.datagrid-overlay-wrapper {
    **overflow-y: hidden;   >>   overflow: hidden;**
}

@whizkidwwe1217 @mathisscott , will you check once with this.

**Comment by whizkidwwe1217** [comment] 2018-10-01 16:33
@asachan2707 That's not a good idea. That will totally hide the scrollbars. You will not be able to scroll to the data grid cells/rows that are not visible in the grid's viewport.

**Comment by hippee-lee** [comment] 2018-10-01 20:02
@whizkidwwe1217 - I took a quick look at this. 
The font color looks like a regression. I'm pretty sure It used to be the light color for dark theme. 

I'm not sure what you are referring to wrt the horizontal scrollbar. Can you elaborate?

**Comment by hippee-lee** [comment] 2018-10-01 20:42
Thanks for reporting this. I'll look into it a bit more and update here when I know whats wrong.

**Comment by hippee-lee** [comment] 2018-10-01 20:48
@whizkidwwe1217 - I'm not able to re-create this issue. I don't see a scrollbar when I uncheck the Tenet column. Is there another step I'm missing?

**Comment by whizkidwwe1217** [comment] 2018-10-02 00:50
@hippee-lee Sorry, my mistake. I forgot to remove the test css that I put in styles.css. I updated the stackblitz. You should now be able to replicate the issue. https://stackblitz.com/edit/clarity-dark-theme-v013-5p45lh

**Comment by hippee-lee** [comment] 2018-10-02 20:19
@whizkidwwe1217 - I took a look at this. Turns out it is a duplicate of #1248. There is a fix for it in a pull request thats in the final stages of review #2670.

I'm going close this issue. Please subscribe to the original issue and/or the pull request to get updates.

**Closed by hippee-lee** 2018-10-02 20:19 UTC
Labels: Awaiting More Info
