### ISSUE TITLE
Datagrid with fixed height - header scrolls out with longer content

### ISSUE THREAD

**Issue by derkoe** [vmware/clarity#4824] opened 2020-07-27 19:27 UTC
## Describe the bug

When scrolling a fixed height Datagrid the header will disappear after scrolling down some rows although it should be sticky at the top.

![datagrid-header-fixed](https://user-images.githubusercontent.com/123199/88582992-e323f600-d04f-11ea-9a7d-8af358e29804.gif)

## How to reproduce

StackBlitz https://stackblitz.com/edit/clarity-v3-light-theme-grizt9

1. Open the app https://clarity-v3-light-theme-grizt9.stackblitz.io/
2. Scroll down in the datagrid
3. The header is only sticky for the first few scrolled rows and then scrolls out

## Expected behavior

The header should be sticky when scrolling all the way down to the end of the rows.

## Versions

**App**

- Angular: 9.1.12
- Node: 12
- Clarity: 3.1.5

**Device:**

- OS: Windows
- Browser: Chrome
- Version: 84

## Additional notes

This only happens when the rows in the Datagrid exceed it's height more than a third of the whole size. For example if you change the height in the StackBlitz to 450px the scrolling works as excpected.

**Comment by gnomeontherun** [comment] 2020-07-29 19:58
Interesting, and thanks for the report Christian, we'll look into it.

**Comment by namitabandal** [comment] 2020-10-08 05:20
@gnomeontherun 
Any updates on this issue? When it will get fixed? I am facing the same issue.

Angular: 9.1.12
Node: 12
Clarity: 3.1.5

**Comment by gnomeontherun** [comment] 2020-10-13 17:31
There was some recent work on this that went out in 3.1.9, can you update and check?

**Comment by namitabandal** [comment] 2020-10-14 08:30
@gnomeontherun Yes, the issue is fixed. Thanks!

**Comment by hippee-lee** [comment] 2020-10-14 14:17
Closing, here are the relevent PR's that backport the change to v3/v4 branches: 

1. For v3 branch: https://github.com/vmware/clarity/pull/5081
2. For v4 branch: https://github.com/vmware/clarity/pull/5080

**Closed by hippee-lee** 2020-10-14 14:17 UTC
Labels: @clr/angular, component: datagrid, status: needs investigation, type: bug
