### ISSUE TITLE
ERROR in node_modules/@cds/core/forms/control-action/control-action.element.d.ts:26:15 - error TS2315: Type 'TemplateResult' is not generic.

### ISSUE THREAD

**Issue by AngelRani** [vmware/clarity#6123] opened 2021-07-06 07:21 UTC
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

i have installed clarity update in the latest version. but got this error 'ERROR in node_modules/@cds/core/forms/control-action/control-action.element.d.ts:26:15 - error TS2315: Type 'TemplateResult' is not generic.
'. i dont no . how can i rectifly this error

**Comment by gnomeontherun** [comment] 2021-07-07 17:59
Hello, please fill out our issue template to help us understand and triage your issue. There is no reproduction here, so I can't be sure what the problem is but it sounds like a TypeScript issue. Please update the original issue with version information, and include the TypeScript version. May be related to #5770 .

**Comment by boeckMt** [comment] 2021-07-09 12:57
I have a similar errors when using @clr/angular in angular Libraries.

```bash
✖ Compiling TypeScript sources through NGC
ERROR: 
node_modules/@cds/core/internal/base/button.base.d.ts:16:25 - error TS2315: Type 'TemplateResult' is not generic.
protected render(): import("lit-html").TemplateResult<1>;
...
```

```bash
✖ Compiling TypeScript sources through NGC
ERROR: 
node_modules/@cds/core/internal/utils/responsive.d.ts:11:86 - error TS2304: Cannot find name 'ResizeObserver'.
export declare function elementResize(element: HTMLElement, callbackFn: () => void): ResizeObserver;
...
```

## Versions
- "@angular/core": "11.2.14",
- "@cds/core": "5.4.2",
- "@clr/angular": "5.4.1",
- "@clr/core": "4.0.15",
- "@clr/icons": "5.4.1",
- "@clr/ui": "5.4.1",
- "typescript": "4.1.5"

**Comment by Jinnie** [comment] 2021-07-12 12:08
Without proper description and especially without reproduction, there is not much we can do.

**Comment by boeckMt** [comment] 2021-07-14 09:56
@Jinnie I tried to reproduce the error .

## How to reproduce
Steps to reproduce the behavior:

1. create a new angular workspace with ng-cli version 11.2.14
`ng new cds-test --create-application=false  --style=scss` // I skipped the app here and create it later because this is the same structure I had on the other repo 

2. create a new angular application
`ng g application test-app --prefix=app --style=scss`

3. add @clr/angular to the application
`ng add @clr/angular`

4. run serve or build 
`ng build --configuration=production` or `ng serve`


then you will see the errors 

```bash

Error: node_modules/@cds/core/internal/utils/responsive.d.ts:11:86 - error TS2304: Cannot find name 'ResizeObserver'.

11 export declare function elementResize(element: HTMLElement, callbackFn: () => void): ResizeObserver;


Error: node_modules/@cds/core/internal/utils/responsive.d.ts:18:124 - error TS2304: Cannot find name 'ResizeObserver'.

18 export declare function updateComponentLayout(component: ResponsiveComponent, layoutConfig: LayoutConfig, fn: () => void): ResizeObserver;
```


Unfortunately I cannot reproduce the error for `Type 'TemplateResult' is not generic.`


## Versions
- "@angular/core": "11.2.14",
- "@clr/angular": "5.4.1",
- "typescript": "4.1.5"

**Comment by Jinnie** [comment] 2021-07-14 11:06
Both errors, with workarounds and solutions, have been discussed in this topic: https://github.com/vmware/clarity/issues/6060 
Make sure you're using latest Typescript version (Angular update does not force the TS update)
And for the TemplateResult error - do not use `@clr/core`, but `@cds/core`
See the linked topic for more details.
Closing this as duplicate.

**Closed as completed by Jinnie** 2021-07-14 11:06 UTC
Labels: status: needs reproduction
