### ISSUE TITLE
Styling of <select> elements with 'size' attribute

### ISSUE THREAD

**Issue by alalev** [vmware/clarity#675] opened 2017-04-04 13:16 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Either `<div class="select single"><select size="...">...</select></div>` or
`<div class="select multiple"><select size="...">...</select></div>` has the same styling as
`<div class="select multiple"><select multiple>...</select></div>`

### Actual behavior

Both `<div class="select single"><select size="...">...</select></div>` and
`<div class="select multiple"><select size="...">...</select></div>` have the same styling as
`<div class="select"><select>...</select></div>`

### Reproduction of behavior

Clarity Plunker: https://plnkr.co/hOZ81f

The bug can be spotted easily.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** Latest (possibly 0.9.0-alpha.2)

* **OS and version:** OS X El Capitan 10.11.6

* **Browser:** Chrome 56

**Comment by adityarb88** [comment] 2017-04-04 13:27
Thanks for raising this issue. We will take a look at this and get back to you.

**Comment by alalev** [comment] 2017-04-13 08:28
Has anyone started looking into this? We aren't in a hurry for this one in particular, so I'm not pushing you to prioritize it, but I'm wondering what its status is.

**Comment by mathisscott** [comment] 2017-04-13 12:27
@alalev : It's in our backlog, which means we are committed to fixing the issue, but hasn't been prioritized due to other items taking precedence. If you have more details around your use case and urgency, I could bring that back to the team to reconsider its priority.

**Comment by alalev** [comment] 2017-04-13 14:30
@mathisscott As I said, we aren't in a hurry so it doesn't need to be prioritized. However I suppose the fix for it is easy because it should only involve changing `select[multiple]` to `select[multiple], select[size]` at _select.clarity.scss:83 . Also considering how a `<select>` element with a `size` attribute has hardly ever been used, there is a low chance of regressions. Therefore it probably won't slow things down much.

Also, a slightly off-topic question - shouldn't the `select[multiple]` styles be under the `.select { ... }` selector so that non-clarity elements are not affected?

**Comment by mathisscott** [comment] 2017-04-13 16:05
@alalev: Yes to everything you just said.

I'm going to mark this as contributions welcome because you've outlined the fix in your comment. If anyone wants to hop in and make that change, it's a very easy fix. I don't even think it would mess with the CSS regression tests.

Thanks, @alalev

**Closed** 2017-04-26 16:31 UTC
Labels: bug, ClarityUI, contributions welcome
