### ISSUE TITLE
Can't find CSS classes utilities documentation that comes bundled with Clarity

### ISSUE THREAD

**Issue by idris-rampurawala** [vmware/clarity#4997] opened 2020-09-02 11:43 UTC
## Summary
There is no documentation of what all classes come with Clarity UI. Under the theme section, it does not talk about the CSS classes available with Clarity.

If you have got any link or documentation, then please attach it in this issue so that is easily available.

- What is the change? Documentation update to add more clarity on available CSS classes while using Clarity.
- Why should it go in Clarity? There's no way to find out if there's any CSS class available for what I am looking for.
- Does this change impact existing behaviors? If so how? No.
- If this change introduces a new behavior, is this behavior accessible? NA

## Use case

NA

## Examples

NA

## Workarounds

NA

**Comment by gnomeontherun** [comment] 2020-09-15 13:31
This is a duplicate of some other requests, and something we've been working to improve. See #2212 for example. We do document most of the CSS classes we consider public and connected with specific components, such as in alerts. 

With our evolution with Core, we are documenting all properties fully.

**Comment by gnomeontherun** [comment] 2021-01-28 21:36
With the new website, Clarity Core documentation contains a whole dedicated section to all styling options. We aren't currently planning to invest in auditing the Clarity Angular documentation for any missing classes (there may be a few but most are documented), but are happy to consider improvements for missing details if people find them in the future. I'm closing this as resolved in new website for Clarity Core.

**Closed by gnomeontherun** 2021-01-28 21:36 UTC
Labels: type: website
