### ISSUE TITLE
clr-signpost  is NOT RESPONSIVE

### ISSUE THREAD

**Issue by monisaivanova** [vmware/clarity#4071] opened 2019-12-04 13:26 UTC
## Describe the bug

clarity SIGNPOST is not responsive

## How to reproduce

https://stackblitz.com/edit/angular-clarity-design-anvjgx?file=src/app/app.component.html

## Expected behavior

be responsive

## Versions

* Angular: 7
* Node: 
* Clarity:  1.3.x

**Comment by gnomeontherun** [comment] 2019-12-13 13:14
Hello, what exactly do you mean by 'not responsive? Do you anticipate that it will reposition? Resize? We have a backlog task to support smarter repositioning with signposts (like we now have in latest v2 with Datagrid popups), but I'm not fully clear what you mean here. Can you give more clear details what the issue is here and your expectations?

**Comment by gnomeontherun** [comment] 2019-12-20 22:29
Ultimately, this will be resolved by #1757 so I'm closing this as a duplicate of that.

**Closed by gnomeontherun** 2019-12-20 22:29 UTC
Labels: @clr/angular, component: utilities, status: needs info, type: enhancement
