### ISSUE TITLE
'IfExpandService' dependency error while writing karma unit test cases for Expandable Rows of Datagrid.

### ISSUE THREAD

**Issue by dharemsj** [vmware/clarity#4311] opened 2020-02-25 12:44 UTC
I am writing unit test cases for Expandable Rows of a datagrid in which i am getting an dependency error i.e. "No provider for IfExpandService!". 

Attaching screenshot of error and stackbliz link for functionality with unit test case file.

 https://stackblitz.com/edit/clarity-light-theme-v2-tvj5wf?embed=1

![expand spec image](https://user-images.githubusercontent.com/43265660/75248169-a54d4800-57f9-11ea-8a82-9a2f63d9bfa5.png)

Please help me in resolving this issue. Thanks in advance.

**Comment by gnomeontherun** [comment] 2020-02-25 17:39
This is a duplicate of #3723, you can manually import the `ClrConditionalModule` for the tests to work until this is resolved. Closing as duplicate.

**Closed by gnomeontherun** 2020-02-25 17:39 UTC

**Comment by dharemsj** [comment] 2020-02-26 10:10
Hi @gnomeontherun 

After implementing ClrConditionalModule in my unit test case file i am getting this error as attached in screenshot also attaching stackblitz link with your suggested changes.  

https://stackblitz.com/edit/clarity-light-theme-v2-tvj5wf?embed=1

I think #3723 is not an workaround for this issue. 

Please reopen this issue and provide me workaround in stackblitz if any correction is required.

![row_details_error_page](https://user-images.githubusercontent.com/43265660/75334259-84dec580-58ad-11ea-84cf-32b18e965367.png)

Thanks

**Comment by gnomeontherun** [comment] 2020-02-26 18:51
Oh right, the module isn't exported. The workaround is to import the whole `ClarityModule` for this test instead of just the Datagrid. We need to fix the Datagrid module to import the conditional module directly to fix this, which is why I say its a duplicate.

**Comment by dharemsj** [comment] 2020-02-27 07:28
Thanks for the quick response @gnomeontherun 

If you look into stackblitz link provided above. I have already imported ClarityModule as a dependency in unit test file still i am getting "No provider for IfExpandService!" error. 

stackblitz link:  https://stackblitz.com/edit/clarity-light-theme-v2-tvj5wf?embed=1

**Unit test case file name**: appDetails.component.spec.ts

Please suggest further.

Thanks
