### ISSUE TITLE
Combobox: selections sometimes misaligned with long options

### ISSUE THREAD

**Issue by jzabinski** [vmware/clarity#5715] opened 2021-03-10 23:52 UTC
## Describe the bug

In mobile portrait displays, when a combobox is horizontally aligned with its label, selections are misaligned with the input text when the selection contains a long name.

## How to reproduce

1.  In Chrome, go to [this Stackblitz page](https://combobox-in-mobile-v4.stackblitz.io/)
2. Open Chrome's Console.
3. Activate Mobile Portrait by [toggling device mode](https://developers.google.com/web/tools/chrome-devtools/device-mode#viewport) and selecting iPhone 6/7/8 Plus.
4. One name is available: 'extreeeeeeeeeeeemelyyyy loooooong naaaaaaaaaaaaaaaaaaame'. Enter 'e' at the input to activate the combobox selector. Notice that the selection is misaligned and bleeds off the left edge of the screen.

## Expected behavior

Selections should be aligned with input regardless of device type and selection text.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x ] v4.x
- [ ] v5.x

**Framework:**

- [ x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_Angular 11

**Device:**

- Type: HP Elitebook
- OS: Windows
- Browser: Chrome
- Version 89.0.4389.72

## Additional notes
Some CSS was added to the label to align it with the combobox, but the problem still reproduces without the CSS in place.

I also tested this in v5, but consistently received the following error:
Error in /turbo_modules/@clr/angular@5.0.2/bundles/clr-angular.umd.js (2:111)
Unexpected token 'export'

**Comment by bdryanovski** [comment] 2021-03-15 11:45
It seems that the issue is with how we decide where to open the suggestion box. 

It seems when you try to type is position correctly, but when you manually open the dropdown is position on the wrong side. It probably some small initialization issue?! Not sure need to test more.

Probably @Jinnie could add more to this?

<img width="390" alt="Screenshot 2021-03-15 at 13 46 22" src="https://user-images.githubusercontent.com/204564/111148930-e47d4100-8594-11eb-9556-52de24e7a440.png">
<img width="389" alt="Screenshot 2021-03-15 at 13 46 35" src="https://user-images.githubusercontent.com/204564/111148942-e8a95e80-8594-11eb-96e9-5df969c7cd74.png">

**Comment by Jinnie** [comment] 2021-03-17 15:10
The Combobox is using the Smart Popovers solution built for internal smart positioning. It has some limitations, though, when it comes to responsive layout, as it only makes one attempt to position the popover better than originally requested.

This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.

**Closed as completed by Jinnie** 2021-03-17 15:10 UTC
Labels: resolution: best with core
