### ISSUE TITLE
Datagrid Filter Shortcomings

### ISSUE THREAD

**Issue by morrykatz** [vmware/clarity#1892] opened 2018-01-29 21:48 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

1.  Filter should be discoverable.
2.  Filter should have a clear function.
3.  Filter should have a title.
4.  X on filter overlay typically means close without taking an action as opposed to apply.

### Actual behavior

1.  The filter icon has serious discoverability challenges.   It looks so much like a down arrow that everyone I have field tested it with when asked to filter a grid says there is no filter available because they think the filter icon is the down arrow sort indicator used on the great majority of web toolkits.
2.  Once one sets a filter it is an incredible pain to clear it.   When one reopens the filter one has to delete all the characters of the current filter.   The existing filter text is not autoselected so that the delete can be performed with a single backspace keystroke.  So, one has to either select all the filter text by hand and then delete or delete the existing filter one character at a time.   Many toolkits that have a similar filter on a per column basis include a clear button on the filter to address this use case.  BTW, if one filters on more than one column it is doubly painful as one has to open each of the column filters one at a time to clear the filter on that column.
3.  Exacerbating the filter icon being nonobvious is that if one selects the icon, the overlay that opens has no title or other text that informs the user that this is a filter.   One simply gets an text input field with no labeling.   
4.  The filter has no apply function.   It only has an X in the upper right corner.   An X in this location typically means to exit without applying any changes.   With the filter in Clarity it means exist after applying the changes to the filter since the filter is incremental as one types characters.   However, th X still connotes to people do not make changes.   For example, if I type a bunch of data into a form or wizard and select the X in the upper right, I can think of no implementation where the data input is applied.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**v0.11

* **OS and version:** MacOS 10.12.6

* **Browser:** [Chrome 64.0.3282.119]

**Comment by tangopt** [comment] 2018-01-30 14:57
I don't know if it's in the right place, happy to add a new issue, but the overlay should also be moved to overlay the header (adding the title will help) as it obfuscate the first line of results.

Also, the selection is cleared every time the filter is changed making the filtering much less usable as there is a selected row counter at the bottom. Is this intended behaviour?

**Comment by mathisscott** [comment] 2018-01-30 19:26
Hi @morrykatz 
We currently have UX work completed on an overhaul of datagrid filtering. That issue can be found at #1632 

Does that solve your use cases/issues above? If so, can we close this out as a duplicate?

**Comment by morrykatz** [comment] 2018-02-05 21:40
Thank you, my item can be closed as a duplicate.

P.S.  I have added to the comment flow on #1632 a gap relative to range filters for future consideration.

Morry Katz
Product Line Manager, Licensing Solutions
mkatz@vmware.com
3401 Hillview Avenue, Palo Alto, CA 94304 (D1145)
650.427.1252 Office
[ware]<http://www.vmware.com/>

**Comment by mathisscott** [comment] 2018-02-05 22:46
Closing as a duplicate of #1632 per @morrykatz request

**Closed by mathisscott** 2018-02-05 22:46 UTC
Labels: Awaiting More Info
