### ISSUE TITLE
Datagrid single row action toggle not working at times

### ISSUE THREAD

**Issue by harihnv** [vmware/clarity#4123] opened 2019-12-17 15:06 UTC
The single row action in datagrid doesn't work for some screen sizes. 
 
![datagrid_sra_bug](https://user-images.githubusercontent.com/58984854/71006923-1f7f9300-210c-11ea-8b18-ad1233694408.gif)

1.  Go to https://v2.clarity.design/datagrid/single-action
2.  Resize the page as shown in the gif above
3.  Click on single row action toggle
4. Action buttons are not shown

Expected behavior - Action buttons should be displayed

**App**

* Angular: 8.2.7
* Clarity: 2.2.0

**Device:**

* Type: MacBook
* OS: iOS
* Browser: Chrome, Firefox

Note: **This issue happens only when mouse is connected via the usb c port. It's working fine otherwise.**

**Comment by gnomeontherun** [comment] 2019-12-17 16:27
I cannot reproduce this problem on the documentation. Can you provide more specific instructions on how we should be able to reproduce this?

**Comment by harihnv** [comment] 2019-12-17 17:49
@gnomeontherun, Missed the important part in the description. This issue occurs only when we have a mouse connected through usb c port. I have edited the description of the ticket. .

**Comment by gnomeontherun** [comment] 2019-12-17 18:50
I can't really provide much help here if we can't reproduce it or have a better explanation as to why this is happening with a connected mouse on your machine. Have you tried another machine? Perhaps this is a local problem.

**Comment by martinbrom** [comment] 2019-12-17 20:28
I investigated a bit and I managed to reproduce it on the doc website on my Ubuntu 16.04 laptop running Chrome 78.0.3904.87, however I did NOT manage to reproduce it on my Windows 10 laptop running Chrome 79.0.3945.79. The issue only occurs between 1300px and 1320px for me on the Ubuntu laptop.

**Comment by gnomeontherun** [comment] 2019-12-17 21:05
I agree, this is likely not a mouse issue. I could not reproduce on Mac with either 78 or 79 of chrome. Has this been seen on any other browser?

**Comment by martinbrom** [comment] 2019-12-17 21:13
Tried Firefox v70 on the laptop where I was able to reproduce the issue but could not reproduce it.

**Comment by sumitzamadar** [comment] 2019-12-18 03:44
It is reproducible in Chrome 79 on Windows 10 laptop also. 
I observed the issue in between >1030px and <1058px on the Clarity document website.

**Comment by bdryanovski** [comment] 2020-11-30 16:16
I try to reproduce this on Mac with Chrome Version 87.0.4280.67 (Official Build) (x86_64) with and without a mouse, try also with an external touchpad. Also, try to set the resolution between 800 and 1500.

I'm closing this issue for now if someone could provide a step-by-step guide on how to reproduce it, feel free to reopen it.

**Closed by bdryanovski** 2020-11-30 16:16 UTC
Labels: @clr/angular, component: datagrid, component: utilities, status: needs info, type: bug
