### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in ./DatagridRow class DatagridRow of datagrid

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#625] opened 2017-03-21 15:08 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No error appear

### Actual behavior
code piece:
<clr-dg-row *ngFor="let p of projects" [clrDgItem]="p">

Throw error:

Error: Error in ./DatagridRow class DatagridRow - inline template:4:21 caused by: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. at ViewWrappedError.ZoneAwareError (https://localhost:4200/vendor.bundle.js:103905:33) at ViewWrappedError.BaseError [as constructor] (https://localhost:4200/vendor.bundle.js:30836:16) at ViewWrappedError.WrappedError [as constructor] (https://localhost:4200/vendor.bundle.js:30901:16) at new ViewWrappedError (https://localhost:4200/vendor.bundle.js:61308:16) at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (https://localhost:4200/vendor.bundle.js:87412:23) at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (https://localhost:4200/vendor.bundle.js:87385:18) at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (https://localhost:4200/vendor.bundle.js:87172:18) at View_ListProjectComponent1.detectChangesInternal (/ProjectModule/ListProjectComponent/component.ngfactory.js:352:19) at View_ListProjectComponent1.AppView.detectChanges (https://localhost:4200/vendor.bundle.js:87187:14) at View_ListProjectComponent1.DebugAppView.detectChanges (https://localhost:4200/vendor.bundle.js:87382:44) at ViewContainer.detectChangesInNestedViews (https://localhost:4200/vendor.bundle.js:87519:37) at CompiledTemplate.proxyViewClass.View_ListProjectComponent0.detectChangesInternal (/ProjectModule/ListProjectComponent/component.ngfactory.js:648:15) at CompiledTemplate.proxyViewClass.AppView.detectChanges (https://localhost:4200/vendor.bundle.js:87187:14) at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (https://localhost:4200/vendor.bundle.js:87382:44) at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (https://localhost:4200/vendor.bundle.js:87172:18

### Reproduction of behavior

Clarity Version: [0.8.7]

### Environment details

* **Angular version:** 2.0.X
2.4.10
* **Clarity version:** 
0.8.7
* **OS and version:** 
Mac
* **Browser:** [all]

**Comment by Shijir** [comment] 2017-03-21 16:10
Hi @steven-zou, please use Plunkr and recreate your issue as the information you provided above doesn't give us enough clue about the issue. Also, It might be a duplicate of https://github.com/vmware/clarity/issues/529. In that case, the fix to the problem was introduced in 0.8.10.

**Comment by steven-zou** [comment] 2017-03-22 04:51
Seems similar issue with #529. As you said it has been fixed in 0.8.10. Actually I have tried 0.8.11, there will be same error thrown out. In our code, we use the *ngFor as data iteration like
<clr-dg-row *ngFor="let p of projects" [clrDgItem]="p">, then the error will be occurred.
But if we change the code to 
<clr-dg-row * clrDgItems="let p of projects" [clrDgItem]="p">, the code will run normally. I'm not sure what's the root cause is?

**Comment by hippee-lee** [comment] 2017-03-22 15:50
Howdy @steven-zou,

I was able to recreate  your issue here: https://plnkr.co/edit/lsjSb7JQAKcdRcnK7nZ3?p=preview
I'll investigate further on this issue.

**Comment by steven-zou** [comment] 2017-03-23 10:22
Hi,

  Is the root cause figured out? As the fix and releasing the fix might need a long while, is there any possibilities to propose a workaround solution?

**Comment by Jinnie** [comment] 2017-03-23 11:14
The plunker is using *ngFor for content iteration.
I don't see this happen with *clrDgItems instead.
Just an observation...

**Comment by steven-zou** [comment] 2017-03-24 07:25
I think the problem may be caused by the *ngIf we used in <clr-ng-action-overflow>

======
`<clr-datagrid (clrDgRefresh)="refresh($event)">
    <clr-dg-column>{{'REPOSITORY.NAME' | translate}}</clr-dg-column>
    <clr-dg-column>{{'REPOSITORY.TAGS_COUNT' | translate}}</clr-dg-column>
    <clr-dg-column>{{'REPOSITORY.PULL_COUNT' | translate}}</clr-dg-column>
    <clr-dg-row *ngFor="let r of repositories" [clrDgItem]='r'>
        <clr-dg-action-overflow *ngIf="listFullMode && hasProjectAdminRole">
            <button class="action-item">{{'REPOSITORY.COPY_ID' | translate}}</button>
            <button class="action-item">{{'REPOSITORY.COPY_PARENT_ID' | translate}}</button>
            <button class="action-item" (click)="deleteRepo(r.name)">{{'REPOSITORY.DELETE' | translate}}</button>
        </clr-dg-action-overflow>`

**Comment by mathisscott** [comment] 2017-04-12 22:51
@steven-zou : Was that workaround satisfactory? We haven't heard back on this issue recently.

**Comment by steven-zou** [comment] 2017-04-13 02:30
*ngFor is working.

**Comment by mathisscott** [comment] 2017-04-13 12:28
@steven-zou : Awesome. Happy to hear that the workaround worked!

**Closed by mathisscott** 2017-04-13 12:28 UTC
Labels: bug, ClarityNG

**Comment by soates** [comment] 2017-05-15 08:30
I am still getting this issue

**Comment by juanmendes** [comment] 2017-07-20 17:44
Why was this closed? This problem still happens and seems to be pretty easy to reproduce? vCD is getting this error when we added a `<clr-dg-action-overflow>` to our data grid https://plnkr.co/edit/VKaN98UkIBzLxRKTa0W8?p=preview 

As the comments mentioned, the problem is when using `*ngFor` to create the rows, but not when using `*clrDgItems`

The workaround mentioned is not sufficient because you don't use `*clrDgItems` for server side paging/filtering.

Please reopen or comment

**Comment by jeeyun** [comment] 2017-07-21 17:25
Hi @juanmendes I believe this is fixed with the latest release (you can check the plunkr you posted, which should be using the latest version of Clarity).
