### ISSUE TITLE
Datagrid Overflow Hides Validation Tooltips

### ISSUE THREAD

**Issue by MRamos62786** [vmware/clarity#836] opened 2017-05-03 16:35 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Tooltips with a datagrid should not be truncated. I believe this is related to the overflow properties on .datagrid-body and .datagrid-host.

I entered an issue related to responsive tooltips, https://github.com/vmware/clarity/issues/777, but I think this can be resolved as a separate issue.

![2017-05-03 12_19_41-admin console](https://cloud.githubusercontent.com/assets/12755463/25670490/d792ad48-2ffa-11e7-8ea3-3ed7227e75f3.png)
![2017-05-03 12_19_45-admin console](https://cloud.githubusercontent.com/assets/12755463/25670491/d8845742-2ffa-11e7-9839-2381df333fd1.png)

### Actual behavior

Tooltips within a datagrid are being truncated.

![2017-05-03 12_04_43-admin console](https://cloud.githubusercontent.com/assets/12755463/25670410/9d8fb1c2-2ffa-11e7-8b15-e76984e1c45f.png)
![2017-05-03 12_04_27-admin console](https://cloud.githubusercontent.com/assets/12755463/25670414/9f20992a-2ffa-11e7-9b49-cef73019fec2.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.3

* **Clarity version:** 0.9.2

* **OS and version:** Windows 7

* **Browser:** Reproduced on Chrome & Firefox (but I'd assume this applies to all browsers...)

**Comment by jeeyun** [comment] 2017-05-03 16:56
Hi @MRamos62786 thanks for your input. You can follow this issue which will solve the problem: https://github.com/vmware/clarity/issues/835. This is not unique to being inside datagrid actually. The solution would require us to angularize our input validation.

**Comment by MRamos62786** [comment] 2017-05-03 17:02
Thanks @jeeyun !!

Should I just close this issue then?

**Comment by jeeyun** [comment] 2017-05-03 17:15
Sure, I'll close it as duplicate of #835.

**Closed by jeeyun** 2017-05-03 17:15 UTC
