### ISSUE TITLE
clr-wizard doesnt activate a page toggled with *ngIf if it is the first page

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#1636] opened 2017-10-24 08:25 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If i have a wizard with three pages out of which the first one is optional, i would toggle that page with a *ngIf but when the condition for *ngIf is truthy, the first page should be activated along with being shown in the steps.

### Actual behavior
For a page with *ngIf modifier, it is not activated and instead the next page is shown upfront. User has to press back to go to the first page/step

### Reproduction of behavior
[https://plnkr.co/zBMmuv?p=preview](https://plnkr.co/zBMmuv?p=preview)
Click show modal.
Wizard should open with first page as active instead of second page.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment] 2017-10-25 15:12
Confirming as a bug, based on other similar issues its because ngIf makes the list of pages async to build and the initial page is set before the ngIf changes propagate through, thus selecting the first page without an ngIf. 

You could workaround by instead having it skip to the second page instead of hiding the first page when you want to make the first one optional.

**Comment by nghiado** [comment] 2017-10-27 14:04
We had the same issue, the first step only available during Add flow so we have to hide in Edit flow.
Please fix this, thanks.

**Comment by zivanov123** [comment] 2018-04-20 08:30
We're having the same issue.
We ended up calling manually navService. setFirstPageCurrent().
The problem is that the second page is still getting onLoad event and tries to load data which is dependent on the first page.

**Comment by typhoon1978** [comment] 2019-08-14 08:41
Hi all! I'm on Angular 8 + Clarity 2.0.1 and still having the same issue...

**Comment by andyjmorgan** [comment] 2019-12-12 14:12
this issue is sadly still present

**Comment by gnomeontherun** [comment] 2021-01-29 15:48
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-01-29 15:48 UTC
Labels: @clr/angular, component: wizard, flag: has workaround, priority: 1 low, status: needs investigation, type: bug
