### ISSUE TITLE
TOC items are interpreted by screen readers with one more that their actual count

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#4055] opened 2019-11-26 15:53 UTC
## Describe the bug

When I enter in a TOC area of a Clarity wizard with 3 items the menu item is announced as
<name of the item> navigation 4 items but actual item count is 3
## How to reproduce
https://v2.clarity.design/wizards

1.  Go to 'https://v2.clarity.design/wizards'
2.  Click on 'Medium Wizard'
3. Start Voice Over
4.  Navigate to any of the items in the TOC of the wizard with the keyboard
5. Then the currently focused menu item is announced as <menu item text> navigation <number of items in the TOC + 1> items

## Expected behavior

The currently focused menu item is announced as <menu item text> navigation <number of items in the TOC> items
## Versions

**App**

* Angular: 8.0.0
* Node: v10.15.3
* Clarity: 2.3.2

**Device:**

* Type: MacBook Pro 
* OS: OSX
* Browser Chrome
* Version 78.0.3904.108

## Additional notes

_Add any other notes about the problem here._

![Screenshot 2019-11-26 17 41 04](https://user-images.githubusercontent.com/2686283/69649300-806bfc00-1075-11ea-802e-5be649895195.png)

**Comment by hippee-lee** [comment] 2019-12-03 01:11
I made a simple stackblitz with just the medium wizard. A couple of things to note:

1. The supported VoiceOver browser is Safari
2. In the medium demo the 2nd/3rd TOC buttons can't be clicked/activated in the TOC menu but VoiceOver can navigate the cursor to them and read out the `Page #` value for the three pages. 

@chlane - can you confirm that this is the correct behavior we should expect here? 
https://stackblitz.com/edit/clarity-light-theme-v2-a6ykys

**Comment by chlane** [comment] 2019-12-03 23:37
Yes this behavior make sense.  But I've found several other issue that are documented at http://cx-guidelines.vmware.com/120319_wizardTesting/

**Comment by chlane** [comment] 2019-12-03 23:40
[issuesFoundWithWizard120319.txt](https://github.com/vmware/clarity/files/3919216/issuesFoundWithWizard120319.txt)

**Comment by mathisscott** [comment] 2019-12-04 00:10
@chlane 
Could you open issues for those you've found? A text file dump isn't something that we can track or prioritize.

**Comment by clane** [comment] 2019-12-04 21:51
@mathisscott Of course. See below.

https://github.com/vmware/clarity/issues/3976
https://github.com/vmware/clarity/issues/4079
https://github.com/vmware/clarity/issues/4080
https://github.com/vmware/clarity/issues/4081
https://github.com/vmware/clarity/issues/4082
https://github.com/vmware/clarity/issues/4083
https://github.com/vmware/clarity/issues/4084
https://github.com/vmware/clarity/issues/4085
https://github.com/vmware/clarity/issues/4086

**Comment by gnomeontherun** [comment] 2021-02-01 22:46
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:46 UTC
Labels: @clr/angular, browser: safari, component: wizard, needs: accessibility input, type: accessibility
