### ISSUE TITLE
[DataGrid] Long text overflows cell width

### ISSUE THREAD

**Issue by TechRazor** [vmware/clarity#815] opened 2017-04-30 00:34 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

DataGrid cells should have overflow hidden so that long continuous text such as website url's or email addresses do not overflow the column width.

### Actual behavior

Currently long continuous text overflows the cell width into text of the next cell.

### Reproduction of behavior

Screenshot of datagrid column title and datagrid cell overflow:
![image](https://cloud.githubusercontent.com/assets/1624021/25560119/bf9eb164-2d07-11e7-8102-77784f091fb6.png)

If I add 'overflow' and 'text-overflow' properties to '.datagrid-cell' in _datagrid.clarity.scss then I can get the cell to look proper, but making similar change to '.datagrid-column' or '.datagrid-column-title' make the column resize handle disappear during times when it overflows.

```css
    .datagrid-cell {
        flex: 1 1 auto;
        overflow: hidden;
        text-overflow: ellipsis;
        &.datagrid-fixed-width {
            flex: 0 0 auto;
        }
    }
```

![image](https://cloud.githubusercontent.com/assets/1624021/25560127/3c257006-2d08-11e7-99fe-691d1952add8.png)

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.9.2

* **OS and version:** MacOS 10.12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment] 2017-05-01 15:03
First, as I mentioned in #618, we cannot and will not implement an `overflow: hidden` on the datagrid cells. They could contain anything, including stuff that should overflow (like tooltips). Knowing that it's very easy for you to simply add this overflow hidden and ellipsis in your CSS, just put putting a class on the "at risk" cells, there is really no reason for us to constrain everyone and break important customizability for one edge case.

More importantly, though, the datagrid handles this kind of long strings properly by making the datagrid scroll horizontally. You can see it on this plunker: https://plnkr.co/edit/Y9pVqbek8L5ftw5BiJ2A?p=preview

I'm closing this as a non-bug because of the overflow explanation, but if you do have a bug where the columns are not properly sized for long text and the datagrid doesn't scroll horizontally, please post a plunker of it. Because right now, we can't reproduce this. Thank you.

**Closed by youdz** 2017-05-01 15:03 UTC
Labels: bug, ClarityNG

**Comment by TechRazor** [comment] 2017-05-01 15:14
Thanks for the details @youdz. Currently I'm running into the same bug as #817 where the datagrid does not resize the columns on dynamically loaded data. Once I resize one of the cells, the datagrid updates and resizes all the cells to the proper size.

**Comment by youdz** [comment] 2017-05-01 15:21
Ok then, we'll try to fix #817 as soons as we can. 😄

**Comment by usmanajmal** [comment] 2017-09-25 22:04
Just wanted to mention that i am seeing the issue mentioned by Bug Reporter where I change width of different columns by dragging-dropping the column separators, after making following change in my css:

```
.datagrid .datagrid-column .datagrid-column-title {
  white-space: nowrap;
}
```

That's because I don't want the title to go to next line and I may show ellipses instead whenever the name gets longer.

**Comment by mathisscott** [comment] 2017-09-25 22:06
@usmanajmal 
you also need to use `overflow: hidden; text-overflow: ellipsis`
