### ISSUE TITLE
clr-dg-column-toggle throws an error when a filter dropdown is active

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#3785] opened 2019-09-04 12:59 UTC
## Describe the bug

clr-dg-column-toggle throws **TypeError: _this.menuDescriptionElement is undefined** when a filter dropdown is active then clr-dg-column-toggle stops responding

## How to reproduce

In order to reproduce we need a clr-datagrid with column filter and hidable columns

1. click on a filter so the dropdown active
2. click on the clr-dg-column-toggle

## Expected behavior

the clr-dg-column-toggle will respond properly after activation

## Versions

**App**

* Angular: 8.0.3
* Node: 10.15.0
* Clarity: 2.1.0
**Device:**

* Type: PC
* OS: Windows 10
* Browser Chrome, Firefox
* Version chrome ver.76, firefox ver.69

## Additional notes
no

**Comment by gnomeontherun** [comment] 2019-09-04 15:04
Please provide a stackblitz demo of your issue so we can triage it properly, thanks! https://stackblitz.com/@clr-team has some starters.

**Comment by Jinnie** [comment] 2019-09-04 15:10
I tried to unsuccessfully reproduce it on my dev env, but probably the issue is fixed with the forthcoming smart popovers update.
So please, do provide a stackblitz, as Jeremy requested above.

**Comment by iivanovgit** [comment] 2019-09-05 06:19
https://stackblitz.com/edit/clarity-light-theme-v2

click filter leave it active then click the hide/show toggle

**Comment by Jinnie** [comment] 2019-09-05 10:00
@iivanovgit You probably didn't [Save] it. I am seeing the default template.

**Comment by Jinnie** [comment] 2019-09-05 10:01
Actually, this is our own `@clr-team` template. Please, [Fork] it and post the fork URL with your changes. Thanks

**Comment by iivanovgit** [comment] 2019-09-06 13:50
my bad here is the correct link https://stackblitz.com/edit/clarity-light-theme-v2-dbxxqm

**Comment by gnomeontherun** [comment] 2019-09-06 15:56
This is fixed by #2923 which is now in 2.2.0, please update for the fix!

**Closed by gnomeontherun** 2019-09-06 15:56 UTC
Labels: status: need info, type: bug
