### ISSUE TITLE
clr-tooltip not conforming to the visual guidelines when used for validation

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#1383] opened 2017-08-29 06:51 UTC
[ ] bug
[X] feature request
[ ] enhancement

### Expected behavior
clr-tooltip component used for validation should conform to the guidelines listed in https://vmware.github.io/clarity/documentation/input-fields (section "Form Validation").

### Actual behavior
The visual guidelines referred to above apply to the markup-only version of the clarity tooltip and does not show if and how the clr-component (introduced in response to https://github.com/vmware/clarity/issues/37) can be used in validation scenarios as well.

Please provide us with a way to style the clr-tooltip similarly or advise us if the same styling is currently achievable.

### Reproduction of behavior
https://plnkr.co/edit/HiyU9Y1A7BSq3Cwap5jw?p=preview

### Environment details
* **Angular version:** 2.0.X
* **Clarity version:** 0.9.x
* **OS and version:** not applicable
* **Browser:** all

**Comment by mathisscott** [comment] 2017-08-29 13:45
Hi @ivvatov 
Thanks for checking back in. I believe you are referring to #835 (which is the issue that will answer a lot of the issues you've brought up with the tooltips used for input validation).

We are currently at the start of a large effort to improve forms in general and this item is part of that. 

I'm closing this as a duplicate of #835 to avoid confusion. Please subscribe to that issue so you can track its progress. Thanks!

**Closed by mathisscott** 2017-08-29 13:45 UTC
Labels: ClarityNG, duplicate
