### ISSUE TITLE
Signpost inside ng form is getting clipped

### ISSUE THREAD

**Issue by LokeshN** [vmware/clarity#1459] opened 2017-09-12 16:17 UTC
Signpost inside ng form is getting clipped

[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Signpost popup should not get clipped

### Actual behavior
https://plnkr.co/edit/Cto4ezZ2As6ydkFt5Dqg?p=preview

### Reproduction of behavior
https://plnkr.co/edit/Cto4ezZ2As6ydkFt5Dqg?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  All

* **OS and version:**  All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment] 2017-09-12 16:59
@LokeshN: Thanks for filing the issue. This should be fixed with #932 but I am keeping this open to make sure we test this case when the issue is fixed.

**Comment by gnomeontherun** [comment] 2018-08-16 18:05
This is resolved with the new form layouts, so signposts and other overlays should not clip.

**Closed by gnomeontherun** 2018-08-16 18:05 UTC
Labels: Bug, Dev
