### ISSUE TITLE
Include required Clarity component in code example documentation

### ISSUE THREAD

**Issue by moiraine** [vmware/clarity#3090] opened 2019-01-31 18:16 UTC
To optimize our code, we'd like to only import required modules, however finding out exactly which module to include is not always straight forward.

Proposal is to include in the Code/Examples section which specific module is required, to avoid having developers include the whole ClarityModule when not necessary.

**Comment by youdz** [comment] 2019-01-31 18:35
@gnomeontherun: You were saying Angular and the CLI now properly drop unused submodules and components from the production bundle. Is that confirmed? If so, then this is a non-issue since there is actually no "optimization" in importing anything other than `ClarityModule`.

**Comment by moiraine** [comment] 2019-01-31 19:03
Does this also optimize for tests?  That was also one of our pain points

**Comment by gnomeontherun** [comment] 2019-02-01 03:34
For the application, including the `ClarityModule` is sufficient when you use the Angular CLI, as it will drop any of the unused modules. So manually including individual modules is not necessary and adds maintenance overhead on your end.

However, for your tests you should import just the Clarity modules for the components you use, or if you aren't necessarily testing anything with the components behaviors you could set the schema to allow for `CUSTOM_ELEMENTS_SCHEMA` and not load them into your tests. I would avoid testing Clarity components in your unit tests, if you are then you might be writing tests that are better suited for e2e or could be refined.

**Comment by youdz** [comment] 2019-02-01 13:43
Yes, the testing use case is real though, you need to import specific modules if you don't want to recompile everything every time. And CUSTOM_ELEMENT_SCHEMA doesn't let you test that you **integrated** the Clarity component correctly, which is a huge part of unit testing an app's component.

So I'm tagging this as a docs issue that we do need to address.

**Comment by gnomeontherun** [comment] 2020-10-29 20:32
No longer an issue or resolved in the upcoming website work. Closing as resolved.

**Closed by gnomeontherun** 2020-10-29 20:32 UTC
Labels: type: website
