### ISSUE TITLE
After removing all elements from datagrid, the view is not rendering newly added rows

### ISSUE THREAD

**Issue by KalinNikolov** [vmware/clarity#5605] opened 2021-02-15 06:51 UTC
## Describe the bug

I have two datagrid components and I'm adding elements from the first datagrid to the second. I'm also removing elements from the second one. So when the second one becomes empty, the view is not updated after adding new elements to it.

## How to reproduce

https://stackblitz.com/edit/datagrid-add-elements?file=src/app/app.component.ts

1. Select element from first datagrid and add it to the second one.
2. Select the newly added in the second datagrid and remove it.
3. Try again to add from first datagrid to the second.
4. Result: Element is added, but the view is not updated.

## Expected behavior

Element is added and view is updated.

## Versions

**Clarity project:**

- [ v4.0.11] Clarity Core
- [v4.0.11 ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular v10.0.2

**Comment by bbogdanov** [comment] 2021-02-15 12:44
https://github.com/vmware/clarity/blob/87b6464f52477da4d1fd3c59ba7f51f28e99e45f/packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts#L241 

Seems like the ViewContainer is missing when we try to insert a row into the datagrid. I'll continue to dig into this but after some investigation, I believe it is a bug on our side.

**Comment by KalinNikolov** [comment] 2021-02-19 13:42
Hi,

Any new findings on that? 
If is a clarity issue, are there any plans to fix it in future v4 patch release?


Kalin

**Comment by gnomeontherun** [comment] 2021-02-19 15:04
I think the first issue here is mutating the array instead of reassigning a modified array, which messes with equality checks. Instead of using splice, push, etc, you should always try to create a temporary array, and then assign it and see if that solves your issue.

**Comment by KalinNikolov** [comment] 2021-02-19 15:56
@gnomeontherun just tried you suggestion, but the issue still exists.

**Comment by gnomeontherun** [comment] 2021-02-19 17:29
Here is an updated Stackblitz that is working. The problem is the pagination has an NgIf which tries to toggle pagination and causes some lifecycle issues. You have another one on the inside container as well, so that should do the trick for you. Putting a template variable on something that is also a template (`*ngIf` turns a node into a template) pulls the rendering of the pagination out of normal lifecycle and causes the expression changed errors, which is the root issue here. Simply removing the NgIf on the clr-dg-pagination element fixes the issue, and has no change to visual experience.

https://stackblitz.com/edit/datagrid-add-elements-thcqm4?file=src%2Fapp%2Fapp.component.html

Closing as an implementation issue.

**Closed as completed by gnomeontherun** 2021-02-19 17:29 UTC
Labels: type: bug, resolution: no fix needed, component: datagrid, @clr/angular
