### ISSUE TITLE
Extra scrollbar appears for no reason in datagrid if the last column is hidden

### ISSUE THREAD

**Issue by combine13** [vmware/clarity#2456] opened 2018-07-13 13:32 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
This extra scrollbar is useless and should not appear there if the last column is hidden. 

### Actual behavior
When you have datagrid (clr-datagrid) if the last column is hidden, a horizontal scrollbar appears under the datagrid. The scrollbar is useless and can be moved just a little bit.

### Reproduction of behavior
See the attached file - clarity.txt - there is working datagrid example that is showing this behaviour.

![claritybug](https://user-images.githubusercontent.com/5833879/42694695-ea3d47dc-86bb-11e8-8034-433da431bd97.png)

[clarity.txt](https://github.com/vmware/clarity/files/2192789/clarity.txt)

### Environment details

* **Angular version:** 4.x.x
5.2.9
* **Clarity version:**
0.11.9
* **OS and version:**
Linux Mint 18.2 64bit Cinnamon

* **Browser:** all

**Comment by gnomeontherun** [comment] 2018-07-13 21:17
Please provide a stackblitz with your issue isolated so we can more easily triage your issue, otherwise it takes us longer to get to it.

**Comment by youdz** [comment] 2018-07-17 16:33
Duplicate of #1248, please subscribe to that issue for updates.

**Closed by youdz** 2018-07-17 16:33 UTC
Labels: Awaiting More Info
