### ISSUE TITLE
Where is my grave accent?

### ISSUE THREAD

**Issue by TMilasius** [vmware/clarity#2967] opened 2018-12-23 15:02 UTC
## Describe the bug

While typing text into an input field (including textarea) for some reason only first grave accent (`) gets displayed. Any following grave accents seems to overlay on top of the first one. This doesn't seem to be affected by the browser, i.e., it can be reproduced using Firefox and Chrome (haven't tested others). On top of that, Angular without Clarity doesn't have this "feature".

## How to reproduce

Try entering grave accents one after another into input/ textarea.
https://stackblitz.com/edit/clarity-light-theme-v1-0-f8rgua

1.  Go to https://vmware.github.io/clarity/documentation/v1.0/input
2.  Scroll down to input field.
3.  Hit grave accent key multiple times on the keyboard.
4.  See all of them displayed as a single grave accent instead of one followed by another.

## Expected behavior
Grave accents should be displayed one after another, instead of overlaying one another.

## Versions

**App**

* Angular: 6.1.0
* Node: 11.5.0
* Clarity: 1.0.2

**Device:**

* Type: Laptop
* OS: Win10
* Browser: Chrome 71.0.3578.98 (Official Build) (64-bit) & Firefox 64.0 (64-bit)

## Additional notes

None.

**Comment by youdz** [comment] 2018-12-23 15:56
Duplicate of #1521, it's a Metropolis bug.

Not sure what the status on this is, since it's the font itself that is bugged. Please subscribe to #1521 for further updates.

**Closed by youdz** 2018-12-23 15:56 UTC

**Comment by mattmutt** [comment] 2019-07-09 23:24
backticks are hiding in a PR. It was a flaw with the font metrics for that keycode

https://github.com/vmware/clarity/pull/3353
