### ISSUE TITLE
Cannot customize aria-label for each checkbox/radiobutton that generated by datagrid when configured with clrDgSelected/clrDgSingleSelected

### ISSUE THREAD

**Issue by xuelichao** [vmware/clarity#5999] opened 2021-05-26 08:27 UTC
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

There are checkboxes and radio buttons in the tables however the controls don't have any name associated with them and are announced with just the role and state information(aria-label="Select", it is hard-coded now)
`<div role="gridcell" class="datagrid-select datagrid-fixed-column datagrid-cell ng-star-inserted">`
`<clr-checkbox-wrapper class="clr-checkbox-wrapper ng-star-inserted">`
`<input clrcheckbox="" type="checkbox" aria-label="Select" id="clr-dg-row-cb37" class="ng-untouched ng-pristine ng-valid">`
`<label class="clr-control-label ng-star-inserted" for="clr-dg-row-cb37"></label>`
`</clr-checkbox-wrapper>`
`</div>`

## How to reproduce
It can be reproduce with datagrid that configured with 'clrDgSelected/clrDgSingleSelected' in version 4.x and 5.x

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior
All interactive elements should have a proper name that conveys the purpose of the elements to screen reader users.
1. As the checkbox / radio button controls are used here for selecting a row.
it can use the value in the Name column(or any other column) as the label for the checkbox / radio control so that they have a proper name that conveys their purpose to screen reader users. The value in the Name column can be associated with the controls using an aria-label or aria-labelledby.
2. Or expose a new input directive on datagrid row that user can use it to pass label value to it.

_A clear and concise description of what you expected to happen._

## Versions
4.x/5.x

**Clarity project:**

- [ ] Clarity Core
- [*] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [*] v4.x
- [*] v5.x

**Framework:**

- [*] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook] mac
- Browser [e.g. chrome, safari] chrome 
- Version [e.g. 22] 90

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment] 2021-06-02 12:41
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed as completed by Jinnie** 2021-06-02 12:41 UTC
Labels: resolution: tracked by a11y
