### ISSUE TITLE
Issue with using Filters on Datagrid with one row

### ISSUE THREAD

**Issue by gauranirudh** [vmware/clarity#3111] opened 2019-02-14 09:41 UTC
## **Problem** :
If the Datagrid has only one row, clicking on the filters moves the row upwards which make the row invisible.

## **How to reproduce**
1. Go to https://clarity.design/documentation/datagrid/full
2. Select Number of users as 1
3. Click on the filter for any column
4. See the row data is not visible anymore

## Actual behavior
![datagrid filters](https://user-images.githubusercontent.com/34673679/52777896-200b5100-3045-11e9-8ee5-f68ee0a5231e.gif)

## Expected behavior

The Row Data should not move up and should be visible after clicking on the filters

## Versions

**App**

* Angular: 7
* Clarity: [1.0]

**Device:**

* Type: [e.g. Lenovo]
* OS: [Windows]
* Browser [Chrome ]
* Version [71.0.3578.98]

**Comment by hippee-lee** [comment] 2019-02-14 18:42
This is a duplicate of https://github.com/vmware/clarity/issues/2683. Please subscribe to that for updates. FYI - I am actively working on a fix for these issues.

**Closed by hippee-lee** 2019-02-14 18:42 UTC
