### ISSUE TITLE
[CSS] Reusing Clarity colors 

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#3979] opened 2019-11-04 19:12 UTC
Hi,

In the previous version of Clarity there was a file called "dependencies.clarity" which included all clarity variables/mixins at one place. We used it to include it in our own components' sass files in order to use clarity's variables/mixins. 

In the latest version there is such file. What is your recommendation for consuming Clarity's variables/mixins?

**Comment by gnomeontherun** [comment] 2019-11-04 23:03
What version are we talking about here? We have issue templates to help fill out useful information like a reproduction if there is a bug or answer questions like what versions of Clarity and Angular you are using, please use them in the future to help organize content better. There is some theming documentation coming for v3 which hasn't landed yet, and probably will address these questions unless its about another version of Clarity.

**Comment by gnomeontherun** [comment] 2020-04-01 00:41
Hello @ttsvetko, due to inactivity on this issue we're closing it per our issue management policy. If you are able to provide additional details and a reproduction of the issue, we can reopen the ticket as necessary.

**Closed by gnomeontherun** 2020-04-01 00:41 UTC
Labels: status: needs reproduction, type: support
