### ISSUE TITLE
Loading mask/overlay does not cover the whole grid if that is too wide

### ISSUE THREAD

**Issue by zlevai** [vmware/clarity#2888] opened 2018-11-27 13:23 UTC
## Describe the bug

Loading mask/overlay does not cover the whole grid if that is too wide. It means the grid and paging panel does not seems to be disabled (and no loading animation bar displayed). It happens because we displays many of columns, the grid is too wide.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clr-loading-overlay-bug
2.  Scroll to right side to the paging bar
3.  Click on next page button (or do some paging action) -> Next page will be loaded

## Actual result
No loading mask displayed. Grid and paging panel is enabled

## Expected behavior

Loading mask (overlay) should be shown while the next page will be loaded. Grid and paging panel should be disabled.

## Versions

Angular CLI: 6.1.9
Node: 8.11.2
Clarity: 0.13.4

**Device:**
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)

## Additional notes

It works correctly with just a few columns.
Request: Can the paging panel be kept on a fix position? User should not scroll there for navigating to next page etc.

**Comment by youdz** [comment] 2018-11-27 14:01
>Request: Can the paging panel be kept on a fix position? User should not scroll there for navigating to next page etc.

StackBlitz can't let me see the dependencies of your demo for some reason, and I can't seem to be able to update them, so I can't check. But I can tell you that the `1.0.0` version of the datagrid keeps the footer in place, so you don't have to scroll to move to a new page.

Because of this, I'm going to re-label this to check if it still happens with 1.0.0-rc.

**Comment by zlevai** [comment] 2018-11-27 14:14
@youdz , thanks for your feedback. 

"@clr/angular": "^0.13.6",
"@clr/icons": "^0.13.6",
"@clr/ui": "^0.13.6",

Then we ar goint to upgrade to 1.0.0.

**Comment by youdz** [comment] 2018-11-27 14:19
Ok, I just reproduced with a 1.0 stackblitz, it's all fixed in 1.0 (both the overlay and the pagination scroll): https://stackblitz.com/edit/clarity-light-theme-v1-0?file=src%2Fapp%2Fapp.component.ts

Closing this as already fixed. 🙂

**Closed by youdz** 2018-11-27 14:19 UTC
Labels: Dev, Needs Investigation
