### ISSUE TITLE
Button spinner is barely visible on primary buttons

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1410] opened 2017-09-03 02:51 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

I used the Login component and enable the spinner in the button using clrLoading. The spinner should be visible enough in a darker button. The button I used is the default Login button of the Login component.

### Actual behavior

Button spinner is barely visible in a primary button
![image](https://user-images.githubusercontent.com/1977391/30000170-a36f3d42-9094-11e7-9e3a-e359d44c63e1.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3

* **Clarity version:** 0.10.3

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-09-04 19:46
Hi @whizkidwwe1217 
Thanks for the feedback. We're currently working on issue #1139 which appears to be a duplicate of this issue.

Please subscribe to that issue. Thanks!

**Closed by mathisscott** 2017-09-04 19:46 UTC
