### ISSUE TITLE
Search function for the documentation

### ISSUE THREAD

**Issue by webia1** [vmware/clarity#4201] opened 2020-01-14 08:42 UTC
A search function for the documentation would be great, thank you!

**Comment by hippee-lee** [comment] 2020-01-14 17:57
Thanks, we have wanted to do this since the beginning but it has been a challenge to make it a priority. 

We are planning to devote some dev cycles to the website and documentation in the coming months. When discussed we considered several options for implementing search functionality.If you have any ideas or suggestions for tooling to add browser search to a static site, please add them here.

**Comment by webia1** [comment] 2020-01-17 09:54
one of the easiest  ways is [Algolia](https://www.algolia.com/)

**Comment by gnomeontherun** [comment] 2020-01-17 16:30
This is has been on our radar for a while, I've even tested with Algolia. The problem is our content is not in a format that is easy to upload currently, which we'll be addressing soon.

**Comment by mathisscott** [comment] 2020-02-04 21:47
This will be taken care of as part of #4005.

**Comment by gnomeontherun** [comment] 2020-10-29 20:35
No longer an issue or resolved in the upcoming website work. Closing as resolved.

**Closed by gnomeontherun** 2020-10-29 20:35 UTC
Labels: needs: design, priority: 1 low, type: enhancement, type: website
