### ISSUE TITLE
Clarity Core: cds-button type="button" being ignored

### ISSUE THREAD

**Issue by andresmgot** [vmware/clarity#5038] opened 2020-09-14 16:51 UTC
## Describe the bug

Hi, I'm using @clr/core components in a React application. In particular the cds-button (https://clarity.design/storybook/core/?path=/story/components-button-getting-started--page).

I've recently upgraded to `4.0.1` and noticed a bug. I have the following button:

```tsx
import { CdsButton } from "@clr/react/button";
import { CdsIcon } from "@clr/react/icon";
...
        <CdsButton action="outline" type="button" onClick={openRestoreDefaultValuesModal}>
          <CdsIcon shape="backup-restore" inverse={true} /> Restore Defaults
        </CdsButton>
```

This gets rendered to (thanks to the react wrapper):

```js
<cds-button tabindex="0" action="outline" type="button" role="button" status="primary" size="md" loading-state="default"><cds-icon slot="button-icon" role="none" shape="backup-restore" inverse="" inner-offset="0"></cds-icon> Restore Defaults
<button aria-hidden="true" tabindex="-1" style="display: none" value="part => {
  const previousValue = previousValues.get(part);

  if (value === undefined &amp;&amp; part instanceof _lit_html_js__WEBPACK_IMPORTED_MODULE_0__[&quot;AttributePart&quot;]) {
    // If the value is undefined, remove the attribute, but only if the value
    // was previously defined.
    if (previousValue !== undefined || !previousValues.has(part)) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else if (value !== previousValue) {
    part.setValue(value);
  }

  previousValues.set(part, value);
}" name="part => {
  const previousValue = previousValues.get(part);

  if (value === undefined &amp;&amp; part instanceof _lit_html_js__WEBPACK_IMPORTED_MODULE_0__[&quot;AttributePart&quot;]) {
    // If the value is undefined, remove the attribute, but only if the value
    // was previously defined.
    if (previousValue !== undefined || !previousValues.has(part)) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else if (value !== previousValue) {
    part.setValue(value);
  }

  previousValues.set(part, value);
}" type="part => {
  const previousValue = previousValues.get(part);

  if (value === undefined &amp;&amp; part instanceof _lit_html_js__WEBPACK_IMPORTED_MODULE_0__[&quot;AttributePart&quot;]) {
    // If the value is undefined, remove the attribute, but only if the value
    // was previously defined.
    if (previousValue !== undefined || !previousValues.has(part)) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else if (value !== previousValue) {
    part.setValue(value);
  }

  previousValues.set(part, value);
}"></button></cds-button>
```

As far as I can see, the inner `<button>` loses the `type` property, causing the `form` in which the `CdsButton` is placed to be submitted. Let me know if I am missing something.

## Versions

**App**

- React: ^16.13.0,
- Node: v12.18.1
- Clarity: 4.0.1

**Comment by coryrylan** [comment] 2020-09-15 16:40
Hmm interesting, can you make the broken behavior reproducible in stackblitz? Here is a link to a example and it seems to be working here https://stackblitz.com/edit/react-ts-xwsjue

**Comment by andresmgot** [comment] 2020-09-16 09:43
hmm, true, I am not able to reproduce it with stackblitz, it has to be something on my side. The culprit seems to be `lit-html` which is a dependency of `@clr/core@^4.0.1`. I've noticed that the code that gets injected within the `type` property comes from it:

https://lit-html.polymer-project.org/api/modules/_directives_guard_.html
```
type="part => {
  const previousValue = previousValues.get(part);

  if (value === undefined &amp;&amp; part instanceof _lit_html_js__WEBPACK_IMPORTED_MODULE_0__[&quot;AttributePart&quot;]) {
    // If the value is undefined, remove the attribute, but only if the value
    // was previously defined.
    if (previousValue !== undefined || !previousValues.has(part)) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else if (value !== previousValue) {
    part.setValue(value);
  }

  previousValues.set(part, value);
}"
```

I suspect that the code is properly resolved in the stackblitz environment but it's escaped in my environment causing the bug. The major difference I can see is that you were using `react-script-ts` and I'm using `react-scripts` to generate the app but I've changed that in stackblitz and I am still not able to reproduce it.

Any suggestion where can I look next? :thinking:

**Comment by mathisscott** [comment] 2020-10-02 13:37
@andresmgot 
I tried to dig into this further but unearthed nothing that has not already been discussed. Like @coryrylan, I cannot reproduce the issue so I will close it as such. It appears to be either build-related or some configuration on the framework side. As such, I will close this issue. If you find a way to reproduce this issue in a way that we can investigate it further, I'd be happy to take a look.

**Closed by mathisscott** 2020-10-02 13:37 UTC
Labels: @clr/react, type: support
