### ISSUE TITLE
[vmw-h5] Checkboxes and filter controls in data grid do not provide sufficient contrast with their background

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#4402] opened 2020-03-25 07:44 UTC
## Describe the bug

Checkboxes and filter controls in the data grid header have a gray color against a light gray background with color contrast 2.8:1

## How to reproduce

- Go to https://clarity.design/documentation/datagrid/full
- on the first grid there
- check the contrast of the multiple selection checkbox in the header of the first grid + the filter popup toggle control

## Expected behavior

Adjust the foreground/background colors of these elements to achieve a minimum 3.0:1 foreground/background color contrast.
## Versions

**App**

* Angular: 9.0.0
* Node: N/A
* Clarity: 3.0.0

**Device:**

* Type: MacBook
* OS: OSX
* Browser Chrome
* Version 80.0.3987.132

**Comment by lf-collins** [comment] 2020-03-30 08:38
Same issue on other controls:

1. Select: https://clarity.design/documentation/select
<img width="847" alt="Screen Shot 2020-03-30 at 3 17 48 PM" src="https://user-images.githubusercontent.com/26111301/77885590-e1ad1180-7299-11ea-8f8a-8a2016c2b74c.png">

2. Datagrid
Filter: https://clarity.design/documentation/datagrid/custom-filtering
<img width="238" alt="Screen Shot 2020-03-30 at 3 20 35 PM" src="https://user-images.githubusercontent.com/26111301/77885781-39e41380-729a-11ea-864c-dde8cee48284.png">
<img width="486" alt="Screen Shot 2020-03-30 at 3 29 53 PM" src="https://user-images.githubusercontent.com/26111301/77886423-6a787d00-729b-11ea-9f87-3c6ca058254a.png">
Batch action: https://clarity.design/documentation/datagrid/batch-action 
<img width="561" alt="Screen Shot 2020-03-30 at 3 42 31 PM" src="https://user-images.githubusercontent.com/26111301/77887445-2a19fe80-729d-11ea-971e-977048839f0e.png">

3. Input: https://clarity.design/documentation/input
<img width="283" alt="Screen Shot 2020-03-30 at 3 35 11 PM" src="https://user-images.githubusercontent.com/26111301/77886839-28037000-729c-11ea-9156-71d27fd07d24.png">

4. Treeview: https://clarity.design/documentation/tree-view
![Screen Shot 2020-03-30 at 4 31 37 PM](https://user-images.githubusercontent.com/26111301/77891794-18882500-72a4-11ea-9447-91300bd834a8.png)

5. Wizards: https://clarity.design/documentation/wizards
<img width="593" alt="Screen Shot 2020-12-14 at 1 33 27 PM" src="https://user-images.githubusercontent.com/26111301/102044129-27524000-3e11-11eb-8925-2bccb8cb2d93.png">

6. Checkboxes: https://clarity.design/documentation/checkboxes
<img width="119" alt="Screen Shot 2020-12-14 at 12 01 03 PM" src="https://user-images.githubusercontent.com/26111301/102039250-37175780-3e04-11eb-86f8-feb9fb31b146.png">

**Comment by hippee-lee** [comment] 2020-03-30 16:21
@colinreedmiller - can you comment on this issue? Is it something that your research has identified?

**Comment by colinreedmiller** [comment] 2020-03-30 16:38
WCAG 2.1 - 1.4.11 Non-text contrast
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
UI controls must meet 3:1 to be compliant - based on what is described in this issue we need to assess and adjust the items in question.
Adding @sheribyrne for confirmation.

**Comment by sheribyrne** [comment] 2020-03-30 16:48
Yes, that is correct.

Sheri

**Comment by gnomeontherun** [comment] 2021-02-01 22:50
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:50 UTC
Labels: @clr/angular, component: datagrid, component: forms, component: tree view, needs: design, priority: 3 medium, status: backlog, type: accessibility
