### ISSUE TITLE
Wizard's Page commit handler not called every time

### ISSUE THREAD

**Issue by sagar-ganatra** [vmware/clarity#3202] opened 2019-03-09 18:11 UTC
## Describe the bug

The `clrWizardPageOnCommit` handler is not called when the user navigates back to one of the pages and then clicks NEXT

## How to reproduce

https://clarity-wizard-page-commit.stackblitz.io

From the above example

1.  Page 1 - Click NEXT, you're navigated to Page 2, note that the page commit handler is called
2. Click BACK, you're navigated to Page 1
3. Click NEXT, the page commit handler is not called

## Expected behavior

Here `clrWizardForceForwardNavigation` is set to true and the page commit handler should be called when you click the NEXT button every time you navigate back and forth between the pages

## Versions

**App**

* Angular:  7
* Node:  8.10.0
* Clarity: 1.0.5

**Device:**

* Type: MacBook
* OS: MacOS
* Browser Chrome, Safari, any
* Version: Latest

## Additional notes

I have debugged this and found that the `completed` flag is set to true for the given page when the user clicks the 'NEXT' button. A check is added where the page commit function is called only if `completed` flag is false for the given page. However, when the user navigates back and forth between the pages since the `completed` flag is set to true the `clrWizardPageOnCommit` handler is not called.

**Comment by gnomeontherun** [comment] 2019-03-19 13:04
This is currently as designed, because it is marked as completed. There is no 'commit' action taken, therefore no commit handler call.

If you want to track clicks to the next button, use the `<clr-wizard-page (clrWizardPageNext)="">` to listen to a specific page (regardless of the commit action), or `<clr-wizard (clrWizardOnNext)="">` to listen to all next events.

Closing as working as intended.

**Closed by gnomeontherun** 2019-03-19 13:04 UTC
Labels: Needs Triage
