### ISSUE TITLE
Combobox emits null when all characters removed from input

### ISSUE THREAD

**Issue by jzabinski** [vmware/clarity#5564] opened 2021-02-04 16:30 UTC
## Describe the bug

When a combobox option is chosen, removing all input causes the combobox to emit `null`, regardless of whether `null` is a valid combobox option.

## How to reproduce

Stackblitz templates don't seem to be working right now. (See [issue #5559](https://github.com/vmware/clarity/issues/5559).) [This repository](https://github.com/jzabinski/clarity-combobox-emits-null) reproduces the bug. 

1. Download the repository.
2. `npm install`
3. `ng serve`
4. Open `localhost:4200/` on a browser.
5. You will see a combobox at the top left. Click the dropdown arrow to open the dropdown.
6. Choose something from the dropdown. Note that the combobox output is displayed to the right of the combobox. Example: choose 'ac', and 'ac' will appear to the right of the combobox.
7. While focused at the end of the combobox input, click Backspace. Notice that the input now displays 'a', and the combobox output does not change. (The dropdown continues to display with all results containing 'a'.) This shows that the combobox is likely designed to only emit output when one of the dropdown options is chosen.
8. Click Backspace again.

Notice that the combobox outputs `null`. `null` is not one of the available dropdown options.

## Expected behavior

The combobox should only emit when a valid option is chosen.

## Versions

**App**

- Angular: 11.1.2
- Node: 12.13.1
- Clarity: 5.0.0/5.0.0-next.0

**Device:**

- Type: PC (HP Elitebook)
- OS: Windows
- Browser: Chrome
- Version: 89

## Additional notes

This has an easy workaround: ignore `null` if need be when processing combobox emits. But emitting `null` may not have been by design.

**Comment by hippee-lee** [comment] 2021-02-05 00:28
Thanks for the report and sorry about Stackblitz :( 
We will triage and get this into the backlog once we know more about what is going on.

**Comment by hippee-lee** [comment] 2021-02-05 00:34
Stackblitz version of the repo from above: https://stackblitz.com/edit/gh-issue-5564-clarity-combobox-emits-null

**Comment by Jinnie** [comment] 2021-02-17 13:46
Thanks for bringing this to our attention. 
It actually behaves correctly, because the single-selection combobox needs to have means for removing the selection. Similarly to the W3C examples we do it when the input field is cleared. So, there is a real "deselection event" happening and the `null` was expected.
Looking at your 7. question - the answer is "...the combobox is ~likely~ designed to only emit output when one of the dropdown options is chosen _or when the value is cleared_"
I'll close this as working as designed. If you have other ideas or preferences, feel free to log them in the [Discusions](https://github.com/vmware/clarity/discussions) section, so they can be considered when working on the Clairty Core version of the Combobox.

**Closed as completed by Jinnie** 2021-02-17 13:46 UTC
Labels: resolution: wontfix, @clr/angular, component: combobox
