### ISSUE TITLE
Enhancement request to provide an option to disable checkbox in clr-tree-node

### ISSUE THREAD

**Issue by raom7** [vmware/clarity#1765] opened 2017-12-12 03:09 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Enhancement request for clr-tree-node to provide an option to disable the checkbox for a checkbox tree node.

### Actual behavior
Current behavior is that we cannot disable a checkbox from selection.

### Reproduction of behavior
This is an enhancement request.

### Environment details

* **Angular version:** 4.3.x

* **Clarity version: 0.10.12

* **OS and version: Windows 10

* **Browser:** [all]

**Comment by youdz** [comment] 2017-12-12 13:35
Duplicate of #1458.

**Closed by youdz** 2017-12-12 13:35 UTC
