### ISSUE TITLE
Focus not moving into modal when open button is last focusable item in page

### ISSUE THREAD

**Issue by WhiteLord** [vmware/clarity#4355] opened 2020-03-10 12:54 UTC
## Describe the bug

Using Clarity 2.0 and Angular 8.0, I create a modal window and expect that the focus would be "trapped" in the modal only.
However, the focus is not trapped, and every single element behind the modal is accessible.
I'm having a specific case where I open a modal window inside an iframe and I observe that every element in the iframe and even outside is accessible.

## How to reproduce

Create some buttons, an iframe, some buttons in the iframe, and add a modal window. 

## Steps to reproduce the behavior:

Stackblitz example: https://stackblitz.com/edit/clarity-iframe-modals?file=src%2Fapp%2Fapp.component.html

## Expected behavior

Only elements in the modal window should be accessible.

## Versions

**App**

* Angular: [6
* Node: [10+]
* Clarity: [2.0.0]

**Device:**
* Type: [MacBook]
* OS: [macOS Mojave]
* Browser [Chrome 80.0.3987.x, FF 73.0.1]

## Additional notes

None

**Comment by gnomeontherun** [comment] 2020-03-10 21:50
This demo is showing a static modal, which has no focus trapping. Only the Angular modal does, and changing this modal to an Angular version works fine. Closing this as not a bug, as the static HTML version does not have any implementation to trigger the focus trap (or open/close behaviors).

**Comment by WhiteLord** [comment] 2020-03-12 08:42
Thanks for the clarification. 
I've updated the stackblitz example I've provided, so that the modal could be dynamically opened on a button click.
I expect this to now trap focus, but it does not.

**Comment by gnomeontherun** [comment] 2020-03-12 21:41
Thanks for following up, I've looked into it a bit more. The iframe is a red-herring, the problem appears to be that our focus trap isn't moving the focus into the modal when the open button is the last focusable item on the page. The iframe is not important here, if you simply add another button after the open modal button, it works as expected with or without the iframe.

This is a bug, but the workaround is to make sure your modal open button isn't the last item on the page. See if that helps for now, and we'll look at this bug.

**Comment by Shijir** [comment] 2020-03-12 21:44
@gnomeontherun I am pretty sure if you upgrade to Clarity V3, that issue won't be present. Because we placed the focus rebounder elements right above and below the modal's host element.

**Comment by gnomeontherun** [comment] 2020-03-12 22:02
Thanks @shijir, you are right that it is fixed by v3 by https://github.com/vmware/clarity/pull/3787 and/or https://github.com/vmware/clarity/pull/4027. I'm not sure we can backport that fix either, as it would be difficult to be sure it doesn't have side effects.

Even so in v2 the workaround is to ensure the button is not the last element of the page.

**Comment by Shijir** [comment] 2020-03-12 22:28
Yes this https://github.com/vmware/clarity/pull/4027 PR can be backported to solve the issue. We just need isolate and backport the focus trap related part.

**Comment by WhiteLord** [comment] 2020-03-14 07:18
I'll try bumping Clarity version to v3 and moving the code block elsewhere to see if that works. 
Thanks for the help, guys!

**Comment by gnomeontherun** [comment] 2021-02-05 22:29
This should be resolved in Clarity v3, so closing as resolved.

**Closed by gnomeontherun** 2021-02-05 22:29 UTC
Labels: @clr/angular, component: modal, flag: has workaround, status: needs investigation, type: bug, v2
