### ISSUE TITLE
Single action click of datagrid will cause scroll auto jump if whole page only has one scrollbar and it is on body

### ISSUE THREAD

**Issue by sheguloves** [vmware/clarity#5342] opened 2020-12-01 02:06 UTC
## Describe the bug

Single action click of datagrid will cause scroll auto jump if whole page only has one scrollbar and it is on body

## How to reproduce

1.  Scroll down the page
2.  Click on single action icon
3.  Scrollbar auto jump to top

## Expected behavior

Scrollbar should keep current position

## Versions

**App**

- Angular: 9.1.12
- Node: 10.16.1
- Clarity: 3.1.5

**Device:**

Chrome

**Comment by bbogdanov** [comment] 2020-12-01 08:23
Hi @sheguloves, can you please provide us a stackblitz example? Thanks!

**Comment by xlucvvs** [comment] 2020-12-07 20:48
same issue here

**Comment by hippee-lee** [comment] 2020-12-07 21:18
It sounds like the issue here is when a datagrid is not placed inside the `.content-area` as described in the [application layout ](https://clarity.design/documentation/app-layout)docs. 

We recommend putting the datagrid inside that container to get proper style and behavior. If this isn't possible please create an isolated reproduction and give us as much details for the use case that forces the app to put it outside of the recommended container. We keep starter applications [here](https://stackblitz.com/@clr-team) for isolating and reproducing issues.

**Comment by xlucvvs** [comment] 2020-12-08 13:43
> It sounds like the issue here is when a datagrid is not placed inside the `.content-area` as described in the [application layout ](https://clarity.design/documentation/app-layout)docs.
> 
> We recommend putting the datagrid inside that container to get proper style and behavior. If this isn't possible please create an isolated reproduction and give us as much details for the use case that forces the app to put it outside of the recommended container. We keep starter applications [here](https://stackblitz.com/@clr-team) for isolating and reproducing issues.

https://stackblitz.com/edit/clarity-v4-light-theme-fakdmw? the code is something like this

**Comment by hippee-lee** [comment] 2020-12-08 19:07
That stackblitz isn't running for me, even if I disable Ivy. 
[Here is a forked version](https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report) that disables ivy and gets around the ngcc issue in stackblitz. Please update it to compile and run without errors so that I can take a look.

**Comment by xlucvvs** [comment] 2020-12-09 12:45
> That stackblitz isn't running for me, even if I disable Ivy.
> [Here is a forked version](https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report) that disables ivy and gets around the ngcc issue in stackblitz. Please update it to compile and run without errors so that I can take a look.

so sorry @hippee-lee, u can see the issue here: https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report-9x6f2g

**Comment by sheguloves** [comment] 2020-12-22 06:43
> > That stackblitz isn't running for me, even if I disable Ivy.
> > [Here is a forked version](https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report) that disables ivy and gets around the ngcc issue in stackblitz. Please update it to compile and run without errors so that I can take a look.
> 
> so sorry @hippee-lee, u can see the issue here: https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report-9x6f2g

@xlucvvs Thanks for your stackblitz example. It works and shows the issue. 

@hippee-lee I checked the code and found that the issue is caused by action item focus. When action pop up, Clarity focus the first item and it cause the issue. 

The root cause is following

```
.datagrid-action-overflow {
    position: absolute; // To make action popover keep current related postion with the row when scrolling
}
```

Once datagrid action overflow DOM element is appended to `document.body`, the following code will be executed. Then the datagrid action overflow DOM element is focused with absolute position. If document.body scrollbar shows with scrolltop is none-zero, then scrollbar will jump to top.

```
focus() {
    if (isPlatformBrowser(this.platformId)) {
      this.renderer.setAttribute(this.el.nativeElement, 'tabindex', '0');
      this.el.nativeElement.focus();
    }
  }
```

**Comment by xlucvvs** [comment] 2020-12-22 12:35
@sheguloves the code is located in which file?

**Comment by xlucvvs** [comment] 2020-12-22 12:57
@sheguloves doesn't work here, I found this line in 4 files, even commenting on all the files it didn't work.

**Comment by sheguloves** [comment] 2020-12-23 03:10
> @sheguloves doesn't work here, I found this line in 4 files, even commenting on all the files it didn't work.

@xlucvvs Sorry for miss leading. I just found the root cause.

```
focus() {
    if (isPlatformBrowser(this.platformId)) {
      this.renderer.setAttribute(this.el.nativeElement, 'tabindex', '0');
      this.el.nativeElement.focus();  // Set focus will cause scrollbar jumping
    }
  }
```
```
.datagrid-action-overflow {
      position: absolute;  // Related with focus
}
```

As comments says, change position to `fixed` to fix scrollbar jumping with the disadvantage: datagrid-action-overflow DOM element will keep current position which means it will not be aligned with datagrid row when datagrid is scrolling.

**Comment by xlucvvs** [comment] 2020-12-23 14:09
@sheguloves I think that is some problem with the element's scrollToClose, 'cause in the Datagrid documentation, you can see that if you scroll the page, the element will be hidden. Looking in the file you mentioned above, I found the line of code:
`* clrPopoverContent =" open; at: smartPosition; outsideClickToClose: true; scrollToClose: true ` 
Where scrollToClose is probably not working...

**Comment by gnomeontherun** [comment] 2021-01-04 16:12
@coryrylan can you review this week?

**Comment by sheguloves** [comment] 2021-01-18 02:30
> @sheguloves I think that is some problem with the element's scrollToClose, 'cause in the Datagrid documentation, you can see that if you scroll the page, the element will be hidden. Looking in the file you mentioned above, I found the line of code:
> `* clrPopoverContent =" open; at: smartPosition; outsideClickToClose: true; scrollToClose: true `
> Where scrollToClose is probably not working...

Hi @xlucvvs 

I downloaded the sample and ran it on my local environment with **Clarity V3**.

datagrid-action-overflow.ts
```
private focusFirstButton(): void {
    if (isPlatformBrowser(this.platformId)) {
      this.zone.runOutsideAngular(() => {
        setTimeout(() => {
          const firstButton: HTMLButtonElement = document.querySelector('button.action-item');
          if (firstButton) {
            // firstButton.focus = () => {} will not cause the bug. The root cause is still focus make scrollbar auto jumping.
            firstButton.focus();
          }
        });
      });
    }
  }
```

**Comment by FabianUntermoser** [comment] 2021-04-06 06:12
Hi, is there a plan on when this will be fixed?

**Comment by hippee-lee** [comment] 2021-04-06 15:28
Hi @FabianUntermoser - I mentioned the DOM structure above but wasn't clear in my explanation, sorry. There is a [workaround](https://stackblitz.com/edit/gh-5342-datagrid-scrolling-issue-report-l1dsps?file=src/app/app.component.html) for the use case presented that uses the exact DOM structure specified in the application layout docs. 

I recognize that this isn't ideal but it is a limitation leftover from some early architecture choices made when Clarity was started back in 2016. There is a high cost to re-writing older components like the datagrid and focus trap and our efforts are on building out the core components. FYI - the core web component for Datagrid/Datatable is under active development as of this date. 

Realistically, as a small team, we don't have the resources at this time to investigate and fix a complicated issue like this given that there is a workaround. I'm going to close this issue for now to keep expectations around this issue realistic. 

If someone from the community wants to pick it up and submit a fix that would be welcome and we could re-open it at that time.

**Closed as completed by hippee-lee** 2021-04-06 15:28 UTC
Labels: type: bug, flag: has workaround, component: datagrid, @clr/angular

**Comment by FabianUntermoser** [comment] 2021-04-08 14:40
@hippee-lee  Thanks for the elaborate answer.
I would be fine with using a workaround, however I cannot use it as I am using a `<router-outlet></router-outlet>` and have nested navigation inside those routed components.

```
<clr-main-container>
  <router-outlet></router-outlet>
  <router-component>
    <div class="content-header"></div>
     <div class="content-container">
       <div class="content-area">
         <clr-datagrid> ... 
       </div>
      </div>
  <router-component>
</clr-main-container>
```

As of this comment https://github.com/vmware/clarity/issues/1186#issuecomment-340666223, I could get it working by adding this to my routed component.
```
   @HostBinding('class.main-container')
   public showContainerClass = true;
```
This however introduces a new scrollbar, due the duplicate main-container.
Any idea on how I should restructure my app to get this fixed?

EDIT:
I could now get it working by adding this in the routable components (Thanks to https://github.com/vmware/clarity/issues/1186#issuecomment-317045466):
```
  @HostBinding('class.u-main-container')
  public showContainerClass = true;
```

**Comment by hippee-lee** [comment] 2021-04-08 16:11
@FabianUntermoser - I am aware of teams that use components to wrap parts of the DOM and use `<router-outlet>` with nested navigations. There were some similar questions about DOM structure from teams a few years ago but not many since so I assume that teams have figured out the right balance for turning the application layout into components. 

I'm really sorry but I don't have an example to copy/paste here. I believe its possible but have not spent any time investigating how to accomplish it. My suggestion for you is to start with a simple, isolated stackblitz or cli angular app that implements the datagrid causing hte problem with your current DOM structure. Then, using the application layout usage info, create `@Components` as needed to achieve the correct DOM structure so that row actions are clickable without scrolling to the top.
