### ISSUE TITLE
[Accessibility] Clarity datagrid clr-dg-page-size enhancement request to improve screen reader experience

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#5555] opened 2021-02-03 11:39 UTC
This is a fork from #3189 which also mentioned the issue with the select box for the page-size, but was closed without fixing it in the PR #3421 . To re-iterate, specifically this part of the previous issue is left unfixed:

- Setting title on the select using the text in clr-dg-page-size. Example rendered html:

    <clr-dg-page-size [clrPageSizeOptions]="[10,20,50,100]">Users per page</clr-dg-page-size>

```
<clr-dg-page-size _ngcontent-c22="">
    Users per page
    <div class="clr-select-wrapper">
<!-- add title to select here, can use the value from component text  -->
        <select class="clr-page-size-select ng-pristine ng-valid ng-touched" title="Users per page">
            <option value="0: 10" class="ng-star-inserted">10</option>
            <option value="1: 20" class="ng-star-inserted">20</option>
            <option value="2: 50" class="ng-star-inserted">50</option>
            <option value="3: 100" class="ng-star-inserted">100</option>
        </select>
    </div>
</clr-dg-page-size>
```

**Comment by scroniser** [comment] 2022-01-14 23:19
@gnomeontherun - FYI, this looks like a duplicate of https://github.com/vmware/clarity/issues/4668. We have 4668 tracked internally.

**Comment by gnomeontherun** [comment] 2022-01-18 14:12
Thank you @scroniser, will close this to avoid duplicate tracking.

**Closed as completed by gnomeontherun** 2022-01-18 14:12 UTC
Labels: resolution: duplicate, type: accessibility, resolution: tracked by a11y
