### ISSUE TITLE
Modal Incorrect Screen Reading of Close Button

### ISSUE THREAD

**Issue by jeff-bacon** [vmware/clarity#4212] opened 2020-01-16 18:57 UTC
## Describe the bug

Using Chrome + NVDA:

When navigating to the close button of a modal, the name of the last button in the modal is read by screen readers.

## How to reproduce

[https://clarity-light-theme-v2-jjgdej.stackblitz.io/](https://clarity-light-theme-v2-jjgdej.stackblitz.io/)

1. Tab until the **Open Modal** button.
2. Press **Enter**
3. Tab until the **OK** button.
4. Continue tabbing until the **X** (close) button has focus.
5. Notice that the screen reader is reading the **OK** button and the **Close** button when it should only be reading the **Close** button.

![image](https://user-images.githubusercontent.com/17691864/72553920-8f3d8680-384e-11ea-9940-f34ebf635d91.png)

## Expected behavior

1. When navigating to the **X** (close) button, screen readers should not read content from other parts of the modal.

## Versions

**App**

* Angular: 8.2.4
* Clarity: 2.1.2

**Device:**

* Type: Surface Book
* OS: Windows 10
* Browser: Chrome
* Version: 79.0.3945.117

**Comment by gnomeontherun** [comment] 2020-02-11 16:50
Is this only on Chrome and NVDA? Our primary platform for PC is Firefox and NVDA.

**Comment by jeff-bacon** [comment] 2020-02-11 17:01
Our testing team did this test pass using both Edge / Narrator and Chrome / NVDA.  It seems to work as intended with the Edge / Narrator combination.  While we don't use Firefox, I can try testing this myself in Firefox to see if it repros there.

**Comment by gnomeontherun** [comment] 2021-02-01 22:48
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:48 UTC
Labels: @clr/angular, browser: screen reader, component: modal, needs: accessibility input, priority: 2 medium-low, status: needs investigation, type: accessibility
