### ISSUE TITLE
clrCheckbox required check

### ISSUE THREAD

**Issue by BennieMeng** [vmware/clarity#3757] opened 2019-08-29 08:59 UTC
## Describe the bug

when i use clrCheckbox latest clarity version,add required both clrCheckbox input, only choose one ,shoult throw error message. i think the error message should be throw only when none was choosed.

1.  Go to [clrCheckbox demo](https://clarity.design/documentation/checkboxes)'
2. search Inline checkboxes demo
## Expected behavior

when add required both clrCheckbox input, only choose one ,shoult throw error message.

## Versions

**App**

* Angular: [e.g. 8.1.x]
* Node: [e.g. 10.16.0]
* Clarity: [e.g. 2.0.2]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2019-08-29 20:33
This is actually how checkboxes work if they are part of the same group. Setting `required` on the last in a checkbox group makes them all required. If you want to validate them independently, you'll have to create a custom validator that checks that one of the checkboxes is checked instead of using `required`. That is all done using Angular forms (and IIRC only possible in reactive forms), and if you set that up the Clarity validation will work as expected.

This is ultimately a duplicate of https://github.com/vmware/clarity/issues/3433#issuecomment-500615551, so closing this in favor of that issue.

**Closed by gnomeontherun** 2019-08-29 20:33 UTC
Labels: resolution: duplicate, type: enhancement
