### ISSUE TITLE
Card stretch and overflow.

### ISSUE THREAD

**Issue by Papipo** [vmware/clarity#182] opened 2016-12-04 10:48 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Cards are expected to stretch in order to contain their children, no less, no more.

### Actual behavior
When they are a direct child of .content-container, they stretch to the height of their parent. It doesn't matter if the content won't fit, or if there will be spare space.

### Reproduction of behavior
Large example so it's easy to see that it doesn't stretch enough: https://plnkr.co/edit/XRgxMgtrUVaDX5A0QLnV?p=preview
Shorter example to see that it stretches too much:
https://plnkr.co/edit/pKCUbK0Y1LMvicxDzr1p?p=preview

### Environment details

Pure CSS, not using angular.

* **Clarity version:**
0.7.2

* **OS and version:** 
MacOS Sierra 10.12.1

* **Browser:** [Chrome 54 | Safari 10.0.1 ]

**Comment by adityarb88** [comment] 2016-12-04 17:51
Hi @Papipo.

I see that you are not using the `.content-area` inside of the `.content-container`.  Our [layout](https://vmware.github.io/clarity/documentation/app-layout) recommends that you place your content inside of the `.content-area`. So your layout should look something like this:

```
<div class="main-container">
    <header class="header">
      <div class="branding">
        <div class="title">Trade proposal</div>
      </div>
    </header>
    <div class="content-container">
      <div class="content-area">
        <div class="card">
         ...
        </div>
      </div>
    </div>
  </div>
</div>
```


Once you do that, both the issues will be resolved.

I will close the issue but if you feel that the issue isn't resolved, please feel free to reopen this issue and we can take a look again.

Thanks!

**Closed by adityarb88** 2016-12-04 17:51 UTC

**Comment by Papipo** [comment] 2016-12-05 07:43
Hey @adityarb88 thanks for your response. Actually that fixed the problem. Since I wasn't using a sidebar I just bypassed the content-area completely.
