### ISSUE TITLE
Deep search for DatagridCells in DatagridRow

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#3475] opened 2019-06-18 09:23 UTC
## Summary

Enable grouping of several ClrDatagridCells in a custom component, by deeper ContentChildren search.

* What is the change?
Search for descendant cells instead of only row's direct children:
https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-row.ts#L167
Current: `@ContentChildren(ClrDatagridCell) dgCells: QueryList<ClrDatagridCell>;`
Wished: `@ContentChildren(ClrDatagridCell, {descendants: true}) dgCells: QueryList<ClrDatagridCell>;`

* Why should it go in Clarity?
To enable better structure/encapsulation in large data grids.

* Does this change impact existing behaviors? If so how?
Maybe if someone has nested cells, which seems for me unlikely.

## Workarounds

Not as far as I know.

**Comment by gnomeontherun** [comment] 2019-06-21 20:50
Hello, I'm trying to make sure I understand the net result of your ask instead of talking about the implementation only. Are you asking if we could support something like the following?

```
<clr-dg-row>
  <my-row-wrapper>
    <clr-dg-cell>Query should also</clr-dg-cell>
    <clr-dg-cell>find these cells</clr-dg-cell>
  </my-row-wrapper>
</clr-dg-row>
```

I'm not really sure what the problem is exactly that you are having with encapsulation/structure in large datagrids, and would prefer to discuss those shortcomings first with clear use cases.

**Comment by twittwer** [comment] 2019-06-24 07:23
Thx for your response - Of course, it's better to discuss the use case first, sorry.

You're got the main idea. I have a component (e.g. parent) with a datagrid. For the rows I want to use a custom component (e.g. row wrapper) which I pass on the data of the current row. That way I try to extract row's template from the datagrid template.

Parent Template
```html
<clr-dg-row *clrDgItems="let data of dataList">
  <my-row-wrapper [data]="data"></my-row-wrapper>
</clr-dg-row>
```
Row Wrapper Template
```ts
@Component({
  selector: 'my-row-wrapper'
  template: `
    <clr-dg-cell>Query should also</clr-dg-cell>
    <clr-dg-cell>find these cells</clr-dg-cell>
    <clr-dg-cell>{{data.description}}</clr-dg-cell>
  `,
})
export class RowWrapperComponent {
  @Input() data: { description: string };
}
```

Did I describe the use case satisfactory?
Maybe I missed another appropriate solution for this.

**Comment by gnomeontherun** [comment] 2019-06-24 15:17
Thanks, I just needed to be sure I understood because it is easy to assume the wrong intent. I'm not certain about the proposed solution, but the request to allow for wrapper components like this is worth consideration.

**Comment by mathisscott** [comment] 2019-08-09 16:50
@gnomeontherun 
Is this something we want to move into the backlog?

**Comment by twittwer** [comment] 2019-09-16 11:34
@gnomeontherun 
I just run into another use case: When I want to wrap my row with an anchor tag.
Something like this:
```html
<clr-dg-row *ngFor="let user of users">
  <a [routerLink]="['/users', user.id]">
    <clr-dg-cell>{{user.name}}</clr-dg-cell>
    <clr-dg-cell>{{user.email}}</clr-dg-cell>
  </a>
</clr-dg-row>
```

**Comment by gnomeontherun** [comment] 2019-09-23 14:14
@twittwer I caution against doing the above behavior with wrapping a row in an anchor. There are a few reasons but namely that the link is not intended to be there and could cause rendering issues. Also we are removing row selection (which this is very similar to) because of accessibility issues and breaking datagrid aria patterns.

**Comment by twittwer** [comment] 2019-09-23 15:16
> we are removing row selection because of accessibility issues

What is the recommended approach to a list-detail-view?
- overview page shows datagrid with item list
- "clicking" on a item navigates to next page with a detail view of the clicked item

**Comment by gnomeontherun** [comment] 2019-09-23 19:39
You should wait for #3797 to land for a detail pane view.

**Comment by gnomeontherun** [comment] 2019-12-20 21:06
After further discussion, this has been determined to be invalid because you should be able to handle this with ng-container and project as, see https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b.

Closing as an Angular capability that should make this possible, and not a bug in Clarity.

**Closed by gnomeontherun** 2019-12-20 21:06 UTC
Labels: component: datagrid, flag: watchlist, status: needs triage
