### ISSUE TITLE
[Accessibility] Signpost heading reads as clickable even though it is not

### ISSUE THREAD

**Issue by Tushar2098** [vmware/clarity#4388] opened 2020-03-20 08:23 UTC
## Describe the bug

Signpost heading reads as clickable even though it is not by NVDA

![image](https://user-images.githubusercontent.com/8487521/77145765-7734ee00-6aaf-11ea-9864-1fabef365e1b.png)

## How to reproduce

1. Go to [https://v2.clarity.design/signposts](https://v2.clarity.design/signposts)
2. Click on the info icon to open the signpost
3. Notice clickable <heading> is announced by screen-reader

## Expected behavior

Remove the text clickable from the heading as it is not clickable

## Versions
This issue is also reproducible in latest Clarity version.

## Environment details

- **Browser:** Chrome/Firefox
- **Screen-reader:** NVDA

**Comment by gnomeontherun** [comment] 2021-02-01 22:50
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:50 UTC
Labels: browser: screen reader, component: signpost, needs: accessibility input, priority: 2 medium-low, status: needs investigation, type: accessibility
