### ISSUE TITLE
Datagrid first action is alway highlighted

### ISSUE THREAD

**Issue by tran2** [vmware/clarity#4100] opened 2019-12-09 20:01 UTC
## Describe the bug
Datagrid first action is alway highlighted even if the user hovers the mouse over other action items.

## How to reproduce

Can be reproduce from the documentation page https://clarity.design/documentation/datagrid/single-action. 

![image](https://user-images.githubusercontent.com/7945885/70468017-2444a700-1a7b-11ea-8ea5-58e69b68fb4d.png)
![image](https://user-images.githubusercontent.com/7945885/70468070-3f171b80-1a7b-11ea-9c1b-b7555b15b502.png)

1.  Go to https://clarity.design/documentation/datagrid/single-action
2. Click on ... to open the action popover
3. See that Edit is already highlighted
4. Hover over Delete and see that Edit is still highlighted

## Expected behavior

The expected behavior should be Edit is no longer highlighted when user hovers over other action items.

## Versions

**App**

* Clarity: 2

**Comment by hippee-lee** [comment] 2019-12-09 22:28
This behavior is needed to support screen readers and make the row action popover content accessible. 
I'm closing as works as intended.

**Closed by hippee-lee** 2019-12-09 22:28 UTC
