### ISSUE TITLE
clr-dropdown should support a dynamic clrPosition

### ISSUE THREAD

**Issue by justindsmith** [vmware/clarity#1262] opened 2017-08-05 01:06 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
When a `clrDropdownToggle` is not positioned so that the associated `clr-dropdown-menu`'s position (`[clrPosition]`) will not be visible in the page, the menu should draw in a direction that _will_ show fully on the page.

### Actual behavior
The dropdown will draw in the specified direction no matter where the menu is going to end up on the page.

This is especially tricky when iterating over a list as the main content of the page, with dropdowns included in the list items. In this case the dropdown menus for the last few items cause layout issues as they try to gain space for the menu.

### Reproduction of behavior
https://plnkr.co/edit/Jlmxcqe9419Nvgpxhkny?p=preview

### Environment details

* **Angular version:** 2.0.X
4.x

* **Clarity version:** 
0.10.0-rc

* **OS and version:** 

* **Browser:**
all

**Comment by youdz** [comment] 2017-08-07 15:42
This is what we've been categorizing as "collision detection" or "smart popovers" for our dropdowns, tooltips, signposts aand any other kind of popovers.

It has not been considered a priority so far. The amount of work required to handle collision detection for every possible use case out there, while integrating with Angular _and_ not slowing down performances, is gigantic. Knowing that this can be solved in all cases by adding minimal extra work on the app side (in your case, keep track of the index in your list's `*ngFor`, and position the last few dropdowns to the top rather than the bottom), the (work required / value provided) ratio is pretty low at the moment.

Thanks for filing this, I will raise it during our next planning session to see if anything has changed.

**Comment by timvl** [comment] 2017-09-06 06:57
is there a workaround possible?

**Comment by juanmendes** [comment] 2017-11-09 16:44
We are running into this problem by having a lot of options in the menu. Using the ngFor index to decide the position is not really feasible, you have to combine it with offsetTop, screen height to get decent results that don't scroll off the top. At the very least, Clarity should make a suggestion as to how longs menus from cards should work. Isn't there a fix like the one suggested at https://github.com/vmware/clarity/issues/1213? We were able to create a directive that implemented the suggested workaround.

**Comment by KevinABoucher** [comment] 2017-11-14 20:27
A similar issue occurs when a signpost is at the end of a paragraph that can flow to different positions on the screen.

**Comment by marvinosswald** [comment] 2018-01-20 14:14
is there any progress on this issue ? Or maybe a dirty workaround for the moment ?

**Comment by timvl** [comment] 2018-03-01 07:43
Hi, any updates on this issue? Is there a workaround?  Especially for the datagrid (https://github.com/vmware/clarity/issues/1412) we're looking for a workaround.

Thanks

**Comment by timvl** [comment] 2018-03-01 08:42
Hi all, I just found a workaround for the datagrid filter issue (https://github.com/vmware/clarity/issues/1412)

In your template add a template variable on the clr-dg-filter component (**#leftFilter**):
```
<clr-datagrid>
      <clr-dg-column [clrDgField]="'myField'">
        My Field
        <clr-dg-filter #leftFilter>
          <x-like-filter></x-like-filter>
        </clr-dg-filter>
      </clr-dg-column>
...
```
In you component, override the popoverOptions of the datagrid filter with **offsetX**:

```
@ViewChild('leftFilter') leftFilter: ClrDatagridFilter;

 ngOnInit(): void {
    this.leftFilter.popoverOptions = {
      offsetX: 100
    } as PopoverOptions;
  }
```

Now the left filter in the datagrid is moved a bit to the right so that is completely visible

**Comment by jayrungta** [comment] 2018-05-09 15:02
@youdz any update on this?

**Comment by youdz** [comment] 2018-05-09 16:09
There is currently no work planned on this, it is not one of our short-term priorities. 

We are all working on higher impact new components and features at the moment.

**Comment by jayrungta** [comment] 2018-05-25 20:08
@youdz any work around you can suggest for the time being?

**Comment by youdz** [comment] 2018-05-29 12:56
As usual, the recommended workaround until we address this is to simply position the dropdown in a direction that is "safe" for your application, since it's entirely dependent on where the dropdown is used within your layout.

**Comment by jayrungta** [comment] 2018-05-30 20:58
I found a work around in case anybody needs (works for my use case):

**overview**:
In my use case, I have a data grid (ag grid, not clarity grid) and each column header of this grid can open a filter dropdown. Inside this filter dropdown, there is a clarity dropdown that opens on the right, kind of like this:
![image](https://user-images.githubusercontent.com/16365416/40746805-6183538c-6429-11e8-909d-28fef875073a.png)
The problem I was facing was that the clarity dropdown did not understand when there was no more window space left on the right, and still opened to the right. After this workaround, the dropdown opens to the left when there is no space left to the right.

**html:**
``` 
<div class="parentDiv" id="parentDiv">
  <clr-dropdown>
          <span clrDropdownToggle>
            Open Dropdown
          </span>
    <clr-dropdown-menu class="dropdown-menu" clrPosition="{{dropdownSide}}">
      <div>
        <a class="dropdown-item">Option 1</a>
        <a class="dropdown-item">Option 2</a>
        <a class="dropdown-item">Option 3</a>
      </div>
    </clr-dropdown-menu>
  </clr-dropdown>
</div>
```

**ts** (inside a function like ngOnInit, which gets called every time the component is rendered)**:**
``` 
const elem = document.getElementById('parentDiv');
const rect = elem.getBoundingClientRect();
const left = rect.left + WIDTH_OF_PARENT_DIV + WIDTH_OF_SIDE_MENU;
const width = window.innerWidth;
if (left > width) {
  this.dropdownSide = 'left-top';
} else {
  this.dropdownSide = 'right-top';
}
```

Not sure about other use cases, but this workaround **will work in cases where the problem is deciding when to open the dropdown to the left, or to the right**.

**Comment by mann-david** [comment] 2018-08-16 18:03
I hate to just +1 and run...but...
+1

This is a big deal for dynamic screens - we can't always control how the user is going to arrange things.

Thx.

**Comment by vlanz** [comment] 2018-09-11 13:00
We have the same issue, as our grids are placed on the left side of the screen and the first column is quite thin (product code). The popup is half cut off. Any kind of workaround is appreciated (@timvl 's solution doesn't seem to work in our case).

**Comment by dpcamp** [comment] 2018-12-11 18:57
Does anyone have a workaround for this using DataStringFilter? I tried @timvl suggested workaround, but have had no such luck

**Comment by JoshuaNitschke** [comment] 2019-04-08 23:24
I used @timvl 's solution as well for my datagrid filter, and it worked for me.  This is an annoying work around, though.

![image](https://user-images.githubusercontent.com/33307206/55763165-b7c06680-5a1a-11e9-8fa7-2ced194e6917.png)

**Comment by gnomeontherun** [comment] 2021-02-05 14:57
When we implemented the smart popovers for dropdowns, we fixed the issues for the datagrid filter. However, the solution is forthcoming with our Clarity Core implementation of dropdowns which will have this capability.

The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).

**Closed by gnomeontherun** 2021-02-05 14:57 UTC
Labels: type: enhancement
