### ISSUE TITLE
Login wrapper forces form to be cut off on short screens

### ISSUE THREAD

**Issue by fluky** [vmware/clarity#4362] opened 2020-03-11 23:35 UTC

**Comment by hippee-lee** [comment] 2020-03-11 23:43
I'm not seeing a login form, just the getting started instructions that are provided in the starter. Did you forget to save?

**Comment by fluky** [comment] 2020-03-11 23:57
> I'm not seeing a login form, just the getting started instructions that are provided in the starter. Did you forget to save?

Yep, saved

**Comment by hippee-lee** [comment] 2020-03-12 00:33
The login form has to go inside of the `.content-area` container. We don't seem to explicitly say that in the docs though. 

Here is an updated stackblitz: https://gh-login-4362.stackblitz.io

**Comment by fluky** [comment] 2020-03-12 01:03
> The login form has to go inside of the `.content-area` container. We don't seem to explicitly say that in the docs though.

I had this in my actual code, just missed it in the copy/paste because it was in another component.  The problem here was that I had:

```
content-wrapper
   content-area
     ui-login <-- My login component
       login-wrapper
```

The host selector for my component messes it up (common problem with flex layouts).  Tried moving the content-area down but that just causes different problems.  Best solution is to put the content-area on the component with @HostBinding.

**Comment by fluky** [comment] 2020-03-12 01:11
Actually looking into this further, that does not fix the problem.  If you check your corrected stackblitz, you will see that it is "better" but "welcome to" is still cut off behind the header.

**Comment by hippee-lee** [comment] 2020-03-12 17:01
`.title` is still cut off so the fix is a little more involved than just adding min-height. 
This seems to apply specifically to the example login form which has a title, when its on a phone,  and is in landscape orientation. 

A simple workaround that an app could use is to apply the min-height and add a `margin-top: 3rem` to the login `.title` element that targets only the moble/landscape use case. 

I'll re-open this and put it in the backlog. This will be a pretty low priority for us, most Clarity apps internally are designed to be used on a larger screen And Clarity CSS is generally written as a desktop first and graceful degradation as screen size decreases. If this affects your app, please consider contributing a mobile / landscape targeted solution fix per our [contribution guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md).

**Comment by gnomeontherun** [comment] 2020-03-12 21:10
The problem is we have `height: auto` for the `.login` element, and on very short height screens this is being calculated as a flex child. If the screen is ever shorter than the height of the login form content, you get this problem.

Quick fix is to put a min-height on the `.login` element, based on the height of your form. Our demo appears to work well around 620px like so.

```
.login {
min-height: 620px;
}
```

**Comment by fluky** [comment] 2020-03-12 22:11
You guys are over complicating it, as I've mentioned changing (not adding as @hippee-lee said) height to min-height seems to solve it for all displays, at least for me.  No special calculations or screen size targeting.

At any rate I had already fixed this locally with that simple change, was just letting you guys know.  Disappointing to hear that you don't consider mobile important enough for a simple fix but it's your project.

**Comment by hippee-lee** [comment] 2020-03-12 22:31
@fluky - it is not that we
> don't consider mobile important enough for a simple fix
It is that 1) design and implentation considers desktop first and gracefully degrades from there as issues are uncovered and 2) this is an open source project so anyone who places a priority on `phone in landscape orientation for login  forms` can contribute the fix for this if it important for their project. 

We have to prioritze and fix issues according to the business cases that makes sense for the team. As I mentioned earlier, this isn't being closed but its not somehting that we will put at the top of the priority list. This was an attempt to let you know that its a recognized issue and is in the backlog. 

Thanks for letting us know and as I mentioned earlier, contributions are always welcome. Please let me know if you are interested in working on this.

**Comment by fluky** [comment] 2020-03-13 00:14
Honestly, do you hear yourself?  Twice now you've suggested that I:
 1. Fork your repository
 1. Download it
 1. Fix it
 1. Find, figure out, and implement your rules for pull requests
 1. Deal with the inevitable comments

in order to make a 4 character change to fix an issue that:

 1. I have already fixed in my project anyway
 2. You don't consider a priority

Lol, no thanks.  Honestly I reported this issue as a courtesy, a mistake I won't make again.

**Comment by mathisscott** [comment] 2020-03-13 00:50
@fluky 

Hi James,

First, thanks again for reporting the issue. @hippee-lee likewise thanked you for your interest and putting the time in to do that.

Second, it's entirely appropriate for an open-source project to suggest a contribution. Especially for lower priority (for us) issues that we may not get to as quickly as some in the community would like. We support hundreds of developers and products within just VMware alone. And thousands outside of that. So we are always faced with priorities that result in some people being happy and others disappointed.

We try our best to meet the needs of our community even when those needs conflict. 

Right now, our UX group has taken a desktop-first approach to design. If you were willing to contribute back to this open-source and freely available library, we'd sure appreciate it. We are a _very_ small team and always have been.

Lastly, we should work together to build a respectful community. That requires all of us to keep things above board. I'd appreciate it if you, James, followed that in your comments here.

Please don't close this ticket. We are keeping it open for a reason. When we can get to it, it will likely be fixed. Those who need it faster than we can get to it are welcome to contribute back.

Thanks again.

**Comment by fluky** [comment] 2020-03-13 03:52
@mathisscott Wait what?  Above the board?  Really, what was below the board?  Saying I was disappointed that you didn't take mobile more seriously?  I thought that was expressed very respectfully.  Or was it pointing out how silly it is to expect your users to spend hours of their time to make a 4 character fix on your project?  Going out of my way to find a fix for your issue and let you know both the issue and the fix was, as I said, a courtesy.  You, of course are free to do with it what you like, but I'm not going any further and I won't be lectured about respectful communities when I've been very polite.  Personally, I think that saying:

 1.  You're doing it wrong, but we didn't document it well and then closing the ticket with a solution that does not actually work, and without any confirmation from the creator.
 1.  Oh, it really is a defect but we're not going to prioritize it.
 1.  You should fix it for us, even though it would take you hours and us minutes.

is not really the best approach.

But as I've said, it's your project you're free to run it with whatever level of professionalism you deem fit.  Just as I am free to choose not to go through the hassle of tying to help out when you've made it very clear that you are only interested in VMware's needs and not the project as a whole.

I am happy to contribute to open source but when someone says, "it's not important to us, you should fix it", why bother?

At any rate, I've deleted all my other comments since they clearly offended.  For what it's worth I think you are creating a quality product.

**Closed** 2021-08-12 19:07 UTC
Labels: type: bug, type: support, priority: 1 low, browser: mobile, status: backlog, component: login
