### ISSUE TITLE
Issue with row selection in datagrids with filters

### ISSUE THREAD

**Issue by sujatharanganathan** [vmware/clarity#2080] opened 2018-03-16 04:11 UTC
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

This issue is regarding selection in datagrids. Consider a datagrid with filtering option.
1. Select a row.
2. Use the filter to type something.
3. The filtered rows are shown.
4. If the selected rows is there in the filtered result then the selection should be maintained.
5. If the selected row is not there in the filtered result, then the selection must be retained after clearing out the filter text.

### Actual behavior

The selection is removed.

### Reproduction of behavior

Screenshots attached.
First image shows that the row with user Darla has been selected.
In the second image when the rows are filtered by username Darla, the selection is removed.

### Environment details

* **Angular version:** 6.0.0-beta.3

* **Clarity version:** 0.11.4

* **OS and version:**  Mac Sierra

* **Browser:** [all]
<img width="694" alt="issue1" src="https://user-images.githubusercontent.com/15010827/37503297-b5fd2832-28fd-11e8-9009-926846fbb65a.png">
<img width="708" alt="issue2" src="https://user-images.githubusercontent.com/15010827/37503298-b6432d00-28fd-11e8-966d-55ae89a26c88.png">

**Comment by sujatharanganathan** [comment] 2018-03-16 04:24
Yes indeed

**Comment by adityarb88** [comment] 2018-03-16 13:43
@sujatharanganathan: This is a duplicate of #1963 like @brinton-chand pointed out above. We will not be changing this as this is the expected behavior. For more details, please see this comment: https://github.com/vmware/clarity/issues/484#issuecomment-285419495

**Comment by adityarb88** [comment] 2018-03-16 13:43
Please feel free to reply back with your questions/feedback on #484

**Closed by adityarb88** 2018-03-16 13:43 UTC
