### ISSUE TITLE
[clr-datagrid] actions overflow is cut-off at grid boundaries

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#652] opened 2017-03-25 18:36 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The actions overflow menu should not be cut-off for first/last/any row for any number of actions (at least 5-6 actions should be possible for each row)

### Actual behavior
The actions menu is cut-off if each row has more than 1 actions

### Reproduction of behavior

https://plnkr.co/edit/XI7L6O?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.12

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-03-25 19:04
Hi @envyN 

I believe this is a duplicate of #37. Please correct me if I am wrong on that.

**Closed by mathisscott** 2017-03-25 19:04 UTC

**Comment by envyN** [comment] 2017-03-26 04:40
#37 talks about tooltips and more so within the context of modals. Does the
actions overflow for data grid have the same underlying implementation? If
so then yes this might be a duplicate.
But otherwise, this is specifically for data grid and the actions overflow
within that.
Check out the plunkr I have provided to see the behaviour and triage
accordingly

**Comment by envyN** [comment] 2017-03-26 06:03
Ok i guess this is being addressed in #649.

**Comment by mathisscott** [comment] 2017-03-26 14:31
It is. Same underlying issue.

**Comment by nghiado** [comment] 2019-01-07 05:52
@mathisscott This happens again in Clarity 1.0. It's blocking our upgrade to Clarity 1.0
Demo https://stackblitz.com/edit/clarity-5f4jkd 
<img width="690" alt="screen shot 2019-01-06 at 11 44 20 pm" src="https://user-images.githubusercontent.com/1259031/50751163-2b7d8800-120e-11e9-8c57-cac3a143f37d.png">
<img width="490" alt="screen shot 2019-01-06 at 11 51 09 pm" src="https://user-images.githubusercontent.com/1259031/50751164-2b7d8800-120e-11e9-8b73-08277afb1adf.png">


Can you reopen this one?

**Comment by hippee-lee** [comment] 2019-01-07 15:52
@nghiado - I'm actively working on a fix for this. Please subscribe and follow this issue to stay informed: #2923
