### ISSUE TITLE
Column toggle change event emitter

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2722] opened 2018-10-11 08:52 UTC
## Summary

I've created a column toggle settings save component, which is almost fully functional:
https://stackblitz.com/edit/clr-column-settings-save
To make it more user friendly, I need an event emitter from `clr-dg-column-toggle` component to catch the selection change event (when the user changes the checkbox selection).

## Use case
With this event emitter I can determine whether a selection change happened and there is dirty data, and then I could enable the save button on update cases only when dirty data presents:
https://stackblitz.com/edit/clr-column-settings-save
Server logic can be added too, we save the settings in json object into the database per user, settings are filtered in the json object per grid, so you can use this for multiple grids (gridId field). Server logic can be implemented in various ways.

## Integration
Can this `ColumnToggleSettingsComponent ` be added into the main @clr/angular package?
This feature can be useful for other users too.

**Comment by youdz** [comment] 2018-10-11 13:17
This looks like a duplicate of #2117 to me. It's a known request, but it's not in our short-term priorities at the moment. Please follow that issue for future updates.

**Closed by youdz** 2018-10-11 13:17 UTC
Labels: Duplicate

**Comment by speti43** [comment] 2018-10-11 17:17
@youdz  Yeah, it seems it's a duplicate. And what about the component, have you checked? Don't you need it?

**Comment by youdz** [comment] 2018-10-11 17:32
It does seem very specific, which is something we try to avoid with Clarity. Being a small team with limited resources, we cannot implement or even accept already implemented features at will (like other libraries do) because the maintenance cost would be too high for us. It also helps us keep the documentation small and the learning overhead to a minimum.

**Comment by speti43** [comment] 2018-10-11 17:39
Sounds reasonable. I'll leave you alone, I know it's release day :)
