### ISSUE TITLE
Unable to pick the date in datepicker

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#3245] opened 2019-03-26 08:02 UTC
Hi, i am adding few form fields in wizard/modal , along with add  datepicker control in at that, when i am try to pick the date this causing issue like below image, even the scroll is not coming. [Stackblitz](https://clarity-issue-3149-double-open-chaneg-events-hikmec.stackblitz.io)

![image](https://user-images.githubusercontent.com/18004992/54980234-381eaa80-4fcb-11e9-8b52-ccd5372a7866.png)

**Comment by gnomeontherun** [comment] 2019-03-27 21:09
This is due to being on a short height screen, and our popovers not being smarter about where they position. This is being reviewed with #2923 and will eventually land in all popovers.

The workaround for now is to move the date input higher in the list so it has vertical space, because a modal blocks the page scrolling (on purpose).

Probably a duplicate of #2331 and would be addressed with refactoring our popovers.

**Comment by gnomeontherun** [comment] 2021-02-01 21:15
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-02-01 21:15 UTC
Labels: component: forms, resolution: duplicate, type: bug
