### ISSUE TITLE
Datagrid leaks JS memory and DOM elements.

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#4712] opened 2020-06-08 12:23 UTC
## Describe the bug

I have a grid in which constantly add new data, update existing one and remove data.
I see that when a row is deleted (data are deleted), row's DOM nodes are not released and the JS memory constantly grows with every added row. 

![Screen Shot 2020-06-08 at 3 11 18 PM](https://user-images.githubusercontent.com/439779/84029658-6ce20c00-a99b-11ea-98fe-054d90553fc8.png)

## How to reproduce

https://stackblitz.com/edit/clarity-v3-datagrid-memory-leak

## Expected behavior

Datagrid not to leak memory and DOM elements.
## Versions

**App**

- Angular: 9
- Clarity: 3.0.0

**Device:**

Type: MacBook
OS: iOS
Browser Chrome
Version latest

**Comment by dkanev** [comment] 2020-06-08 15:58
Second version without *ngFor through the columns in the rows:

https://clarity-v3-datagrid-memory-leak-v2.stackblitz.io/

Strange that comparing both approaches, it looks the first one with second *ngFor without track by is better, the memory leaks are bigger with the second approach

**Comment by mattmutt** [comment] 2020-06-08 16:35
Regarding memory leaks on the heap, is it true it that it grew by 5MB over the course of about 2 minutes?

Worthy of deeper inspection within Clarity datagrid:
Sometimes observables are not cleared or fully unsubscribed. Moreover dangling references are left around to these heavy DOM objects that accumulate.  After 2 minutes, one would expect GC to have been triggered, but it has not. We should see a triangular-shaped heap memory usage over time.

For the use case of recreating the grid's data set periodically, is there any manual need from the developer's code to trigger something else or meddle with ChangeDetectorRef?

**Comment by gnomeontherun** [comment] 2020-06-11 17:58
Thank for for the report and the reproduction. In Stackblitz, it does seems like a problem with growing memory but in order to better triage and understand the situation it is best to run a local instance to minimize variables. Stackblitz itself modifies the runtime in a way that might be causing the memory leaks in that environment.

### Findings

First I started looking at the Stackblitz demo, and it does show increasing memory over time with lots of detached DOM nodes. However, this is hard to debug because the heap size at the start is well over 400 MB, making it very inneficient already.

Second, I tried to reduce the complexity of the demo by removing the unnecessary NgFor loops, suspecting it might cause some issues to have nested iterators. This did not yield significant differences. 

Third, I created the reproduction above using the same code logic with a fresh Angular CLI project outside of Stackblitz. This removes the variable of Stackblitz and also lets the memory stay low enough to more easily profile. I ran the sample for 30 minutes, taking heap samples along the way and saw it staying steady between 13.4-13.6 MB (meaning it went up and down between those values, showing it would decrease depending on GC). Also, there is not the increasing detached DOM nodes that I saw in Stackblitz. In short, this means that locally, the memory leak doesn't appear and this particular reproduction appears to be specific to Stackblitz. 

##### Screenshot of 10 minute run of the profiler with memory holding steady and cleaning up at regular, stable intervals. 

![image](https://user-images.githubusercontent.com/79500/84422007-03a00a00-abe2-11ea-8ce8-1a12b23e76ee.png)

These findings are correllated with another team member's triage and testing. So based on the reproduction, I cannot conclude that Clarity is the reason that the initial report is growing in memory with detached DOM nodes.

### Updated Reproduction

I created https://github.com/gnomeontherun/clarity-issue-4712/ which has the initial reproduction in a standalone Angular app, as well as an updated version that is more isolated by not having ngFor or rxjs. When I run either of these versions locally, I do not see a memory leak. Memory grows and stabilizes, even after 30 minutes of running.

### Next steps

Can you please investigate my repository above and see if you get different results? Otherwise, it would seem there is something else at work here and Clarity itself is not holding onto DOM nodes in this scenario. A review of the code also does not immediately surface a place where that might be the case. There might be more details or context that could illuminate the issue further, but I need an updated reproduction to demonstrate it in action.

**Comment by gnomeontherun** [comment] 2020-06-11 18:41
Also as a follow up, the demo also does not clean up the interval subscription manually so if you are working with the sample code, it will cause a memory leak if the app does a hot module reload to restart the demo. Therefore, you need to either unsubscribe to clean up, or only profile the initial load and not touch the code.

**Comment by dkanev** [comment] 2020-06-15 08:32
@gnomeontherun Thanks that looking this issue.
I modified a little bit your example to become more near to my use cases and verify that it works. It works without memory leaks according to me.  I see the memory leaks in our app, but it uses older version of Clarity and Angular (Angular 8.2.14, Clarity 2.4.3). I modified your example to use Angular 8.2.14 and Clarity 2.4.3 and I started to see memory leaks again. I just noticed also that the Stackblitz example which I posted here also uses  older version of Clarity and Angular (Clarity 3.0.0, Angular 9.0.4, "@angular/cli": "~7.0.2",  "@angular/compiler-cli": "~7.0.0"). 

Do you know whether there are some memory leak fixes related to the datagrid in the latest versions of the Clarity library?

**Comment by gnomeontherun** [comment] 2020-06-15 18:56
Quick update, Clarity v1 and v2 do have a problem with not cleaning up templates, which was fixed during an update to Angular 9 support for Clarity v3 (https://github.com/vmware/clarity/blob/v3/src/clr-angular/data/datagrid/wrapped-row.ts#L29) @Shijir is working on backporting the necessary changes for the next release.

**Comment by gnomeontherun** [comment] 2020-06-18 01:23
Resolved by #4732

**Closed by gnomeontherun** 2020-06-18 01:23 UTC
Labels: @clr/angular, component: datagrid, status: in progress, type: bug, v1, v2
