### ISSUE TITLE
[vmw-h5] Move Datagrid column filters from the table headers

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#4465] opened 2020-04-13 09:43 UTC
## Summary

Please move column filters from the datagrid headers to different row of the thead or outside the grid table because multiple controls are nested into table column headers.
Or provide an configuration option to display filters in header or outside the header
 
* What is the change?
The grid filters must be moved from grid headers
* Why should it go in Clarity?
Accessibility improvement
* Does this change impact existing behaviors? If so how?
Changes the structure of the grid component
* If this change introduces a new behavior, is this behavior accessible?
Yes
## Use case

This makes the calculation of the table header name by screen readers unclear, and makes identifying the sorted state of each table column unclear.
## Examples

Current - https://clarity.design/documentation/datagrid/custom-sorting
Proposal example- https://www.telerik.com/kendo-angular-ui/components/grid/filtering/#toc-filter-row

## Workarounds

N/A

**Comment by mathisscott** [comment] 2020-04-13 13:37
This is a duplicate of #1632 

Please subscribe to that issue to track progress.

**Closed by mathisscott** 2020-04-13 13:37 UTC
