### ISSUE TITLE
Error after updating Clarity

### ISSUE THREAD

**Issue by quetool** [vmware/clarity#1588] opened 2017-10-12 21:50 UTC
Hi! I don't know if is a Clarity error or something else but after update to Clarity 0.9.20 I am getting this error "fixedAttrs.map is not a function"

### console.log
```
vendor.bundle.js:111572 ERROR TypeError: fixedAttrs.map is not a function
    at elementDef (vendor.bundle.js:119669)
    at View_AppComponent_Host_0 (ng:///AppModule/AppComponent_Host.ngfactory.js:5)
    at proxyClass (vendor.bundle.js:97654)
    at resolveDefinition (vendor.bundle.js:119309)
    at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (vendor.bundle.js:120422)
    at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (vendor.bundle.js:113885)
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (vendor.bundle.js:115320)
    at vendor.bundle.js:115098
    at Array.forEach (<anonymous>)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap (vendor.bundle.js:115098)
defaultErrorLogger @ vendor.bundle.js:111572
vendor.bundle.js:69497 Unhandled Promise rejection: fixedAttrs.map is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: fixedAttrs.map is not a function
    at elementDef (vendor.bundle.js:119669)
    at View_AppComponent_Host_0 (ng:///AppModule/AppComponent_Host.ngfactory.js:5)
    at proxyClass (vendor.bundle.js:97654)
    at resolveDefinition (vendor.bundle.js:119309)
    at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (vendor.bundle.js:120422)
    at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (vendor.bundle.js:113885)
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (vendor.bundle.js:115320)
    at vendor.bundle.js:115098
    at Array.forEach (<anonymous>)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap (vendor.bundle.js:115098) TypeError: fixedAttrs.map is not a function
    at elementDef (http://localhost:4200/vendor.bundle.js:119669:46)
    at View_AppComponent_Host_0 (ng:///AppModule/AppComponent_Host.ngfactory.js:5:35)
    at proxyClass (http://localhost:4200/vendor.bundle.js:97654:29)
    at resolveDefinition (http://localhost:4200/vendor.bundle.js:119309:17)
    at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:120422:40)
    at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:113885:29)
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:115320:57)
    at http://localhost:4200/vendor.bundle.js:115098:81
    at Array.forEach (<anonymous>)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:115098:44)
api.onUnhandledError @ vendor.bundle.js:69497

```

### Environment details
```
@angular/cli: 1.4.7
node: 8.2.0
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.4
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
typescript: 2.3.4
```

### npm outdated output if it helps
```
Package                      Current         Wanted      Latest  Location
@angular/animations            4.4.4          4.4.4       4.4.5  clarity-seed
@angular/core                  4.4.4          4.4.4       4.4.5  clarity-seed
@types/jasmine                2.2.34         2.2.34       2.6.0  clarity-seed
@types/node                   6.0.89         6.0.89      8.0.34  clarity-seed
angularfire2              5.0.0-rc.1     5.0.0-rc.1  5.0.0-rc.2  clarity-seed
bootstrap              4.0.0-alpha.5  4.0.0-alpha.5       3.3.7  clarity-seed
clarity-angular               0.9.20         0.9.20      0.10.9  clarity-seed
clarity-icons                 0.9.20         0.9.20      0.10.9  clarity-seed
clarity-ui                    0.9.20         0.9.20      0.10.9  clarity-seed
codelyzer                      2.0.1          2.0.1       3.2.1  clarity-seed
jasmine-core                   2.4.1          2.4.1       2.8.0  clarity-seed
jasmine-spec-reporter          2.5.0          2.5.0       4.2.1  clarity-seed
karma                          1.2.0          1.2.0       1.7.1  clarity-seed
karma-remap-istanbul           0.2.2          0.2.2       0.6.0  clarity-seed
protractor                     4.0.9          4.0.9       5.1.2  clarity-seed
ts-node                        1.2.1          1.2.1       3.3.0  clarity-seed
tslint                         4.5.1          4.5.1       5.7.0  clarity-seed
typescript                     2.3.4          2.5.3       2.5.3  clarity-seed
typings                        1.5.0          1.5.0       2.1.1  clarity-seed
webdriver-manager             10.2.5         10.2.5      12.0.6  clarity-seed
```

**Comment by adityarb88** [comment] 2017-10-12 21:55
doesn't look like Clarity. I don't remember anyone else raising this issue. Could you please provide more info about the error? Does it only fail on 0.9.20? Is it possible to replicate this on a Plnkr?

**Comment by quetool** [comment] 2017-10-13 12:25
@adityarb88 I do not have more info right now... In order to continue with my development I had to downgrade to 0.9.16. Sorry, I will update with more info soon!

**Comment by adityarb88** [comment] 2017-10-24 02:53
@quetool: Were you able to figure out what the issue was? No one else has reported this issue and we definitely require more information to reproduce this. We are closing this issue assuming that this issue is specific to your application. Please feel free to reopen the issue if you have more info on how to reproduce this and we will take a look. Thanks!

**Closed by adityarb88** 2017-10-24 02:53 UTC
Labels: waiting-for-more-info

**Comment by quetool** [comment] 2017-10-24 12:49
no @adityarb88 I am sorry! I went forward with the development after downgrade to 0.9.16. Yes, I will definitely reopen the issue if necessary! Thanks and sorry!

**Comment by lingqiao1994** [comment] 2017-12-18 08:45
I think you might need to check if your @ angualr/core and @ angular/compiler versions are the same, new version of angular's elementDef  function added a property called checkIndex, if you core and compiler's version are different, you will get this error.

**Comment by mathisscott** [comment] 2017-12-18 14:24
@hippee-lee 
Could you verify whether this is an issue for 0.10.17?

**Comment by hippee-lee** [comment] 2017-12-18 18:06
@mathisscott - yes, this will still be an issue for `v0.10.17`. @lingqiao1994 is correct in diagnosign the cause. 

I used our seed app and could recreate it whit the version of angular posted in the issue. The fix is on the application side. The `package.json` should be checked to make sure that all the `@angular` dependencies are the same version.

**Comment by 2upmedia** [comment] 2018-06-29 19:16
@hippee-lee Thanks for that. That clue helped us figure out what was going on. 

I'll add also, not only should your @angular dependencies bet the same version but check package-lock.json and double check that they're all the same there. Our package.json versions were all the same, but because the versions were ranges the @angular compiler was ahead by a few minor versions in the lock file vs the rest of the dependencies and that caused the problem. We fixed it by changing package.json to have strict version numbers.
