### ISSUE TITLE
Provide a light version of tooltips (with borders) for the light theme.

### ISSUE THREAD

**Issue by hspier** [vmware/clarity#1955] opened 2018-02-05 18:55 UTC
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
'$clr-tooltip-background-color' is not used for the border of the tooltip and a new variable '$clr-tooltip-border-color' defaulting to '$clr-tooltip-background-color' is created.

### Actual behavior
'$clr-tooltip-background-color' is used both for the background AND the border of the tooltip. This works well for a colored tooltip, but not for a tooltip that has a white background.

**Comment by UttamA** [comment] 2018-04-04 06:51
I see this issue in slackblitz for dark theme. 

Dark Theme: https://clarity-dark-theme-v10-tooltips.stackblitz.io/
Light Theme: https://clarity-light-theme-v11-tooltips.stackblitz.io/

**Comment by UttamA** [comment] 2018-04-04 10:15
@hspier I just looked into the scss files and $clr-tooltip-background-color is used to fill the triangle tip using the border. So same variable is used to fill both the rectangle and tip triangle. I have changed the color of both for confirmation. 
So I don't think this will make sense to separate the colors. Please let me know your thought on the same 

![tooltips_border](https://user-images.githubusercontent.com/4607437/38302027-f8630ad6-381e-11e8-89f9-e188ecb23460.png)

**Comment by hspier** [comment] 2018-04-04 14:00
The ask was not to have separate colors for the tooltip area and tooltip arrow. It was to have separate colors for the background color of the tooltip and the border of the tooltip. Just so you can reproduce, change the $clr-tooltip-background-color to 'white'. You will see that there isn't any border to the tooltip.

**Comment by UttamA** [comment] 2018-04-04 14:27
@hspier if you see below code we are not using border color for tooltip area. It is used only in tooltip arrow which is used to create the complete arrow with $arrow-height & $arrow-width. Please let me know if I am missing something.
 
`@mixin vertical-tooltip-generator($dirA:top, $dirB:right) {
    $oppA: map-get($opp-directions,$dirA);
    $oppB: map-get($opp-directions,$dirB);

    @include common-tooltip-styles;

    position: absolute;
    #{$dirA}: auto;
    #{$oppA}: 100%;
    #{$oppB}: 50%;
    #{$dirB}: auto;

    border-#{$oppA}-#{$oppB}-radius: 0;
    margin-#{$oppA}: $clr-tooltip-adjusted-margin;

    &::before {
        position: absolute;
        #{$oppA}: -0.375rem;
        #{$oppB}: 0;
        #{$dirA}: auto;
        #{$dirB}: auto;
        content: '';
        border-#{$oppB}: $arrow-height solid green;
        border-#{$dirA}: $arrow-width solid green;
        border-#{$dirB}: $arrow-height solid transparent;
        border-#{$oppA}: $arrow-width solid transparent;
    }
}
`

**Comment by hspier** [comment] 2018-04-04 14:52
@UttamA I am not talking about the border CSS properties. I am talking about the entire tooltip to have a visible border. This will obviously requires some changes on how you create the arrow and the area of the tooltip. 

In this image, using Clarity light theme and changing colors of the tooltip, this is how the tooltip looks if it is white:

<img width="151" alt="screen shot 2018-04-04 at 10 35 25 am" src="https://user-images.githubusercontent.com/6555494/38314456-3c2f5d8a-37f4-11e8-9d40-c0ddbbdc01ac.png">

Notice that it is barely visible from the content because it lacks a border.

What I would like to be able to do:
<img width="590" alt="screen shot 2018-04-04 at 10 51 01 am" src="https://user-images.githubusercontent.com/6555494/38315291-2bad77c4-37f6-11e8-9a24-ae1283606aae.png">

**Comment by UttamA** [comment] 2018-04-04 15:05
@hspier Thanks. I got confused with the explanation. Now I got the requirement.

**Comment by UttamA** [comment] 2018-04-04 15:07
I am looking in this issue

**Comment by UttamA** [comment] 2018-04-06 04:14
@adityarb88 I want to discuss the solution of this issue. I tried multiple options as below

1) transform: rotate -> We can rotate the rectangle and fit the right angle isosceles triangle at the edge but the border will not work in this case

2) clip path -> We can clip the right angle isosceles triangle and fit in the edge but same the border does not work

3) Create two triangle and overlap each other: I have used pseudo element :before and :after and fit the triangle. In this case border works. Still I need to exactly calculate the width of  hypotenuse to exactly match. Presently you will see little zig zag at the edge. 

Please find the solution of third option.
https://stackblitz.com/edit/clarity-light-theme-v11-tooltip
https://clarity-light-theme-v11-tooltip.stackblitz.io

Please let me know your thought on the same.

**Comment by adityarb88** [comment] 2018-04-06 16:30
@UttamA: 
We can't use `clip-path` because its not supported on IE11 and Edge both. 
The last solution could work. I adjusted the values a little bit and i think it looks fine now so you might need to try different values and test if the supported browsers render this correctly: https://stackblitz.com/edit/clarity-light-theme-v11-tooltip-u6zx9l?file=app/app.component.css

This change might affect signposts and error validation too. It is not as simple as changing the variable color value. Will have to verify which components use the tooltip generator mixin. Am going to increase the estimate of this task.

**Comment by adityarb88** [comment] 2018-04-06 16:30
@UttamA: Thanks for taking a look at this!

**Comment by UttamA** [comment] 2018-04-08 15:32
@adityarb88 Thanks Aditya. I will verify and test all the references of tooltip generator mixin.

**Comment by UttamA** [comment] 2018-04-23 03:59
@adityarb88 I have done the changes but the CI is failing in [✘ wizard form-validation default [chrome]]. This is because the arrow width which I added. I am new to gemini test case so I think we need to change the screen shots @clarity\gemini\screens\wizard\form-validation\default to accommodate the new size. 
Can you please check the changes once and let me know how to move forward in this issue. 

Thanks in advance

**Comment by hippee-lee** [comment] 2018-04-23 16:37
@UttamA - when the reference image needs to be updated, anyone can update it and commit it to the PR so we can take a look and approve. You can update the images in set4 whouch should generate new images only for the tests affected by your change. 

You do need to have docker installed and running on your system. See the wiki page on [css regression ](https://github.com/vmware/clarity/wiki/CSS-Regression-Testing)testing for more info. Once Docker is running all you need to do is run:

```npm run cssUpdate set4``` 

on the root of the project.

**Comment by UttamA** [comment] 2018-04-24 15:36
@hippee-lee Thanks for the help. I tried to setup the docker and gemini in my system. I executed npm run cssUpdate set4. I am seeing below error. Do you I need to do any other setup? 

Element .btn was not shown in 5000ms
✘ wizard custom-danger-button default [chrome]
Element .btn was not shown in 5000ms
✘ wizard default-header-actions default [chrome]
Element .btn was not shown in 5000ms
✘ wizard page-header-actions default [chrome]
Element .btn was not shown in 5000ms
✘ wizard static-wizard default [chrome]
Element .content-for-page-1 was not shown in 5000ms
✘ wizard static-wizard-shortcontent default [chrome]
Element .content-for-page-1 was not shown in 5000ms
✘ wizard dynamic-wizard default [chrome]
Element .btn was not shown in 5000ms
Total: 54 Passed: 0 Failed: 54 Skipped: 0 Retries: 0
Your HTML report is here: file://C:\All\workspace\clarity\reports\gemini\index.html
clarity_chrome

**Comment by hippee-lee** [comment] 2018-04-24 16:31
Hmm, it looks like Chrome wasn't able to connect to the server for those. 
I've seen that before and making sure the docker container was stopped (`$ docker container ls` to see running containers and `$docker stop <container ID here>`) 
If there is no container running you are good and can just run the updates again. If the selenium/chrom container is running you will need to stop it before re-running `npm run cssUpdate set4`.

**Comment by UttamA** [comment] 2018-04-25 04:44
@hippee-lee I tried the above command and observed empty list. Anyways after execution the container is killed. Actually I am running the script directly as` $ ./scripts/docker-cdc.js -u set4` instead of `npm run cssUpdate set4` because in window when I run this command then I am getting below errors.

> clr-all@0.11.14 cssUpdate C:\All\workspace\clarity
> ./scripts/docker-cdc.js -u

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clr-all@0.11.14 cssUpdate: `./scripts/docker-cdc.js -u`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clr-all@0.11.14 cssUpdate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uagarwal\AppData\Roaming\npm-cache\_logs\2018-04-25T04_37_06_347Z-debug.log

**Comment by hippee-lee** [comment] 2018-04-25 15:52
@UttamA - I see. And it still times out when you re-run set4 with the `docker-cdc.js` script? 
I do see the `Element .btn was not shown in 5000ms` error occasionally, usually when i'm running the gemini suites after re-starting my computer. When I see that, I kill the job on the command line, stop the docker container and re-run. The tests will run as I expect them to after that. 

So when you re-run the suites for set4 you are still getting `elements not shown` errors?

**Comment by CodingChum** [comment] 2018-04-26 03:12
@hippee-lee yes I still get the same error. I thought something related to windows on docker is the problem then I tried two version of docker then still the same problem. I also tried `gemini test `and still the same problem. 

I am thinking to write simple HTML with CSS and then run the gemini test case and see the result.

**Comment by UttamA** [comment] 2018-04-26 03:14
@hippee-lee Sorry I posted with different email id. CodingChum is also my user id.

**Comment by hippee-lee** [comment] 2018-04-26 18:01
Can you confirm the pull request we are talking about and make sure your latest changes have been pushed up to it? 
I'll pull your code and see if there is something I can do to help with the screenshots.

**Comment by UttamA** [comment] 2018-04-27 08:58
@hippee-lee I rebased and pushed the latest changes. You can pull the code. Thanks for the help

**Comment by adityarb88** [comment] 2018-05-08 17:36
@hspier: Discussed this with @reddolan & we are going to add this to our backlog. In the meanwhile, you could use `#ccc` color as the background for both the tooltip and the arrow.

![image](https://user-images.githubusercontent.com/1426805/39772924-80102d50-52c4-11e8-81cf-ee57fcf847d9.png)

The border solution is requires more work than simply flipping a variable as of now because the arrow requires multiple shapes to generate.

@reddolan recommends that we move in the direction that we used for dropdowns which is `border + box-shadow`.

**Comment by gnomeontherun** [comment] 2021-05-06 22:48
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.

**Closed by gnomeontherun** 2021-05-06 22:48 UTC
Labels: flag: has workaround, needs: design, priority: 1 low, type: design
