### ISSUE TITLE
[Datagrid] Manually updating clrDgPageSize no longer results in clrDgRefresh being triggered

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#1752] opened 2017-12-06 21:43 UTC
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Manually updating the clrDgPageSize should trigger a clrDgRefresh event to be fired on the table (this was how it worked in Clarity v0.9.x). 

### Actual behavior
Manually updating clrDgPageSize no longer triggers a clrDgRefresh event.

### Reproduction of behavior
Here is a working version (v0.9.x): https://plnkr.co/edit/7PBBUqnPSopd21NCyfxU?p=preview
And here is the same code running in v0.10.x where the event is no longer fired: https://plnkr.co/edit/cl9WfX76lYlbVTh6nm2u?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** MacOS Sierra

* **Browser:** Chrome 62.0.3202.94 (Official Build) (64-bit)

**Comment by hippee-lee** [comment] 2018-01-24 23:19
[StateProvider.change](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/state.provider.ts#L31) is not broadcasting events to `Datagrid` for some reason. I traced it into the settor for clrDgPageSize and stopped there for now.

**Comment by dragon503** [comment] 2018-04-19 09:03
@jbgarr Have you fixed it? 
I met the same issue and use "clrDgStateChange" as mentioned in #1099 but do not work.

**Comment by stefnoten** [comment] 2018-05-04 09:16
We have the same problem. The problem seems to be that the Page service does not trigger the StateDebouncer inside the [size setter](https://github.com/vmware/clarity/blob/a2bc32dc49bc63a968983a6a00f94d74282f0b1d/src/clr-angular/data/datagrid/providers/page.ts#L22). It only does this for changes of the [current page](https://github.com/vmware/clarity/blob/a2bc32dc49bc63a968983a6a00f94d74282f0b1d/src/clr-angular/data/datagrid/providers/page.ts#L98).

**Comment by mathisscott** [comment] 2018-09-04 13:06
@m-tomczyk 
This is on our radar but we do not currently have it assigned to anyone to be fixed. If it is a potential blocker for your team, we are certainly open to contributions.

**Comment by Jinnie** [comment] 2018-11-14 12:14
Btw, plunkr reproduction no longer working.
Attaching the stackblitz one I did while researching the issue, if needed for future reference:
https://stackblitz.com/edit/clarity-issue-1752

**Comment by Jinnie** [comment] 2018-11-14 19:04
Fixed in 0.13 and 1.0
Thanks, @stefnoten and @hippee-lee for the issue research. Very helpful!

**Closed by Jinnie** 2018-11-14 19:04 UTC
Labels: Bug
