### ISSUE TITLE
Spinner button ignores disabled attribute

### ISSUE THREAD

**Issue by emmalivingstone** [vmware/clarity#2427] opened 2018-07-05 08:13 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Once a spinner button has changed state from Loading to Success and the animation has completed, it should respect the 'disabled' attribute on the button.

### Actual behavior

It ignores the disabled attribute. In the example below the spinner button starts off as enabled, then once it's clicked it transitions from Loading to Success and the disabled property binding is set to true - however the button remains enabled.

### Reproduction of behavior

[Stackblitz reproduction](https://stackblitz.com/edit/disabled-spinner-button)

### Environment details

* **Angular version:** 6.0.7

* **Clarity version:** 0.12.2

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment] 2018-07-05 12:41
@emmalivingstone: Hi. This looks a duplicate of #2375. We have a PR https://github.com/vmware/clarity/pull/2421 which is under review right to now to fix this issue. Please subscribe to both for further updates.

Closing this as a duplicate. Thanks!

**Closed by adityarb88** 2018-07-05 12:41 UTC
