### ISSUE TITLE
clr-combobox multi select - the dropdown not to closes on outside click

### ISSUE THREAD

**Issue by asychikov** [vmware/clarity#5344] opened 2020-12-01 09:11 UTC
## Describe the bug

Multiselect combobox dropdown not to close on select. Also, the dropdown list does not close when mouse click outside of the target element.

Also, see #5307 

## How to reproduce

https://stackblitz.com/edit/clarity-v4-dark-theme-q2uh3r?file=src/app/app.component.html

![demo](https://user-images.githubusercontent.com/15362165/100718991-13e4b500-33cd-11eb-8331-66f7a08c846b.gif)

## Versions

**App**

- Clarity: **4.0.7**

## Workarounds
No workaround at the moment.

**Comment by bdryanovski** [comment] 2020-12-01 12:01
@Jinnie

**Comment by Jinnie** [comment] 2020-12-01 13:41
In multi-select it should not close on selection anymore, as described in the linked PR. This helps with the case when the user wants to select multiple entries at once. Especially when using KB only, or a screen reader.
But not closing on outside click is a problem and we need to investigate it.
It seems to only happen after selection. If no selection was done, the outside-click-to-close works okay.
Thanks for reporting.

**Comment by asychikov** [comment] 2020-12-09 07:00
also there is the following problem when using modals

**How to reproduce**

https://stackblitz.com/edit/clarity-v4-dark-theme-mtec8m?file=src/app/app.component.html

![5344_2](https://user-images.githubusercontent.com/15362165/101595667-ce476e00-3a04-11eb-9c3a-eaceecec5ed7.gif)

**Comment by ryan-bradford** [comment] 2021-01-15 21:11
Experiencing this same problem in VCD UI running v4.0.9

**Comment by toolen** [comment] 2021-02-04 09:18
Hi @Jinnie, any updates on this?

**Comment by haichaom** [comment] 2021-02-05 07:58
Same problem running on 5.0.0

**Comment by hippee-lee** [comment] 2021-02-05 18:07
Hi @toolen and @haichaom - I did a little bit of investigation here and I think I see where the issue is. If its a small change that I can make I'll try to get a PR up soon. If the change has side effects for Combobox we will have to wait until there is time to prioritize and properly address this.

**Closed as completed** 2021-02-18 09:08 UTC
Labels: status: needs investigation, component: combobox
