### ISSUE TITLE
Datagrid should not be stealing focus when the page change

### ISSUE THREAD

**Issue by ttsvetanov-vmware** [vmware/clarity#5374] opened 2020-12-10 11:32 UTC
## Describe the accessibility issue
In many places, we set Datagrid pagination page, size, ... programmatically. This trigger page changes observable and sets focus on Datagrid.

## WCAG Guideline
WCAG-G2.4.3 Level-A

## How to reproduce
https://stackblitz.com/edit/clarity-v4-light-theme-jj3zdt

1.  Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-jj3zdt'
2.  Click on the 'Page' button
3.  This button set currentPage on Datagrid pagination 
4.  See the focus on Datagrid 

## Expected behavior
Datagrid should not be stealing focus when the page changes

## Versions

**App**

- Angular: [9.1.0]
- Clarity: [3.1.7]

**Device:**

- Type: [PC]
- OS: [Windows 10 (64-bit)]
- Browser [Google Chrome (Version )]
- Version [84.0.4147.135 (Official Build) (64-bit)]
- Screen Reader: [NVDA]

For screen readers, we primarily support the following combinations, and other combinations will be considered on a case by case basis.

- NVDA + Firefox (Windows)
- VoiceOver + Safari (Apple)

**Comment by gnomeontherun** [comment] 2020-12-10 16:51
This is actually a duplicate of #4229, please check for existing issues when creating issues.

Accessibility has required that focus moves on page changes of data, but the PR #5375 will also address this with an optional disable for certain cases where the default behavior has side effects.

**Closed as completed by gnomeontherun** 2020-12-10 16:51 UTC
