### ISSUE TITLE
Datagrid columns have minimum width

### ISSUE THREAD

**Issue by oliverhanappi** [vmware/clarity#1405] opened 2017-08-31 15:33 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

It should be possible to fully control the width of datagrid columns, hence there should also not be a minimum width. There are situations in which a denser grid with small columns makes sense, e.g.:

![grid](https://user-images.githubusercontent.com/401938/29931739-5e9fcf3e-8e72-11e7-8d01-91feff74e67c.png)

### Actual behavior

The width of datagrid columns can be set by using CSS. However, the minimum width of a datagrid column is currently 96px. I do not know if this is by design or not, however it should either be clearly documented or the constraint should be removed. 

### Reproduction of behavior

https://plnkr.co/UVREum

1. Create a datagrid column that is sized to 40px.
2. Observe that the column is still 96px wide.

### Environment details

* **Clarity version:** 0.10
* **Browser:** all

**Comment by youdz** [comment] 2018-01-24 17:27
We need the minimum width to be the default case to ensure we have enough room for the filter toggle, sort icons, or anything else that might be added by Clarity to the column. But we understand your use case, so a good compromise would be to simply have a CSS class in Clarity that you can add to a column header, and it will remove the `min-width` for that column. Please only do this when the corresponding columns cannot be sorted of filtered.

**Comment by Trojaan** [comment] 2018-09-10 08:17
Any workarounds possible to achieve this in the current version?

**Comment by mathisscott** [comment] 2018-09-10 15:56
@Trojaan 
If the goal is to have a non-sortable, non-filterable, tabular display of a fixed set of data (as in the OP example), you [should just use a table](https://vmware.github.io/clarity/documentation/v0.13/tables).

**Comment by GaryHyland** [comment] 2019-05-24 08:41
![Calrity Datagrid col header sizing issue](https://user-images.githubusercontent.com/39715655/58314405-03e82e80-7e42-11e9-81a1-02b2bff7b0a0.png)
I also need this.. there are some cols that contain for eg Qty or other small width (with no need to sort or filter), but I still want to use sort/filter for others cols and pagination for the set as a whole.
I toyed around with changing the min-width: 4rem to 3rem or 50px in the 4 spots in CSS and it seems to work but I see some artifacts as below that are "sort of" related to #2906 or #1725. Actually seems to be a combination of the column header length AND the page size ie data grid size.
Top pic shows wider datagrid where clicking on the header did not affect col header separator position adversely, next one shows  smaller grid but with end col selected, final pic shows same smaller grid but with same col header selected as original, but this time shows artefact - col separator pushed out to the right.
Would appreciate any suggestions with CSS to workaround these col header artifacts.
Loving your work though..

**Comment by bret-bailey** [comment] 2019-06-04 18:28
> 
> 
> @Trojaan
> If the goal is to have a non-sortable, non-filterable, tabular display of a fixed set of data (as in the OP example), you [should just use a table](https://vmware.github.io/clarity/documentation/v0.13/tables).

@mathisscott - the main goal of using a UI Framework is uniform output - the 'just use a table' approach creates output that is not consistent with the datagrid style - you end up with 2 differently styled tables - that's an unfortunate stance to take for end users - couldn't it be prudent to check if those features are not leveraged within the clr-dg-column component and unset the min-width style?  or something along those lines instead of saying 'just use something else' outright  ...

@hippee-lee [mentioned here](https://github.com/vmware/clarity/issues/2906#issuecomment-482217440) that he had figured out why the .% style doesn't work - it would be great if this was resolved - at this point, I could not even get the .px style to work - html always shows width: 0px - datagrid width has become a frustrating thing to work around - 

One thing I noticed is when you get the cursor change to <-||-> (if you were to resize the columns) & double-click, then all of the widths are calculated properly based on the cell data width ... perhaps the code within that double-click event should be used from the datagrid initialization/calculation code?  (in this case, there are 9 columns where they are auto-initialized to all be the exact same width (0px) despite some cell data being longer than others)

**Comment by hippee-lee** [comment] 2019-06-04 19:18
@bret-bailey

- Our tables should have style parity with the datagrids. If that is not the case can you replicate the issue and submit a new ticket focused on that? 
- I know this is a problem for you and I'm really sorry that I don't have a satisfactory answer for you. I hope I can explain some of whats going on properly. Here goes - the datagrid layout is complex under the hood. In order to support the various combination of use cases we will likely stay with a flexbox layout and this is what I believe is causing the issue with % widths on columns and cells. To this point, I haven't found a way to support `% widths + flex: 1 1 auto + user resized columns or declared widths on columns + the requirements for the last column<sup>1</sup>` + the use case when a user has resized a column`
- In addition to the last point. Width are calculated buy putting only the columns, rows and cells into a container with native table element styles with ```display: table;
      table-layout: auto;``` - this allows us to let the browser handle the sizing calculation ands provide auto sizing for _any content given to columns and cells_ and then we can apply specific widths as we need to or not based on the combination of datagrid features in use at any given time
- If you have any ideas or want to take a stab at coming up with a solution please let me know I'll be happy to support that as best I can. Right now this isn't one of the issues we can work on given some of the other priorities related to a11y and other larger feature tickets. 

**1:** When all columns are resized or have a width set by the consumer then the last column cannot have a fixed width of any kind. It needs to flex to take up the remaining width of the table even when the width of the table overflows on the x axis.

**Comment by hippee-lee** [comment] 2019-06-04 19:39
Related to the comment about not getting a px width to work. Here is an example where I set the first colum to a `500px` width: https://stackblitz.com/edit/gh-1405-px-width-column

**Comment by Shijir** [comment] 2019-06-04 21:38
The min-width on column is not a bug. This is expected behavior of Datagrid columns. Users could simply override the default `min-width` style as below:
```
<clr-dg-column [style.min-width.px]="anyPxValueYouWant"></clr-dg-column>
```
Maybe, this is a documentation issue.

**Comment by bret-bailey** [comment] 2019-06-05 11:11
@hippee-lee - thank you for the explanation - definitely can see how difficult a problem this really is to tackle - I'll give it some further thought & review the code to see if something pops out 

https://gh-1405-px-width-column-ncmdfk.stackblitz.io
Here is an example of 'just a table' compared to the datagrid - without any style changes - they are noticeably different - specifically, header text alignment & dividers - our product uses the 'datagrid-compact' class, which only further separates the uniform ui differences

@Shijir - thanks for that suggestion - in order for that to work, you still need the width setting as well - so you end up with this:
`<clr-dg-column [style.min-width.px]="pxValue" [style.width.px]="pxValue"></clr-dg-column>`
However, it is noticeable that the columns no longer align with the cell values once you set the min-width below 96 - so I'm not certain that this is a viable work around

Oddly enough, despite the stackblitz working as expected with regards to setting the width and min-width - both values are still ignored within my application - very strange - something else must be affecting the width styles ...

**Comment by whizkidwwe1217** [comment] 2020-02-02 14:59
I also have a pretty good use case where I need to only display status icons in a column but since there's a minimum width set to it, I can't set the width same as the icon.

![image](https://user-images.githubusercontent.com/1977391/73610150-5f90cb80-460f-11ea-9b63-1f3eeed84266.png)

**Comment by hippee-lee** [comment] 2020-02-03 16:10
As a workaround, override the css for the column with status icons.

Here is one way to do that with an Angular style binding but it could also be accomplished with css placed directly on the column.: https://stackblitz.com/edit/gh-1405-px-width-column-gjlaxw?file=src/app/app.component.html

Note: this approach needs the styles applied to with the column and the cell with the status icon in it.

**Comment by gnomeontherun** [comment] 2021-01-29 15:45
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-01-29 15:45 UTC
Labels: component: datagrid, type: enhancement
