### ISSUE TITLE
Support aligning table cells to the right

### ISSUE THREAD

**Issue by innerjoin** [vmware/clarity#2794] opened 2018-10-30 15:52 UTC
## Summary

Table cells are aligned to the center by default and can be changed to the left by adding the `.left` class. Consequently there should be a `.right` class as well.

* _What is the change?_ <br>Add a new `.right` class that allows aligning cells to the right.
* _Why should it go in Clarity?_ <br>As aligning is supported, it seems consequent to me to support `.right` as well.
* _Does this change impact existing behaviors? If so how?_<br>No (as far as I can see)

## Use case

I have some budget numbers of very different size. Aligning them to the right would make it easier for the end user to compare the numbers.

## Examples

| `.left` aligned | Center aligned | New: `.right` aligned |
| :---         |     :---:      |          ---: |
| 16'500 €   | 16'500 €      | 16'500 €     |
| 180 €     | 180 €      | 180 €     |

## Workarounds

Yes, I can just use the CSS of my component to override the alignment

**Comment by mathisscott** [comment] 2018-10-30 16:00
The hardest part of this enhancement will be making sure to generate CSS regression tests for Gemini.

**Comment by colinreedmiller** [comment] 2019-06-07 23:16
Documentation should specify the following:

1. Right alignment is discouraged for a11y reasons as well as basic good design practice. It should only be used in cases where it provides clearly improved content specific formatting, such as the (currency) example above.

2. When using right alignment, use tabular numbers (available in the Consolas font) since they also serve the intent of comparative clarity via aligned columns.

Consolas reference: https://v1.clarity.design/typography

**Comment by gnomeontherun** [comment] 2021-01-29 22:50
Given the limited cases where this would be viable for accessibility and ux reasons, I'm going to close this request since applications can easily handle this on their own.

**Closed by gnomeontherun** 2021-01-29 22:50 UTC
Labels: Dev, Help Wanted, flag: has workaround, priority: 1 low, type: design, type: enhancement
