### ISSUE TITLE
Clarity Icons slow down page load times significantly

### ISSUE THREAD

**Issue by oliverhanappi** [vmware/clarity#1296] opened 2017-08-14 07:46 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Including clarity icons in your page should not slow down the page load significantly.

### Actual behavior

When including claritiy icons in your page, the page loads very slow, especially in Internet Explorer it is unacceptable. The load time I refer to is the time the javascript script files need to execute, so this times are without network transfer times.

The overhead of including clarity icons on my machine is approx. as follows:

- Internet Explorer 11: 4200 ms
- Chrome: 500 ms
- Firefox: 700 ms
- Edge: 3300 ms

I am aware of the possibility to include only a subset of all icons, however I think that it should be possible to use all icons without such an high impact on load times. When reducing the icon set to only core and essential, page load times drop also, so it seems to be linear to the number of icons included.

Other icon libraries like Font Awesome do not suffer from such issues.

### Reproduction of behavior

https://plnkr.co/SbZL7QHr55AgHTXJIH8d

Open the plunkr and wait for a time to appear. The page measures the time it takes until the body.onload callback is executed. Open the plunkr twice such that caching is utilized for the clarity icons javascript file and you see the pure overhead of parsing the SVGs in the browser.

### Environment details

* **Clarity version:** 0.10
* **Browser:** all

**Comment by oliverhanappi** [comment] 2017-08-14 07:47
Is probably related to #1253.

**Comment by adityarb88** [comment] 2017-08-14 13:15
@oliverhanappi: Yes this is a duplicate of #1253. Closing this but please subscribe to that issue for updates on the issue.

**Closed by adityarb88** 2017-08-14 13:15 UTC
Labels: duplicate
