### ISSUE TITLE
Column width override not available for clr-checkbox-container and clr-radio-container

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#4119] opened 2019-12-16 16:02 UTC
## Describe the bug
As per the section, Overriding column widths in Forms documentation - https://v2.clarity.design/forms, one can adjust the width of label and input elements by applying clr-col-* of choice.
```
<form clrForm>
    <clr-input-container>
        <label class="clr-col-12 clr-col-md-4">Field 1 label</label>
        <input class="clr-col-12 clr-col-md-8" clrInput type="text" [(ngModel)]="model" name="example" required />
        <clr-control-helper>Helper text that shows while it is pristine and valid</clr-control-helper>
        <clr-control-error>Error message that appears after focus is lost and control is invalid</clr-control-error>
    </clr-input-container>
</form>
```

Unfortunately, there does not seem to be any way to do same for `clr-checkbox-container`.
The markup for checkbox looks like below:
```
<clr-checkbox-container>
  <label>Inline checkbox example</label>
  <clr-checkbox-wrapper>
    <input type="checkbox" clrCheckbox name="checkboxes" required value="option1" [(ngModel)]="checkboxes.option1" />
    <label>Option 1</label>
  </clr-checkbox-wrapper>
  <clr-checkbox-wrapper>
    <input type="checkbox" clrCheckbox name="checkboxes" required value="option2" [(ngModel)]="checkboxes.option2" />
    <label>Option 2</label>
  </clr-checkbox-wrapper>
  <clr-control-helper>Helper text</clr-control-helper>
  <clr-control-error>This field is required!</clr-control-error>
</clr-checkbox-container>
```
If we do inspect element, then, one will observe that Clarity adds clr-col-md-10 to a &lt;div&gt; which is parent of `clr-checkbox-wrapper` and is not exposed to users of the control.

![image](https://user-images.githubusercontent.com/102016/70921950-41651100-204b-11ea-8871-106b70bba2fb.png)

## Expected behavior

Checkbox containers label and checkbox area widths are controllable by developers to fit their form layours.

## Versions

**App**

* Angular:  8.3.17
* Node: v10.13
* Clarity: 2.2.2

**Device:**

* Type: Dell
* OS: Windows 10
* Browser Chrome
* Version 

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2019-12-16 21:32
This sounds like it might be a duplicate of https://github.com/vmware/clarity/issues/4072, can you review that and see if it helps you out?

**Comment by srikanthps** [comment] 2019-12-17 05:32
The [Stackblitz example](https://stackblitz.com/edit/clarity-form-lmezj2-rayhfy?file=src/app/app.component.html) from #4072 seems to work for me - though it seems quite counter-intuitive.   

May be you should add that it to documentation.

```
<clr-checkbox-container clrInline>
  <label class="clr-col-12 clr-col-sm-4 ">Inline checkbox example</label>
  <clr-checkbox-wrapper>
    <input type="checkbox" class="clr-col-12 clr-col-sm-8 " clrCheckbox name="checkboxes" required value="option1" [(ngModel)]="checkboxes.option1" />
    <label>Option 1</label>
  </clr-checkbox-wrapper>
  <clr-checkbox-wrapper>
    <input type="checkbox" clrCheckbox name="checkboxes" required value="option2" [(ngModel)]="checkboxes.option2" />
    <label>Option 2</label>
  </clr-checkbox-wrapper>
  <clr-control-helper>Helper text</clr-control-helper>
  <clr-control-error>This field is required!</clr-control-error>
</clr-checkbox-container>
```

**Comment by gnomeontherun** [comment] 2021-02-02 22:53
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-02-02 22:53 UTC
Labels: @clr/angular, component: forms, status: needs info, type: bug
