### ISSUE TITLE
Accordion Expand Collapse All panels Using Two way binding

### ISSUE THREAD

**Issue by siddharth1903** [vmware/clarity#5287] opened 2020-11-11 12:35 UTC
## Bug Description
I have an accordion with [clrAccordionMultiPanel]="true" 
All the panels are two way bound to a state object which is an array of booleans using [(clrAccordionPanelOpen)]
When trying to expand or collapse all of them one shot using the state array, only one of them opens at once

## How to reproduce

https://stackblitz.com/edit/accordion-expand

1. Click Expand all 
2. Click Collapse all 

## Expected behavior

All panels need to be opened and closed when they are two way bound

## Versions

**App**

- Angular: [~10.2.0]
- Node: [ 12.x]
- Clarity: [4.0.5]

**Device:**

- All

## Additional notes

I have added an alternate implementation that seems to work when the same behaviour is tried to be achieved through ViewChildren. I would not have to do this ideally. To get this, please use(in html) expandAllUsingVC and collapseAllUsingVC methods defined in ts

**Comment by Jinnie** [comment] 2020-11-13 15:40
Looks like a lifecycle bug to me. May be related to the series of animations that need to be performed simultaneously.
Another workaround could be to request for change detection cycle for each panel you want to open/close like this:
```
  collapseAll() {
    this.state.forEach((state, i) => {
      this.state[i] = false;
      this.cdRef.detectChanges();
    })
  }
  expandAll() {
    this.state.forEach((state, i) => {
      this.state[i] = true;
      this.cdRef.detectChanges();
    })
  }
```

**Comment by siddharth1903** [comment] 2020-11-14 13:16
@Jinnie yes the workaround is okay for now. However it would be great to have this addressed without the cdref!

**Comment by bdryanovski** [comment] 2020-11-23 10:57
I spend some time working on some solution, the issue here is that we needed to redesign how we pass changes across the open/closed panels. 

The problem is that after the first-panel update it states, it also updates all other panels with their previous state, basically overwriting them. So to fix that we need to update panel-by-panel but this requires much more refactoring that I think it would take, these changes will affect Stepper witch is sharing a lot of internals with the Accordion.

The effect of this could be easily demonstrated by pressing multiple times the close-all or open-all button and the pannels will change one-by-one in the order they are defined. 

The code that is related to the issue could be found here
```ts
// projects/clr-angular/src/accordion/providers/accordion.service.ts

  protected emitUpdatedPanels() {
    this._panelsChanges.next(this.accordion.panels);
  }
```

For example trigger by this line or any other, that is updating `panels`

```ts
  togglePanel(panelId: string, open?: boolean) {
    this.accordion.togglePanel(panelId, open);
    this.emitUpdatedPanels();
  }
```

Will update only one panel and overwrite everything else with their previous state. 

So for now the workaround will have to do the trick and spend some time rethinking it or address it into Core.

**Comment by siddharth1903** [comment] 2020-12-16 11:10
@bdryanovski do you guys have a tentative date in mind when this can be addressed?

**Comment by gnomeontherun** [comment] 2021-02-05 20:53
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed as completed by gnomeontherun** 2021-02-05 20:53 UTC
Labels: type: enhancement, v3, v4, v5, resolution: enhancement request
