### ISSUE TITLE
Grid action menu is cut off in stack view

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#2425] opened 2018-07-04 15:21 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Action menu should be accessible and visible. When action menu is displayed and it overflows - then scrolling down/up to see all items from the menu should not close the menu.

https://stackblitz.com/edit/clarity-light-theme-v11-gzhqk4

As the main-container height is set to 200px(in order to simulate window borders), the grid item's action menu does not fit in the screen. I should be able to scroll in order to see all items from the action menu. 

Also, the action menu of the last item inside the grid is cut off. I expect to be visible outside of the grid.

### Actual behavior
The action menu is not completely visible and is tricky to select an option from the action menu if the menu is long and user should scroll.

This is applicable for  dropdown menus as well.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-gzhqk4

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.11

* **OS and version:** MacOS High Sierra

* **Browser:** Chrome, Firefox

**Comment by gnomeontherun** [comment] 2020-03-31 18:07
Hi there, the reproduction provided is no longer available and I'm also unsure what the issue is based on the description. This mentions a stack view but it does not have an action menu.

I'm going to close this based on the inability to triage, please reopen with an updated reproduction if it is still an issue.

**Closed by gnomeontherun** 2020-03-31 18:07 UTC
Labels: status: needs investigation
