### ISSUE TITLE
Datagrid with filter on the left side

### ISSUE THREAD

**Issue by timvl** [vmware/clarity#1412] opened 2017-09-04 07:21 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
On a datagrid with filters; the filter on the most left column should be aligned to be completely visible on the screen

### Actual behavior
The filter on the most left column is outside the screen.

### Reproduction of behavior
https://plnkr.co/edit/T4SmuRrrOX6yrNKxaNnO?p=preview
### Environment details

* **Angular version:** 4.0.0

* **Clarity version:** 0.10.3

* **OS and version:** Windows 7

* **Browser:** Chrome Latest

**Comment by youdz** [comment] 2017-09-05 15:33
This is what we've been referring to as "collision detection" for our popovers, and it's a pretty difficult problem to solve. I'm marking this as duplicate of #1262 for now, even though it's on different popovers (dropdowns vs datagrid filters) because the issue is the same. Thanks. :)

**Closed by youdz** 2017-09-05 15:33 UTC
