### ISSUE TITLE
clicking on the internal anchor tag inside drop down list which is placed inside clr-header does not trigger Hamburer menu close

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#5204] opened 2020-10-27 11:38 UTC
clicking on the internal anchor tag inside drop down list which is placed inside clr-header does not trigger Hamburer menu close

**Comment by coryrylan** [comment] 2020-10-27 14:48
Closing as duplicate of https://github.com/vmware/clarity/issues/5203

**Closed by coryrylan** 2020-10-27 14:48 UTC
