### ISSUE TITLE
Wizard Incorrect Screen Readings After Reaching End of Content

### ISSUE THREAD

**Issue by jeff-bacon** [vmware/clarity#4210] opened 2020-01-16 17:37 UTC
## Describe the bug

Using Chrome + NVDA:

1. The button used to open the wizard is read by screen readers after reaching the end of the wizards content and before focus returns to the beginning of the wizard.

2. The last button of the wizard is read by screen readers after reaching the end of the wizards content and focus returns to the first tab of the wizard.

## How to reproduce

[https://clarity-light-theme-v2-p315xm.stackblitz.io/](https://clarity-light-theme-v2-p315xm.stackblitz.io/)

1. Tab until reaching the **Open Wizard** button.
2. Press **Enter**
3. Tab until reaching the **Next** button.
4. Tab more to continue to the start of the wizard.
5. Notice that the screen reader reads **Open Wizard**
6. Tab until reaching the **Page 1** tab.
7. Tab and notice the screen reader is reading **Next**

![Untitled](https://user-images.githubusercontent.com/17691864/72550590-e855ec00-3847-11ea-9548-913068790cfe.png)

## Expected behavior

1. Navigating through the wizard should not prompt screen readers to read content which is outside the wizard.

2. Navigating through the wizard should not prompt screen readers to read incorrect content.

## Versions

**App**

* Angular: 8.2.4
* Clarity: 2.1.2

**Device:**

* Type: Surface Book
* OS: Windows 10
* Browser: Chrome
* Version: 79.0.3945.117

**Comment by gnomeontherun** [comment] 2021-02-01 22:47
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:47 UTC
Labels: @clr/angular, browser: screen reader, component: wizard, needs: accessibility input, priority: 2 medium-low, status: backlog, type: accessibility
