### ISSUE TITLE
[Wizard] Stepnav is jumping to the wrong page when pages are hidden/shown (bullet pt #2 below)

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#810] opened 2017-04-27 19:15 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
* Use *ngIf to control page skipping and unskipping for dynamically created pages.

### Actual behavior
* Open wizard, hit "Toggle page 2 visibility" button twice. Click Next to page 2. The dynamically generated page content is missing.
* Relevant issue: Open wizard, navigate to page 3, then navigate back to page 1. Hit button twice. It jumps to page 3 directly.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates: https://plnkr.co/edit/8bkNAtzXiadhq4THKQS7?p=preview

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.1

**Comment by mathisscott** [comment] 2017-04-27 19:44
@yaooluu : This appears to be two separate issues.

The first issue is the generated page content going away after toggling the second step. This is because the generated page content is only being inserted on `ngAfterViewInit`. You will likely want to change this to insert the page content either with `ngOnChanges` or in both `ngAfterViewInit` _and_ `ngOnChanges`. I'll ping @youdz to set me straight on this if I'm confused.

The second issue is the navigation jumping to the third step. I believe that to be a bug.

If my assessment of the first issue is accurate, it's not a bug but a way that the dynamically generated wizard pages will need to interact/integrate with Angular.

If that is correct, we'll convert this to a stepnav bug and triage accordingly.

**Comment by youdz** [comment] 2017-04-27 22:14
Hi @yaooluu, I think adding the dynamic pages this from the parent component (in this case, `AppComponent`) creates a lot of issues if you want to stay dynamic, and you end up reinventing the wheel by listening to every lifecycle event that happens. Right now, you'd need to listen to the `Querylist` changes, identify the ones that appeared, and re-insert the dynamic component. Not only is this painful to write and maintain, it also has no reason to fall under the responsibility of the app component. 

I believe the correct solution is simply to use a "placeholder" page component that appends the real page to itself on init. I modified your plunker to show how it would work:
https://plnkr.co/edit/RjLGlkFkUmhpohNUCSvy?p=preview
Most of it stayed intact, but the dynamic creation moved into the `MyPage` component and happens on initialization. The whole point is that every time your `*ngIf` changes, you re-create a new `MyPage` instance which will run its `ngOnInit()`.

I'm guessing not all pages are `RealPage`, but you use the index or something to identify the right component. This is still possible with the pattern I suggest, since the index or any other indicator can be passed as a simple input, and will already be set when `ngOnInit()` runs. You could also easily use a service that each `MyPage` component can inject in its constructor to request the correct component type.

So I believe the dynamic creation is a non-issue here, with the right pattern it works absolutely fine. The page jump when toggling page 2 is a real bug though, so I'll let @mathisscott triage this issue accordingly.

**Comment by mathisscott** [comment] 2017-04-27 22:18
Awesome. Thanks, @youdz. If it's okay with you @yaooluu, I'm going to switch this issue over to the stepnav jumping. That looks like a real bug.

Thanks for the feedback, @yaooluu

**Comment by yaooluu** [comment] 2017-04-28 22:14
@youdz Thanks for the explanation and workaround!

@mathisscott I think there're two concerns:

> I believe the correct solution is simply to use a "placeholder" page component that appends the real page to itself on init.

For supporting dynamic page creation, do you think Clarity Wizard can provide this out of the box? (E.g. an input `clrWizardPages` which takes an array of page classnames)

> The whole point is that every time your *ngIf changes, you re-create a new MyPage instance which will run its ngOnInit()

Re-creating the page every time will lose page data. Any developer that uses *ngIf to hide/show pages will have to save page data somewhere else when hiding the page and recover them when re-creating the page. This can be a pain for maintaining the wizard state...

In old wizard we're only visually showing/hiding and filtering the page through `clrWizardStepIsSkipped`. What's the design consideration regarding this feature in new wizard?

https://github.com/vmware/clarity/search?utf8=%E2%9C%93&q=isSkipped

**Comment by mathisscott** [comment] 2017-04-28 22:35
@yaoolu

Thanks for the feedback.

I will answer what I can and leave the floor open for @youdz to fill in or correct any details I may miss.

The skipped feature of the old wizard was always a hack. There are performance reasons why you would not want wizard pages lurking around after they are deactivated. Consider if you had a wizard with three or four workflows, each with several data grids within them.

I would say that the proper approach is to not store data in your pages. That's what models are for. The pages should be consumers of the data in the model. Not only does that make it easier to reset the wizard (because you have a clear picture of your data in the model) but it also limits the responsibilities and concerns of the view layer of your application.

If you want to inject your own views inside a page, I would recommend keeping your models above those injected views. That way the state of your data is all-in-one place. If you wanted to pass that model down to your injected pages, I believe you could do that. If you needed the page to communicate up to whichever layer holds your model, you would likely need a service.

**Comment by mathisscott** [comment] 2017-05-10 19:27
I have verified that bullet point 2 is fixed with the changes in #877 

We may still want tweaks in the resulting behavior but we should open those as additional enhancements/fixes.

**Closed by mathisscott** 2017-05-10 19:27 UTC
Labels: bug, ClarityNG
