### ISSUE TITLE
Password input component layout issues

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3317] opened 2019-04-24 07:08 UTC
## Describe the bug

I'm creating a responsive layout form that is composed of text and password inputs. But I found issues in the password component:

1. Unable to set width of the password component equal to other input components.
![image](https://user-images.githubusercontent.com/1977391/56638480-e4be7b80-66a0-11e9-98cf-c6bce7e70216.png)
2. Setting the width of the password input component to 100% doesn't take effect and while other inputs like text works fine in 100% width,
![image](https://user-images.githubusercontent.com/1977391/56638498-ee47e380-66a0-11e9-8a8a-75ee1781a6b1.png)
3. It makes the password eye overlap the error control icon when the width is set to 100%
![image](https://user-images.githubusercontent.com/1977391/56638513-f4d65b00-66a0-11e9-9487-d5470b931919.png)

## How to reproduce
Please take a look at this stackblitz:
https://stackblitz.com/edit/clarity-light-theme-v1-0-rdq5tq

To reproduce the overlapping icons in the password component, please resize the preview pane to 500px. The css in appcomponent.css sets the width of the input elements to 100%:

```css
@media only screen and (max-width: 576px) {
    input {
         width: 100%;
     }
}
```
## Expected behavior

Same width:
![image](https://user-images.githubusercontent.com/1977391/56638639-3d8e1400-66a1-11e9-9797-6fb0b062104d.png)
Eye & error indicator should not overlap:
![image](https://user-images.githubusercontent.com/1977391/56638736-804fec00-66a1-11e9-8968-5299d1cf91c2.png)

## Versions

**App**

* Angular: 7.*
* Node: 10.*
* Clarity: 1.1.3

**Device:**

* Type: Dell XPS 13
* OS: Windows 10
* Browser: Chrome/Edge Chromium Dev
* Version: Latest

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2019-04-24 16:36
The size of the input is controlled by the browser, and the show/hide icon is added for passwords, so we don't expect equal withs. I don't have time to work out the CSS for the whole solution here, but our current design expects this behavior and it is up to applications to override if they need.

We've had several similar issues opened lately, and it is something on our radar to consider holistically because its not a change we're going to make for just one component if we address this.

I'm going to close this as working as intended and take notes for this in the future.

**Closed by gnomeontherun** 2019-04-24 16:36 UTC
