### ISSUE TITLE
Form with clrLayout="compact" breaks `clr-control-helper` text

### ISSUE THREAD

**Issue by antonevane** [vmware/clarity#5154] opened 2020-10-16 03:12 UTC
## Describe the bug

The form with a compact layout doesn't place `clr-control-helper` under input.
Reactive Forms, Clarity 4.0.4.
`clrForm`
`clrLayout="compact"`

## How to reproduce
1.  Go to [stackblitz](https://stackblitz.com/edit/angular-ivy-2igq8f?file=src/app/app.component.html)
2. The first form has a compact layout and helper text moved to the right - angular 3.x had under the input field.

## Expected behavior

The `clr-control-helper` test has been displayed under the input field instead of right side.

## Versions
- Angular: 10.1.6
- Node: v14.13.1
- Clarity: 4.0.4

**Device:**

- Type: [iMac ]
- OS: [OSX Catalina]
- Browser [chrome]
- Version [86.0.4240.80]

**Comment by bbogdanov** [comment] 2020-10-16 09:18
We need to revisit the styles for layouts in forms.

Sharing a quick fix for it [here](https://stackblitz.com/edit/angular-ivy-pvts6u?file=src%2Fapp%2Fapp.component.css) until we fix it in the library.

**Comment by antonevane** [comment] 2020-10-16 13:57
@bbogdanov Thank you for a quick response and for the provided workaround.

**Comment by gnomeontherun** [comment] 2020-10-16 23:14
This is the correct layout for compact, where the helper text is inline with the form field. That is the key point for compact over horizontal layouts. Please see https://clarity.design/documentation/forms for demos of each type and you can see the layout was the same in v3 as well, so I'm not sure what you had before but it looks correct to me as it stands. 

I'm going to close this as working as intended, and I see it working in v3 and v4 the same way on the documentation.

**Closed by gnomeontherun** 2020-10-16 23:14 UTC
Labels: @clr/angular, component: forms, flag: has workaround, type: bug

**Comment by antonevane** [comment] 2020-10-17 00:26
@gnomeontherun It is an interesting point, I do see it in the doc.
We had behavior that I have mentioned for about a year, but we had a form with CSS classes.

`<form clrForm class="clr-form clr-form-compact"></form>`
