### ISSUE TITLE
clr-datagrid with clrDgItems and trackBy is tearing down complete grid DOM and creating new DOM

### ISSUE THREAD

**Issue by vraddy** [vmware/clarity#4543] opened 2020-05-07 07:34 UTC
## Describe the bug

clr-datagrid with clrDgItems and trackBy is tearing down complete grid DOM and creating new DOM, where table with ngFor and trackBy does it by appending only new row.

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v2-kddu58
In this demo new record is adding to rows for every 3 seconds, this data is used in clr-datagrid with clrDgItems and trackBy, the same data used in table with ngFor and trackBy.. looks like clr-datagrid is tearing down complete DOM where table does it very silent by appending last row(tr), from chrome DevTool brief highlight of nodes which are altered.
clr-datagrid is briefly highlighting complete datagrid DOM and table is briefly highlighting only new added row(tr)

## Expected behavior

If trackBy is to avoid tearing down complete DOM and update only new data, then clr-datagrid should not alter any of existing rows DOM, append only last row.

## Versions
- Angular: 8
- Clarity: 2

**Comment by gnomeontherun** [comment] 2020-05-11 16:52
Hi there, this is the expected behavior. A table is static, so adding a row is simple to compute. However, imagine you have a sorted list that has new items, in order to apply the sorting properly it would have to rerender the rows to apply sorting and other possible transformations. If you change `clrDgItems` to `ngFor` the behavior remains the same. There is potential to try to determine when it is truly necessary to recreate the DOM for each row, but I'm not sure how important that would be since the idea that the datagrid would grow ever larger like the demo is not very usable or functional.

I'm not really sure what the real use case behind this type of behavior is, could you express more about what you are trying to do and why this pattern?

**Comment by vraddy** [comment] 2020-05-12 10:16
Hi @gnomeontherun thanks for your response.. yes having sorting or other transformation in place it would not make sense to just add new row at the end, since there is a trackBy i was looking for silent update..

My use case, the example i given here is bit unrealistic.. but i have something like there will be a new data for grid via websocket(not very frequent) and record count may go up to 1000 so thought it would be performance hit to remove 1000 records from DOM and recreate.. I have solved it by paging with size of 100.. recreating 100 records would not be problem.

**Comment by gnomeontherun** [comment] 2020-05-13 00:31
Thanks for the update. I'm going to close this as resolved as pagination is always recommended to limit complexity in both performance and usability.

**Closed by gnomeontherun** 2020-05-13 00:31 UTC
Labels: status: needs info

**Comment by juanmendes** [comment] 2020-07-30 21:29
Just a note: properly supporting `trackBy` means that your rows won't lose state when it gets refreshed, if all the DOM nodes are recreated, they will lose any state. 

We have rows that display signposts, with this approach of always re-rendering, any signposts that were opened will be closed after a row update. We had to do a lot of workarounds to get this to work properly.
