### ISSUE TITLE
Provide deprecated forms as opt-in to ease migration

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#3419] opened 2019-06-05 18:08 UTC
## Summary

We ask that the CSS for the old forms will be around longer and not dropped in 2.0. Or having a way to include them separately. The news forms are limited and requires a lot of work that will not happen any time soon on our and many others applications. The new forms also don' support some of our use cases. E.g. support signposts.

## Use case

See above

## Workarounds

No

**Comment by gnomeontherun** [comment] 2019-06-05 18:34
Due to the complexity of some applications, we're considering how we can export the deprecated forms CSS as a standalone file to opt-in to it, and perhaps also the old clr-checkbox Angular module. This is a special case where we have already deprecated and removed the support, but to ease migration challenges we can offer this for a little longer.

We also need to define exactly what our support policy is on this, since it would be an exception to our normal support policy.

**Comment by rbirkgit** [comment] 2019-06-19 15:01
We noticed some styles assumes the use of the boostrap css. I assume we either need to keep that as an option too or update them to the new clarity ones. We noticed this when we started updating the columns only without updating the forms and got issues.

`.form .form-group.row > [class*='col-'] > span {
     color: #000; }
     form .form-group > label:first-child.required:after,
     form .form-group > span:first-child.required:after,
     form .form-group.row > [class*='col-'] > label.required:after,
     form .form-group.row > [class*='col-'] > span.required:after,
     .form .form-group > label:first-child.required:after,
     .form .form-group > span:first-child.required:after,
     .form .form-group.row > [class*='col-'] > label.required:after,
     .form .form-group.row > [class*='col-'] > span.required:after {
       content: '*';
       font-size: 0.58479532rem;
       line-height: 0.5rem;
       color: #c92100;
       margin-left: 0.25rem; }`

**Comment by gnomeontherun** [comment] 2019-08-02 21:08
@rbirkgit The basic steps here would be to try and have a new file built from a branch based on v1 that exports only the necessary forms that your application needs. We've talked about this and think it might be best for applications that need this to handle it on their own since its not something we'll be supporting directly. If you are able to address this on your own, it would be helpful to share the steps you took so others could follow suit if necessary.

**Comment by gnomeontherun** [comment] 2019-09-03 20:12
I'm curious @rbirkgit if you have looked into this?

**Comment by rbirkgit** [comment] 2019-09-03 20:19
We have not looked into it.

**Comment by rbirkgit** [comment] 2019-09-05 16:01
Not sure we are knowledgeable enough about Clarity to know how to do this. At the moment we have no plans to move CAS (Tango) to Clarity v2 any time soon. The forms are the biggest hurdle for us.

**Comment by rbirkgit** [comment] 2019-09-24 00:25
I spent the day extracted the deprecated forms scss files and putting them in our project. They however need many utility scss files and after copying them one by one I am basically running a copy of a quite a big chunk of clarity and now I am getting worried I will get conflicts. I tried using the 2.x files as much as needed but they changed names or removed functions etc (which I understand with new versions. Not sure what the best strategy is.

**Comment by gnomeontherun** [comment] 2019-09-24 21:13
You should be using `v1` branch since all of the files are there, and what we'd be expecting is that you'd use some scripts (in the package.json) to run the same types of commands but making sure it builds with only the necessary forms pieces.

**Comment by rbirkgit** [comment] 2019-09-24 22:09
After two days I think I got it working using this in the main styles.scss  Had to copy a few clarity 1.x scss files as they contain functions etc that no longer exist in clarity 2.x

```
// Clarity 2.x
@import '../node_modules/@clr/ui/src/utils/helpers.clarity';
@import '../node_modules/@clr/ui/src/layout/grid/variables/variables.clarity';
@import '../node_modules/@clr/ui/src/utils/layers.clarity';
@import '../node_modules/@clr/ui/src/utils/mixins.clarity';
@import '../node_modules/@clr/ui/src/utils/variables.clarity';
// Skip creating styles
@include exports('images.clarity') {
}
@import '../node_modules/@clr/ui/src/image/images.clarity';
@import '../node_modules/@clr/ui/src/image/icons.clarity';

// Clarity 1.x
@import 'app/forms-deprecated/legacy/bs4-grid-breakpoint-overrides.clarity';
@import 'app/forms-deprecated/legacy/color.clarity';
@import 'app/forms-deprecated/legacy/colors.clarity';
@import 'app/forms-deprecated/legacy/helpers.clarity';
@import 'app/forms-deprecated/legacy/maps.clarity';
@import 'app/forms-deprecated/legacy/typography.clarity';

// Forms Deprecated
@import 'app/forms-deprecated/variables.forms';
@import 'app/forms-deprecated/variables.inputs';
@import 'app/forms-deprecated/variables.select';
@import 'app/forms-deprecated/mixins.clarity';
@import 'app/forms-deprecated/inputs.clarity';
@import 'app/forms-deprecated/select.clarity';
@import 'app/forms-deprecated/forms.clarity';
```

**Comment by adumesny** [comment] 2019-10-03 19:30
The form breaking in 2.x is also affecting FlyingDragon and apps that use that lib. looking back at 0.11 documentation - the LAST to have more fancy form with multiple items per line and controls https://vmware.github.io/clarity/documentation/v0.11/forms I don't see anything close to that complexity in 0.12 - 2.x documentation! I can switch code to new angular format, but then all input controls seem to run together now (like 2 inputs in a row). Please update your doc to have some realistic controls and support what we have before deprecating the old CSS/angular options.

**Comment by caubah** [comment] 2019-10-04 10:04
Do we have any estimates on this one? Updating to latest Angular is vital for our app since it contains multiple performance updates that will affect directly our customers. 

As @rbirkgit suggested if we have easier migration path it will even speed up the form rewriting as this can be done in multiple commits, instead of a huge one, that will most probably introduce regressions in our Production environment.

**Comment by gnomeontherun** [comment] 2019-12-21 02:09
To close the loop on this one, we won't be backporting this into v2 but the assets are here if you want to include the CSS for old forms. Simply copy the file into your project and make sure it gets loaded into your application build.

https://gist.github.com/gnomeontherun/dec0ae6925b47e27b9120076cdb717c4

Closing as resolved with this workaround.

**Closed by gnomeontherun** 2019-12-21 02:09 UTC
Labels: Help Wanted, component: forms, flag: deprecation
