### ISSUE TITLE
Clarity clrDate input does not accept initial date value applied to Reactive form control

### ISSUE THREAD

**Issue by ghost** [vmware/clarity#4697] opened 2020-06-03 15:19 UTC
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce
https://stackblitz.com/edit/angular-ehvcxx?file=src%2Fapp%2Fmocktabs%2Fmocktabs.component.html 

1. Create a component and include an input element with the clrDate directive. 
2. Assign the input element a formControlName that matches the Reactive Forms control. 
3. Set the value of the Reactive control to a date object, e.g. new Date() during component initialization.
4. Observe the value of the control does not reflect the value assigned. 
5. Observe error "date.match" is not a function in the F12 browser debug window. 

Please see the StackBlitz. 

## Expected behavior
The clrDate control should properly bind to the value of the Reactive Form control's initial date value. This should not cause errors in the console.

## Versions

**App**

- Angular: 8 and 9
- Node: 10.16.3
- Clarity: 3

**Device:**

- Type: Dell laptop ?
- OS: Windows 10
- Browser Chrome, Edge
- Version latest

## Additional notes
This is the code that establishes the value of the Reactive control:
class MyComponent … {
 mainForm:FormGroup;
  constructor(protected svcFormBuilder:FormBuilder) { }

  ngOnInit() {
    let viewmodel = {
      Discover_x0020_Date: new Date()
    };
    this.mainForm = this.svcFormBuilder.group(viewmodel);
  }
…
}

**Comment by hippee-lee** [comment] 2020-06-03 16:51
I think the issue is [here](https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/forms/datepicker/date-input.ts#L203) where we are looking for a string on the NgControl.  I'm not sure if this was by design or there is another reasons as I recall that there was some back and forth about how to support string and Date() models. 

The workaround would be to use a string to initialze the control: https://stackblitz.com/edit/gh-4697-set-datepicker-value.

I'm marking this as needs investigation b/c I can't remember some of the past decisions we made about what to accept as valid date input for both template and reactive forms.

**Comment by Katydude** [comment] 2020-06-03 21:54
Yes, I came to the same conclusion. I didn't dig in much further but it seemed to me that simply calling a .toString()-type method on whatever object was sent in, prior to analyzing it for mm-dd or dd-mm, would at least handle a few more cases and would do no harm to the current value since it's already presumed to be a string. I think I'd look to see if the object contains toLocaleDateString() and, if so, call that and then proceed normally. 

Just my 2 cents but forcing the input of a string starts to complicate the viewmodel side of things unnecessarily and may even limit Clarity's ability later to, say, add a Time component to the widget. Easier to deal with too much information than not enough imho :)

**Comment by hippee-lee** [comment] 2020-06-03 22:54
Thanks for the report and follow-up. I'll add this to the backlog so we can re-visit it.

**Comment by gnomeontherun** [comment] 2021-02-26 19:49
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-02-26 19:49 UTC
Labels: component: date-picker, flag: has workaround, status: needs investigation
