### ISSUE TITLE
Datagrid selected emptied on initialization with active filter

### ISSUE THREAD

**Issue by nmussy** [vmware/clarity#2977] opened 2019-01-02 08:37 UTC
## Describe the bug

When initializing a Datagrid with a set of pre-selected elements, that list will be emptied if there is a currently active filter. This issue occurs even when the selected elements are not filtered out.

## How to reproduce

[Stackblitz with active filter](https://stackblitz.com/edit/clarity-selected-emptied-with-active-filter)
[Stackblitz with inactive filter](https://stackblitz.com/edit/clarity-selected-emptied-with-inactive-filter)

1.  Go to the [first Stackblitz](https://stackblitz.com/edit/clarity-selected-emptied-with-active-filter), which has an active filter, allowing every element
2.  Notice the lack of selected users
3.  Go to the [second Stackblitz](https://stackblitz.com/edit/clarity-selected-emptied-with-active-filter), with the same filter, but inactive
4.  Notice that the first user is selected

## Expected behavior

In the first example, the first element should be selected on initialization

## Versions

**App**

* Angular: 7.1.3
* Clarity: 1.0.3

**Device:**

* Type: Desktop
* OS: Windows 10
* Browser Chrome
* Version 71

## Additional notes

I have found that giving Datagrid a copy of the elements will work, [as shown in this Stackblitz](https://stackblitz.com/edit/clarity-selected-emptied-with-active-filter-workaround)

**Comment by gnomeontherun** [comment] 2019-01-02 19:43
This is a duplicate of https://github.com/vmware/clarity/issues/2342 because we automatically clear selection when a filter is applied.

**Closed by gnomeontherun** 2019-01-02 19:43 UTC
