### ISSUE TITLE
[1.0] Layout service continiously spams current layout into console

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2880] opened 2018-11-25 17:27 UTC
## Describe the bug

Layout service logs the current layout into the console, which looks like a thing, which should be removed from the code

## How to reproduce

1. Open [1.0 input documentation](https://vmware.github.io/clarity/documentation/v1.0/input)
2. Open browser console and see multiple "horizontal" messages appearing on any action with a page

## Expected behavior

No debug/testing messages in console

## Additional notes
Looks like line# 28 should be removed from this file: [layout.service.ts](https://github.com/vmware/clarity/blob/08536f10c836ad1aab1c07b2639865d16c4f7b4b/src/clr-angular/forms/common/providers/layout.service.ts)

**Comment by Jinnie** [comment] 2018-11-25 22:35
Thanks, but it is a duplicate of #2839. There is a pull request with a fix for it.

**Closed** 2018-11-25 22:36 UTC
