### ISSUE TITLE
Textarea overwrite input field in wizard

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1223] opened 2017-07-28 04:31 UTC
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I have a wizard with several leading input fields of type text, then a textarea, 'Description',  (rows = 5), followed again by several input fields of type text. I expect the subsequent input fields to appear below the text area. 

### Actual behavior

The text area extends down over the subsequent input fields. The subsequent fields are visible through the textarea though, just not below it.

Sorry, don't know how to create a plunker link but I've included screenshots of the issue and sample code from my app (using your wizard with form validation code as a starting point).

![issue](https://user-images.githubusercontent.com/27329476/28702476-064e5736-7312-11e7-9132-231b1444bd1b.jpeg)

[wizard.component.txt](https://github.com/vmware/clarity/files/1182013/wizard.component.txt)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 
.9.13
* **OS and version:** 
macOS 10.12.6
* **Browser:** [all | Chrome 60  | Safari 10.12 |

**Comment by mathisscott** [comment] 2017-07-28 13:48
@beaker1977 
What's causing this is the label that is being wrapped around the textarea to force a validation tooltip on the textarea.

This appears to be a duplicate of #45 which we have not implemented yet.

As for plunkr, it's fairly easy to copy-paste the code you sent into the [sample app in plunkr](https://plnkr.co/edit/x1EujKesxR2De3q0pxNI?p=preview).

The problem for us is that we get so many requests that we can't possibly do the plunkr for everyone who might have an issue.

**Closed by mathisscott** 2017-07-28 13:48 UTC
