### ISSUE TITLE
[clr-datagrid] Details pane throws exceptions once populated with new data on ngOnInit

### ISSUE THREAD

**Issue by WhiteLord** [vmware/clarity#6508] opened 2021-12-08 08:53 UTC
## Describe the bug

The example works the following way:
- A button that, when pressed, triggers ngOnInit.
- ngOnInit invokes a method that, in our example, changes a field in the component
- This field is used to render content in the datagird details pane
- Once we hit the refresh button, we see that there is an ExpressionChangedAfterItHasBeenCheckedError entry in the console. 

## How to reproduce

Link: 
https://clarity-5-alert-examples-trk9un.stackblitz.io 
or 
https://stackblitz.com/edit/clarity-5-alert-examples-trk9un?file=src/app/app.component.html

1. Click on the refresh button
2. Observe that there is an ExpressionChangedAfterItHasBeenCheckedError in the console.

## Expected behavior

No such error should be thrown OR advise how to use the example correctly once new data has been fetched, so that the content of the datagrid could be updated properly.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 5

**Device:**

- Type: MacBook
- OS: Big Sur
- Browser: Chrome Canary
- Version: 97.0.xxxx

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2021-12-08 16:46
Hi @WhiteLord, I'm not completely sure what your intent here is, but I see a few issues. Stackblitz isn't working well for me though to try and fix it.

* Using `ngOnChanges` to change data is going to be a performance problem and leads to some complexity with values being reassigned twice when you click `refresh` because the refresh runs `ngOnChanges` method directly and then `ngOnChanges` will fire again causing the ExpressionChangedAfterItHasBeenCheckedError error. 
* Normally you use `ngOnInit` to initialize the data (which is also duplicated in the constructor definition) so that can also be possible cause of ExpressionChangedAfterItHasBeenCheckedError.
* The detail pane implementation is hooked into the `selection` value, which is also being used to track the currently selected item. These should be different values or again it could be firing methods multiple times leading to ExpressionChangedAfterItHasBeenCheckedError type errors.

Can you try addressing these issues and see if that helps?

**Comment by WhiteLord** [comment] 2021-12-09 16:01
The idea here is the following: 
We have a datagrid, like the one in the example, which is populated by different entries.
When the application is refreshed, the datagrid is repopulated. There might be the old, existing entries, but there might be new ones, we don't know.
For this reason, whenever the `ngOnChanges` method is triggered, we need to repopulate the datagrid.
Since we're dealing with complex objects, there is a certain processing that needs to be done, in our case the `buildItems` method.
Once the items are populated, the first element should be displayed in the details pane. It's important that there is a selection, meaning - we could not simply display a datagrid with no selection, the details pane should be expanded.

- Regarding your answer - I don't see how `ngOnChanges` will be called twice with this code. If we `console.log` a simple string in the method, we can observe that it's displayed only once, am I missing something here?
- I agree with this, currently I needed to display some information prior to the refresh. In the original variation, we're obviously not doing this 😄 
- Your third hypothesis might lead me to finding the correct solution to my problem. What should be the best approach? I need to display the first element of an array which is populated when `ngOnChanges` is called, and the details pane should be expanded.

**Comment by gnomeontherun** [comment] 2021-12-10 18:43
I've seen many demo issues in the past related to this kind of error because there is a lifecycle issue with values being set more than once in a digest cycle, which is what `ExpressionChangedAfterItHasBeenCheckedError` essentially means. So the goal is to always look at ways and places values are being set. You are doing complex data manipulation to the data when it arrives, so the result is that you will need to set the `items` array with the new data. 

1. The refresh method calls `ngOnChanges`, which you are then changing the `select` value which triggers `ngOnChanges` again for the component since it is an input value. I didn't dig into this one deeply so I am just quickly picturing the call chain, but calling lifecycle methods directly is an antipattern, only Angular should do that to ensure instructions fire as expected. 
2. There are loading patterns and probably several examples in our GitHub issues that might help here.
3. The sample here seems to be using row selection and detail pane for the same concept. They are independent in both UX and programmatic behavior. The `clrIfDetail` binding generates a local template variable (you are calling yours `selection` which is a duplicate name of the component property `selection`). I'm not sure which value is resolved here, but name them differently to avoid collision and probably other buggy behaviors.
4. Lastly I also saw you are using `clrDgItems` but this might be best to use `ngFor` with a server driven approach since you are refreshing data often. You also need to use TrackBy to improve performance of tracking the array, otherwise you could have a memory leak.

**Comment by WhiteLord** [comment] 2021-12-13 10:07
Thanks for the exhaustive answer, @gnomeontherun !
Regarding 1 - Yes, I'm aware that calling lifecycle methods is not the correct thing, however, this is out of our reach, and out of our scope. For the demo purposes, I used the "general" way it's done in our codebase (meaning when a button is pressed - ngOnChanges is called).
2. In the current example I did not make use of this, as there wasn't any need, but in our production code, we do utilize the datagrid loading indication.
3. I realize that the variable I've assigned could cause confusion and unwanted side effects. I've renamed the locally assignable variable to `sel`.
The reasoning behind row selection and the expanded detail pane is the following - when the user firstly loads the application, as per UX design, we should have:
A) A selection in the datagrid (the user could utilize some of the details of the selected object to execute other business logic)
B) Details pane disclosing additional information per selection, and making it possible to execute different actions on the selected item
In the current example, I've switched to using another variable.

The number 4 is definitely something I should consider. Thanks for the idea!

In conclusion, playing around with the datagrid, I found that I'm either doing something totally wrong, or "pre-selection" does not function the way I think it should. When I assign a value to the `selection` object (which is used with `[(clrIfDetail)]`) in `ngOnChanges`, I observe that something goes terribly wrong and spits out the `ExpressionChangedAfterItHasBeenCheckedError`.
A not so elegant fix consists in adding the `ChangeDetectorRef` in the constructor, and manually invoking change detection once the `selection` object has been set.

This begs the question - Is there a "standard" way of doing a pre-selection in the datagrid and the details pane? The case I've described might serve a demo purpose how one should not to do it, and there might be a code block how to actually do it.
Given the current example, I find it very possible that other teams / users might come across this scenario.
Having said this, maybe I should have started with the following question - Is there a standard way of creating a preselection in the datagrid, AND the details pane?

**Comment by gnomeontherun** [comment] 2021-12-13 22:49
I want to push back on the UX of mixing selection and detail pane behaviors. I think this has other side effects for accessibility as well. The issue is in the UX. If someone opens and then closes the detail pane, the selection remains active and can make things funky. 

They are meant to be separate things, so you'll have to work out the UX here carefully. They are meant to operate as independent things, so you have to manually trigger the changes between both features instead of expecting them to share. That said, things are still not working quite right because this is a single feature changing the state of two features at the same time, and the side effects are not fully addressed here, but here is a better demo.

https://stackblitz.com/edit/clarity-5-alert-examples-qpdeto?file=src%2Fapp%2Fapp.component.ts

There also seems to be some strange issue with ng-touched on the radio control in my demo.

While maybe we can work out how to fix this, these kinds of issues tend to be quite difficult to change in Clarity Angular without possibly breaking other things. They were intended to be independent features, so they have different lifecycles and this would likely be a large effort to address, for a use case that I'm not sure we can consider good UX.

**Comment by WhiteLord** [comment] 2021-12-16 08:34
Thank you for the example!
As it seems, we're not going to be able to "pre-select" an item. Alas, we're bound to using `ngOnChanges`, which at the end of the day, results in the above-mentioned error.
I haven't put much thought about the A11Y impact such a change may have. However, A11Y should be taken into serious consideration here, as you mentioned.
From our conversation, I will take away the following - "If you're trying to pre-select an item in `ngOnChanges`, you're going to have a bad time, furthermore - having a pre-selection is bad for your a11y and isn't a great design approach."

**Comment by gnomeontherun** [comment] 2021-12-16 14:23
I think the biggest a11y concern with this is that you are doing two things with one action, selection and opening a modal (the detail pane is a modal). That will trap a keyboard user in the detail pane until it is closed (an a11y requirement for the detail pane is it acts like a modal). It prevents someone from navigating the table as they wish and optionally opening the details, which would likely be an a11y violation. For these reasons, I think we should not be trying to support this behavior. Also, the Clarity Core datagrid is nearing completion and may offer options. 

If there is an error that still arises from the general behavior of the datagrid in use cases that we do support, happy to review those. Otherwise I'll go ahead and close as trying to build a UX that leads to a11y violations.

**Closed as completed by gnomeontherun** 2021-12-16 14:23 UTC
Labels: resolution: wontfix, component: datagrid, @clr/angular
