### ISSUE TITLE
Changelist #4733 introduced breaking change for datagrid custom filters implementation 

### ISSUE THREAD

**Issue by kumar-tadepalli** [vmware/clarity#5309] opened 2020-11-17 13:39 UTC
## Describe the bug
Applying filter and changing the option should filter the datagrid and show the data. But once the filter get into scenario like filter criteria doesn't satisfy the given condition or return empty list. In next filter change also, the rows are not visible even the given condition is returning the records. This forces user to reload the entire page.
![DGrid_custom_filter_breaking_in_v2 4 4_2](https://user-images.githubusercontent.com/12848838/99396775-2ad4d300-2908-11eb-81c5-fa2f6bcee589.gif)

The same code is working fine in Clarity v2.4.3 but it is breaking in clarity v2.4.4.
Mostly because of this changelist https://github.com/vmware/clarity/pull/4733

Please resolve this issue.

## How to reproduce
https://stackblitz.com/edit/clr-basic-datagrid-filter-v244?file=src/app/basic-datagrid.component.ts

![DGrid_custom_filter_breaking_in_v2 4 4](https://user-images.githubusercontent.com/12848838/99396859-44761a80-2908-11eb-847a-50aa37c40b6c.gif)

## Expected behavior
It should behave same way as working in clarity v2.4.3
https://stackblitz.com/edit/clr-basic-datagrid-filter-v243?file=src/app/basic-datagrid.component.ts
![DGrid_custom_filter_working_in_v2 4 3](https://user-images.githubusercontent.com/12848838/99396926-55269080-2908-11eb-9ea4-e0525f916ba8.gif)

## Versions

**App**

- Angular: [8.x]
- Node: [12.13.x]
- Clarity: [**2.4.4** and above]

**Device:**

- Browser [chrome, mozilla, edge]

## Additional notes

_Add any other notes about the problem here._

**Comment by gerinjacob** [comment] 2020-11-25 01:51
Seeing similar issue with out of the box filter - https://v2.clarity.design/datagrid/full
Do I need to open a separate issue for this?
![datagrid](https://user-images.githubusercontent.com/7568688/100172560-9d3c4900-2eee-11eb-888e-02fa6a0c2a07.gif)

**Comment by gerinjacob** [comment] 2020-11-25 05:24
Sorting as well - https://v2.clarity.design/datagrid/full
![datagrid-sort](https://user-images.githubusercontent.com/7568688/100186719-8d336200-2f0c-11eb-99af-a5c60ee76b9f.gif)

**Comment by bdryanovski** [comment] 2020-11-25 14:17
When the #5334 PR is merged it will be released into the next release for v2.

The issue is not reproducible into v3 and v4 - so this could be a nice opportunity to update to v3 if you can.

**Closed as completed** 2020-11-26 10:42 UTC
