### ISSUE TITLE
Dark theme container background is not filling complete page

### ISSUE THREAD

**Issue by timvl** [vmware/clarity#2951] opened 2018-12-18 15:57 UTC
## Describe the bug

When using the dark theme, and scrolling down on a page: the background is white at the bottom of the page.

## How to reproduce

1. Create a page with content that goes below the browser window.
2. The background of the page is dark
3. Scroll down
4. The scrolled down part has a white background

![image](https://user-images.githubusercontent.com/15107738/50165764-e1c41080-02e5-11e9-888d-d634e8530e9d.png)

## Expected behavior

The background should be completely dark on the whole page.

## Versions

**App**

* Angular: 7.0.1
* Node: v10.14.1
* Clarity: 1.0.2

**Device:**

* OS: Windows 10
* Browser Chrome
* Version latest

**Comment by youdz** [comment] 2018-12-18 16:09
Looks to me like a duplicate of #2937 and #1186. Did you follow the exact nesting of layout containers we recommend, or do you have extra element in there? We can't check without a StackBlitz reproduction.

**Closed** 2019-03-08 18:28 UTC
Labels: Duplicate
