### ISSUE TITLE
 Ensure custom controls provide proper textual name, role, and state information in clarity signposts

### ISSUE THREAD

**Issue by poorvi12-vmware** [vmware/clarity#4725] opened 2020-06-11 08:50 UTC
## Describe the bug

The information icon button, does not have an appropriate name or state. The element is currently announced only as an unlabeled button. The corresponding pop-up that appears when the "i" button is activated also does not have an appropriate role or label to associate the region with the "i" button.

Screen reader users will be unable to identify the purpose of the "i" controls, or identify the expanded/collapsed state of a control. Screen reader users will also have difficulty recognizing where pop-up content begins/ends and which pop-up is associated with which button.

## How to reproduce

https://clarity.design/documentation/signposts

Login to vSphere.
Navigate to hosts and clusters
Select a host.
Navigate to actions menu.
Select alarms.
Select new alarm definition
Enable "Send email notifications"
Check Information icon beside

## Expected behavior

To the information icon button itself provide a meaningful label using off-screen text or using aria-label, along with an aria-expanded attribute set to true/false to identify the element's expanded/collapsed state.

For the information pop-up, apply a role="region" to the pop-up container along with a label applied using aria-label to associate the pop-up region with its corresponding control.

## Versions

**App**

- Angular: [8.2.14]
- Node:  [12]
- Clarity: [2.3.9]

**Device:**

- Type: [MacBook]
- OS: [macOS]
- Browser [chrome]
- Version [81.0.4044.138]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment] 2020-06-11 20:02
Hi @poorvi12-vmware - if this is for an internal accessibility issue we ask that you work with the accessibility team internally to investigate and triage it before opening an issue here. This will help us identify and consolidate issues that are dependent on Clarity and help the accessibility team track any issues that are occurring across products so they can be identified and fixed for everyone. 

In addition, the demos on the website are not a good example for reporting issues like this, many have not been updated since we triaged and fixed issues last year. There may be steps that the app needs to implement on that side to make things work. Again, working with the accessability team internally should help guide you here. 

I'm going to close this as working as intended for now. Please let me know if this is not a report for a VMware product.

**Closed by hippee-lee** 2020-06-11 20:02 UTC
