### ISSUE TITLE
Tree View Component: Collapsed parent checkbox state changes are not reflecting to child nodes

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#1772] opened 2017-12-13 12:36 UTC
Tree View Component collapsed parent checkbox state changes are not reflecting to child nodes. 
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Changes done on collapsed parent node should be propagated and make changes to the child checkbox states. The same should be retained when we expand the parent node also.

### Actual behavior
Tree View Component not retaining applying the parent checkbox state to children if we change the state of the parent node when it is in the collapsed state. 

### Reproduction of behavior
We could take the example given in official Clarity documentation.
https://vmware.github.io/clarity/documentation/tree-view

Step 1: Open the above link and scroll to Checkbox Tree example.
 ![step1](https://user-images.githubusercontent.com/12848838/33938632-2f0a781a-e02e-11e7-8c33-a84ab66ba2c4.JPG)

Step 2: Collapse Authenticated Users node (higlighted)
![step2](https://user-images.githubusercontent.com/12848838/33938671-58ed76aa-e02e-11e7-84a8-b36e5c6fa42d.JPG)

Step 3: Checked Authenticated Users node (highlighted). 
![step3](https://user-images.githubusercontent.com/12848838/33938799-c27bc360-e02e-11e7-87b3-6f4d390abcb0.JPG)

Step 4: Now expand the Authenticated Users node. We could observe node state are not retained and came back to the step-1 selection state, even we had changed the state of the parent node. 
![step4](https://user-images.githubusercontent.com/12848838/33938847-f6506fec-e02e-11e7-9ef0-c7fdd5ee334a.JPG)

Expected Behavior: Changes made on the collapsed parent node should be reflected and retained even after node is expanded.
![expected](https://user-images.githubusercontent.com/12848838/33939135-fde9bcee-e02f-11e7-8162-e46fbe9c1544.JPG)

NOTE: 
### Environment details

* **Angular version: 4.4.6**

* **Clarity version: 0.10.17**

* **OS and version:** 

* **Browser: [all]**

**Comment by adityarb88** [comment] 2017-12-13 12:48
@shravansofts: This looks like a duplicate of #1400. Please subscribe to that issue for more updates.

Thanks!

**Closed by adityarb88** 2017-12-13 12:48 UTC
