### ISSUE TITLE
clr-tree-node expanded by default and not responding

### ISSUE THREAD

**Issue by MattMattV** [vmware/clarity#1005] opened 2017-06-02 08:36 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The `<clr-tree-node>` should be minimized by default and hiding it's children, also clicking on the arrow on the left should expand/reduce it

### Actual behavior
The `<clr-tree-node>` is expanded by default and clicking on the left arrow only trigger the rotate animation of the arrow, nothing else.

### Reproduction of behavior
https://plnkr.co/edit/lSOn1DbZpO6nSJs46zph?p=preview
also in our app  : https://github.com/TraceSoftwareInternational/HostMyDocs/blob/master/FrontEnd/src/ts/components/projects-tree/template.html
### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.7

* **OS and version:** Linux Mint 18.1 Cinnamon edition 64-bit

* **Browser:** [Chrome Beta 59.0.3071.83 &&  Firefox Nightly 55.0a1 (2017-06-01) (64 bits)]

**Comment by adityarb88** [comment] 2017-06-02 15:03
@MattMattV: Thanks for reporting this. We will take a look and get back to you.

**Comment by adityarb88** [comment] 2017-06-07 13:20
@MattMattV: We took a look at this and found out that this is happening because of the `ng-container` not being projected at the right place. You will have to add `ngProjectAs="clr-tree-node` on `ng-container` to make this work. Here is a plunkr showing this: https://plnkr.co/edit/kZp2yDYm62PmTF1jfKOq?p=preview I am closing this issue but feel free to reopen this if you feel that the issue is still unresolved.

**Closed by adityarb88** 2017-06-07 13:20 UTC
Labels: bug, ClarityNG

**Comment by MattMattV** [comment] 2017-06-07 14:03
Thank you for your answer !1

**Comment by icepoint0** [comment] 2017-07-25 03:29
where is the demo ? my tree node not work too! error->'clrTreeNodeExpandable' since it isn't a known property of 'clr-tree-node'

**Comment by mathisscott** [comment] 2017-07-25 03:34
@icepoint0 
Please take a look at the Plunkr @adityarb88 posted here:

https://plnkr.co/edit/kZp2yDYm62PmTF1jfKOq?p=preview

Thanks.

**Comment by adityarb88** [comment] 2017-07-25 03:54
@icepoint0: Not sure what happened to the plnkr but you should find the demos in our documentation: https://vmware.github.io/clarity/documentation/tree-view Please note that this documentation is for v0.9. It seems that you are using one of the alpha versions of 0.10 which has a breaking in tree view. You can find more info about migrating from 0.9 to 0.10 here: https://vmware.github.io/clarity/news/0.10.0-alpha

**Comment by icepoint0** [comment] 2017-07-25 04:00
@adityarb88 thank u , by the way, document is v0.9 now?

**Comment by adityarb88** [comment] 2017-07-25 04:31
@icepoint0: Yes the documentation is on v0.9 because 0.10 is still in alpha.
