### ISSUE TITLE
Date Picker (clrDate directive): Introduce clear value button

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#2718] opened 2018-10-10 13:37 UTC
Current behavior: 
Currently, in order to remove a selected date, one has to delete the input value manually.

Desired behavior: 
What could be more user-friendly is either (1) a "clear" button in the date popup (clr-datepicker-view-manager) or (2) an "x" button next to the date input ( like in https://material-ui.com/demos/pickers/ ).

The current behavior can be observed at the date picker clarity page (https://vmware.github.io/clarity/documentation/v0.13/datepicker as of the time of writing).

**Comment by AbhiAgarwal192** [comment] 2018-10-27 04:10
Added data-picker icon. OnClick event for the same is yet to be added. Will keep you posted.

**Comment by colinreedmiller** [comment] 2019-04-15 21:50
Should this be merged with #963 - Keyboard input for date picker resembles form inputs since forms redesign. There is a design for a clear function in the 'Forms - input groups' design spec.

![forms-imput_groups.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/a051f965-f5f9-430f-9caf-645e58085c5d)

**Comment by andreiconstantinbytex** [comment] 2019-10-15 09:51
I would like to be assigned to this issue.

**Comment by gnomeontherun** [comment] 2021-01-29 22:52
This is really just a duplicate of #963, closing in favor of it.

**Closed by gnomeontherun** 2021-01-29 22:52 UTC
Labels: component: forms, status: in progress, type: design, type: enhancement, ux: ready
