### ISSUE TITLE
Custom styles via scss lack clear dependencies

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3870] opened 2019-10-03 10:41 UTC
## Describe the bug

I want to be able to customize the Clarity grid and components, to use component-specific variables, i.e. $clr-header-height, in my custom global scss (not for theming, but first and foremost, for fine-tuning existing components layout).

In previous versions of Clarity we had `dependencied.clarity` scss file. Currently, I can't figure out how to make things work.

I've tried to attach _variables.clarity file first, but it has its own dependencies and CLI gives me a build error.

## How to reproduce

1.  In `styles.scss` add imports like in a documentation
2.  In overrides, try using $clr-header-height variable
3.  Add variables.clarity import prior to other imports
4.  See build error

```
@import '~@clr/ui/src/utils/variables.clarity';
@import './styles/overrides.scss';
@import '~@clr/ui/src/utils/components.clarity';
```

![image](https://user-images.githubusercontent.com/32732457/66120229-168a2580-e5e3-11e9-9abe-0408c7753ee0.png)

If I try resolve this dependency, it asks for another one, and so on.

## Expected behavior

I expect to have either single import with all deps or subset of variables for components to work without having to follow an endless chain of related dependencies.

## Versions

**App**
![image](https://user-images.githubusercontent.com/32732457/66120409-7385db80-e5e3-11e9-978d-d95c7861f638.png)

**Device:**

* Type: [PC]
* OS: [Win 10]
* Browser [chrome, opera]
* Version [latest]

**Comment by mathisscott** [comment] 2019-10-03 12:54
Hi @sdurnov 
Just so I understand what is being asked...

It sounds like you don't want to make a theme but you want to get a hold of the Clarity variables? But it seems like you still want to be able to change those variables in your own styles? Or are you trying to reuse the variables in your own CSS?

But in the steps to reproduce, a theme is being generated.

This may be a documentation issue. But generating a theme should only require...

**Comment by sdurnov** [comment] 2019-10-03 13:10
@mathisscott I want to reuse existing variables AND to override some of them.

After investigating imports in your website code, I came up with a solution, where I do something like this:
```
@import './styles/grid';
@import '~@clr/ui/src/utils/components.clarity';
@import './styles/overrides';

```

in a first import, I only override the grid breakpoints map, in overrides, I have this:
```
@import '_variables';
@import 'container';
@import 'header';
```

variables is a copy of the same file from your website code,
container and header are just global overrides for a Clarity layout items (main container, content container, etc.) and a header component (I added support for dropdowns by copy-pasting original items CSS and changing it for dropdowns, so it uses variables and mixins from that code).

I had to mess with grid breakpoints stuff not working, but after moving it here and there, I found that it works only when it goes before anything else.

So, all in all, I just needed to use components variables and to override grid breakpoints.

**Comment by gnomeontherun** [comment] 2019-10-03 14:37
I have run into this behavior before if you try to pull certain files, sometimes the dependency tree is unclear and it is a challenge to trace back.

However, I believe this should be resolved by changing to custom properties, which means you wouldn't have to build our Sass to customize variables for v3+. That indirectly will address your concern.

**Comment by sdurnov** [comment] 2019-10-03 14:44
@gnomeontherun so are you planning to switch to CSS variables? Am I getting it right? Then how are you going to provide, let's say, ability to extend/change the grid breakpoints and classes, generated with mixins, based on sass maps?

**Comment by mathisscott** [comment] 2019-10-03 16:26
@sdurnov 
Even if we moved to CSS variables, there would still be global CSS that has to be generated by SASS. Somethings would still need to hang out in SASS. The grid breakpoints being one of those things. CSS variables will give some degree of control over the layout of components. But they aren't going to allow you to edit the responsive breakpoints we have today in SASS. That will still require SASS.

**Comment by gnomeontherun** [comment] 2019-10-03 21:31
This seems like a duplicate of #3479. At this point I'm going to close this in favor of the original.

**Closed by gnomeontherun** 2019-10-03 21:31 UTC
Labels: type: question
