### ISSUE TITLE
[datagrid] clrDgLoading loading spinner breaks table

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#872] opened 2017-05-09 19:40 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Using clrDgLoading to display a loading spinner should not break the datagrid when used to indicate actions being made.

### Actual behavior
When the clrDgLoading loading spinner is used, it breaks the datagrid with the `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.` error and becomes unresponsive after that.

### Reproduction of behavior
https://plnkr.co/edit/r0At1g9YYd2wKxcCnZIH?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.3

**Comment by mathisscott** [comment] 2017-05-09 19:54
@youdz : Please triage...

**Comment by hippee-lee** [comment] 2017-05-09 19:57
This is a duplicate of #847.
@jbgarr please follow that issue as I am currently working on it and hope to resolve it soon.

**Closed by hippee-lee** 2017-05-09 19:57 UTC

**Comment by jbgarr** [comment] 2017-05-09 20:15
Ah yes, sorry about the dupe!

**Comment by hippee-lee** [comment] 2017-05-09 20:17
No worries. Do follow along with #847 though to stay up to date on the fix.
