### ISSUE TITLE
Cannot type `(backquote) in input

### ISSUE THREAD

**Issue by jimmy29347** [vmware/clarity#2909] opened 2018-12-05 00:03 UTC
## Describe the bug

Unable to input ` correctly in text input

## How to reproduce

1.  Go to https://vmware.github.io/clarity/documentation/v1.0/input
2.  press ` twice in any text input

## Expected behavior
text input value changes to ``

## Versions
Clarity 0.13 1.0

**Device:**
windows chrome

**Comment by hippee-lee** [comment] 2018-12-05 01:11
I believe this is a duplicate of https://github.com/vmware/clarity/issues/1521. Please subscribe to that issue for updates. 

If you believe it is a different issue feel free to re-open the issue and add some more context as to the difference between  #1521 and this one.

**Closed by hippee-lee** 2018-12-05 01:11 UTC
Labels: Duplicate

**Comment by mattmutt** [comment] 2019-07-09 23:25
solved it fixing the definition for that single character.

https://github.com/vmware/clarity/pull/3353
