### ISSUE TITLE
DataGrid: Filter bottom cannot be reached if few items are displayed in the grid

### ISSUE THREAD

**Issue by mohammedzamakhan** [vmware/clarity#3011] opened 2019-01-09 21:26 UTC
## Describe the bug

Can't scroll to the bottom of the filter. Check the GIF
![kapture 2019-01-09 at 12 58 38](https://user-images.githubusercontent.com/2327532/50921810-841b7380-140e-11e9-9470-ee80c1929fa3.gif)

## How to reproduce

GIF has the steps

## Expected behavior

Should be able to scroll and unselect the filter.

## Versions

**App**

* Angular: 7
* Node: 9.1.0
* Clarity: Latest

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment] 2019-01-09 22:43
Thanks for the report. This is a duplicate of #2683, please subscribe to that issue for future updates.

**Closed by hippee-lee** 2019-01-09 22:43 UTC
