### ISSUE TITLE
Selection on DataGrid reset on filtering

### ISSUE THREAD

**Issue by borcherspm** [vmware/clarity#2366] opened 2018-06-15 18:50 UTC
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I would like to be able to maintain the selection in a grid even if the filters changed.  Even if it's just an new input that can configured whether it resets on filtering.  

### Actual behavior
DataGrid selection is reset everytime the filters are changed.  

### Reproduction of behavior
* [Example Plunker](https://stackblitz.com/edit/clarity-light-theme-v11-uk35vf)
  * Select row(s)
  * Use column filter
  * Selection is reset to none selected.

### Environment details
* **Angular version:** 5.2.10

* **Clarity version:** 0.11.15

* **OS and version:** Windows

* **Browser:** [all | Chrome 66 | Firefox 59 | Edge 41 | IE 11 ]

**Comment by gnomeontherun** [comment] 2018-06-15 19:28
This is a duplicate of #2342, feel free to subscribe to that issue to follow progress and discussion.

**Closed by gnomeontherun** 2018-06-15 19:28 UTC

**Comment by borcherspm** [comment] 2018-06-15 19:29
Cool, thanks.  Sorry I didn't see it.
