### ISSUE TITLE
Clarity Alerts Documentation - error code example 1. clrAlertClosable

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#1392] opened 2017-08-30 08:49 UTC
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
example should work

### Actual behavior
example doesnt work

### Reproduction of behavior
copy&paste code example 1 (clrAlertClosable)

### Current code:
```
<clr-alert [clrAlertClosable]="false">
    <div clr-alert-item class="alert-item">
        <span class="alert-text">
            This alert cannot be dismissed.
        </span>
        <clr-dropdown-menu class="alert-actions">
            <clr-dropdown>
                <button class="dropdown-toggle" clrDropdownTrigger>
                    Actions
                    <clr-icon shape="caret down"></clr-icon>
                </button>
                <clr-dropdown-menu clrPosition="bottom-right">
                    <a href="..." class="dropdown-item" clrDropdownItem>Shutdown</a>
                    <a href="..." class="dropdown-item" clrDropdownItem>Delete</a>
                    <a href="..." class="dropdown-item" clrDropdownItem>Reboot</a>
                </clr-dropdown-menu>
            </clr-dropdown>
        </div>
    </div>
</clr-alert>
```

### Should be:

Third line from below, close clr-dropdown-menu instead of div.

```
<clr-alert [clrAlertClosable]="false">
    <div clr-alert-item class="alert-item">
        <span class="alert-text">
            This alert cannot be dismissed.
        </span>
        <clr-dropdown-menu class="alert-actions">
            <clr-dropdown>
                <button class="dropdown-toggle" clrDropdownTrigger>
                    Actions
                    <clr-icon shape="caret down"></clr-icon>
                </button>
                <clr-dropdown-menu clrPosition="bottom-right">
                    <a href="..." class="dropdown-item" clrDropdownItem>Shutdown</a>
                    <a href="..." class="dropdown-item" clrDropdownItem>Delete</a>
                    <a href="..." class="dropdown-item" clrDropdownItem>Reboot</a>
                </clr-dropdown-menu>
            </clr-dropdown>
         </clr-dropdown-menu>
    </div>
</clr-alert>
```

**Comment by adityarb88** [comment] 2017-08-30 12:11
@TekSiDoT: Closing this issue as a duplicate of #1391. Please subscribe to #1391 for more updates.

**Closed by adityarb88** 2017-08-30 12:11 UTC
