### ISSUE TITLE
Set min and max dates with clrDate

### ISSUE THREAD

**Issue by sagarp2901** [vmware/clarity#2707] opened 2018-10-05 18:10 UTC
## Summary
Unable to set min and max to disable dates when using clrDate on the date input.

## Use case
Date: <input type="date" clrDate [(ngModel)]="startDate" />
min and max to disable dates in this case has no effect and all the dates are enabled.

**Comment by gnomeontherun** [comment] 2018-10-05 18:28
This is a duplicate of https://github.com/vmware/clarity/issues/1984, please subscribe to that issue.

**Closed by gnomeontherun** 2018-10-05 18:28 UTC

**Comment by sagarp2901** [comment] 2018-10-05 18:40
> This is a duplicate of #1984, please subscribe to that issue.

I have been through #1984 and the solution provided there does not works when <input> contains clrDate.

**Comment by gnomeontherun** [comment] 2018-10-05 18:41
That is because we have to build it yet, thats just a prototype of the idea which needs updating for the current implementation.

**Comment by sagarp2901** [comment] 2018-10-05 18:43
Okay. Any estimates on when it will be available?
