### ISSUE TITLE
Clarity 1.0.0 Main container css rule bug

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2937] opened 2018-12-12 23:06 UTC
## Describe the bug

When `<div class="content-container">` is not immediate child of `<clr-main-container class="main-container">`, then css rules are broken, main container height won't be 100%.
This issue appeared in our application with all of the grid, because our structure looks like this:

```
<clr-main-container>
    <app-header></app-header>
    <router-outlet></router-outlet>
</clr-main-container>
```
And router outlet will load the components, and the component structure looks like this:
```
<div class="content-header">
    <h2>Header text</h2>
</div>
<div class="content-container">
    <div class="content-area">
...
```
## How to reproduce

1.  Go to https://stackblitz.com/edit/show-hide-ng7-down
2.  Click on column toggle button
3.  Grid container height is not 100%, most of the pop-over is hidden.

## Expected behavior

Css rules should handle the existence of router outlet, and wrapping `<div class="content-container">` inside a component.

## Versions

Angular CLI: 7.1.3
Node: 8.11.2
Clarity: 1.0.0

Device:
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Chrome - Version: 69.0.3497.92 (Official Build) (64-bit)

**Comment by youdz** [comment] 2018-12-13 16:25
Our layout relies on Flexbox. It's not a question of our rules not being applied, it's that inserting intermediate elements that have `display: inline` will break flexbox nesting. Note that with `<router-outlet>` only it would work fine, since `<router-outlet>` doesn't create nested elements. What breaks it here is your `<app-grid>` that wraps the `<div class="content-container">`.

The recommended solution is to lift the `<div class="content-container">` and put it in your `app.html` directly, and have the various routed components just contain their content. Or even better, to add the `.content-container` class to your `app-grid` component directly. Both of these solutions are actually better than what you have now since it removes duplication of that container, because with your current version every single one of your routed components needs to make sure to include `<div class="content-container">` in the template. 

But I see you are using a non-Clarity `content-header` too, so if you cannot do the recommended solution above, we provide a `.u-main-container` utility class you can add to your extra wrapper(s) in order to restore the proper layout: https://stackblitz.com/edit/show-hide-ng7-down-fixed?file=src%2Fapp%2Fgrid%2Fgrid.component.ts

I'm closing this as it's expected behavior with a flexbox layout. We already have an open issue about documenting these restrictions about our layout, and the utility class: https://github.com/vmware/clarity/issues/1186

**Closed by youdz** 2018-12-13 16:25 UTC

**Comment by speti43** [comment] 2018-12-13 16:46
Hmm, content-header is non-clarity? I have no idea why is it there then, I'll review my layout and make it right then. Thanks, for the help.
