### ISSUE TITLE
[Treeview Component] Change selection of collapsed parent node doesn't change the selection of children nodes

### ISSUE THREAD

**Issue by Dead96** [vmware/clarity#1991] opened 2018-02-14 09:05 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When you change the selection of a collapsed parent element of Treeview component, the selection of children elements should be changed

### Actual behavior
When you change the selection of a collapsed parent element of Treeview component, the selection of children elements don't changed and, when you expand the parent element, the selection come back as before.

### Reproduction of behavior
[Clarity TreeView Documentation](https://vmware.github.io/clarity/documentation/v0.11/tree-view#examples) (Checkbox Tree example)

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

* **OS and version:** [Win10]

* **Browser:** [all]

**Comment by adityarb88** [comment] 2018-02-14 14:10
@Dead96: Thanks for filing the issue. This looks like a duplicate of #1400. Please subscribe to #1400 for more updates.

**Closed by adityarb88** 2018-02-14 14:10 UTC
