### ISSUE TITLE
SCSS helpers no longer use maps ... they use hard coded chains of if/else making it impossible to define custom buttons

### ISSUE THREAD

**Issue by Rush** [vmware/clarity#3444] opened 2019-06-12 07:09 UTC
## Describe the bug

It should be possible to generate a custom button using Clarity helpers ... Instead, the previously flexible functions have been refactored to be chain of if/elses, preventing from having any flexibility.

Previously I was able to define a custom `$clr-global-button-properties-map` with my custom button type.

Changes have been done as part of https://github.com/vmware/clarity/issues/2946 https://github.com/vmware/clarity/pull/3207 @mathisscott 

Clarity 2.0.0:
```scss
@function getSassButtonColor($type: default, $property: null) {
  @if $property == null {
    @return null;
  }

  @if $type == default {
    @return lookupFromDefaultButtonColors($property);
  }

  @if $type == default-outline {
    @return lookupFromDefaultOutlineButtonColors($property);
  }

  @if $type == primary {
    @return lookupFromPrimaryButtonColors($property);
  }

  @if $type == success {
    @return lookupFromSuccessButtonColors($property);
  }

  @if $type == success-outline {
    @return lookupFromSuccessOutlineButtonColors($property);
  }

  @if $type == danger {
    @return lookupFromDangerButtonColors($property);
  }

  @if $type == danger-outline {
    @return lookupFromDangerOutlineButtonColors($property);
  }

  @if $type == link {
    @return lookupFromLinkButtonColors($property);
  }

  @if $type == inverse {
    @return lookupFromInverseButtonColors($property);
  }

  @if $type == icon {
    @return lookupFromIconButtonColors($property);
  }

  @return null;
}

@mixin populateButtonProperties($button-type: default) {
  border-color: getSassButtonColor($button-type, border-color);
  background-color: getSassButtonColor($button-type, bg-color);
  color: getSassButtonColor($button-type, color);

  //To override the visited state of anchor links styled as buttons
  &:visited {
    color: getSassButtonColor($button-type, color);
  }

  &:hover {
    background-color: getSassButtonColor($button-type, hover-bg-color);
    color: getSassButtonColor($button-type, hover-color);
  }

  &:active {
    @if $button-type == link {
      box-shadow: none;
    } @else {
      box-shadow: 0
        getActiveWidthBoxShadowTop($button-type)
        0
        0
        getSassButtonColor($button-type, box-shadow-color)
        inset;
    }
  }

  &.disabled,
  &:disabled {
    color: getSassButtonColor($button-type, disabled-color);
    cursor: not-allowed;
    opacity: 0.4;
    background-color: getSassButtonColor($button-type, disabled-bg-color);
    border-color: getSassButtonColor($button-type, disabled-border-color);
    box-shadow: none;
  }
}
```

Previously in Clarity 1.0.0, declaring a custom map would let you define custom buttons:
```scss
@mixin populateButtonProperties($button-type: default, $button-global-map: $clr-global-button-properties-map) {
  $button-property-map: map-get($button-global-map, $button-type);
  border-color: map-get($button-property-map, border-color);
  background-color: map-get($button-property-map, background-color);
  color: map-get($button-property-map, color);

  //To override the visited state of anchor links styled as buttons
  &:visited {
    color: map-get($button-property-map, color);
  }

  &:hover {
    background-color: map-get($button-property-map, hover-background-color);
    color: map-get($button-property-map, hover-color);
  }

  &:active {
    box-shadow: 0 map-get($button-property-map, active-box-shadow-width-top) 0 0
      map-get($button-property-map, active-box-shadow-color) inset;
  }

  &.disabled,
  &:disabled {
    color: map-get($button-property-map, disabled-color);
    cursor: not-allowed;
    background-color: map-get($button-property-map, disabled-background-color);
    border-color: map-get($button-property-map, disabled-border-color);
    opacity: 0.4;
  }
}
```

## How to reproduce

Try to declare your own button type:
```scss
.btn.btn-secondary,
  .btn-secondary .btn {
    @include populateButtonProperties(secondary);
  }

  .btn.btn-secondary-outline,
  .btn.btn-outline-secondary,
  .btn-secondary-outline .btn,
  .btn-outline-secondary .btn {
    @include populateButtonProperties(outline-secondary);
  }
```
Due to hard coded if/else chain in `populateButtonProperties`, it's not really possible to declare new button types anymore. 

## Expected behavior

SCSS functions and helpers should have flexibility to generate styles for new types buttons (and other components possibly)

## Versions
* Clarity: 2.0.0

## Additional notes

The issues with SCSS have originally been discussed over here https://github.com/vmware/clarity/issues/2442

**Comment by mathisscott** [comment] 2019-06-12 13:34
Hi @Rush 
Thanks for submitting this issue.

What is the use case for another button type? Clarity already supports primary, secondary, ternary/flat, success, warning, and danger – all in filled and outlined (ghost) versions. That's 12 types of buttons.

Why would you want 14?

Also, the mixins/functions are an intermediary step that is moving us from SASS-based theming to custom properties. As you note, it will make it more challenging to do something like a quaternary button that is purple or something. But the final destination will make theming/customizing the buttons clarity offers so much easier.

**Comment by mathisscott** [comment] 2019-10-08 13:57
Hi @Rush 
Per your comments on #3479 ...

The removal of the maps is intentional as I explained above. Likewise, those lookup functions are an intermediary step that we are likewise moving away from and will be deprecating in the future.

All of this is a journey to move the library towards CSS custom properties.

That doesn't help your use case but it is good background information for this conversation.

So when it comes to making new button types... my understanding is you preferred the old maps that were being used so you could add new buttons to it and they would just be auto-generated with the Clarity SCSS code. The problem is that we never intended for those maps to be used in that way. The maps (and there were a few) weren't documented as part of how to customize Clarity. The team unanimously wanted to get rid of the maps because it was harder for them to maintain. It also made the migration to custom properties problematic so we went in the direction of removing the maps.

Given that you are using the Clarity button styles already, what would prevent you from creating a new style of button in just CSS? If you create a class that changes the colors of the existing `.btn-outline` class, it seems like an easier way to move forward than rebuilding the Clarity SCSS.

But there are likely details and use cases of which I am unaware...

**Comment by Rush** [comment] 2019-10-08 14:06
Thanks @mathisscott for your reply - I have somebody working on this again. I'll report back any feedback and lessons learned. Even if only to let other people educated about the challenges.

**Comment by mathisscott** [comment] 2019-10-08 14:15
That would be great and super helpful. It should be noted that with custom properties _styling_ the buttons will become easier but _creating new types of buttons_ will be... well... as hard as it is right now.

If we have a better understanding of what you are trying to do with the buttons, we might be able to add some hooks in that will make it easier for you. Maybe a couple of custom variants that can be styled separately?

**Comment by gnomeontherun** [comment] 2021-01-29 23:04
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-01-29 23:04 UTC
