### ISSUE TITLE
Wizard vertical scrolling issue on Firefox browsers

### ISSUE THREAD

**Issue by gzink** [vmware/clarity#2763] opened 2018-10-21 17:09 UTC
## Describe the bug

Dynamical height adjustment is not working on Firefox browsers when using xl wizards and wizard content is exceeding display size. Buttons below the wizard content can not be used anymore.

## How to reproduce

https://vmware.github.io/clarity/documentation/v0.13/wizards
When using "Wizard with Form Validation" -> Minimize height of browser -> Control buttons are not visible anymore

## Expected behavior

Control buttons are still visible/usable
see https://vmware.github.io/clarity/documentation/v0.12/wizards

## Versions

**App**

* Clarity: 0.13.6

**Device:**

* OS: Ubuntu 18.04
* Browser Firefox
* Version 62

## Additional notes

I think the bug is introduced through Commit
https://github.com/vmware/clarity/commit/182c70a2b868cc482bbc24e21da95c456dfdef29
by removing

`
.modal-content,	
.clr-wizard-stepnav-wrapper {	
    max-height: $clr-wizard-xl-dialog-max-height;
}
`

**Comment by gnomeontherun** [comment] 2018-10-22 20:38
Confirmed the bug, not necessarily the specific commit causing it yet though.

**Comment by IoannesBracciano** [comment] 2019-01-30 13:01
I was looking into the issue, it seems that the height of `.modal-content-wrapper` is miscalculated because Firefox treats the `flex-basis` property differently. Changing it from `100%` to `auto` for this element seems to solve the issue (or getting rid of the whole `flex: 1 1 100%` rule as well).

**Comment by youdz** [comment] 2019-01-30 19:53
I think it's https://github.com/vmware/clarity/commit/e9118a60570aeb6fdea76741bf9480739690cf4d that introduced it. We have to be careful how we fix this, it looks like we're looping through the same issues over and over.

**Comment by Jinnie** [comment] 2019-01-31 11:13
Before e9118a6 Firefox was not showing a scroll at all. All large content just stayed visible.
We have a test, but it's not run under Firefox, so I agree we have to be careful with the fix. Edge also had it's own interpretations of how to render it.

**Comment by gnomeontherun** [comment] 2021-01-29 22:51
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.

**Closed by gnomeontherun** 2021-01-29 22:51 UTC
Labels: type: bug
