### ISSUE TITLE
Datagrid is truncated in IE11.

### ISSUE THREAD

**Issue by collins1830207** [vmware/clarity#2172] opened 2018-04-09 08:50 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
I encounter a problem in IE11. When the data of the datagrid is less, the table shows well:
<img width="643" alt="screen shot 2018-04-09 at 4 18 30 pm" src="https://user-images.githubusercontent.com/17468210/38487753-d0e0b370-3c13-11e8-99c8-52b464145782.png">
but when I add text it is truncated:
<img width="651" alt="screen shot 2018-04-09 at 4 25 49 pm" src="https://user-images.githubusercontent.com/17468210/38487759-d3fc9100-3c13-11e8-8de3-bdd8eeab2739.png">

I didn't reproduce this issue in Firefox and chrome, I guess this issue is related to https://github.com/vmware/clarity/issues/1150

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.10.27

* **OS and version:** Win7

* **Browser:** IE 10

**Comment by youdz** [comment] 2018-04-09 12:55
As you pointed out, this is a duplicate of #1150 which is being worked on right now. Please follow that issue for updates, we have a team member already working on a fix for it (among other fixes).

**Closed by youdz** 2018-04-09 12:55 UTC
