### ISSUE TITLE
Data grid filter display issue

### ISSUE THREAD

**Issue by HegdeSach** [vmware/clarity#505] opened 2017-02-17 10:45 UTC
When I use filter and the output data grid is empty then my display is getting distorted.

![image](https://cloud.githubusercontent.com/assets/21358983/23062455/c748b766-f52b-11e6-9028-3d9847b743f0.png)

This is the result

![image](https://cloud.githubusercontent.com/assets/21358983/23062403/9e2381d6-f52b-11e6-9149-32fcb9e4b72f.png)

This is my code:

![image](https://cloud.githubusercontent.com/assets/21358983/23062537/3350dbe6-f52c-11e6-9177-7c9ca3f1287e.png)

**Comment by youdz** [comment] 2017-02-17 18:43
I just tried this directly on our website using the live demos, and wasn't able to reproduce it:
<img width="873" alt="screen shot 2017-02-17 at 13 38 09" src="https://cloud.githubusercontent.com/assets/4647197/23078470/ddad987e-f516-11e6-826e-491471f930fa.png">
The demo I used has literally the same code as the one you posted, so I'm guessing it's a CSS conflict in your particular setup.

Please post a plunker reproducing the error if you want us to be able to investigate. Thanks!

**Comment by HegdeSach** [comment] 2017-02-18 11:28
Can you get me the link to create Plunker clarity project?

**Comment by Jinnie** [comment] 2017-02-18 15:59
Btw, what's your Clarity version? Does it happen on all browsers? Do you have CSS on your project, that may be messing with the Clarity styles?
I'm asking because I also use datagrids (in several components) on my project, and I can't reproduce your issue there.

Best regards!

**Comment by Jinnie** [comment] 2017-02-18 16:03
https://plnkr.co/edit/8TwwdL 
Try this. I found it in a nearby thread

**Comment by HegdeSach** [comment] 2017-02-18 16:32
Thank you @youdz and @Jinnie 

I am very much new to angular2 and clarity. I just used the commands whatever given in the documents.
I don't know how to check the version.

I don't have any other style applied. Even on the all browser I have it is giving the issue.

I am using the code given in the document and trying.

**Comment by HegdeSach** [comment] 2017-02-18 16:37
I am not getting the issue in Plunker.

I don't know how to resolve the issue now.

**Comment by Jinnie** [comment] 2017-02-18 23:42
If you open the package.json in the root of your project, you will find the desired version. Please, check it and post it here.
Sadly, that's not what you really have installed. To find the actual version, open ./node_modules/clarity-angular/package.json, and search for version: "x.y.z"

It's good to know both values. The first represents, sort of, your request for the artefact, while the second is what you really received.

For example, my "request" is for "^0.7.3", while what's downloaded is "0.7.6"
And that's rather old :), but while I'll update it after 0.8.8."

The plunker is probably 0.8.x. So, if your version is lower than mine, try updating.
0.8.7 is the latest released. Put it in the root package.json, delete node_modules and run npm install again.

Good luck :)

**Comment by HegdeSach** [comment] 2017-02-20 06:19
I have updated the clarity to new version. It is working fine now. Thank you @Jinnie and @youdz .
@Jinnie does clarity have export feature for datagrid?

**Comment by Jinnie** [comment] 2017-02-20 08:10
I don't think so.
IMO, this is something that you should implement in your application, based on the data you want to export.
It should be pretty straightforward with some library like this one [https://github.com/zemirco/json2csv](https://github.com/zemirco/json2csv)

**Comment by jaffoneh** [comment] 2017-02-21 20:10
Based on @HegdeSach's last comment, the issue seems to be resolved. Closing.

**Closed by jaffoneh** 2017-02-21 20:10 UTC

**Comment by gondomar** [comment] 2018-08-28 18:19
This is still an issue, but I'm guessing only an issue when using custom filters and a very small data set (like two records).  The attached image has at least one more item in the filter that can't be displayed.  If you need a plunkr, I can probably put one together.
![filternotshowingenough](https://user-images.githubusercontent.com/8398561/44742251-a0042580-aabc-11e8-92c8-96835c83ef18.JPG)
