### ISSUE TITLE
Vertical Tab component (new)

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#452] opened 2017-02-03 02:36 UTC
### Description
Vertical tabs offer a clean, easy way to navigate sections of content in an app while maximizing vertical space for content.

### Usage 

- When a longer list of tab links can’t be accommodated in a horizontal tab 
- When vertical space needs to be maximized for content
- When group headings are needed
- As the sole navigation in a single-tab UI or as the primary/secondary navigation in a multi-tab UI. In the latter case, layer the nested navigation by alternating vertical and horizontal orientation. For example, vertical tabs should be nested under horizontal tabs and vice versa. 

### Features
- One level with or without a group heading  
- Flat list, not collapsible/expandable
- Scrollable
- May be used on the left or right side of the content
- Individual tab links have hover and click/selected states. Group headings do not.

### Vertical tab 
![example without headings](https://cloud.githubusercontent.com/assets/23196444/22753375/c3591106-edf0-11e6-807d-81941587083a.png)

### Vertical tab with headings
![vertical tab with headings](https://cloud.githubusercontent.com/assets/23196444/22753412/db6188b4-edf0-11e6-98fa-8ba8f2f17588.png)

### Vertical Tabs vs other forms of vertical navigation
**Vertical tabs:**
- The simplest form of vertical navigation with only one level of navigation that is not collapsible.
- Scrolls with content

**Sidenav:** Features a disclosure arrow(optional) in the group heading to collapse and expand lists of links, making it a better option for longer lists with deep hierarchies.

**Tree:** The most complex form of vertical navigation with multiple levels of nested hierarchy that is collapsible and expandable.

### Typography
- Headings and tab links are left aligned. No indents.
- Section names should be short and concise. Wrapping text should be avoided if possible

Sketch file attached:
[Vertical Tabs Design_452.zip](https://github.com/vmware/clarity/files/761728/Vertical.Tabs.Design_452.zip)

**Comment by lil-kim** [comment] 2017-02-03 02:56
Trying a new method for providing specs...
https://vmware.invisionapp.com/share/D4AAUTWTA
Please try using the INSPECT MODE in InVision to get the detailed specs. Let me know if it's not working out well. I've also attached the Sketch file above: Vertical Tabs Design_334.zip

**Comment by hippee-lee** [comment] 2018-04-05 22:47
Still on the roadmap but low priority.

**Comment by Jinnie** [comment] 2018-12-14 14:11
Shall we have a hover color different from the selected background color? Or the background from the screenshot is for hover only and selected has only blue line indicator?

**Comment by Jinnie** [comment] 2018-12-14 16:16
Early CSS only prototype:
https://stackblitz.com/edit/vertical-tabs-prototype?file=src%2Fapp%2Fapp.component.css
It's with palette default colors (as the ones used in the old sidebar). I'll change them to the ones you define, as soon as we have them.
Headings will be added separately. I'd be grateful to any comments about margins, minimal width of the tab panes, any other things you consider wrong on the prototype demo.

**Comment by hippee-lee** [comment] 2018-12-14 16:21
We have a global hover color (https://github.com/vmware/clarity/blob/master/src/clr-angular/utils/_variables.global.scss#L47) and global selection color (https://github.com/vmware/clarity/blob/master/src/clr-angular/utils/_variables.global.scss#L44) defined for light / dark themes. Should those be used here? I'm pretty sure they are used for datagrid hover and selection.

**Comment by colinreedmiller** [comment] 2018-12-14 17:49
We've had some consistency issues with hover / selected and need to do a compare / contrast analysis so we can give you specs. The stackblitz example is fine for the time being.

**Comment by lil-kim** [comment] 2018-12-14 17:54
Hi @Jinnie 
Good point. Originally it was designed with the hover color only, but in hindsight, it should be consistent with other components. So, I agree w/ Colin. 
Matt is correct regarding dark theme. Hover color is: #22343C. Selected: #22343C

**Comment by Jinnie** [comment] 2018-12-15 15:46
Some spec about the tab overflow in vertical tabs will be good too.
We may also decide not to support overflow in vertical tabs, as we can fit a lot more tab buttons in a workspace, compared to horizontal tabs.

**Comment by Jinnie** [comment] 2018-12-15 16:41
A small WIP screenshot with the current overflow +minor CSS tweak on the position, so it's aligned to the left, not the right:
<img width="395" alt="vert-tabs-wip-1" src="https://user-images.githubusercontent.com/1798828/50045285-b6001b00-0098-11e9-8c22-c83e24943493.png">

We may want to align it to the ellipsis, not to the start of the menu, but my basic developer taste liked this more :) 
Any ideas or changes are welcome.

**Comment by Jinnie** [comment] 2018-12-15 16:44
Thinking more about it, it's not smart to have the overflow going down. If we had space down - we'd not set overflow in the 1st place :)
Waiting for your comments

**Comment by colinreedmiller** [comment] 2018-12-17 16:07
Something I have done previously was to address this case with an ellipsis on tab content that exceeded a specified character count, and revealing the entire text in a tooltip style popup on hover.

**Comment by mathisscott** [comment] 2018-12-17 16:12
@colinreedmiller 
Since we have vertical space, ellipsizing long content in the tabs is not a pattern we would want to employ. In general, we have always tried to account for text wrapping when possible.

What @Jinnie is concerned with is the overflow "tab" or, rather, a tab that appears when there are too many tabs to fit vertically in the container. Ellipsizing content would not solve that problem.

@Jinnie, it probably makes sense to align the dropdown such that the bottom left corner of the dropdown is aligned to the bottom right corner of the overflow tab. That way it doesn't obscure the other tabs, a user's path through focus remains clear, and we also know with relative certainty that there is space to the right and above the overflow tab.

**Comment by Jinnie** [comment] 2018-12-17 17:06
Ok, this one gets pretty spaghettic, and I'll try to explain why, after which I'll give some possible solutions.

Issues:
1) Overflow tab
- We can have like 80 lines in a page normally so the overflow is a bit overkill. We do the overflow for horizontal, because we can't put many labels on one line. Even if we possibly do need to overflow, a better approach might be auto vertical scrolling.
2) Headings
Headings are a little strange bird:
- we don't have them in horizontal view, need to hide them there, show them here
- we need to define the html templating that will be triggering them. It can be:
    - just some heading element between tabs - a bit ugly html, but rather easy to implement.
    - groups with labels, that wraps several tabs - tidier html, but will lead to heavy component refactory, as (tech-internals follow...) we're now iterating not over the tab elements, but over the tab-links inside them. We do this using ContentChildren, which leads to that we can't have children of mixed types, especially not intermixed types (like 2 normal tabs followed by a tab group, followed by 1 more tab, etc...).
- headings + overflow - it will be very hard to define and implement the rules of how to mix headings and overflow. Not impossible, but hard to implement and maintain.

Suggestions:
1) Overflow - I suggest we skip the overflow feature for the vertical scenario. This will save many problems. Having the overflow for vertical scenario will have more limited value and application.
2) Headings - I'd suggest starting with an implementation without the headings. It will be a small, fast, manageable change.
    2.1) After it's in, we can estimate a separate task for the headings, which will be heavier, longer task, but with lower priority. Also, vertical tabs with groups and headings remind me too much of 2 other already existing nav components. 
    2.2) Adding the headers and/or groups we're actually changing the semantics of the tabs, as such... but this can be discussed on the 2.1 estimation.

Don't get me wrong - it's not that I am don't want to implement it, I already have working prototypes for most of the discussed topics, but I don't like the increase it component complexity, compared to the expected value.

**Comment by lil-kim** [comment] 2018-12-17 19:01
@Jinnie 
I agree with you that overflow is a bit overkill for vertical tabs. It should be vertical scrolling as you suggest.
As for the headings, IIRC, we added headings to the spec because you can show so many more items in vertical tabs than you can in horizontal that grouping becomes very useful. See how vSphere currently uses a table of contents (essentially vertical tabs) with headings:
![screen shot 2018-12-17 at 10 58 49 am](https://user-images.githubusercontent.com/23196444/50108708-d0e2a480-01ea-11e9-8345-c47259d38739.png)
For wrapping text, I will provide a visual spec. Thanks.

**Comment by Jinnie** [comment] 2018-12-18 16:48
Thanks for the detailed reviews!
Then I'll push the MVP pretty soon but won't close this issue until we figure out all the details about the Headings API and implementation (@lil-kim, your justification about the need for these headings is totally convincing)

**Comment by didkobravo** [comment] 2018-12-19 13:00
I've found this issue a several months ago and used the UX-ready visuals from @lil-kim to "shape-shift" the existing clr-tabs component into a vertical ones.

Made it work with: 
- a bit of CSS
- a custom directive (to show the active clr-tab)
and we've been using them in our product ever since.

You can test it all here:
https://clr-vertical-tabs.stackblitz.io/

+ editors link:
https://stackblitz.com/edit/clr-vertical-tabs

**Comment by Jinnie** [comment] 2018-12-19 21:59
@didkobravo 
The thing that puzzled me the most was why do you need the directive that sets class="active" on the tab-content.
After our talk I'll add the details, for whoever else may be reviewing this issue.
Our DOM looks like this now:
`clr-tabs(`
`  ul (contains all tab-links)`
`  clr-tab - EMPTY`
`  clr-tab - EMPTY`
`  clr-tab - clr-tab-content`
`  clr-tab - EMPTY`
`)`

Due to the empty clr-tab elements it is impossible to set width: 100% on the element with the clr-tab-content.
This leads to one of these 2 layout problems:
1) Unable to reach 100% width:
<img width="406" alt="screen shot 2018-12-19 at 11 19 26 pm" src="https://user-images.githubusercontent.com/1798828/50250117-a1998680-03e8-11e9-95bf-d85b0be4899a.png">
or

2) Empty clr-tabs expanding and taking space:
<img width="398" alt="screen shot 2018-12-19 at 11 14 50 pm" src="https://user-images.githubusercontent.com/1798828/50250163-bb3ace00-03e8-11e9-909b-1ed9a09ed478.png">

What your directive does is to add class="active" to the tab with the tab-content. It's a one line change for us to support it OOTB. But I think that the clr-tab - EMPTY elements have no real value and we'd better try to remove them from our DOM instead. I'll discuss this with the team and get back to you. Actually, the discussion is open here for all.

**Comment by didkobravo** [comment] 2018-12-20 08:21
Thanks for the good summary of what the problem is here that we're solving.
Currently I can think of 3 ways of solving it:

1. [no markup change] will need a way to know which is the active tab (.actveTab directive)
`clr-tabs(
ul (contains all tab-links)
clr-tab - EMPTY
clr-tab - EMPTY
clr-tab.actveTab - clr-tab-content
clr-tab - EMPTY
)`

2. [no markup change] will not need a directive or way to know which tab's selected if there are no clr-tabs with empty elements in them
`clr-tabs(
ul (contains all tab-links)
clr-tab - clr-tab-content
)`

3. [change from current markup] we can differentiate the active visible clr-tab-content easily no directive needed
`clr-tabs(
ul (contains all tab-links)
clr-tab-content.EMPTY
clr-tab-content.EMPTY
clr-tab-content
clr-tab-content.EMPTY
)`

**Comment by Jinnie** [comment] 2019-03-14 15:54
MVP of the Vertical Tabs merged.
I'll keep this open, so we can track the possible future addition of vertical tabs headings.

**Closed** 2019-03-18 13:57 UTC
Labels: New Component, UX Ready
