### ISSUE TITLE
Wizard Focus Does Not Switch To Content After Selecting a Tab

### ISSUE THREAD

**Issue by jeff-bacon** [vmware/clarity#4211] opened 2020-01-16 18:29 UTC
## Describe the bug

When selecting a tab on the left side of the wizard, the focus does not jump to that tabs content.  Keyboard only users and screen reader users will find it difficult to access the pop-up as they have to navigate through all the controls in the left navigation to reach the main content.

## How to reproduce

[https://clarity-light-theme-v2-p315xm.stackblitz.io/](https://clarity-light-theme-v2-p315xm.stackblitz.io/)

1. Tab to the **Open Wizard** button.
2. Press **Enter**
3. Tab until the **Next** button.
4. Press **Enter**
5. Repeat until the last page of the wizard can be accessed.
6. Tab until any tab has focus.
7. Press **Enter**
8. Notice that the content for that tab does not gain focus.

## Expected behavior

When clicking on a wizard tab, focus should move to that tabs content to make the wizard more accessible.

## Versions

**App**

* Angular: 8.2.4
* Clarity: 2.1.2

**Device:**

* Type: Surface Book
* OS: Windows 10
* Browser: Chrome
* Version: 79.0.3945.117

**Comment by gnomeontherun** [comment] 2021-02-01 22:48
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Comment by hippee-lee** [comment] 2022-02-08 17:18
Looking into this as part of VPAT-749 (

It sounds like the a11y requirement is to move focus to the WizardPage after a WizardStepNav item is activated.

**Closed** 2022-05-03 13:44 UTC
Labels: type: accessibility, needs: accessibility input, @clr/angular, component: wizard, status: backlog, priority: 2 medium-low
