### ISSUE TITLE
clr-stack-label/content are not properly aligned when clr-stack-content contains nested button

### ISSUE THREAD

**Issue by dennitsa** [vmware/clarity#153] opened 2016-11-28 15:31 UTC
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When having clr-stack-content with content that is wrapped in a button, the label field in clr-stack-label should be vertically aligned similarly to other clr-stack-label cells. The clr-stack-content should be horizontally aligned similarly to other clr-stack-content cells.
The button in the clr-stack-header should be properly aligned on the right side.

### Actual behavior
Currently, when the content of clr-stack-content contains a nested button, the label's vertical alignment is broken and the clr-stack-content's horizontal alignment is broken.
Also the button in the clr-stack-header is standing out on the right side, which causes the view to display horizontal scroller. This last issue is not actually related to the nested button, but happens always, no matter what is the content.

### Reproduction of behavior
```
<clr-stack-view >
   <clr-stack-header>
      Header
      <button class="stack-action btn btn-sm" type="button">Edit...</button>
   </clr-stack-header>
      <clr-stack-block>
         <clr-stack-label>Label 1</clr-stack-label>
         <clr-stack-content>Value 1</clr-stack-content>
         <clr-stack-block>
            <clr-stack-label>Inner label vertically misaligned</clr-stack-label>
            <clr-stack-content>
               <button class="btn btn-sm btn-link" type="button">
                  Inner value horizontally misaligned
               </button>
            </clr-stack-content>
         </clr-stack-block>
         <clr-stack-block>
            <clr-stack-label>Inner label ok</clr-stack-label>
            <clr-stack-content>Inner value 2</clr-stack-content>
         </clr-stack-block>
      </clr-stack-block>
</clr-stack-view>
```
### Environment details

* **Angular version:** 2.1.1

* **Clarity version:** 0.7.0

* **OS and version:** Windows 10

* **Browser:** Chrome XX
![clarity-bug](https://cloud.githubusercontent.com/assets/17265957/20674039/0a32f45a-b590-11e6-9b66-6b4cd9e2461b.png)

**Comment by adityarb88** [comment] 2016-11-28 15:40
Hi @dennitsa. I am assuming that you are using a `.btn-link` over here. Adding the `.btn-sm` class to it will fix the vertical alignment issue. Currently, `.btn-link` have a horizontal padding of `12px` which is the same padding that we assign to all other buttons in Clarity. The only way I can think of fixing this right now is to either remove the padding for that specific button or add a negative margin to that `stack-block-content`. 

cc: @youdz.

**Comment by dennitsa** [comment] 2016-11-28 16:06
Hello @adityarb88 , In the example that I have provided, you can see that I have used:
<button class="btn btn-sm btn-link" type="button"> 
I'm not sure how this will have effect on the label's vertical alignment, but anyway btn-sm is already there and it doesn't seem to help.
I have 3 alignment problems with the code.
* The label's vertical alignment
* The content's horizontal alignment
* The action button's horizontal alignment.

**Comment by adityarb88** [comment] 2016-11-28 16:09
Hi @dennitsa. Could you please add the markup of your Stack View to the issue so that we can investigate this further?

**Comment by dennitsa** [comment] 2016-11-28 16:14
I have added it in the "Reproduction of behavior" section. Is it not visible somehow?

**Comment by dennitsa** [comment] 2016-11-28 16:17
Pasting here, just in case:
```
<clr-stack-view >
   <clr-stack-header>
      Header
      <button class="stack-action btn btn-sm" type="button">Edit...</button>
   </clr-stack-header>
      <clr-stack-block>
         <clr-stack-label>Label 1</clr-stack-label>
         <clr-stack-content>Value 1</clr-stack-content>
         <clr-stack-block>
            <clr-stack-label>Inner label vertically misaligned</clr-stack-label>
            <clr-stack-content>
               <button class="btn btn-sm btn-link" type="button">
                  Inner value horizontally misaligned
               </button>
            </clr-stack-content>
         </clr-stack-block>
         <clr-stack-block>
            <clr-stack-label>Inner label ok</clr-stack-label>
            <clr-stack-content>Inner value 2</clr-stack-content>
         </clr-stack-block>
      </clr-stack-block>
</clr-stack-view>
```

**Comment by adityarb88** [comment] 2016-11-28 16:53
Hi @dennitsa. Thanks for pasting the markup. You are missing the `.btn-link` class on the action button in the `stack-header`. That should fix that part. We recommend the stack actions be of the type `.btn-link`. For the link button in `clr-stack-content`, I will check with the team and get back to you soon.

**Comment by adityarb88** [comment] 2016-12-02 23:08
Hi @dennitsa. Could you please provide us more details on the why you are considering using a link button in the `clr-stack-content`? I am asking because the example shown in the issue is an editable stack view. What would happen to the link button when you click on the edit action button in the stack header?

Regarding the alignment issues that you raised:
1. The action button in `clr-stack-header` should be a `.btn-link` button

2. The content horizontal alignment: This is actually an issue with the link button. I am planning to open a separate issue for that since its not related to the Stack View. Thanks for reporting this.

3. The label alignment actually works fine. I tried adding multiple lines of text and the alignment looks alright.
![image](https://cloud.githubusercontent.com/assets/1426805/20853243/949882ce-b89f-11e6-9b1f-c246685cdb63.png)
It does break when you use a link button but we want to know more about the use case when a link button would be used in the stack view.

**Comment by dennitsa** [comment] 2016-12-03 06:22
Hello @adityarb88, 
The stack view I have in the example is not going to be editable. We just happen to have an action button with label Edit... It will be used to open a dialog for editing some settings and no inline editing will be supported in the stack view.
As to why we have a link in the stack view: I work at vmware and we are porting existing flex UI to html, using clarity components. We have a link in the existing ui, therefore we need to add a link in the ported one to match the existing functionality.
The label gets displaced when the content has a link. When there is only text in it it is fine.
Also for the action button we must use the btn-outline style, since all other similar screens in our UI are using such buttons and we must be consistent, so using the btn-link style there is not possible for us. Using btn-outline also moves the button to the right.

**Comment by adityarb88** [comment] 2016-12-06 22:23
Hi @dennitsa. The link button problem that you mentioned inside of the stack block content is being looked at. We have an open issue over here: https://github.com/vmware/clarity/issues/184.

For the use case that you mentioned and for using the outline button on the stackview header, I want to check what our UX team says.

cc: @reddolan, @yenmade

**Comment by reddolan** [comment] 2016-12-09 17:47
@dennitsa is the link button navigating the user somewhere or performing an action within the stack view?

**Comment by dtsvetkova** [comment] 2016-12-09 18:52
Hello @reddolan, the link button is used for navigating to another screen.

**Comment by reddolan** [comment] 2016-12-09 22:34
@dtsvetkova it is recommended that if you are navigating a user, that a standard anchor link <a> be used. If you are giving the user some action that they can perform, then a button is recommended. 

The implementation that is in the provided screenshot shows a flat button being used. It would be better if an anchor <a> were used.

```
Use this
<a href="">Link</a>

Not this
<button class="btn btn-link">Action</button>
```

**Comment by dtsvetkova** [comment] 2016-12-10 07:45
Ok, I can try with <a> tag if that won't cause the misalignment in the labels. 
The reason we used a link button is, because we invoke a function to perform the navigation. It's a bit complicated, but our view resides inside an iframe and we navigate to a page inside the parent web application.

**Comment by dennitsa** [comment] 2016-12-10 08:08
Hmm, adding '''<a href='#' (click)='test($event)'>''' to the stackview does invoke my function, but it also reloads the whole page and we just want to handle the click and call our function, which will do  the actual navigation.
Is it not possible to fix the allignment when a link button is used?
Also what about the outline button on the stackview header, which goes to the right?

**Comment by adityarb88** [comment] 2016-12-11 00:25
Hi @dennitsa: If you page is being redirected, I believe its because of the `href='#'`. You can instead try `<a href='javascript://' (click)='test($event)'>` and check if that works. But this again is not a recommended way of handling this because this might cause accessibility problems.

For the alignment issue for the link button, we are planning on fixing that but it may take some time to release that fix as it might be a breaking change for other users. For now you could override the CSS and remove the padding and margins from the link button in the StackView. That will fix the alignment issues for sure.

For the button on the header action, we have added a fix to limit the negative margin to only affect link buttons. Although using outline buttons is not the standard way to use Stack View, it should be fixed in 0.7.5

**Comment by reddolan** [comment] 2016-12-12 19:55
@dennitsa, @adityarb88's is correct, using button versus anchor would be an accessibility issue. The way the link text renders is also misleading. The button displays in all caps, whereas the link would be in normal casing.

**Comment by reddolan** [comment] 2017-06-13 15:28
@dennitsa were you able to get this resolved using and `<a>` versus `<button>`?

**Comment by dennitsa** [comment] 2017-06-20 07:37
@reddolan 
With 4.1.3 clarity components, the button in the clr-stack-header is being properly aligned, no need to workaround it anymore. 
Thanks.

**Comment by mathisscott** [comment] 2017-06-20 12:22
Thanks for the update, @dennitsa

**Closed by mathisscott** 2017-06-20 12:22 UTC
Labels: needs-UX-input
