### ISSUE TITLE
Disabling checkboxes on datagrid rows

### ISSUE THREAD

**Issue by halachliyskid** [vmware/clarity#1550] opened 2017-10-06 07:52 UTC
[x] bug
[ ] feature request
[ ] enhancement

I have a datagrid with checkboxes, but some of them are disabled for a reason (lack of permissions, object state or something else).

### Expected behavior
If I click on the "Select All" checkbox in the title, all rows EXCEPT the disabled ones are selected.

### Actual behavior
If I click on the "Select All" checkbox in the title, all rows INCLUDING the disabled ones are selected.

**Comment by mathisscott** [comment] 2017-10-06 13:28
@gnomeontherun 
Can we validate that this is the case? If so, let's move this into the backlog as a bug. If not, then can we ask for a plunkr?

**Comment by mathisscott** [comment] 2017-10-11 13:56
Just need to be able to add an input on a row that disables checkboxes and radio buttons for that row.

**Comment by govi2010** [comment] 2017-11-09 05:35
I am working on this .

**Comment by belyan** [comment] 2017-11-15 13:21
I have the question related to this issue. How to disable check box to avoid the selection of certain rows in a data grid?

**Comment by msoni11** [comment] 2018-01-21 06:41
@govi2010 : Do you have any updates for us on this ?

**Comment by kalpeshhpatel** [comment] 2018-01-30 05:50
Hey guys, do we have any update on this?

Thanks

**Comment by mathisscott** [comment] 2018-01-30 19:30
@govi2010 mentioned that he was working on this and I haven't heard back.

@belyan, @msoni11, and @kalpeshhpatel 
This isn't scheduled for us in the near term. It's marked open for external contribution if it is a critical issue for your teams.

**Comment by govi2010** [comment] 2018-01-31 07:07
@mathisscott  I have completed this but can not find my uncommitted code. From last 2 month, i have lots of work to do so cannot find time to get this done. I will try to complete this weekend. 

Thanks

**Comment by kalpeshhpatel** [comment] 2018-02-07 06:22
Hey @govi2010 , thanks for you reply. Were you able to complete this? It's bit urgent for us.

Thanks

**Comment by youdz** [comment] 2018-04-03 21:15
We received a request to make sure that the "select all" checkbox at the top properly ignores disabled rows, so I'm posting it here to make sure we don't forget. Please add a unit test for this specific case.

**Comment by hippee-lee** [comment] 2018-04-16 18:05
Moving back to the backlog for now. 
This fix needs to wait until we wrap the pure consumer models to an internal model so that we can take advantage of a shared state.

**Comment by kathygit** [comment] 2018-08-30 05:01
We really need the ability to disable or hide the selection checkbox or radio. 
When can we have it ? Thank you!

**Comment by mathisscott** [comment] 2018-08-30 17:51
@hippee-lee 
Could you give an update on where this is and what may be holding it up?

**Comment by hippee-lee** [comment] 2018-09-25 21:31
When I last looked at this the issue is that the datagrid model needs to be able to wrap the consumers model so that the row select can use the shared state. Right now, iir correctly, the row doesn't know about the disabled state for its consumer model.

**Comment by govi2010** [comment] 2018-09-27 10:27
@hippee-lee  I really lost my fix in my old laptop. Recently I tried to looked into this bug . but I forgot how reproduce this issue So i can fix again and push my code.

**Comment by asachan2707** [comment] 2018-09-27 11:05
@hippee-lee , As  @kathygit mentioned that we need configurable checkbox-group inside datagrid. So make it configurable. 👍

**Comment by gnomeontherun** [comment] 2019-10-18 19:46
This should be resolved by https://github.com/vmware/clarity/pull/3749.

**Closed by gnomeontherun** 2019-10-18 19:46 UTC
Labels: !, component: datagrid, type: enhancement

**Comment by hamza1100** [comment] 2020-03-13 10:46
> [x] bug
> [ ] feature request
> [ ] enhancement
> 
> I have a datagrid with checkboxes, but some of them are disabled for a reason (lack of permissions, object state or something else).
> 
> ### Expected behavior
> If I click on the "Select All" checkbox in the title, all rows EXCEPT the disabled ones are selected.
> 
> ### Actual behavior
> If I click on the "Select All" checkbox in the title, all rows INCLUDING the disabled ones are selected.

Hey,
Could you please share that piece of code. My use-case is, after loading the data, some of the checkboxes should be disabled and when selecting all, only those that are enabled gets selected. I'm having some trouble implementing this.

**Comment by gnomeontherun** [comment] 2020-03-13 15:15
@hamza1100 Can you post onto StackOverflow and tag with `vmware-clarity` for implementation questions? Also see our documentation https://clarity.design/documentation/datagrid to find relecant information about disabling selection for a row.
