### ISSUE TITLE
Add option to deselect all columns in `clr-dg-column-toggle-button`

### ISSUE THREAD

**Issue by pbialy** [vmware/clarity#2861] opened 2018-11-19 12:01 UTC
## Summary

In `clr-dg-column-toggle-button` we can pass two `clrType` params:
`ok` - saves changes
`selectAll` - selects all checkboxes

* What is the change?
Would be nice to also have
`deselectAll` - unselects all checkboxes

* Why should it go in Clarity?
I think It's something basic to have something like this - if you can select all, then why you can't unselect all? Also it will prevent long time spend on hacking this to add something like this (I need to do this right now)

* Does this change impact existing behaviors? If so how?
No, it doesn't. It just adds new possibility

* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case

_Provide some specific details about how this change would improve your application and use case._
Well if you have, let's say, 20 columns selected, and you want to see just 3, then you could just unselect all and then select those 3 (so it's 4 clicks), instead of unselecting 17 columns (17 clicks).

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
Well it's basically a master checkbox, but Clarity only supports selecting all now :(

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
I'm trying to do it right now, working with concept of changing behaviour of component from libraries (see https://blog.angularindepth.com/changing-the-behavior-of-a-3rd-party-angular-component-91f84fb9af28), but no success until now.

**Comment by youdz** [comment] 2018-11-19 12:32
This is a duplicate of #2528, please check out the conversation over there regarding limitations and subscribe for updates.

**Closed by youdz** 2018-11-19 12:32 UTC
