### ISSUE TITLE
Modal is missing fade-out animation on close

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#3416] opened 2019-06-05 17:07 UTC
## Describe the bug

Our modal is missing fade-out animation on close. It was originally an issue due to Angular's issue specified in the following issue report: https://github.com/angular/angular/issues/15798

## How to reproduce

It's visible on our doc site.

## Expected behavior

The modal component should run fade-out animation on close.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2019-06-05 18:40
Duplicate of #1148

**Closed by gnomeontherun** 2019-06-05 18:40 UTC
Labels: Bug
