### ISSUE TITLE
datagrid resize header bug

### ISSUE THREAD

**Issue by spetri** [vmware/clarity#1902] opened 2018-01-31 18:57 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When resizing the datagrid, the header text should resize accordingly by either wrapping or ellipsis'ing.

### Actual behavior
The header text bleeds into the cell next to it.

### Reproduction of behavior
All you need to do is have two headers side by side with long text, the adjust both cells to be wide, then shrink the right cell as much as possible and it'll bleed.
Here's an image from the Clarity docs:

![screen shot 2018-01-31 at 10 56 04 am](https://user-images.githubusercontent.com/1146420/35641571-6a2dd97e-0675-11e8-8e6b-ad0a42ffe466.png)

### Environment details

* **Angular version:** Latest

* **Clarity version:** Latest

* **OS and version:**  Latest Mac OSX

* **Browser:** All

**Comment by Shijir** [comment] 2018-01-31 20:47
if you are manipulating the column text using a web inspection tool, that won't let Datagrid column resize accordingly to its content.

**Comment by Shijir** [comment] 2018-01-31 20:50
Also, closing this issue as it's a duplicate of https://github.com/vmware/clarity/issues/1725.

**Closed by Shijir** 2018-01-31 20:50 UTC
