### ISSUE TITLE
Clarity vertical nav expanded icon misalligned.

### ISSUE THREAD

**Issue by Sunny2720** [vmware/clarity#5861] opened 2021-04-16 10:58 UTC
## Describe the bug

Vertical nav group (clr-vertical-nav-group) expand icon is misaligned.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: PC
- OS: Windows 10
- Browser: chrome

**Current:**
![image](https://user-images.githubusercontent.com/15946983/115014646-3be23a00-9ed0-11eb-889b-1101f254040f.png)

**Expected Behaviour:**
![image](https://user-images.githubusercontent.com/15946983/115014995-aabf9300-9ed0-11eb-8d32-443d8529e8e4.png)

**Comment by sis0k0** [comment] 2021-04-16 16:01
Closing of duplicate of https://github.com/vmware/clarity/issues/5644. The fix is coming soon :)

**Closed as completed by sis0k0** 2021-04-16 16:01 UTC
Labels: type: bug, resolution: duplicate, flag: regression, component: vertical-nav
