### ISSUE TITLE
Tree View in Data Grid

### ISSUE THREAD

**Issue by jatinchhabra-1** [vmware/clarity#4704] opened 2020-06-04 14:56 UTC
I want to show a tree view in Clarity Data Grid. 
In my requirements, each row has some child elements which I need to show when I click on expand icon on that row. And this parent-child relation can go up to many levels deep.
The structure and operations of parents and child elements are almost similar. So a grid view is the best suited. Is there any way to achieve this using a clarity grid. 
The required grid is almost the same as https://www.ag-grid.com/javascript-grid-tree-data/  with single selection and multi-selection operations. Is there any way to achieve this using clarity.

**Comment by gnomeontherun** [comment] 2020-06-04 17:10
Hello @jatinchhabra-1, Clarity intentionally does not provide this behavior for a number of reasons, some of which are defined here https://github.com/vmware/clarity/wiki/Hierarchical-datagrid. 

I'm going to close this is a duplicate of https://github.com/vmware/clarity/issues/2759 and as something we won't be implementing based on previous research and experience. The Tree View is our solution for hierarchical structures.

**Closed by gnomeontherun** 2020-06-04 17:10 UTC
