### ISSUE TITLE
No provider for VerticalNavIconService triggered by clrVerticalNavIcon attribute

### ISSUE THREAD

**Issue by thinkingerrol** [vmware/clarity#3268] opened 2019-04-02 17:42 UTC
## No provider for VerticalNavIconService only in test only with clrVerticalNavIcon attribute

This is very similar to #1552 but only in test and only when adding the `clrVerticalNavIcon` attribute like this:

`<a clrVerticalNavLink [routerLink]="['/']" routerLinkActive="active">
  <clr-icon shape="home" clrVerticalNavIcon></clr-icon>
  Start
</a>`

The error:
```
       Chrome 73.0.3683 (Mac OS X 10.13.4) SidenavComponent should create FAILED
[INFO] 	Error: StaticInjectorError(DynamicTestModule)[ClrVerticalNavIcon -> VerticalNavIconService]: 
[INFO] 	  StaticInjectorError(Platform: core)[ClrVerticalNavIcon -> VerticalNavIconService]: 
[INFO] 	    NullInjectorError: No provider for VerticalNavIconService!
[INFO] 	error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ClrVerticalNavIcon', Function ], ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 639287331, rootNodeFlags: 33554433, nodeMatchedQueries: 349524, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 605732899, directChildFlags: 1753123, childMatchedQueries: 4, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 10, bindings: [ Object({ flags: 1, ns: '', name: 'target', nonMinifiedName: 'target', securityContext: 0, suffix: undefined }), Object({ flags: 8, ns: '', name: 'href', nonMinifiedName: 'href', securityContext: 4, suffix: undefined }) ], bindingFlags: 9, outputs: [ Object({ type: 0, target: null, eventName: 'click', propName: null }) ], element: Object({ ns: '', name: 'a', attrs: [ Array, Array, Array ], template: null, componentPr ...
[INFO] 	    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (node_modules/@angular/core/fesm5/core.js:8895:1)
[INFO] 	    at resolveToken (node_modules/@angular/core/fesm5/core.js:9140:1)
[INFO] 	    at tryResolveToken (node_modules/@angular/core/fesm5/core.js:9084:1)
[INFO] 	    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (node_modules/@angular/core/fesm5/core.js:8981:1)
[INFO] 	    at resolveToken (node_modules/@angular/core/fesm5/core.js:9140:1)
[INFO] 	    at tryResolveToken (node_modules/@angular/core/fesm5/core.js:9084:1)
[INFO] 	    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (node_modules/@angular/core/fesm5/core.js:8981:1)
[INFO] 	    at resolveNgModuleDep (node_modules/@angular/core/fesm5/core.js:21217:1)
[INFO] 	    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (node_modules/@angular/core/fesm5/core.js:21906:1)
[INFO] 	    at resolveDep (node_modules/@angular/core/fesm5/core.js:22277:1)
[INFO] 	Error: Expected undefined to be truthy.
[INFO] 	    at <Jasmine>
[INFO] 	    at UserContext.<anonymous> (src/app/shared/sidenav/sidenav.component.spec.ts:28:23)
[INFO] 	    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:1)
[INFO] 	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:289:1)
[INFO] Chrome 73.0.3683 (Mac OS X 10.13.4): Executed 6 of 6 (1 FAILED) (0 secs / 3.406 secs)

```

## How to reproduce

Unfortunately I'm not sure how to reproduce it from scratch. Clarity is installed on top of Angular not from seed. Project has a backend. Test is started via `mvn clean install`. Until the `clrVerticalNavIcon` attribute is added, everything goes fine. Without test, running is fine even with the attribute.

## Expected behavior

Test should work

## Versions

**App**

* Angular: 7.2.9
* Node: 10.15.0
* Clarity: 1.1.1
* Karma: 4.0.1
* Jasmine: 3.3.0

**Device:**

* Type: MacBook
* OS: 10.13.4
* Browser: chrome
* Version: 73

**Comment by gnomeontherun** [comment] 2019-04-02 18:05
I'm not sure what your full test is, but using `clrVerticalNavIcon` without being inside of a `<clr-vertical-nav>` element will fail due to the provider trees. If your test has a complete example of a vertical nav instead of just a fragment, please provide more details and a reproduction for us to triage.

I'm going to go ahead and close this likely as implementation issue, and general questions like this we ask folks to post on StackOverflow with the `vmware-clarity` tag, and we help there. We use GitHub for bug and feature issues. If this doesn't solve it and you can reproduce this with a demo, feel free to reopen with more details.

**Closed by gnomeontherun** 2019-04-02 18:05 UTC

**Comment by thinkingerrol** [comment] 2019-04-02 18:51
I was able to fix the error by following your advice about having to be inside of a `<clr-vertical-nav>`. Problem was that I had this element in another component. Next problem is the navigation bar has jumped to the other side of the screen now, but that is a different issue and probably also not a bug. Thanks for being so nice and helpful here, although I didn't even follow the bug submission procedure.

Cheers!
