### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by babarxm** [vmware/clarity#670] opened 2017-04-03 12:32 UTC
Error: moduleId should be a string in "WizardPage". See https://goo.gl/wIDDiL for more information. If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.

right after import it into my module I got this error any solution for this ?

**Comment by mathisscott** [comment] 2017-04-03 12:42
@babarxm : Which version of Clarity are you seeing this in?

**Comment by babarxm** [comment] 2017-04-03 12:44
just followed up the instructions setup all things and installed it

`"clarity-angular": "^0.9.0-alpha.1",
 "clarity-icons": "^0.9.0-alpha.1",`

this is what in my `package.json`

and my angular version is

`"@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/flex-layout": "2.0.0-beta.5",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "2.4.6",
    "@angular/platform-browser-dynamic": "2.4.6",
    "@angular/platform-server": "2.4.6",
    "@angular/router": "3.4.6",`

**Comment by mathisscott** [comment] 2017-04-03 12:52
@babarxm : Try using the latest _stable_ release instead of the alpha of 0.9.

```
"clarity-angular": "~0.8.13",
"clarity-icons": "~0.8.13",
"clarity-ui": "`0.8.13",
...
```

**Comment by mathisscott** [comment] 2017-04-03 13:37
@babarxm : Closing this as a duplicate of #667

**Closed by mathisscott** 2017-04-03 13:37 UTC
