### ISSUE TITLE
[String filter] Configure only on enter click or user write stop

### ISSUE THREAD

**Issue by Kevin2iBi** [vmware/clarity#2496] opened 2018-07-26 08:03 UTC
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

When I type in the search field of the respective column I want the filtering to start only when the user clicks enter or stops typing.

### Actual behavior
Currently when the user writes in the search field the filters are automatically submitted, this behavior has a very big cost when worked with data coming from the server, every field change should make an API call, if the user types 15 letters in this field, there are 15 calls in the API.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment] 2018-07-26 14:35
Closing this a duplicate of 
https://github.com/vmware/clarity/issues/793, this is something you can and should handle on your side to debounce the requests to the server when you determine the appropriate time.

**Closed by gnomeontherun** 2018-07-26 14:35 UTC
Labels: Needs Triage
