### ISSUE TITLE
Modal and Wizard with form throws an error when pressing escape to close

### ISSUE THREAD

**Issue by exk0730** [vmware/clarity#1194] opened 2017-07-23 02:13 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Don't throw an error when pushing "escape" to close a modal with a form.

### Actual behavior

1) Open the modal
2) Click the input (so it's `ng-touched`)
3) Press "escape"
4) Observe the error thrown in the console

<details>
<summary>Error</summary>
<pre>
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at viewDebugError (errors.ts:30)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:29)
    at checkBindingNoChanges (util.ts:145)
    at checkNoChangesNodeInline (view.ts:477)
    at checkNoChangesNode (view.ts:568)
    at debugCheckNoChangesNode (services.ts:557)
    at debugCheckRenderNodeFn (services.ts:500)
    at Object.eval [as updateRenderer] (app.component.html:17)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:477)
    at checkNoChangesView (view.ts:383)
</pre>
</details>

### Reproduction of behavior
https://plnkr.co/edit/FJLwhI13nzeETVqWBYI2?p=preview

### Environment details
* **Angular version:** 2.0.X

* **Clarity version:** 0.9.7

* **OS and version:** Mac

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-07-24 14:39
@exk0730 
This is working for me in Chrome, using the plunkr provided and the steps to reproduce. It works fine for me.

Which browser are you using?

**Comment by exk0730** [comment] 2017-07-24 14:52
@mathisscott Do you mean you don't get an error?

Yeh, Chrome Version 59.0.3071.115 on Mac OS X 10.11.6

**Comment by mathisscott** [comment] 2017-07-24 14:56
I am on Chrome 59.0.3071.115 (64-bit). Mac OS X 10.11.6.

Opening the plunkr and going through the steps to reproduce this morning, I cannot replicate.

Could this have been fixed by #1169 ?

**Comment by deviant32** [comment] 2017-07-24 15:03
I was able to reproduce the error, make sure you click on the input to set the focus and then hit escape.

**Comment by mathisscott** [comment] 2017-07-24 15:04
Yes, that is what I'm doing. I'm very good at following directions; just ask my wife!

**Comment by adityarb88** [comment] 2017-07-24 15:06
@exk0730: Could you please try updating to the latest 0.9 version and see if the error goes away? The latest version is 0.9.14: https://vmware.github.io/clarity/news/0.9.14

**Comment by hippee-lee** [comment] 2017-07-24 15:06
@deviant32, @exk0730 - I have reproduced the issue and am looking into it. I'll post here again when I have more info for you.

**Comment by exk0730** [comment] 2017-07-24 15:08
@mathisscott Lol!

@adityarb88 I think the plunker is actually using the latest, but I first noticed it in my own app with 0.9.7 and wanted to make sure it wasn't my app causing the issue

@hippee-lee Awesome! Thanks.

**Comment by mathisscott** [comment] 2017-08-09 22:09
@hippee-lee : Any update on this?

**Comment by hippee-lee** [comment] 2017-08-09 22:48
It seems like a real bug but only under specific conditions. 
Here is my fork of the provided plunk: https://plnkr.co/edit/L63h8hSOeXkTEgH09QPL?p=preview

### Case 1

1. I open the model
2. Put focus into the text box
3. Press escape -> it throws the _ehcaiwc_ (Chocolate) error. 

### Case 2 
0. I open the model
1. I put text in it
2. Escape -> no error
3. Reopen and remove the text -> No error 

I don't have an exact cause yet but it feels like a lifecycle issue and/or ngModel issue.

**Comment by mathisscott** [comment] 2017-08-30 14:49
@hippee-lee 
Any update on the root cause here?

**Comment by hippee-lee** [comment] 2017-09-12 22:47
@mathisscott - fyi still working on this.

**Comment by hippee-lee** [comment] 2017-09-12 22:57
I am also seeing this issue in wizards. Updated the title to reflect that.

**Comment by exk0730** [comment] 2017-09-17 19:22
@mathisscott @hippee-lee Hey Matt, is there any special thing I need to do to get this bug to go away in 0.10.4/5? I tried using your demo files in a plunker, and the error is still thrown.

https://plnkr.co/edit/RTK6txS9QGYjTSzr0FMo

**Comment by mathisscott** [comment] 2017-09-18 15:27
@exk0730 
Make sure the plunkr is using clarity 0.10.5...

**Comment by exk0730** [comment] 2017-09-18 15:34
@mathisscott It's using 'unpkg' `npm:clarity-angular/clarity-angular.umd.js` which points to the latest, if I'm not mistaken...

**Comment by hippee-lee** [comment] 2017-09-18 15:54
@mathisscott - I'm looking into this. Re-opening for now, debugging on plunker wasn't working for me with `clarity-angular` this morning.

**Comment by hippee-lee** [comment] 2017-09-18 16:32
@exk0730 - this bugfix will be released this week. It's merged to master but hasn't been released yet. Please follow up if you continue to experience the `expression has changed after it was checked` error on modals or wizards.

**Closed by hippee-lee** 2017-09-18 16:32 UTC
Labels: !!, bug, ClarityNG, |>

**Comment by exk0730** [comment] 2017-09-18 16:51
@hippee-lee Ahhhh gotchya. Yeah, I saw #1472 and figured it was already merged to a release. Thanks Matt!
