### ISSUE TITLE
clr-dg-pagination should not set clrDgPage on destruction

### ISSUE THREAD

**Issue by asgerjensen** [vmware/clarity#2085] opened 2018-03-17 19:54 UTC
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I should be able to bind to `clrDgPage` and only have it change when user clicks something.

Specifically, I am binding it to a global data service, so having it stay on the last selected value, allows user to return to a view without having to page forward again.

### Actual behavior

During destruction, the pageNumber binding gets one last update, to return to page 1.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

- Globally provided data service, with pageNumber attribute
- Create two routes
- On route one put a data grid, and bind it using
```
      <clr-dg-pagination #pagination [(clrDgPage)]="pageNumber" [clrDgPageSize]="service.pageSize" [clrDgTotalItems]="service.totalItems"></clr-dg-pagination>
```
Put this in your component
```
  set pageNumber(value: number) {
    console.log('setting ', value);
    this.service.pageNumber = value;
  }

  get pageNumber(): number { 
    return this.service.pageNumber;
  }
```
Navigate to page two of the data grid. See that console says 'setting 2'

Navigate to the second route, 
See that console says 'setting 1', when you leave the first route.

### Environment details

* **Angular version:** 5

* **Clarity version:** V11?

* **OS and version:** Mac OS X 

* **Browser:** [all]

**Comment by youdz** [comment] 2018-03-19 13:47
This is a duplicate of #2016 and #1099.

As mentioned in these issues, we are currently blocked because of an Angular bug and there is no workaround we can implement until it is fixed. We can't even provide you with a time estimate, it's fully out of our hands.

**Closed by youdz** 2018-03-19 13:47 UTC
