### ISSUE TITLE
Support for Stacked rows inside Clarity Datagrid component.

### ISSUE THREAD

**Issue by Maharshi** [vmware/clarity#436] opened 2017-02-01 02:05 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Clarity provides Datagrid and StackView as separate components. Our team has requirement that requires us to show data in stacked view. However, stacked view component that does not offer filtering/sorting feature and semantics (at least out of the box). Thus, what I am requesting here is best of both the worlds i.e. Support for Stacked rows inside Datagrid component. 

### Actual behavior
Rows cannot be stacked inside a Datagrid component

### Reproduction of behavior
This is a feature request and hence the feature does not exist in the code for me to demonstrate it using Plunker.

### Environment details

* **Angular version:** 2.2.0

* **Clarity version:0.8.4

* **OS and version: Mac OS X (El Capitan) 

* **Browser:** [all]

**Comment by jaffoneh** [comment] 2017-02-01 07:25
@Maharshi are you basically asking for a summary > detail type of an interaction in a datagrid?

**Comment by Maharshi** [comment] 2017-02-02 04:18
Yes, pretty much. The rows in the grid should be header rows that can be expanded/collapsed and should show the details with data for all the columns in the table, when expanded. Also, the existing filtering/sorting functionality should work along-with the above mentioned feature.

**Comment by jaffoneh** [comment] 2017-02-02 18:53
Alright, if you don't mind I am going to close this one as a duplicate of #403 which is something we're going to work on during the design cycle start next week.

**Closed by jaffoneh** 2017-02-02 18:53 UTC

**Comment by Maharshi** [comment] 2017-02-07 00:35
Ok, [#403](https://github.com/vmware/clarity/issues/403) explains exactly what I am requesting for as well. Do you any rough estimate as to by what date I can expect to get this behavior in data-grid component?

**Comment by jaffoneh** [comment] 2017-02-07 00:36
@Maharshi there is no exact timeline yet but it is going through the design cycle starting this week.

**Comment by Maharshi** [comment] 2017-02-07 00:37
Ok, sounds good.
