### ISSUE TITLE
Wrong margin button with clrLoading inside modal > form-group

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#2583] opened 2018-08-24 14:33 UTC
## Describe the bug

button with clrLoading inside form-group gets wrong margin.

```
<clr-modal [(clrModalOpen)]="opened" [clrModalClosable]="false">
  <h3 class="modal-title">No "x" in the top-right corner</h3>
  <div class="modal-body">
    <form>
      <div class="form-block">
        <p>Clicking on the backdrop doesn't do anything.</p>
        <div class="form-group">
          <button type="button" class="btn btn-primary" (click)="opened = false" [clrLoading]="false">
              I'm the only way to close the modal!
          </button>
        </div>
      </div>
    </form>
  </div>
  <div class="modal-footer">
  </div>
</clr-modal>
```

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v012-sribv1

1.  Open modal

## Expected behavior

Button with clrLoading has the same margin as the normal button

## Versions

**App**

* Angular: 6.1.4
* Node: 10.8.0
* Clarity: 0.12.8

**Comment by hippee-lee** [comment] 2018-08-24 16:12
Hi @williangd. I forked your stackblitz and updated it a bit. The issue is actually with the form, not the modal. There is a new forms structure (read more here: https://vmware.github.io/clarity/documentation/v0.12/forms) and when I place the button in a the new forms structure with the new classes the button is correct. Take a look here and see if it helps: https://stackblitz.com/edit/clarity-dark-theme-v012-issue-2583

I'm closing the issue as I do not believe it is a bug. Please respond with more information if you still have the issue.

**Closed by hippee-lee** 2018-08-24 16:12 UTC
