### ISSUE TITLE
Data selection on search unselect checkboxes

### ISSUE THREAD

**Issue by rotirk20** [vmware/clarity#4764] opened 2020-07-02 13:17 UTC
## Describe the bug
When I check any element and try to search the element unselects or the checkbox unselects.It should be normal without that.

## How to reproduce
I got the code I use optional.I use also server side pagination so I can't really reproduce.So I made an video and put some code on this link https://stackblitz.com/edit/clarity-v3-light-theme-up8dvc?file=src%2Fapp%2Fapp.component.html

Video: https://ttprivatenew.s3.amazonaws.com/pulse/tare/attachments/13983615/TinyTake02-07-2020-03-13-43.mp4

## Expected behavior
To keep the checkbox checked on search

## Versions

**App**

- Angular: [9]
- Clarity: [3]

**Comment by bdryanovski** [comment] 2020-07-13 14:22
It seems that this is related to how we trackBy selected items, I have to dig a little bit more to be sure.

I try the demo above but for some reason it did not work as expected I suspect my browser not doing its job today.

**Comment by bdryanovski** [comment] 2020-07-14 12:50
@rotirk20 - Sorry to say but I could not reproduce this issue - Can you provide a better demo so we could take a look. Everything is looking good on my side.

Thanks.

**Comment by rotirk20** [comment] 2020-07-14 13:05
> @rotirk20 - Sorry to say but I could not reproduce this issue - Can you provide a better demo so we could take a look. Everything is looking good on my side.
> 
> Thanks.

I can't really reproduce the demo because I use two endpoints and plus server driven pagination.I have made an update for the search please check..

https://stackblitz.com/edit/clarity-v3-light-theme-odrady?file=src%2Fapp%2Fapp.component.ts

**Comment by bdryanovski** [comment] 2020-11-24 15:53
Hey it seems that this is fixed into the latest version for v3 `v3.1.12` also you need to use `*clrDgItems` instead of `*ngFor` to make everything work as expected (filtering, pagination, and more)

**Closed by bdryanovski** 2020-11-24 15:53 UTC
Labels: component: datagrid, status: needs investigation
