### ISSUE TITLE
[1.0] Datagrid custom column width

### ISSUE THREAD

**Issue by gonzobard777** [vmware/clarity#2906] opened 2018-12-03 10:52 UTC
## Describe the bug
The version ^0.13.10 worked well with the approach taken from [here](https://stackoverflow.com/questions/48881029/how-can-i-column-width-with-datagrid#48911927).
But on version 1.0 this column width setting does not work.

## How to reproduce
[https://stackblitz.com/edit/clarity-light-theme-v013-wrxgpk](https://stackblitz.com/edit/clarity-light-theme-v013-wrxgpk)
or from github: [https://github.com/gonzobard777/datagrid-custom-column-width](https://github.com/gonzobard777/datagrid-custom-column-width)

1.  Go to 'stackblitz'
2.  Click on 'Open in New Window'
3.  You will see that the columns do not match the contents of the table

Note that I just added the width for the column:
![01](https://user-images.githubusercontent.com/45559041/49370106-47b87180-f704-11e8-9c3d-bb3f3a29a464.png)

## Expected behavior

You can specify an arbitrary width for an arbitrary column. And the columns and content will be the same

## Versions

**App**

* Angular: 7.1
* Node: last in stackblitz
* Clarity: 1.0

**Device:**

* Type: Descktop
* OS: Win10
* Browser chrome, firefox

**Comment by hippee-lee** [comment] 2018-12-18 00:50
The datagrid row uses flexbox for its layout so there might be some issues with trying to use `%` for column width and I'm not 100% sure we supported that pre v1.0.0. I tested using `px` for a predefined width and that works as expected. 

There are two ways to explicitly set column width.
First, bind the width value you want using the template:
``` html
<clr-dg-column [style.width.px]="150" class="width--num"> #</clr-dg-column>
```
Second, using css classes as your example was doing with percentages:
```css
.width--progress {
  width: 200px;
}
```
```html
<clr-dg-column class="width--progress"> %</clr-dg-column>
```

**Comment by gonzobard777** [comment] 2018-12-18 09:32
Hi **hippee-lee**, thanks for your explanation.
As a result of the struggle with these columns, we eventually came to specify the width of the column in pixels. But I would like to be able to set the width in percentage (as it was possible in v0.13.10)

**Comment by hippee-lee** [comment] 2018-12-18 17:38
Hey, @gonzobard777 - I will label this as a regression and look more into it when I have some time. For now I'm going to move it into the backlog. If this is urgent- feel free to take a stab at fixing it. Ask me any questions if you want to know how the renderer calculates cell/column widths. 

I believe that the root cause is related to the cells when they are in the calculation table. They are not getting the correct width from the header when a consumer sets width with a `%` value.

**Comment by hippee-lee** [comment] 2019-04-11 17:31
I did some more investigation and know why. With recent datagrid state changes I still need to figure out how to fix this. I'll update when I make progress.

**Comment by envyN** [comment] 2019-09-20 08:59
Facing this issue with Clarity v1.1.5. But even px setting is non-functional.
Here's the stackblitz : https://stackblitz.com/edit/clarity-light-theme-v013-hh4sot

**Comment by envyN** [comment] 2019-09-20 09:03
ok i guess it does work with px, but somehow there is a min-width being applied. it seems to work for 100px / 200px

**Comment by belyan** [comment] 2020-02-04 11:01
Hi @gonzobard777.
I have the same problem and found the workaround solution.

You still need to set width for datagrid column as it was in Clarity 0.13. You can do it with CSS class or by inline style. Here is an example with inline style.

```
<clr-dg-column [style.width.%]="20"></clr-dg-column>
```

And in addition of that in Clarity 1.0 you also need to set width for datagrid cell related to this column. But you should use CSS property `flex-basis` instead of `width`. This property overrides inline property `width` with incorrectly calculated value.

```
<clr-dg-cell [style.flexBasis.%]="20"></clr-dg-cell>
```

Here is the working example:
https://stackblitz.com/edit/clarity-light-theme-v013-aepwzg?file=src/app/app.component.html

**Comment by gnomeontherun** [comment] 2021-01-25 23:21
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-01-25 23:21 UTC
Labels: component: datagrid, flag: has workaround, flag: regression, resolution: wontfix, type: bug
