### ISSUE TITLE
Backticks in Metropolis font appear to have no width (and stack on each other)

### ISSUE THREAD

**Issue by svarlamov** [vmware/clarity#5255] opened 2020-11-03 10:38 UTC
## Describe the bug

Whenever rendering multiple backticks (`) they just appear on top of each other -- as if there is just a single backtick. 

## How to reproduce

1. Type several backticks in an input that uses the Metropolis font used by Clarity

2. You will only 'see' a single backtick, because of this font bug

## Expected behavior

Would expect to see the number of backticks that are actually in the text.

## Versions

**App**

- Angular: 9
- Node: 10.15.2
- Clarity: 3.1.0

**Device:**

- Type: MacBook
- OS: OS X
- Browser: Chrome
- Version: 86

## Additional notes

Discussion for another similar font here: https://github.com/googlefonts/noto-fonts/issues/736

Patch that worked for me:

```
@font-face {
  font-family: 'Metropolis';
  /* Any substitutes can be used */
  src: local("Helvetica Neue"), local("Arial");
  unicode-range: U+60;
}
```

**Comment by gnomeontherun** [comment] 2020-11-03 14:29
This is a duplicate of #1521 and was resolved by using Clarity City. The Metropolis font is not something we controlled unfortunately. If you have multiple ` characters, I believe you might have to escape them with a space between them.

Closing as resolved in Clarity City, which you could replace Metropolis with Clarity City but there are some differences which is why we haven't automatically updated to use it. Clarity Core is using Clarity City.

**Closed as completed by gnomeontherun** 2020-11-03 14:29 UTC
