### ISSUE TITLE
Tooltips conflict with agm-map

### ISSUE THREAD

**Issue by duzenko** [vmware/clarity#5338] opened 2020-11-30 10:03 UTC
## Describe the bug

If a tooltip is assigned to a disabled button, it goes behind the nearby Google Map.

## How to reproduce

1.  Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-3tvwya?file=src/app/app.component.html'
2.  Hover mouse on the enabled top button - tooltip is OK
3.  Hover mouse on the disabled bottom button - tooltip is cut off

## Expected behavior

Tooltips don't get cut off for disabled buttons

## Versions

**App**

- Angular: clarity demo default
- Node: clarity demo default
- Clarity: clarity demo default

**Device:**

Firefox, Chrome

## Additional notes

![image](https://user-images.githubusercontent.com/1481807/100595437-92752000-3303-11eb-82f2-eb09c8e789aa.png)

**Comment by bdryanovski** [comment] 2020-11-30 11:07
@duzenko  you are right, we need to check why the `z-index` change for `disabled` tooltips.

This is an easy fix ( I think ) we gonna investigate and try to include it in the next releases.

**Comment by duzenko** [comment] 2020-11-30 11:10
> 
> 
> @duzenko you are right, we need to check why the `z-index` change for `disabled` tooltips.
> 
> This is an easy fix ( I think ) we gonna investigate and try to include it in the next releases.

That was my first thought too but I can't see that `z-index` actually changes for disabled buttons.
I may be wrong with this, too. I'm no css guru.

**Comment by bdryanovski** [comment] 2020-11-30 11:19
After inspecting it,

```css
.btn.disabled, .btn:disabled {
  opacity: .4;  /* this is triggering the issue */
}
```

I don't have a solution right now, will have to play a little more

**Comment by bdryanovski** [comment] 2020-11-30 13:02
It seems that it's more complicated than I expected.

The issue is that the parent element is setting the `opacity` so this is messing up the viewing order. Try to set the correct `opacity` to the child element but that did not have any effect. An experimental solution that I found was to use color with opacity value (`rgba`) - but this will require a lot of workarounds related to the `disabled` state and the tooltip.

We have in the roadmap to rework the tooltips and we are reworking our color schema and theming at the moment.

I think that this issue will be best addressed there. For the moment as a workaround, I could suggest changing the position of the tooltip if possible - so it won't be shown on top of the affected component.

**Comment by duzenko** [comment] 2020-11-30 13:29
Using `opacity: 1` as a workaround in our app for now
I understand that the tooltip is supposed to be semi-transparent for disabled buttons but this is not critical for us.

**Comment by gnomeontherun** [comment] 2021-03-10 16:37
Given this is a very specific conflict with another library and it has a workaround, I'm going to close this issue. In the future our Core implementation of tooltips don't expect to have this kind of issue and will recommend updating to it when they are available.

**Closed as completed by gnomeontherun** 2021-03-10 16:37 UTC
Labels: type: bug, priority: 1 low, component: tooltip

**Comment by duzenko** [comment] 2021-03-10 17:59
> 
> 
> Given this is a very specific conflict with another library and it has a workaround, I'm going to close this issue. In the future our Core implementation of tooltips don't expect to have this kind of issue and will recommend updating to it when they are available.

What if it's not just another library it conflicts with? Would you reopen?
