### ISSUE TITLE
Stepper panel header status icons do not reflect their step's Angular FormGroup state

### ISSUE THREAD

**Issue by rob3c** [vmware/clarity#4934] opened 2020-08-21 07:10 UTC
## Describe the bug

_This is essentially my comment https://github.com/vmware/clarity/issues/4539#issuecomment-676840330 turned into a bug report here as suggested by @gnomeontherun_

The Stepper panel header status icons do not reflect their step's bound Angular FormGroup state in all circumstances.

## How to reproduce

The problematic behavior is already apparent in the working Stepper sample in the Clarity docs for the Stepper control [here](https://v3.clarity.design/stepper#examples).

I've also recreated it in a complete example of it on CodeSandbox as well (Stackblitz requires my email to create an account and an example, but CodeSandbox does not):
https://codesandbox.io/s/clarity-stepper-panel-status-bug-repro-qppgs?file=/src/app/app.component.html

That CodeSandbox includes repro instructions in the space above the Stepper component, but I'll also list the steps here and provide a screenshot:

### Steps to reproduce the behavior:

First, create a Stepper component with at least two steps and bind it to an Angular form. (In my example as well as the one linked to, I use Reactive Forms.) Make fields in the first step required, so that there's validation to determine the panel's FormGroup status. Then:

1. Populate fields in the Step 1 panel and click NEXT. (FormGroup valid; step 1 panel header has green checkmark.)
2. Reopen the Step 1 panel and clear one or both fields. (FormGroup invalid; panel status unchanged.)
3. Either collapse the Step 1 panel or return focus to the Step 2 panel <b>without</b> clicking NEXT. (FormGroup and panel status both unchanged.)

Notice that the Step 1 panel's `FormGroup`'s status is `INVALID` and the empty fields in the show `required` errors. But the panel's header still shows a valid status with a green checkmark, even after navigating away from the Step 1 controls, either by collapsing the panel or moving focus to a different one.
    
## Expected behavior

When navigating away from a Stepper panel - whether using buttons or not - I expect the Stepper panel header reflect its associated `FormGroup` status correctly. While there may be an argument for waiting until focus leaves the current Step, I think it's a bug to keep the green checkmark for an invalid FormGroup when leaving the Step.

## Versions

**App**

- Angular: I've tried 9 and 10, but any compatible version will likely show the problem
- Node: 12.18.3 on my dev box, but otherwise irrelevant
- Clarity: 3.1.4 in the CodeSandbox, but any 3.x or 4.x is likely a problem.

**Device:**

- Type: Windows VMs and Macbook Pro
- OS: Windows, macOS
- Browser: Chrome, Firefox, Safari
- Version: latest evergreen on each OS

## Additional notes

Here's a screenshot showing the problematic state:
![clarity-stepper-panel-status-bug-repro-screenshot](https://user-images.githubusercontent.com/1098077/90862519-891b0580-e35b-11ea-9e93-cfd4f298c6a6.png)

**Comment by LinkiPinki** [comment] 2020-09-30 10:28
It looks like currently, the headers are only updated on reset or when you move to the next step.

See [ClrStepper](https://github.com/vmware/clarity/blob/8baca78c5d0640ab5f74fc93b73d3b96207d01a2/packages/angular/projects/clr-angular/src/accordion/stepper/stepper.ts#75)'s functions `listenForFormResetChanges`, `listenForPanelsCompleted` and `setPanelsWithFormErrors`.

This issue is also prevalent if your a stepper has a cross-validation between controls in different panels. I for example have a select box in the first panel that defines a template for the next steppers. After filling out the stepper, you can go back and change the  template which will trigger the form groups to be invalid for one or more stepper-panels but the panel's title won't update until the final submit call.

**Comment by mathisscott** [comment] 2020-10-02 19:54
I dug deep into this and the problem is that the stepper is so proscriptive in how it marks these panels as valid and invalid. There is no easy way to just get it to work with the stepper as is. The refactor involved is non-trivial and would requiring unwinding all these services, models, and components. Or knowing some super-secret backdoor into them that I was unable to uncover.

I will move this into our backlog. Ultimately, the answer may be to use the stepper in `@clr/core` when it is ready. But I'm not closing this one until we know for certain.

**Comment by mattmutt** [comment] 2021-10-18 22:22
One year later, just revisiting to see if some action or recommended workaround can be done using any imperative code to force a panel header icon to accurately reflect state. Our workflow code is heavily depending on this container component for correctness. Right now the usability is a bit confused by status icons.

* Are there supporting tests written that have validation triggers work across panels?


* If one makes use of the `clr-control-error` will it work if triggered from a separate panel? I have seen where the `errors` map on the control is `null`, but a red error message didn't get cleaned up. What might cause this staleness?

Just an example recording of how the debug in the storage panel correctly displays the form group and individual form control's validation state. However the red exclamation icon and the `clr-control-error` are simply stale. I would toggle between a storage size of 11 and 12 which determines a valid or invalid state respectively.

The Clarity Next button in the Storage panel is correctly being enabled or disabled at all times, because that has a standard Angular binding expression applied. We don't have so much direct control elsewhere, and rely on the declarative Clarity markup to just work.

```
<button clrStepButton='next' [disabled]='formGroup.get("storage").invalid'>Next</button>
```

https://user-images.githubusercontent.com/8688570/137813476-77c33d33-6c69-45d2-ae1a-ac60e338c76b.mov

**Closed** 2022-05-03 13:44 UTC
Labels: type: bug, component: stepper, v4, v5

**Comment by rob3c** [comment] 2022-05-03 23:56
As another commenter mentioned above, the ClrStepper state logic was a bit too convoluted for a simple fix. I didn't like the design, so I solved it another way. I still left this issue open, because it obviously still needed fixing.

Anyway, my solution at the time was to build a stepper directly out of the `ClrAccordion` (which the `ClrStepper` also does) while using the `ClrStepper` modifications in the Clarity source for inspiration. For example, added the `clr-stepper-forms` class to it, and leveraged various other tactics to get it working.

Here's a test clip showing a cropped part of the customized accordion in action, both with and without angular validation json in the header:

https://user-images.githubusercontent.com/1098077/166591349-ba59661f-786f-4beb-8b09-1b9b611219d4.mov

**Comment by ashleyryan** [comment] 2022-05-04 13:53
@rob3c I've been cleaning up this repo since it's archived (temporarily unarchived for cleanup). 

If this is still an issue - can you recreate the issue in https://github.com/vmware-clarity/ng-clarity/issues
