### ISSUE TITLE
Clarity input style is not applied to an input element without a clrInput directive

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3469] opened 2019-06-16 12:04 UTC
## Describe the bug
The input style is only applied to an input element with a clrInput directive.
I'm not sure if this is intended in 2.0 but in previous versions, an input with a clrInput directive and an input without the directive have consistent styling.

![image](https://user-images.githubusercontent.com/1977391/59563855-c60dad00-9071-11e9-914b-562775d989bf.png)

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v2-hyve11

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2019-06-16 18:37
This is intentional. We don't want to target elements globally, but rather specific ones. There are cases where people use inputs in custom components (or third party components) and we don't want to bork those behaviors or styles by default. Closing as intended.

If you want just the styles, you can also put `class="clr-input"` onto the input and get the styling without the Angular functionality (this is the basic CSS case in the documentation).

**Closed by gnomeontherun** 2019-06-16 18:37 UTC
