### ISSUE TITLE
Error occurred when upgraded Clarity project seed

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#390] opened 2017-01-20 03:59 UTC
There occurred an error when I upgraded Clarity project seed fold by overwritten the src folder with the last contents.

**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Pass through.

### Actual behavior
Error reported in browser console:
`Unhandled Promise rejection: Error in .....  inline template:0:0 caused by: No provider for ClrResponsiveNavigationService! ; Zone: angular ; Task: `

### Environment details

* **Angular version:** 2.0.X
2.2.3
* **Clarity version:** 
0.7.5
* **OS and version:** 
OS X, Ubuntu
* **Browser:** [Chrome | Firefox]

**Comment by Shijir** [comment] 2017-01-20 04:34
Duplicate of #341

**Closed** 2017-01-20 04:34 UTC
