### ISSUE TITLE
angular 11 - error while configuring clarity library - unable to resolve `ResizeObserver`.

### ISSUE THREAD

**Issue by Divine1** [vmware/clarity#6089] opened 2021-06-21 09:03 UTC
Angular 11

i followed the steps mentioned in this [link](https://clarity.design/get-started/developing/angular/#manually-adding-clarity-to-an-angular-project)

Receiving below error 
![image](https://user-images.githubusercontent.com/10482177/122734118-6d460000-d29b-11eb-8f0b-be7ea26483ed.png)

to fix it i replaced `ResizeObserver` with `any` in the file `node_modules/@cds/core/internal/utils/responsive.d.ts`

is this arising due to some kind of bug or did i miss to install any other package?
kindly let me know the permanent solution for this issue.

**Comment by Shijir** [comment] 2021-06-21 17:42
Closing as it's a duplicate of https://github.com/vmware/clarity/issues/6060.

**Closed as completed by Shijir** 2021-06-21 17:42 UTC
