### ISSUE TITLE
Scrollbar appears when the last column of the datagrid is hidden

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#2454] opened 2018-07-12 09:36 UTC
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

There should be no scrollbar when datagrid fits in its parent container.

### Actual behavior

Although the datagrid fits perfectly, there is a scrollbar because the last column of the datagrid is hidden by default.

### Reproduction of behavior

  https://stackblitz.com/edit/clarity-dark-theme-v11-exxkms
  
### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11

* **OS and version:** MacOS High Sierra

* **Browser:** all

**Comment by youdz** [comment] 2018-07-12 12:17
This is a duplicate of #1248, please subscribe to that issue for updates. It might be fixed when our current work on the datagrid's rendering engine lands.

**Closed by youdz** 2018-07-12 12:17 UTC
Labels: Duplicate
