### ISSUE TITLE
Datagrid footer is not fully visible in IE and Edge browsers when there is a horizontal scrollbar

### ISSUE THREAD

**Issue by kaleksandrov** [vmware/clarity#1655] opened 2017-10-30 09:23 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The datagrid footer should be fully visible in all browsers.

### Actual behavior
When there is a horizontal scrollbar, it covers the datagrid footer in IE and Edge browsers

### Reproduction of behavior
https://plnkr.co/edit/UC5YXXKWYsDqTaAOIJJs

### Environment details

* **Browser:** IE, Edge

**Comment by adityarb88** [comment] 2017-10-30 13:17
I believe this is a duplicate of #1255. Please subscribe to #1255 for more updates. Closing the issue as duplicate.

**Closed by adityarb88** 2017-10-30 13:17 UTC
