### ISSUE TITLE
FocusTrapDirective RangeError: maximum call stack size exceeded

### ISSUE THREAD

**Issue by zivanov123** [vmware/clarity#1473] opened 2017-09-15 13:37 UTC
```
[ X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
To be able to use modals without errors.

### Actual behavior
We have a modal showing above a wizard (a login dialog above a wizard). However after bumping from 0.9.11 to 0.10.4 we found this error occurring when trying to close the modal:

Uncaught RangeError: Maximum call stack size exceeded.
    at FocusTrapDirective.onFocusIn (VM3171 clarity-angular.umd.js:8388)
    at Object.eval [as handleEvent] (VM3270 Modal.ngfactory.js:59)
    at handleEvent (VM3177 core.umd.js:12046)
    at callWithDebugContext (VM3177 core.umd.js:13507)
    at Object.debugHandleEvent [as handleEvent] (VM3177 core.umd.js:13095)
    at dispatchEvent (VM3177 core.umd.js:8639)
    at eval (VM3177 core.umd.js:9250)
    at HTMLDocument.eval (VM3176 platform-browser.umd.js:2685)
    at ZoneDelegate.invokeTask (VM3153 zone.js:424)
    at Object.onInvokeTask (VM3177 core.umd.js:3913)

We don't have any workaround for this. Also there is no option to turn this directive off.

### Reproduction of behavior

Including plunker to see the simple case with two dialogs one above another.
1. Click "Show Modal"
2. Click "OK" -> Second modal is shown
3. Click "OK" or "Cancel"
4. Observe the error in the console

https://plnkr.co/edit/82Tz7Nwdrgfoi8Wed8cR?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.10.4

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-09-15 14:04
I believe this is a duplicate of #1428 

We already have a PR in review for that at #1441 

Please subscribe to those to track progress. I would expect this to be resolved within the next couple of releases.

**Closed by mathisscott** 2017-09-15 14:04 UTC

**Comment by lmauri** [comment] 2018-07-25 16:19
I still have this problem on my app.
I've the lastest angular and clarity versions.
Has it been fixed?

**Comment by Shijir** [comment] 2018-07-25 17:06
@lmauri this bug no longer exists. I've reproduced your original Plunkr issue in StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v012-pn3g9f?file=src/app/app.component.html
