### ISSUE TITLE
shouldn't the size conform to the rest of Clarity widgets

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#1429] opened 2017-09-06 20:28 UTC
https://github.com/vmware/clarity/blob/55e90f4b474a25fa259d387829e8f7db66eb5b80/src/clarity-angular/emphasis/alert/alert.ts#L15

boolean suggest there would only be two sizes..ever.

whereas the rest of clarity abides by `[clrSize]`.. Should be consistent across the interfaces

**Comment by mathisscott** [comment] 2017-09-06 21:20
Hi @mattmutt 
IIRC, the input was carried over from the initial implementation of alerts months and months ago. The intention behind that was to minimize breaking changes as much as possible.

We have an open issue to bring consistency throughout Clarity's inputs/outputs across all components. That issue is #1425 

I'm going to close this one as a duplicate of that...

**Closed by mathisscott** 2017-09-06 21:20 UTC
