### ISSUE TITLE
The "Select All" checkbox has some positioning issue in Datagrid

### ISSUE THREAD

**Issue by sisohs** [vmware/clarity#4103] opened 2019-12-10 05:29 UTC
## Describe the bug

When using the clarity datagrid with checkbox, the Select All checkbox appears off from the center. This happens in both the normal and compact datagrid as shown in the below attached screenshot

## How to reproduce

Just create a datagrid with data as Input from other component. Enable clrDgSelected and render.
![Annotation 2019-12-10 105848](https://user-images.githubusercontent.com/51208593/70498349-17d45300-1b3c-11ea-898d-5df61018698b.jpg)

## Expected behavior

The checkbox button should be positioned in the center

## Versions

**App**

* Angular: 8
* Node: 12.13.0
* Clarity: 2.3.1

**Device:**

* Browser : Firefox and Chrome
* Version 67+

**Comment by hippee-lee** [comment] 2019-12-10 16:40
Here is a stackblitz reproduction: https://stackblitz.com/edit/gh-4103-select-datagrid-alignment-issue

**Comment by aliitani** [comment] 2019-12-18 00:18
Hello, is this issue still open. I can help out!

**Comment by gnomeontherun** [comment] 2019-12-18 00:44
Yes it is open, if you are able to identify a solution please open a PR!

**Comment by sisohs** [comment] 2019-12-18 06:24
> 
> 
> Hello, is this issue still open. I can help out!

**Comment by sisohs** [comment] 2019-12-18 06:25
> 
> 
> Hello, is this issue still open. I can help out!

Can you point out the reason for bug till you create a PR?

**Comment by aliitani** [comment] 2019-12-18 17:39
> Can you point out the reason for bug till you create a PR?

Going through the stackblitz link, it looks like it has to do with a class assigned to one of the HTML elements, within 'clr-datagrid' component. Also, the class assigned to the HTML element is triggering both compact and non-compact data grids.

**Comment by aliitani** [comment] 2019-12-18 20:31
PR: https://github.com/vmware/clarity/pull/4131

**Closed** 2020-01-09 16:20 UTC
Labels: @clr/angular, component: datagrid, flag: regression, type: bug

**Comment by sisohs** [comment] 2020-02-25 10:35
![image](https://user-images.githubusercontent.com/51208593/75239365-91e5b100-57e8-11ea-90aa-b9438e300409.png)
The fix doesn't help to avoid weird line below Header and also the Checkbox Icon is misaligned
