### ISSUE TITLE
Datagrid filter icon state is not updated when the filter is applied programmatically

### ISSUE THREAD

**Issue by danail-vasilev** [vmware/clarity#3951] opened 2019-10-30 08:47 UTC
Hello, 
I am trying to set a built-in datagrid filter programmatically. When doing so the filter is properly applied but the filter icon is not applied. If you click on the filter icon its state is updated.  You can find a runnable example here:
snapshot - https://www.screencast.com/t/S0uUaE9lYJU4
example - https://stackblitz.com/edit/clarity-2umjop

I am not sure why the filter in this example is not applied either but in my local enviornment it is.

**Comment by hippee-lee** [comment] 2019-10-30 15:32
The custom filter needs to implement the [isActive](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/interfaces/filter.interface.ts#L9) method. 

You can see the examples for this [here](https://github.com/vmware/clarity/blob/master/src/website/src/app/documentation/demos/datagrid/filtering/examples.ts). 

Closing as this is a question and not an issue.

**Comment by danail-vasilev** [comment] 2019-10-30 15:51
I am using the built-in numeric filter.  It implements ClrDatagridNumericFilterInterface which has only accepts() method and not isActive()

**Comment by danail-vasilev** [comment] 2019-10-31 14:06
Thanks for looking into this.
The issue seems to be reproducible since Clarity 2.2.0 - https://stackblitz.com/edit/github-question-3951-6rt82x?file=package.json
If you downgrade to an earlier version the issue is not reproducible.

**Comment by hippee-lee** [comment] 2019-10-31 15:33
It looks like this could be a regression but needs some more investigation. The issue might be related to the underlying issue of https://github.com/vmware/clarity/issues/3804

**Comment by BramMeerten** [comment] 2020-01-20 12:33
> [Here](https://stackblitz.com/edit/github-question-3951) is a simple stackblitz that implements a string filter and allows the user to toggle the preset value. The active state works there so there may be an issue with the code in the stackblitz provided. I would suggest starting with a simple version like this one: https://stackblitz.com/edit/github-question-3951
> and building it back up to include all the functionality that is needed.

This seems to be fixed in version 2.3.3, I tried the example  provided by hippee-lee above.
With version 2.2.0 it's broken, but from version 2.3.3 it works again.

**Comment by sis0k0** [comment] 2020-08-12 09:02
This issue was resolved in v2.3 - https://stackblitz.com/edit/datagrid-filter-icon-state-23?file=package.json. The behavior's correct in the `next` version too - https://stackblitz.com/edit/datagrid-filter-icon-state-next?file=package.json.

**Closed by sis0k0** 2020-08-12 09:02 UTC
Labels: component: datagrid, flag: regression, status: needs investigation
