### ISSUE TITLE
 Indeterminate (Looping) Progress Bar control is not compatible to firefox

### ISSUE THREAD

**Issue by Rajpradeep26** [vmware/clarity#5071] opened 2020-09-22 12:34 UTC
## Bug description

Indeterminate (Looping) Progress Bar is not working in firefox

## How to reproduce

_Link: [Progress bars](https://clarity.design/documentation/progress)._

1.  Open firefox browser and paste the url 'https://clarity.design/documentation/progress' in address bar
2.  Scroll down to 'Indeterminate (Looping) Progress Bar'
3.  See the progress bar looping is static (not working)
![InfiniteProgressBar](https://user-images.githubusercontent.com/54431553/93882969-89ae0f80-fcfe-11ea-81a9-7dbcceb8963d.PNG)

## Expected behavior

_Progress bar should be looping infinitely_

## Versions

**App**

- Clarity: v4

**Device:**

- Firefox Browser [v80.0.1 (64-bit)]

**Comment by hippee-lee** [comment] 2020-09-22 15:51
I tested this on macOS and Windows but it works as expected. The demo is only set to repeat ten times.

**Comment by hippee-lee** [comment] 2020-09-22 15:56
Thanks for reporting this. There is something going on with FF for sure.

**Comment by gnomeontherun** [comment] 2021-05-06 21:03
I cannot reproduce this issue in current versions of Firefox, closing as fixed in the browser.

**Closed by gnomeontherun** 2021-05-06 21:03 UTC
Labels: browser: firefox, component: progress, type: bug
