### ISSUE TITLE
Vertical Nav renders to right when inside component

### ISSUE THREAD

**Issue by ImNightwing** [vmware/clarity#3049] opened 2019-01-16 18:28 UTC
## Describe the bug

I want to move the logic of the vertical nav to a separate component. If the vertical nav component is not directly inside the content-container and inside an inner component, the css is thrown off. The responsive functionality works as expect.

Documentation also does not explain that it must go inside the content-container. This is only shown in the one code example for Basic Structure.

## How to reproduce

https://stackblitz.com/edit/angular-tcm1hm

Must be used in a 768px+ width screen to see issue

## Expected behavior

I would expect the vertical nav to appear correctly when inside a nested component

## Versions

**App**

* Angular: [e.g. 6] 7
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5] 1.0.4

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment] 2019-01-17 01:02
The styles for `.sidenav` depend on a specific DOM structure. I modified your stackblitz to show one way it could achieve the DOM structure needed for the `.sidenav` to work in your component; 

https://stackblitz.com/edit/issue-3049

I'm closing this b/c its an implementation issue and not a bug. If you have any follow up wrt the stackblitz please post a question on stackoverflow and tag it with `vmware-clarity`. 
Thanks.

**Closed by hippee-lee** 2019-01-17 01:02 UTC
