### ISSUE TITLE
Signposts are cut off on smartphones

### ISSUE THREAD

**Issue by gurumaxi** [vmware/clarity#3949] opened 2019-10-29 12:52 UTC
## Describe the bug
Signposts are cut off when the distance from the info icon to the border of the screen is too small.

## How to reproduce
1. Got to https://clarity.design/
2. Shrink the window to mobile width
3. Go to the signposts page
4. In the section Code & Examples, click on the info icon above the second code example.

## Expected behavior
The signpost should change position automatically if there is to little space left or be centered in the middle of the screen on smaller screens.

**Device:**
mobile device or small desktop window
all browsers

## Screenshot
![signpost](https://user-images.githubusercontent.com/44405244/67937783-7669f100-fbce-11e9-9c6a-50d4ea7b6a10.png)

**Comment by gnomeontherun** [comment] 2019-10-29 15:58
When reporting a bug, please provide more information and a reproduction to help us understand and triage. Screenshots are pretty hard to debug in many cases. I can't be sure this is a problem with Clarity or with something specific in your application.

In this case, this is likely because of position relative clipping issues that will be solved when we migrate signposts to our new popovers logic (coming soon). In the meantime, this looks like a custom tree/table? For the signpost on Auto Config 3.1, you could put the signpost into a different orientation to give it more space and avoid clipping. You could also consider a different pattern, mobile signposts are more difficult to use than perhaps using a modal due to sizing constraints of the screen.

**Comment by hippee-lee** [comment] 2019-10-29 16:29
We definitely need a reproduction for this. Smart popovers won't fix content that is too large (so tall or wide it goes offscreen on two sides of the viewport) to have a valid position.

**Comment by gnomeontherun** [comment] 2019-12-21 01:57
I believe this will be best solved by the work in #1757, so closing in favor of it.

**Closed by gnomeontherun** 2019-12-21 01:57 UTC
Labels: status: needs reproduction, type: bug
