### ISSUE TITLE
Further documentation corresponding CSS Custom Property theming

### ISSUE THREAD

**Issue by boeckMt** [vmware/clarity#4435] opened 2020-04-02 10:18 UTC
## Summary

In the documentation on [theming](https://clarity.design/documentation/themes) is mentioned that SASS-based theming is deprecated and will be removed in version 4.0.

To better prepare for the switch, it would be helpful to get a reference for all used CSS Custom Properties and which sass variables will be converted in the feature.

## Use case

People can earlier start to replace the SASS-based theming.

## Examples

For example sorted the used/planed variables by package:
* clr-angular
* clr-core
* clr-ui
...

**Comment by elielia** [comment] 2020-04-08 08:14
Would love to get some updates on this. How is this done?

**Comment by mathisscott** [comment] 2020-04-08 17:30
@boeckMt 
We are presently working on updating the website so this information will hopefully be clearer when that work is done. Given the timelines we are working against, it is highly unlikely that SASS-based theming will be removed in 4.0. It's looking more like a change that will happen in 5.0 or 6.0. So no worries on the timeline right now.

@elielia 
What are you asking?

**Comment by mathisscott** [comment] 2020-04-08 17:31
FWIW, this looks to be a duplicate of #4005 . I will close once the questions above are resolved.

**Comment by ilikeprograms** [comment] 2020-05-05 14:14
Im currently looking at updating our code at work to switch to using the new CSS variables you guys have moved towards.
However im also looking at SASS Modules, will you eventually move away from Sass entirely and just support theming using CSS variables?

**Comment by mathisscott** [comment] 2020-05-05 14:36
@ilikeprograms 
Our public-facing code will support theming through CSS variables. Internally, the Clarity code will still be using SASS. People using Clarity in their projects will still be able to build Clarity CSS from the SASS in the `node_modules`. But that would be a harder way to "theme" Clarity than using the CSS custom properties. And it's not a path we would offer support for once custom properties (CSS variables) becomes the officially recommended way to theme Clarity.

**Comment by gnomeontherun** [comment] 2020-10-29 20:36
No longer an issue or resolved in the upcoming website work. Closing as resolved.

**Closed by gnomeontherun** 2020-10-29 20:36 UTC
Labels: type: support
