### ISSUE TITLE
Datagrid Improper Column Width

### ISSUE THREAD

**Issue by Nishant-Ingle** [vmware/clarity#4673] opened 2020-05-22 12:10 UTC
## Describe the bug

Column `Resource Hostname` is pushing text into adjacent column.

<img width="1436" alt="Screenshot 2020-05-22 at 4 49 40 PM" src="https://user-images.githubusercontent.com/30694286/82665784-24fc7e80-9c52-11ea-8a16-5e9caa11fb23.png">

The problem of overflow can be solved by using the workaround provided
in https://github.com/vmware/clarity/issues/815.
<img width="1440" alt="handling overflow" src="https://user-images.githubusercontent.com/30694286/82665917-62f9a280-9c52-11ea-8902-1789be421800.png">

The actual problem is that Clarity is giving incorrect widths to the columns.
This is very disturbing to the user as columns with less wider content (like `Valid From`) are given
relatively larger width while columns requiring large widths (like `Resource Hostname`) are given very small one. Clarity must use a smart mechanism to allot column widths.

## How to reproduce

1.  Clone project https://github.com/Nishant-Ingle/Clarity-DataGrid-Issue
2.  Run `ng serve`
3.  See error in the Datagrid

## Expected behavior

Column `Resource Hostname` should have a much larger width. Columns like
`Valid From` and `Valid Until` should have smaller width.
<img width="1440" alt="expected" src="https://user-images.githubusercontent.com/30694286/82666122-caafed80-9c52-11ea-97a8-8533c955eeb5.png">

## Versions

**App**

- Angular: 9.1.4
- Node: 10.19.0
- Clarity: 2.4.2

**Device:**

- Type: MacBook Pro 2015
- OS: MacOsX 10.15.4
- Browser: Chrome
- Version: 83.0.4103.61 (Official Build) (64-bit)

## Additional notes

None

**Comment by gnomeontherun** [comment] 2020-05-29 20:42
This is a duplicate of https://github.com/vmware/clarity/issues/4015, which provides the option for changing the overflow settings to allow text to wrap inside of cell. Clarity does not know about the size of content, so calculations can be difficult in cases where really long strings of text exist, and apps should either set the overflow properties or set an explicit width on the cells. Closing as duplicate.

**Closed by gnomeontherun** 2020-05-29 20:42 UTC
