### ISSUE TITLE
Clarity does not work correctly with checkbox groups

### ISSUE THREAD

**Issue by raijinsetsu** [vmware/clarity#3433] opened 2019-06-10 16:59 UTC
## Describe the bug
From the documentation, it appears that Clarity assumes that each checkbox in a group will have the same form control (ie. "formControl", "formControlName", or "ngModel") as every example for check-boxes has the same ngModel binding for every input. However, even in the sample on the page, this does not work correctly: selecting one option selects them all and this is not expected.

If, instead, we bind each input to a different member of a FormArray control, for example, then clicking an option correctly selects just that one option. Unfortunately, any validation errors on the FormArray (ex. to enforce a minimum or maximum number of selections) does not cause the "clr-control-error" element to appear and there appears to be no way to connect the clr-control-error element with the parent control.

The underlying issue is that Angular itself does not support checkbox groups natively and the modules that have been created to simplify this do not play well with Clarity (ie. CSS get's mangled or the Clarity component stops functioning).

I cannot determine if the documentation is incomplete or if this is a missing feature. However, it is certainly true that the examples in the documentation do not currently work as expected.

## Versions
**App**
* Angular: 7.2.0
* Node: 10.x
* Clarity: 1.1.3

## Additional notes
I'm not sure if this is just an issue with documentation, if this needs to be a feature request, or if there is a different component that should be used when you want the user to select multiple options.

**Comment by gnomeontherun** [comment] 2019-06-10 22:18
As you said, Angular itself doesn't support this natively. Therefore, we don't have a solution for this ourselves, though I'm curious what solutions you've seen and used. Our forms are tied deeply to Angular, so other modules might not behave in a way that our forms can understand.

There is a need to build a demo of this where you create a FormArray validator that handles the validation. I did some work on this a long time ago, but it was something that an application would build and not Clarity, so its not in our documentation. That said, we could do something in our docs with a simple demo to get folks started.

You can see some of the work here, though I recall there being some issues to work out https://github.com/vmware/clarity/blob/v1/src/dev/src/app/checkboxes/checkboxes.demo.ts.

**Comment by raijinsetsu** [comment] 2019-06-11 01:01
Well, there are two issues here:
1) The documentation shows non-working examples of multiple checkbox
setups. This is misleading and I wasted several hours figuring out what I
was doing wrong when I hadn't even checked if the example worked correctly.
It really looks like the checkbox example is just a clone of the radio
example and while the radio examples work correctly, this is not true for
the checkboxes.
2) If we had a way to bind a control to which ever component controls
whether or not the clr-control-error element appears, that would solve our
primary issue. The rest of it is really an Angular issue and that can be
worked around.

I understand that Clarity and Angular can not take every possible layout
into account, but the primary issue is that we cannot display errors like
in other inputs without reverse engineering the markup and styles applied
by the Clarity components and then putting all that boiler plate into our
templates.

**Comment by gnomeontherun** [comment] 2019-06-11 13:57
Yes 

1) is a problem that I swear we fixed more than once now, fixing it again. 
2) The problem is inconsistent behaviors with Angular forms, Template Driven don't support FormArray  (https://github.com/angular/angular/issues/9615). We've been hesitant to build a feature which requires one of the form solutions provided by Angular to date. 

I'm going to leave this open as a feature and website docs issue, we might be able to build this in directly. Here is a workaround I just setup quick that shows how it could work (though its not ideal).

https://stackblitz.com/edit/clarity-form-checkbox-formarray-group-validation-workaround?file=src/app/app.component.html

**Comment by raijinsetsu** [comment] 2019-06-12 22:52
Re #2:
Completely understand. Having Angular support FormArray in the template
would be HUGE. We actually have our own component for this because Angular
does not.

The issue is that we can't trigger Clarity's clr-control-error component to
display without implementing that ourselves and updating it anytime Clarity
changes a style. For this, would you be opposed to adding a binding to the
clr-control-error component to allow developers to trigger it's display,
allowing us developers to override it's default behavior? I would not mind
submitting a PR for that. Example (modifying your linked example):
      <form clrForm>
<clr-checkbox-container [formGroup]="controls"
[class.clr-error]="controls.touched
&& controls.invalid">
<label>Which voice assistant do you use?</label>
<clr-checkbox-wrapper formArrayName="devices" *ngFor="let device of
devices; let i = index">
<label>{{device}}</label>
<input type="checkbox" clrCheckbox [formControl]=
"controls.get('devices').at(i)" />
</clr-checkbox-wrapper>
<clr-control-helper *ngIf="controls.touched && controls.invalid">You must
select at least one option</clr-control-helper>
<clr-control-error [clrShow]="controls.get('devices').errors">ERROR TEXT
GOES HERE</clr-control-error>
</clr-checkbox-container>
      </form>

**Comment by gnomeontherun** [comment] 2019-06-13 14:20
I'm certainly happy to take a contribution and greatly appreciate that mode of thinking! I'd like to suggest a slightly different approach so its more generic. I can think of other cases where people might put more than one control into container and need to validate them together (like you might have 2 inputs for a credit card month/year expiration). I'd like @coryrylan to review this idea before we fully sign off on it.

In this case, my basic theory is that there may be cases where someone should be able to tell the container if it is in an error state or not. If they opt into setting a new input `clrControlError` and passing a boolean to tell when to show the error. Then internally, if this value is present the container will no longer look at the validity of the NgControl but just use the boolean provided. There are three main places where that would be needed, in the container template (which sets `.clr-error`), in the `clr-control-helper` and in the `clr-control-error`. 

```
<clr-checkbox-container [clrControlError]="controls.touched && controls.invalid" [formGroup]="controls">
...
</clr-checkbox-container>
```

My only additional thought here is that `clrControlError` could take a string as well, and that would allow you to set different types of error messages so that `<clr-control-error *clrIfError="'minimum'">` type validation would still work.

**Comment by gnomeontherun** [comment] 2021-02-01 21:22
Angular still doesn't provide this functionality so we are limited in what we can do here. In an effort to help clean up our backlog, I'm going to close this request largely as blocked by Angular and might not require us to do additional work if it is supported. We can revisit the notion in the future if necessary if Angular makes it available.

**Closed by gnomeontherun** 2021-02-01 21:22 UTC
Labels: component: forms, type: enhancement, type: website
