### ISSUE TITLE
clrDisabled on clrDropdownItem still emits click events

### ISSUE THREAD

**Issue by sylvaingirardbe** [vmware/clarity#5626] opened 2021-02-18 09:36 UTC
## Describe the bug

We have a directive that sets the disabled attribute on controls based on metadata on the object we're displaying. 

First of all, this didn't work on `clrDropdownItem` which is really inconvenient and we needed to hack around that with the `clrDisabled` property. 

Second, after having implemented that, it appeared that users were still able to click the button since it's not actually disabled. This, in my opinion, is a bug since a disabled control should be just disabled and not emitting events.

Our `clrDropdownItem` look like this
```
<button
    clrDropdownItem
    [clrDisabled]="getActionMetaData(truckDossier.actionMetaData, 'CanCloseOrderItem')"
    [agidensActionMetadata]="truckDossier.actionMetaData"
    [actionName]="'CanCloseOrderItem'"
    [translationKeyPrefix]="'handling.truckDossier.actionMetaData.messageCodes'"
    (click)="openConfirmCloseDialog(truckDossier)">
    {{ 'handling.truckDossier.menu.close' | translate }} 
</button>
```
while they should look like this, ideally
```
<button
    clrDropdownItem
    [agidensActionMetadata]="truckDossier.actionMetaData"
    [actionName]="'CanCloseOrderItem'"
    [translationKeyPrefix]="'handling.truckDossier.actionMetaData.messageCodes'"
    (click)="openConfirmCloseDialog(truckDossier)">
    {{ 'handling.truckDossier.menu.close' | translate }} 
</button>
```

## How to reproduce

[https://stackblitz.com/edit/clarity-v4-dark-theme-eughli](Stackblitz)

## Expected behavior

Not emit click when disabled and it would be nice to just respect a disabled attribute instead of that hideous clrDisabled.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [x] Angular

**Framework version:**
Angular 9 & 11

**Comment by bbogdanov** [comment] 2021-02-19 18:25
Hi @sylvaingirardbe,

The `disabled` attribute seems to work as expected. 

https://stackblitz.com/edit/clarity-v4-dark-theme-yver8f?file=src%2Fapp%2Fapp.component.html

Line 20

I'm going to close it cause it is not a bug from our side.

**Closed as completed by bbogdanov** 2021-02-19 18:25 UTC
Labels: type: support, @clr/angular, component: button
