### ISSUE TITLE
Double-Clicking Datagrid Column Handle Should Resize Column to Fit Content

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1773] opened 2017-12-13 15:17 UTC
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
On a data grid header, where the column can be resized, double clicking should resize to fit the content.

### Actual behavior
Double clicking does nothing.

### Reproduction of behavior
This is best demonstrated in either Google Sheets or Excel. They both display the same functionality.

**Comment by mathisscott** [comment] 2018-01-31 15:23
@youdz 
Thoughts?

**Comment by youdz** [comment] 2018-01-31 15:44
I believe double-clicking is a pattern we will not implement for web applications, so this feature would never be implemented. On top of this, this feature feels very "spreadsheet" to me, which is different from what we're doing with the datagrid, especially knowing that columns are _already_ sized to fit the content on initial rendering.

I'll wait for UX confirmation before closing. cc @mathisscott, @reddolan

**Comment by mathisscott** [comment] 2018-01-31 15:45
+1

**Closed by mathisscott** 2018-01-31 15:45 UTC
Labels: ClarityNG, enhancement

**Comment by reddolan** [comment] 2018-02-02 00:04
I agree with @youdz and @mathisscott on this. Looks like the issue is already closed
