### ISSUE TITLE
Documentation for v0.10 broken

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#1906] opened 2018-02-01 15:03 UTC
Go to https://vmware.github.io/clarity/documentation/v0.10/
Try to navigate in left menu - broken.

**Comment by mathisscott** [comment] 2018-02-01 15:06
@ph55 
This works for me. What browser are you using?

**Comment by ph55** [comment] 2018-02-01 15:20
@mathisscott Chrome latest - Version 63.0.3239.132 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/1386622/35686101-25ea58c8-0774-11e8-836a-d90476c37295.png)

**Comment by mathisscott** [comment] 2018-02-01 15:31
Hmm. I can see that error (just one of them). But the site still works for me. Any other ideas on how to reproduce this?

**Comment by ph55** [comment] 2018-02-01 15:33
You mean this URL works for you as well ?
https://vmware.github.io/clarity/documentation/v0.10/datagrid/custom-filtering

**Comment by SayakMukhopadhyay** [comment] 2018-02-01 15:35
I am getting the same errors too. Firefox latest here.

**Comment by mathisscott** [comment] 2018-02-01 15:36
@ph55 
That URL doesn't work for me.

**Comment by ph55** [comment] 2018-02-01 15:36
Also tried in incognito - same thing.
Have you tried in incognito ? Maybe works for you because of cache...

**Comment by gnomeontherun** [comment] 2018-02-01 15:36
I'm seeing it, and will take a look for today's release.

**Comment by mathisscott** [comment] 2018-02-01 15:44
@gnomeontherun 
Please feel free to pull in anyone else you need to on this. It's #1 priority and then some.

@ph55 
Thanks for bringing this to our attention.

**Comment by gnomeontherun** [comment] 2018-02-02 00:08
Fixed in website, thanks for catching it. It was relative links in 0.10 branch that were not quite right.

**Closed by gnomeontherun** 2018-02-02 00:08 UTC
Labels: Critical, WEB, bug
