### ISSUE TITLE
When Drop down menu has no items empty drop down is shown throwing an console error

### ISSUE THREAD

**Issue by jeevanm18** [vmware/clarity#5312] opened 2020-11-18 05:47 UTC
## Describe the bug

when drop down menu doesnt have any items it shows the empty drop down menu by throwing the console error
Cannot read property ‘disabled’ of undefined.So in some scenarios menu items wont be there since  api returns null. so at that time when the user clicks on drop down button menu should be not shown.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-xedwjs?file=src%2Fapp%2Fapp.component.html

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-xedwjs?file=src%2Fapp%2Fapp.component.html
2.  Click on dropdown
3.  open the console log
4.  See error Cannot read property ‘disabled’ of undefined also empty drop drop down in shown

## Expected behavior
empty drop drop down should not be shown

## Versions

**App**

- Angular: [8]
- Node: [12]
- Clarity: [2]

**Device:**

- Type: [MacBook]
- OS: [iOS]
- Browser [chrome, safari]
- Version [84]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2020-11-18 23:20
I believe the issue is here https://github.com/vmware/clarity/issues/3610#issuecomment-510701613 because we have to move focus into the menu to comply with accessibility needs. If there is nothing in the menu to focus on, this error would be thrown and cause problems. If a menu has no items, you will either need to provide a default backup menu item, or disable the menu to prevent this. 

Closing as a duplicate from the above issue with a workaround.

**Closed as completed by gnomeontherun** 2020-11-18 23:20 UTC
