### ISSUE TITLE
Two Custom filters in Datagrid, can not get correct state.filters

### ISSUE THREAD

**Issue by ThinkontrolSY** [vmware/clarity#303] opened 2017-01-02 05:14 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I have two customer filter in datagrid,
```typescript
import { Component, OnInit, Input } from '@angular/core';
import {Filter, DatagridFilter} from "clarity-angular";
import {Subject} from 'rxjs';
@Component({
    selector: 'string-search',
    template: `
        <input type="text" placeholder="Customer Name" (change)="search($event)">
    `
})
export class StringSearchWidget implements OnInit, Filter<any> {
    @Input() property;
    private value;
    constructor(private filterContainer: DatagridFilter) {
        filterContainer.filter = this;
    }

    ngOnInit() { }
    changes = new Subject<any>();
    isActive():boolean {
        return this.value ? true : false;
    }
    accepts(item: any){
        // return (this.trueSelected && item['customer'] && item['customer']['openid']) || (this.falseSelected && (!item['customer'] || !item['customer']['openid']))
        return true;
    }
    search(event){
        if(event.target.value){
            this.value = { $search: event.target.value };  
        }else{
            this.value = null;
        }
        this.changes.next(true);
    }
}
```
```typescript
import { Component, OnInit, Input } from '@angular/core';
import {Filter, DatagridFilter} from "clarity-angular";
import {Subject} from 'rxjs';
@Component({
    selector: 'true-false-filter',
    template: require('./true-false-filter.template.html')
})
export class TrueFalseFilterWidget implements OnInit, Filter<any> {
    private trueSelected = false;
    private falseSelected = false;
    @Input() property;
    private value = {};
    constructor(private filterContainer: DatagridFilter) {
        filterContainer.filter = this;
    }

    ngOnInit() { }
    changes = new Subject<any>();
    isActive():boolean {
        return this.trueSelected || this.falseSelected;
    }
    accepts(item: any){
        // return (this.trueSelected && item['customer'] && item['customer']['openid']) || (this.falseSelected && (!item['customer'] || !item['customer']['openid']))
        return true;
    }
    filter(s: boolean){
        let filter = [];
        if(s){
            this.falseSelected = false;
            this.trueSelected = !this.trueSelected;
        }else{
            this.trueSelected = false;
            this.falseSelected = !this.falseSelected;
        }
        if(this.trueSelected){
            this.value = { $ne: null };
        }
        if(this.falseSelected){
            this.value = { $eq: null };
        }
        this.changes.next(true);
    }
}
```
```html
<clr-datagrid (clrDgRefresh)="refresh($event)" [clrDgLoading]="loading">
    <clr-dg-column [clrDgField]="'thinkBoxId'">box ID</clr-dg-column>
    <clr-dg-column>Device ID</clr-dg-column>
    <clr-dg-column>User Name
        <clr-dg-filter [clrDgFilter]="mySearchText">
            <string-search #mySearchText [property]="'$text'"></string-search>
        </clr-dg-filter>
    </clr-dg-column>
    <clr-dg-column>Open ID
        <clr-dg-filter [clrDgFilter]="colorFilter">
            <true-false-filter #colorFilter [property]="'customer.openid'"></true-false-filter>
        </clr-dg-filter>
    </clr-dg-column>
    <clr-dg-column [clrDgField]="'customer.expireDate'">Expire Date</clr-dg-column>
    <clr-dg-placeholder>We couldn't find any boxs!</clr-dg-placeholder>
    <clr-dg-row *ngFor="let box of boxs">
        <clr-dg-cell><a (click)="goto(box)">{{box?.thinkBoxId}}</a></clr-dg-cell>
        <clr-dg-cell>{{box?.deviceId}}</clr-dg-cell>
        <clr-dg-cell>{{box?.customer?.name}}</clr-dg-cell>
        <clr-dg-cell><span class="color-square" [style.backgroundColor]="openidColor(box)"></span></clr-dg-cell>
        <clr-dg-cell>{{box?.customer?.expireDate | date}}</clr-dg-cell>
    </clr-dg-row>

    <clr-dg-footer>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{total}} boxs
        <clr-dg-pagination #pagination [clrDgTotalItems]="total"></clr-dg-pagination>
    </clr-dg-footer>
</clr-datagrid>
```
```typescript
refresh(state: State) {
        this.loading = true;
        let query:{[prop:string]: any} = {};
        if (state.filters) {
            for (let filter of state.filters) {
                let {property, value} = <{property: string, value: any}>filter;
                query[property] = value;
            }
        }
        console.log(state, query)
    }
```

I want these two customer filters give me two separated element in state.filters. But it isn't

### Actual behavior

I can not get filter element in state.filters when I active the first customer filter, but I got two copy of same filter element in state.filters when I activated the second one.

If I deleted the second one, the first one works well.

It seams like only on customer filter can work at the same html template.

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.0

* **OS and version:** ubuntu 16.04.1

* **Browser:** Chrome 55.0.2883.87 64-bit

**Comment by hippee-lee** [comment] 2017-01-17 20:00
Hi @ThinkontrolSY ,

I have tried to recreate your issue with the information you provided but am having some trouble.
If I understand the issue you have two custom filters: true-false-filter and string-filter but you are getting two copies of the same filter in your filters._all for the datagrid component. 

I have tried to recreate this issue on my clarity fork here: https://github.com/hippee-lee/clarity/tree/issue/303. When you run the project there is a datagrid/two-custom-filters link where I am debugging this issue.

When I debug the two-custom-filters code, 
I am able to 1) See both custom filters in the filters._all collection for datagrid and able to break when the user changes the contents of either the IdFIlter or the CustomNameFilter while they are both active.

 If this is different from your use case can you post a simple repo that recreates the issue as you are experiencing it? It would help me understand better.

**Comment by hippee-lee** [comment] 2017-01-23 17:17
Closing this for now as unable to reproduce.

**Closed by hippee-lee** 2017-01-23 17:17 UTC
Labels: ClarityNG

**Comment by JoshuaNitschke** [comment] 2019-04-09 00:23
@hippee-lee I have the exact same problem and found this issue via google.  I'll create a stackblitz - would you prefer for me to link to it in a comment on this existing issue and you will reopen the issue, or should I make a brand new issue and reference this one?
