### ISSUE TITLE
Card text with bigger font-size set overflows the parent div height

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#5260] opened 2020-11-03 18:48 UTC
## Describe the bug

Card text with bigger font-size set overflows the parent div height. The parent div does not seem to wrap around the increased font size.

![image](https://user-images.githubusercontent.com/4148643/98027726-63a38100-1e0d-11eb-860a-02bc95b04378.png)

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-tq2p1g?file=src/app/app.component.html

```
<div class="card">
	<div class="card-block">
		<h4 class="card-title">Count</h4>
		<div class="card-text text-center">
			<div style="font-size: 200px; color: rgb(98, 164, 32);">5</div>
		</div>
	</div>
</div>
```

## Expected behavior

The bigger text should expand the parent div.

## Versions

**App**

- Angular: 10.0.1
- Node: n/a
- Clarity: 4.0.5

**Device:**

- Type: n/a
- OS: Windows 10
- Browser: Chrome
- Version: 86

**Comment by gnomeontherun** [comment] 2020-11-03 20:13
Hi there @wokis, this is not a bug with Clarity as this could be a problem anywhere you have a large font with a small line-height. You need to also update the line-height if you increase the font size. Also, we suggest you use `rem` values instead so that sizes are more responsive to user zoom and settings.

```
<div style="font-size: 200px; line-height: 200px; color: rgb(98, 164, 32);">5</div>
```

Closing as not an issue but easily resolved in implementation.

**Closed as completed by gnomeontherun** 2020-11-03 20:13 UTC
Labels: resolution: no fix needed
