### ISSUE TITLE
Checkbox cannot be seen in modal.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#301] opened 2016-12-30 09:27 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Showing checkbox tag in modal with Clarity styles.

### Actual behavior

Checkbox tag cannot be seen in modal. 
It should be a bug.

### Environment details

* **Angular version:** 2.2.3

* **Clarity version:** 
clarity-angular: 0.7.5
clarity-icons: 0.7.5
clarity-ui: 0.7.5
* **OS and version:** 
OS X
* **Browser:** [all | Chrome 55 ]

**Comment by jaffoneh** [comment] 2016-12-30 12:47
@wknet123 thanks for reporting an issue. Do you mind including more information including a plnkr using the clarity template if possible? That would help us reproduce this issue: https://plnkr.co/edit/VPxyl7?p=preview

**Comment by wknet123** [comment] 2017-01-03 03:15
I found it only disappeared when it does not follow with a label tag, I think this is a limitation. 
e.g.
&lt;div class="checkbox-inline"&gt;
     &lt;input type="checkbox" id="create_project_public"&gt;
    &lt;abel for="create_project_public"&gt;&lt;/label&gt;
&lt;/div&gt; , looks fine.
but,
&lt;div class="checkbox-inline"&gt;
    &lt;input type="checkbox" id="create_project_public"&gt;
&lt;/div>
for this, it's disappeared.
BTW, I found the plnkr link you provided is not available since some reference libs does not exist.

**Comment by adityarb88** [comment] 2017-01-03 18:33
@wknet123: Yes you definitely need the label inside of the checkbox because Clarity has custom checkboxes and they are generated by adding styles to the pseudo elements in the label. If you have no text in the checkbox you still have to use an empty label.

Thanks for reporting the plnkr issue. @hippee-lee is taking a look at it.

I am closing this issue but please feel free to reach out if you face any other issues.

**Closed by adityarb88** 2017-01-03 18:33 UTC

**Comment by hippee-lee** [comment] 2017-01-03 19:47
Howdy @wknet123.
I created a new plunkr that uses the latest (v0.8.0) version of clarity here: https://plnkr.co/edit/8TwwdL?p=preview

I'll update the docs asap but am posting it here if you need it.
