### ISSUE TITLE
Datagrid no bottom border

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#532] opened 2017-02-25 15:42 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid should have a bottom border when summary panel is removed.

### Actual behavior
When no summary is provided, the datagrid has an awkward look. There's no border on the bottom of the grid.

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Jinnie** [comment] 2017-02-25 21:27
Hi @whizkidwwe1217,
Could you please provide a screenshot, or a plunker reproducing the problem?
I've been working with the datagrid for a while now, and the only "awkward" border issues that I've observed were when my browser was accidentally set to 90% Zoom.
 
Here's the plunker template you can use: https://plnkr.co/8TwwdL

**Comment by youdz** [comment] 2017-02-27 15:19
We actually know about this. Duplicate of #217, should be fixed as part of #511.

That said, you should look at the last comment of #217, which states that we do not recommend (and will probably not go out of our way to support) datagrids without a footer. Right now it only contains pagination information but we have already several planned features, like column selection, which intend to use the remaining space.

**Comment by jaffoneh** [comment] 2017-02-27 16:55
Considering the last comment, this is a duplicate

**Closed by jaffoneh** 2017-02-27 16:55 UTC
Labels: duplicate
