### ISSUE TITLE
Combobox Single Select: Shows only selected item in combobox, and there is no clear button to clear the drop down. 

### ISSUE THREAD

**Issue by zoom2ashish** [vmware/clarity#5724] opened 2021-03-12 19:34 UTC
Clarity v4:

If combobox has long list of items and one item is already selected, then it shows only selected item in combobox content. To see all the items in SingleSelect mode, user has user has to press "backspace" keys (or select entire text and delete) to clear the combobox search textbox and load the all the items in dropdown content.

combobox need to have clear button to set currently selected item, and load the combobox content with all the items.

**Comment by coryrylan** [comment] 2021-03-12 22:07
This behavior can be replicated https://v4.clarity.design/documentation/combobox Marking as needs UX input so we make sure to have the correct behavior with the single select vs multi-select.

![Screen Shot 2021-03-12 at 4 07 19 PM](https://user-images.githubusercontent.com/2021067/111003588-0ab0a000-834d-11eb-9827-2ac9dcea6012.png)

![Screen Shot 2021-03-12 at 4 07 53 PM](https://user-images.githubusercontent.com/2021067/111003636-1f8d3380-834d-11eb-9a21-bf6aa57a4a92.png)

**Comment by Jinnie** [comment] 2021-03-15 21:49
This is the official W3C ARIA pattern.
Duplicate of https://github.com/vmware/clarity/issues/5589

**Comment by Jinnie** [comment] 2021-03-15 21:50
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

**Closed as completed by Jinnie** 2021-03-15 21:49 UTC
Labels: resolution: duplicate, needs: ux input
