### ISSUE TITLE
Server-Driven Datagrid Error

### ISSUE THREAD

**Issue by ThinkontrolSY** [vmware/clarity#1039] opened 2017-06-13 03:28 UTC
**Select one ...**  (check one with "x")
```
[*] bug
[ ] feature request
[ ] enhancement
```
### clrDgLoading input get an error:
```
UserComponent.html:6 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.
    at viewDebugError (core.es5.js:8507)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8485)
    at checkBindingNoChanges (core.es5.js:8649)
    at checkNoChangesNodeInline (core.es5.js:12502)
    at checkNoChangesNode (core.es5.js:12476)
    at debugCheckNoChangesNode (core.es5.js:13251)
    at debugCheckDirectivesFn (core.es5.js:13153)
    at Object.View_UserComponent_0._co [as updateDirectives] (UserComponent.html:6)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13135)
    at checkNoChangesView (core.es5.js:12296)
```

### HTML
```html
<div class="content-container">
  <main class="content-area">
    <h1>
      User List
    </h1>
    <clr-datagrid (clrDgRefresh)="refresh($event)" [clrDgLoading]="dataloading">
      <clr-dg-column>Name</clr-dg-column>
      <clr-dg-column>Full Name</clr-dg-column>
      <clr-dg-column>Role</clr-dg-column>
      <clr-dg-placeholder>We couldn't find any user!</clr-dg-placeholder>
      <clr-dg-row *clrDgItems="let user of users | async">
        <clr-dg-cell>{{user.username}}</clr-dg-cell>
        <clr-dg-cell>{{user.fullName}}</clr-dg-cell>
        <clr-dg-cell>{{user.role}}</clr-dg-cell>
      </clr-dg-row>

      <clr-dg-footer>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} of {{total | async}} users
        <clr-dg-pagination #pagination [clrDgTotalItems]="total | async" [clrDgPageSize]="pageSize"></clr-dg-pagination>
      </clr-dg-footer>
    </clr-datagrid>
  </main>
</div>
```

### Angular script
```typescript
import { Component, OnInit } from '@angular/core';
import { URLSearchParams } from '@angular/http';
import { BoxServiceService } from '../../box-service.service';
@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.css']
})
export class UserComponent implements OnInit {
  users;
  dataloading = false;
  pageSize = 10;
  lastPage;
  total;
  constructor(private _bs: BoxServiceService) { }

  ngOnInit() {
  }
  refresh(event) {
    if (!event) {
      return;
    }
    console.log(event)
    const state = {
      limit: event.page.size,
      skip: event.page.from
    };
    if (event.sort) {
      const sort = {};
      sort[event.sort.by] = event.sort.reverse ? 1 : -1;
      state['sort'] = sort;
    }
    if (event.filters) {
      const query = {};
      for (const filter of event.filters) {
        query[filter.property] = typeof filter.value === 'string' ? { $regex: filter.value } : filter.value;
      }
      state['query'] = query;
    }
    console.log(state)
    this.total = this._bs.getUserCount();
    this.dataloading = true;
    this.users = this._bs.getUserList(state);
    this.users.subscribe({
      error: val => this.dataloading = false,
      next: val => { this.dataloading = false; console.log(val); }
    });
    this.lastPage = event;
  }
  onDelete(user) {
    console.log(user)
  }
}
```

### Environment details

* **Angular version:** 
```
├─┬ @angular/animations@4.2.2
├─┬ @angular/cli@1.0.0
├─┬ UNMET PEER DEPENDENCY @angular/common@4.2.2
├─┬ @angular/compiler@4.2.2
├─┬ @angular/compiler-cli@4.2.2
│ ├─┬ @angular/tsc-wrapped@4.2.2
├─┬ UNMET PEER DEPENDENCY @angular/core@4.2.2
├─┬ @angular/forms@4.2.2
├─┬ @angular/http@4.2.2
├─┬ @angular/platform-browser@4.2.2
├─┬ @angular/platform-browser-dynamic@4.2.2
├─┬ @angular/router@4.2.2
```

* **Clarity version:** 
```
├── clarity-angular@0.9.8
├─┬ clarity-icons@0.9.8
├── clarity-ui@0.9.8
```

* **OS and version:**  ubuntu 16.04

* **node version:**  v6.10.2

* **Browser:**  Chromium Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by ThinkontrolSY** [comment] 2017-06-13 03:57
![image](https://user-images.githubusercontent.com/11331554/27065330-13c880c2-502f-11e7-914c-e6609fcee2c2.png)

**Comment by mathisscott** [comment] 2017-06-21 21:42
@ThinkontrolSY : I'm marking this as a duplicate of #1040

**Closed by mathisscott** 2017-06-21 21:42 UTC
