### ISSUE TITLE
stepper re-opens first step window when clicking next on a later step

### ISSUE THREAD

**Issue by dpcamp** [vmware/clarity#4223] opened 2020-01-21 18:48 UTC
## Describe the bug
After first step form is completed, when clicking next on step 3, step 1 will open along with step 4. If required fields are edited to be not required, and form is not filled out at all, step 1 will always open along with the next step. 
## How to reproduce
Working code here:
https://stackblitz.com/edit/clarity-light-theme-v2-graock

1.  fill out step 1 form (only first and last name are required atm)
2.  Click next and complete step 2 form. 
3.  Click next and complete step 3 form. 
4.  Step one re-opens along with step 4. 

## Expected behavior

step 1 should stay closed when clicking next on step 3. 

## Versions

**App**

* Angular: [e.g. 8]
* Node: 10
* Clarity: 2

**Device:**

* Type: PC
* OS: Windows 10
* Browser chrome
* Version [e.g. 22]

## Additional notes

Not sure if this is a bug or something wrong with my code, but I've looked at the code till blue in the face and not seeing much difference other than using ngModel along with FormControlName in the input fields.

**Comment by dexfab** [comment] 2020-03-05 12:01
Same issue happens to us but only since we upgraded to Clarity 3.0.0. Could this be looked at as it's a bit of a blocker for us to upgrade to 3.

**Comment by martinbrom** [comment] 2020-04-06 07:54
It seems to be fixed with version 3.1.0, probably a duplicate of https://github.com/vmware/clarity/issues/4353.

**Comment by gnomeontherun** [comment] 2020-04-17 16:14
Tagging @bdryanovski to see if the fix from #4353 solves this in v2 and if so to backport it.

**Comment by gnomeontherun** [comment] 2020-04-23 20:06
This should be resolved in the latest release. Thanks!

**Closed by gnomeontherun** 2020-04-23 20:06 UTC
