### ISSUE TITLE
When a datagrid filter is applied, the aria-label of filter button should be updated to reflect the filter state change.

### ISSUE THREAD

**Issue by lf-collins** [vmware/clarity#4347] opened 2020-03-06 07:08 UTC
## Describe the bug

When using a data-grid column filter, the filter button is highlighted, so we can see and notice that the filter is applied. But for screen reader users, they cannot see the highlighted filter icon and cannot know the filter status. The filter button should be updated to reflect the change in the status of the filter button. For example, we can change its aria-label from "Toggle Column Filter" to "Edit Column Filter".

## How to reproduce

It can be reproduced here: https://clarity.design/documentation/datagrid/built-in-filters

1.  Go to https://clarity.design/documentation/datagrid/built-in-filters
2.  Screen reader reads the same string regardless of whether the column filter is applied.

## Expected behavior

Screen reader should be able to know if a column filter is applied or not.

## Versions

**Device:**

* Browser [Chrome]
* Screen reader [NVDA]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2021-02-01 22:49
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:49 UTC
Labels: @clr/angular, component: datagrid, needs: accessibility input, priority: 2 medium-low, status: needs triage, type: accessibility
