### ISSUE TITLE
The expand/collapse icon of vertical nav group is not centered

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#5764] opened 2021-03-23 04:34 UTC
Clarity Version: 5

When using a  vertical nav groups, its icon not center-aligned when expanded
![navgroup](https://user-images.githubusercontent.com/50942719/112092867-642d9000-8bd3-11eb-8414-335c1911e2df.gif)

Reproduction:
Use the v5 stackblitz and use the sample code from the Vertical Nav Group documentation:
https://clarity.design/angular-components/vertical-nav/#verticalnav-groups

or from someone's stackblitz: https://stackblitz.com/edit/clarity-nav?file=package.json

**Comment by mathisscott** [comment] 2021-03-23 13:56
I believe this is a duplicate of #5644 

@Jinnie is looking into that already.

**Closed as completed by mathisscott** 2021-03-23 13:56 UTC
Labels: resolution: duplicate
