### ISSUE TITLE
Caret position does not increase when typing `

### ISSUE THREAD

**Issue by sjcetx** [vmware/clarity#1911] opened 2018-02-02 11:22 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Caret position to increase when typing ` character

### Actual behavior
When typing \` the caret position does not increase, subsequent presses of  \` will draw over the original one.  
Can be tested on your own example site
https://vmware.github.io/clarity/documentation/v0.11/input-fields

I have tested it in chrome and firefox

**Comment by adityarb88** [comment] 2018-02-02 16:59
@sjcetx: This looks like a duplicate of #1521. Please subscribe to that issue for more updates. Thanks!

Closing this as duplicate.

**Closed by adityarb88** 2018-02-02 16:59 UTC
