### ISSUE TITLE
I need a calendar and date-time picker to start a task on a given time and date

### ISSUE THREAD

**Issue by blackdust21** [vmware/clarity#599] opened 2017-03-15 03:08 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
I was not able to find a component for datetime or calendar. If I've missed, please do share.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all ]

**Comment by Jinnie** [comment] 2017-03-15 09:46
Check and follow this issue:
https://github.com/vmware/clarity/issues/474

**Comment by blackdust21** [comment] 2017-03-15 22:05
I went through the thread and there's a chance I've misunderstood but it seems like it is under progress?
Can I use it as is? I think the Date & Time Picker would be ideal for me. 

Is it possible to share a code snippet of using it. Thank you

    use when the user needs to input a date and time value for something
    has all of the normal functionality of Date and Time Picker combined into one
    used with one input field
    updating either component will update the value in the input field

**Comment by roeeovadia** [comment] 2017-03-21 09:14
When are you going to release this feature?

**Comment by jaffoneh** [comment] 2017-03-21 16:27
This seems a duplicate of #474. Closing based on that.

**Closed by jaffoneh** 2017-03-21 16:27 UTC
