### ISSUE TITLE
Stepper component in clarity

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#1708] opened 2017-11-22 05:21 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
Stepper provides a wizard-like workflow by dividing content into logical steps.
This will be useful for building Getting Started pages for the product.

Can we get a stepper component in clarity like one in angular-material?
https://material.angular.io/components/stepper/overview

Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.x

* **OS and version:** 

* **Browser:** [all  ]

**Comment by adityarb88** [comment] 2017-11-22 14:22
@shravansofts: I believe this is a duplicate of: https://github.com/vmware/clarity/issues/1633

Please subscribe to the above issue for more updates. Closing this one as a duplicate.

**Closed by adityarb88** 2017-11-22 14:22 UTC
