### ISSUE TITLE
Sticky / Collapsable side menu

### ISSUE THREAD

**Issue by mooreaa** [vmware/clarity#1050] opened 2017-06-13 19:33 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior
Should have a way to get side menu to collapse and stay small even on larger screens (see wordpress behavior). In apps where content matters more, the sidenavs shouldn't take over the screen. 

Similarly, when expanding the burger menu, an option should allow for the sidebar to expand without obscuring main content.

### Actual behavior
https://vmware.github.io/clarity/documentation

### Reproduction of behavior
https://vmware.github.io/clarity/documentation

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-06-13 19:36
@mooreaa 

I believe this is a duplicate of #1001 

Please reopen if you feel that assessment is incorrect.

**Closed** 2017-06-13 19:37 UTC
Labels: duplicate
