### ISSUE TITLE
[Datagrid] Ability to provide custom inline markup for column filters

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#1801] opened 2017-12-21 01:57 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
I would like a way to provide custom markup for the clr-dg-column component that will allow for filtering inline (underneath the column header for example) rather than putting the filter content inside of the clr-dg-filter popup. The filter would work just like the current built-in filters and custom filters, but would always be visible to the user. I'm not sure if this is already possible?

The use case is so that users can easily see which filters are active and the value for each of them without having to have multiple filter popups open at the same time (and possibly overlapping each other). I've also asked this question on [StackOverflow](https://stackoverflow.com/questions/47915913/clarity-clr-datagrid-use-custom-filter-markup-but-retain-built-in-functionality) in case it's already possible.

### Actual behavior
Currently the only way to provide a custom filter puts the provided markup inside of the clr-dg-column component and is hidden until the user clicks the filter icon.

**Comment by mathisscott** [comment] 2017-12-21 16:02
Hi @jbgarr 
[Would you consider this feature request to be a duplicate of the linked issue?](https://github.com/vmware/clarity/issues/1632)

**Comment by jbgarr** [comment] 2017-12-21 17:16
Hi @mathisscott,

Thanks for your reply. I did see that issue before I wrote up mine, and I think they are different issues that are related to a similar problem. I would like to simply be able to wire up any custom markup to built in functionality that the Clarity data grid provides. I think/hope my request would be much easier to deliver than the other proposed issue. Here's what I have in mind:

![screen shot 2017-12-21 at 9 15 23 am](https://user-images.githubusercontent.com/3316981/34266851-8aa7bb36-e62f-11e7-9189-3ee4ef94dd4e.png)

**Comment by mathisscott** [comment] 2017-12-21 19:41
I will leave this open for @youdz to comment on it. There are product teams inside of VMware that have this sort of meta-filter input field. I don't know what they tie into, however.

**Comment by jbgarr** [comment] 2017-12-21 19:58
@mathisscott Hopefully we're on the same page here. I don't want to create a single input field that searches across the whole datagrid and its contents. Instead I want to provide custom content for the datagrid clr-dg-column elements and show an input inline for each column (if I have provided my own markup).

**Comment by jbgarr** [comment] 2017-12-29 16:41
Just wanted to check in here to see if there is some proposed workaround for this issue? Our users are asking for this feature in our production application, but I'm not sure the best way to move forward with it yet. I am able to provide custom markup, but tying it in with the existing sort and filter functionality provided by the data grid component is the part I'm not sure about. I want to avoid having to take an all or nothing approach where I have to roll my own sort and filter functionality if possible. Thanks for any insights you can provide.

**Comment by youdz** [comment] 2018-01-02 22:39
I don't see a way to do this right now. The entire design revolves around the little filter icon and the corresponding dropdown, and because of this the `<clr-dg-filter>` component handles all the wiring. The wiring happens with internal providers that we do not export, so you can't even try and hack it in on your side.

Maybe we could add some kind of directive that says "this is a custom filter" on something that's not necessarily our dropdown. You could then use our [DatagridPropertyStringFilter](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/built-in/filters/datagrid-property-string-filter.ts) class, which we export publicly, so that the "filtering logic" stays on our side. I haven't checked all the details, I'm hoping it can work.

But as of today, I don't see any workaround for this, sorry.

**Comment by jbgarr** [comment] 2018-01-03 16:39
Thanks for the investigation/confirmation. I was thinking that may be the case, but wasn't sure there wouldn't be some sort of workaround that you guys could suggest. I'll keep an eye on this issue then.

**Comment by gnomeontherun** [comment] 2018-07-18 23:50
We've discussed and this is largely a duplicate of #1632. It is slightly different ask, but we don't want to support multiple approaches for this problem.

**Closed by gnomeontherun** 2018-07-18 23:50 UTC
Labels: ClarityNG, Duplicate, Needs UX Input
