### ISSUE TITLE
Unexpected horizontal scrollbar appears in datagrid with clr-dg-action-overflow

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#3630] opened 2019-07-17 09:40 UTC
## Describe the bug

When `<clr-dg-action-overflow>` is used in a datagrid, at the same time the number of columns is relatively a lot, say 9, with a relatively small browser width (not too small, larger than 991px), say 1024px, the initial width calculation of the datagrid might not consider the width of `<clr-dg-action-overflow>`. As a result, a horizontal scroll bar will appear. The reason is just a guess.

## How to reproduce

In this example: https://stackblitz.com/edit/clarity-light-theme-v2-axy356 (open https://clarity-light-theme-v2-axy356.stackblitz.io/ with browser width 1024px), there are 9 columns and `<clr-dg-action-overflow>` is used, open the app with browser width 1024px, you'll see the datagrid container has the width of 961px (if there is body vertical scroll bar) while the content (datagrid-table) is 999px. The difference is exactly the width of `<clr-dg-action-overflow>` (38px). User has to scroll horizontally to see the most right content.

## Expected behavior

Horizontal scroll bar is not expected while the contents have enough space to display. 

## Versions

**App**

* Angular: [e.g. 8]
* Clarity: [e.g. 2.x]

**Device:**

* Type: MacBook
* Browser chrome
* Version 75

**Comment by hippee-lee** [comment] 2019-07-17 15:52
Thanks for reporting this. It's a duplicate of #3108 and I'll leave a comment about the root cause there. Please subscribe to that issue for updates.

**Closed by hippee-lee** 2019-07-17 15:52 UTC
Labels: Bug
