### ISSUE TITLE
clrInput won't trigger validation unless click somewhere else

### ISSUE THREAD

**Issue by KerryXuanWang** [vmware/clarity#4747] opened 2020-06-23 09:15 UTC
## Describe the bug

Hello team, i met an issue with clr input recently. If using clrInput, it won't trigger validation while type in the input, unless click somewhere else. As long as the error message appears once , it will show directly without any need to click when type something again. This issue not happens if using css input.

## How to reproduce

Here is a simple example copied from official site,  both of the two inputs need required validation:
https://stackblitz.com/edit/clarity-angular8-starter-auvjuz?file=src%2Fapp%2Fapp.component.html

1. delete the string in the input box
2. the css input will trigger validation immediately
3. the clr input won't trigger the validation for the first time, but will behave normally for the second time and later.

**App**

- Angular: 8
- Node: 12
- Clarity: 2

**Device:**

- Type: [ MacBook]
- OS: [iOS]
- Browser: [ chrome]

**Comment by gnomeontherun** [comment] 2020-06-29 14:07
Hello, this is intentional behavior. The field doesn't validate until it is blurred, otherwise it might throw errors while a user is still trying to put in the right information. For example, if you expect a zip code that is 5 numbers long and 1 number is considered invalid, it would be confusing to invalidate after the first keystroke while they are still trying to type. This is built into the Angular controls, something you can't do with the CSS only versions.

If you need to force validation on a field immediately, you can call `markAsTouched()` using Angular, and that will tell our validation to display as well.

Closing as intended behavior.

**Closed by gnomeontherun** 2020-06-29 14:07 UTC

**Comment by KerryXuanWang** [comment] 2020-06-30 01:23
Sorry, i hear you. But, the problem is it only occurs for the first time. 
Users don't need to click elsewhere for the second time or third time, just with your example, users can see the validation error at once when they type less than 5 numbers.

**Comment by gnomeontherun** [comment] 2020-06-30 02:22
Right, that is also expected. Once the field is touched, it validates in real time so once a user puts in the correct value the errors will correct immediately instead of after blur.
