### ISSUE TITLE
Error "panel is undefined " when using Clarity stepper with steps in different components.

### ISSUE THREAD

**Issue by valkanov** [vmware/clarity#5995] opened 2021-05-25 13:20 UTC
## Describe the bug

Stepper not expanding and  content not shown when using clarity stepper with different components.

```
<form clrStepper [formGroup]="form" >
  <clr-stepper-panel >
    <clr-step-title>title</clr-step-title>
    <clr-step-description>description.</clr-step-description>
    <clr-step-content *clrIfExpanded>
       content
      <button clrStepButton="next">next</button>
    </clr-step-content>
  </clr-stepper-panel>

 <a-component-containing-clarity-stepper-panel></a-component-containing-clarity-stepper-panel>

  <clr-stepper-panel >
    <clr-step-title>title</clr-step-title>
    <clr-step-description>...</clr-step-description>
    <clr-step-content *clrIfExpanded>
        content
    </clr-step-content>
  </clr-stepper-panel>
</form>
```

## How to reproduce

[stackblitz eample](https://stackblitz.com/edit/clarity-stepper-nested-components)

## Expected behavior

To be able to use steps in different components. Keeping all the steps in a single component is not scalable and reusable.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: MacBook
- Browser: any

**Comment by Jinnie** [comment] 2021-06-03 20:13
My first thought is that we don't usually support sub-elements inside user components. Instead we advise adding the user components inside the clarity sub-elements.

Looking at the code though, we do resolve the deep descendants. The problem is that we rely on the natural order of the sub-elements. And adding the sub-element to a user component breaks this natural order of discovery of content children and we get this instead:
![Screen Shot 2021-06-03 at 23 04 12](https://user-images.githubusercontent.com/1798828/120705418-7889e500-c4c0-11eb-8469-d6e05a351fd2.jpg)
`contacts` should be second. 

This can not be easily resolved in Clarity Angular with the current architecture. And even if it's achievable, this is not a pattern which we globally support inside Clarity. Most of our components will not even resolve the nested children.

So, my advice is to either try to nest your components inside the regular Clarity panels, or research a solution based on the Clarity Core Accordion, which is much more flexible for any custom case.

**Closed as completed by Jinnie** 2021-06-03 20:13 UTC
Labels: resolution: wontfix, @clr/angular, component: stepper
