### ISSUE TITLE
Prod build warnings  with clr 0.12.4

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#2465] opened 2018-07-16 03:08 UTC
**Select one ...** (check one with "x")

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

prod build without the following warnings

### Actual behavior

upgraded to clr 0.12.4 via
npm install --save @clr/angular@latest
npm install --save @clr/ui@latest
npm install --save @clr/icons@latest

Then do a ng build --prod to check form any warnings, etc and the following show up. The app still seems to run fine but unsure about these. I cannot find any of the actual referenced files - gather they may be part of the build process?

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
1107:471-494 "export 'ClrTextareaContainer' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
1108:98-121 "export 'ClrTextareaContainer' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
47:69-89 "export 'ClrTextareaModule' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
47:877-897 "export 'ClrTextareaModule' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
47:899-919 "export 'ClrTextareaModule' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
49:1252-1272 "export 'ClrTextareaModule' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
49:1274-1294 "export 'ClrTextareaModule' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
830:253-271 "export 'ClrControlError' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
831:88-106 "export 'ClrControlError' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
837:257-276 "export 'ClrControlHelper' (imported as 'i1') was not found in '@clr/angular'

WARNING in ./node_modules/@clr/angular/clr-angular.ngfactory.js
838:90-109 "export 'ClrControlHelper' (imported as 'i1') was not found in '@clr/angular'

WARNING in Invalid font values at 1766:1. Ignoring.

### Reproduction of behavior

Per above

### Environment details

* **Angular version:** 6.0.3

* **Clarity version:** 0.12.4

* **OS and version:** Win10

* **Browser:** [Edge]

**Comment by gnomeontherun** [comment] 2018-07-16 12:35
Can you reproduce this and share a github repo with it? Doing a fresh install doesn't have this error from my testing, unless there is something special you are doing. I presume you are trying to use the new textarea right?

**Comment by GaryHyland** [comment] 2018-07-18 08:51
Hmm.. Tried various step backs in versions. The "ng build --prod" errors above do not happen for 0.12.0, but happen for 0.12.4 and 0.12.3-patch.2. Can try other versions possibly if it would help to nail down but pretty hammered just now. Will hold off until 0.13 I figure and try again unless a good reason to update.
Appreciate the work you are doing people... Awesome product..  ;o)
Happy to close for now - will soon become apparent if others getting this.

**Comment by gnomeontherun** [comment] 2018-07-18 13:18
New things have been introduced since 0.12.0, notably the textarea component. If you are having an issue, then I need more details about how to reproduce it so I can verify if it is an issue with Clarity or something else. I would expect that you'd see the same issues in 0.13 so if you are able to describe or demonstrate what you've done to cause it then I can debug from there.

**Comment by GaryHyland** [comment] 2018-07-18 13:40
Yeah - I kind of figured I would really need to get a reproducible example.
I will try two approaches
- create new app from the seed and test prod build
- clone my app, upgrade, cut it back to bare basics and see whether it persists.
Not writing off that it may be my relative newby status regarding npm/node and Ng.
Will block some time out towards end of this week.
I am really wanting to use the new forms stuff - validation/helper/error stuff look nice.

**Comment by mathisscott** [comment] 2018-08-15 17:02
@GaryHyland 
Any update on this issue?

**Comment by GaryHyland** [comment] 2018-08-16 04:01
Unfortunately not yet. Had some brutal deadlines dropped on us that have had me working pretty hard. I will get to it but prob not this or next week at this stage.

**Comment by gnomeontherun** [comment] 2018-08-21 18:11
I still believe this is an issue that occurred in 0.12.3 release and has been resolved. I'm going to close this issue unless details for a reproduction of the issue can be provided.

**Closed by gnomeontherun** 2018-08-21 18:11 UTC
Labels: Awaiting More Info

**Comment by GaryHyland** [comment] 2019-02-22 03:58
Can confirm that update to 1.1.0 has no such issue.
