### ISSUE TITLE
Uncaught TypeError: Cannot set property 'ClarityIcons' of undefined'

### ISSUE THREAD

**Issue by skycoop** [vmware/clarity#3585] opened 2019-07-03 23:14 UTC
## Describe the bug

I bootstrapped a new Clarity application using the CLI and am getting the following error in the Chrome console
```
Uncaught TypeError: Cannot set property 'ClarityIcons' of undefined
    at clr-icons.min.js:formatted:912
    at clr-icons.min.js:formatted:912
```

Firefox error
```
TypeError: undefined has no properties
    <anonymous> clr-icons.min.js:1
    <anonymous> clr-icons.min.js:1
    InnerModuleEvaluation self-hosted:4430
    evaluation self-hosted:4376
```

## How to reproduce

1.  Bootstrap the project
```
$ ng new clarity-bug-test --skip-git --defaults
$ cd clarity-bug-test
$ ng add @clr/angular
$ ng serve --open # adding --prod doesn't change the behaviour
```
2. Open the dev console, error should be in the console

I [attempted to reproduce in Stackblitz](https://stackblitz.com/edit/clarity-dark-theme-v2-icon-error) by duplicating the `package.json` but I just get stuck loading forever...

## Expected behavior

There not to be an error :stuck_out_tongue: As far as I can tell nothing else is broken, icons still work correctly, but the existence of the error does cause issues

## Versions

**App**

* Angular: 8.1.0
* Node: 10.16.0
* Clarity: 2.0.1

**Device:**

* Type: Desktop
* OS: Linux x64
* Browser: Chrome, Firefox
* Version: 
  * Chrome: 75.0.3770.90 (Official Build) (64-bit)
  * Firefox: 67.0.4 (64-bit)

## Additional notes

```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0
Node: 10.16.0
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
```

**Comment by Jinnie** [comment] 2019-07-04 08:30
I could not reproduce your problem. Followed your steps 1 by 1 and I can not see any errors.
As the error refers clarity icons, I added an icon on the default page and it appears correctly.
Your stackblitz seems okay, after I click the "Install Dependencies" button it gives (only core-js needs to be downgraded to ^2.0.0)
https://stackblitz.com/edit/clarity-dark-theme-v2-icon-error-jzv99r?file=package.json

Your node version seems fine, I'm using 10.13.0, yours is 10.16.0.
What version of `npm` are you using? That's my only idea what might be going wrong.

**Comment by Devfdez** [comment] 2019-07-04 12:35
I also have the same issue, I created a new Angular 8 project, added clarity and got the issue. The icons render just fine, but I get that error on the console all the time.

**Comment by amrsalama** [comment] 2019-07-04 18:58
Same issue with me
```
Angular CLI: 8.1.0
Node: 10.16.0
OS: linux x64
Angular: 8.1.0
```

Error
```
:4200/scripts.js:43 Uncaught TypeError: Cannot set property 'ClarityIcons' of undefined
    at :4200/scripts.js:43
    at :4200/scripts.js:43
(anonymous) @ :4200/scripts.js:43
(anonymous) @ :4200/scripts.js:43
```

**Comment by rivelash** [comment] 2019-07-05 12:16
same here.

```
Angular CLI: 8.1.0
Node: 10.16.0
OS: Windows 10
Angular: 8.1.0
```

Error

```
Uncaught TypeError: Cannot set property 'ClarityIcons' of undefined
    at clr-icons.min.js:1
    at clr-icons.min.js:1
```

**Comment by gnomeontherun** [comment] 2019-07-05 15:45
I can reproduce this only with Angular CLI 8.1.0. If you have 8.0.x it works fine. 

I think this is due to https://github.com/angular/angular-cli/commit/44a0d0fb4e68d8402f223e225adfab06f504d4a7. 

See https://github.com/angular/angular-cli/issues/14952. For now, the workaround is to downgrade CLI to 8.0.6, and this seems to be affecting other global type scripts (Icons are a web component and not an Angular component).

**Comment by skycoop** [comment] 2019-07-05 15:52
That definitely looks like the issue. Thanks for finding that. I'll keep an eye on that issue for now. I'm not super eager to downgrade since then I'd have to upgrade my brand new application, and I don't notice any real issues other than broken e2e tests.

**Comment by gnomeontherun** [comment] 2019-07-05 15:54
Downgrade the CLI, not Angular. `npm install -D @angular/cli@8.0.6` should do it for your project. You should be able to run @angular/core and other libs as 8.1+.

**Comment by amrsalama** [comment] 2019-07-05 16:12
@gnomeontherun Thanks for catching the problem. I tried to downgrade @angular/cli to 8.0.6 but the problem still exists.

![Screenshot](https://user-images.githubusercontent.com/15939360/60734457-56902c80-9f50-11e9-9f7b-86b07dbc57db.png)

```
clr-icons.min.js:1 Uncaught TypeError: Cannot set property 'ClarityIcons' of undefined
    at clr-icons.min.js:1
    at clr-icons.min.js:1
```

**Comment by gnomeontherun** [comment] 2019-07-05 16:31
WORKAROUND TO DOWNGRADE.

It looks like you need to also downgrade build-angular, as this is where the actual issue lies. Unfortunately the CLI doesn't internalize this dependency so you'll have to run the following. It worked for me at least. You might have to review other CLI dependencies (like if you have ngpackagr setup) as well.

```
npm i -D @angular/cli@8.0.6 @angular-devkit/build-angular@0.800.6
```

**Comment by gnomeontherun** [comment] 2019-07-11 14:10
I just tested with Angular CLI 8.1.1, and everything works as expected. I think we can close this as fixed by Angular! 

https://github.com/angular/angular-cli/releases/tag/v8.1.1
https://github.com/angular/angular-cli/commit/67cd378138b3c40628ad87afcd967b2c98309462

Fix now is to update the CLI to latest Angular v8 release.

**Closed by gnomeontherun** 2019-07-11 14:10 UTC
Labels: Dependency Regression, High
