### ISSUE TITLE
Focus is lost after activating the finish button in the last step of the wizard using Safari

### ISSUE THREAD

**Issue by clane** [vmware/clarity#4084] opened 2019-12-04 21:39 UTC
## Describe the bug

 [Test URL]
https://clarity-light-theme-v2-a6ykys.stackblitz.io

[WCAG 2.1 Guideline]
2.4.3 Focus Order
(Level A)

[Screen Reader/Browser]
Safari Version 13.0.3 (15608.3.10.1.4)/VoiceOver

[Description]
Focus is lost after activating the finish button in the last step of the wizard.

[User Impact]
Sighted keyboard-only users and non-sighted VoiceOver users using Safari may be confused when focus is lost.

[Recommendation]
Focus should go to the Toggle button when the wizard closes when using Safari as it does with other browsers. I do not know the root cause of this issue.

## How to reproduce

1. Using the keyboard alone, or a screen reader, go to the Test URL
2. Activate the "Toggle" button
3.  Complete all the steps in the wizard and activate the Finish button.
4. Observe that focus is lost
5. Repeat the previous steps with Safari/VoiceOver and observe that you do not hear anything after activating the Finish button.

## Expected behavior
Focus should go to the Toggle button when the wizard closes when using Safari as it does with other browsers. I do not know the root cause of this issue.

## Versions

**App**

* Angular: Uknown
* Node: : Uknown
* Clarity: : Uknown

**Device:**

* Type: Any
* OS: Any
* Browser: Any
* Version: Any

## Additional notes
NA

**Comment by gnomeontherun** [comment] 2019-12-20 22:16
Safari isn't showing any focus indicators for me except on the Close button, which is very strange. I don't know the root of this one yet, but we aren't suppressing focus outline directly. Seems like we might have a Safari bug to contend with here.

**Comment by gnomeontherun** [comment] 2021-02-01 22:46
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:46 UTC
Labels: @clr/angular, component: wizard, status: backlog, status: needs investigation, type: accessibility
