### ISSUE TITLE
grid row alignment broken with a  clr-input-container

### ISSUE THREAD

**Issue by jmls** [vmware/clarity#4287] opened 2020-02-18 12:05 UTC
## Describe the bug

if you put a "clr-input-container" element inside a row it breaks the row alignment

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v2-376wfi

1.  Go to 'https://stackblitz.com/edit/clarity-light-theme-v2-376wfi'
2. layout is ok - odd focus around the input
3.  Click in the input field
4. Click outside the input fieldd
4. layout no longer alignedSee error

## Expected behavior

the row layout to retain it's alignment

## Versions

* Angular: 8
* Clarity: 2.1 (also reproduced on @next)

**Device:**

* Type:desktop
* OS: linux]
* Browser chrome 
* Version  79.0.3945.117

**Comment by martinbrom** [comment] 2020-02-19 12:35
You are using [formGroup] on the form element and formControlName on the input element without defining those in the component Typescript file. This is the cause of your issues.

You can learn more by reading this for example: [https://angular.io/guide/reactive-forms](https://angular.io/guide/reactive-forms#step-2-generating-and-importing-a-new-form-control)

**Comment by jmls** [comment] 2020-02-19 12:44
yeah, good catch - that was a typo when creating the example. 

**However**, now that I've corrected that , I still have the alignment isssus

https://stackblitz.com/edit/clarity-light-theme-v2-376wfi?file=src%2Fapp%2Fapp.component.ts

**Comment by gnomeontherun** [comment] 2020-02-19 18:52
The form controls are laying out correct and as I would expect, its the customizations around it that are causing strange behaviors. I'm honestly not sure what you are trying to do based on this demo, but you are mixing grid rows with forms (which automatically add grids) so you get a nested grid structure. I really need more detail about what you think is wrong to triage this, as while it might not look great in this demo I'm unclear what your expectations are. Technically though, it looks correct based on what you've written.

If you need a specific layout, you might need to look at our HTML/CSS formatting option for form controls instead so you can make a custom layout.

**Comment by jmls** [comment] 2020-02-20 11:55
I'm not sure what you mean about customizations ?  I'm struggling with the docs (class="row" or class="clr-row" ? ) 

https://stackblitz.com/edit/clarity-light-theme-v2-376wfi

What I want to do is have a form field, with a button aligned next to it. So I tried to use "rows" and "columns" 

Perhaps if you could explain why things are the way they are I could have a lightbulb moment.

#1 the input field is right at the bottom of the row - there's no padding or margin, so it looks a little odd

#2 I cannot get the input field to fill the column. I have tried adding "clr-col-12" on the label and field to no effect

#3 why is the button at the top of the second column ? How do I align the 2 columns so that they horizontal aligned ?

**Comment by hippee-lee** [comment] 2020-02-20 19:00
I modified the stackblitz to make it have a formfield and a button aligned to it. Its hard to know for sure if this is what you need to accomplish. Here is the stackblitz: https://stackblitz.com/edit/clarity-light-theme-v2-adgxqh

As far as explaining why things are the way they are, thats complicated and difficult. I'm sure you have experienced how a codebase evolves based on time, feedback, issues ... etc. 

Because Clarity is open source we have alot of this info in our issues and pull requests but that makes it difficult to pull together. I did some searching in our issues and here are some that migh have some of the insight that you are looking for:

1. Refactor Forms: https://github.com/vmware/clarity/issues/932
2. Forms documentation & usage: https://github.com/vmware/clarity/issues/2468
3. Research required and optional fields: https://github.com/vmware/clarity/issues/1118
4. Forms redesign implementation plan: https://github.com/vmware/clarity/issues/1878

I'm not 100% sure what the desired form for the app should look like so feel free to fork the stackblitz or share more details about the layout and visual of the form that is being build.

**Comment by gnomeontherun** [comment] 2020-02-21 23:19
By default, our Angular form controls assume a label and input, with no other things in the same line. Our documentation only shows these kinds of examples, which is where your example of having the forms inside of another grid becomes more complicated. Certain assumptions are broken with this kind of layout, which is why its working as expected from my perspective and you'll need custom CSS to change the default behaviors. 

1. When you use the `vertical` layout, form controls layout with the label above and input below. 
2. There isn't support for making the input fill the width of its container. There are some CSS hacks to do this, but its not currently supported by our forms as we let the browsers size things. Expanding to full width can be problematic in some areas, particularly in cases where you have a wide screen.
3. All form containers have margin on top to provide spacing. You'd have to remove that with custom CSS for them to align in your scenario.

It seems like https://github.com/vmware/clarity/issues/3778 close to what you might really want since you want more than one thing in a form control line. I'm going to close this in favor of that issue, and because this layout just requires custom CSS to complete since it goes beyond our recommended forms layout currently.

**Closed by gnomeontherun** 2020-02-21 23:19 UTC
Labels: @clr/ui, component: forms, status: needs info, type: bug
