### ISSUE TITLE
Hovering over an image with the cursor causes an extra scrollbar to appear

### ISSUE THREAD

**Issue by dustwhirl** [vmware/clarity#3301] opened 2019-04-17 00:15 UTC
## Describe the bug

Hovering over an image with the cursor causes an extra scrollbar to appear

## How to reproduce

The easiest way to view this issue is to go to https://v1.clarity.design/color and scroll down to the section on Colorblind Accessibility and hover over the images in this section with your cursor.

## Expected behavior

An extra scrollbar should not appear

## Versions

**App**

* Angular: 7
* Node: NA
* Clarity: 1.0

**Device:**

* Type: HP
* OS: Windows 10
* Browser: Chrome
* Version: 73

**Comment by hippee-lee** [comment] 2019-04-17 18:41
Hi @dustwhirl - can you create a simple stackblitz from one of the Clarity starters that reproduces the issue you are describing? 

Our website and documentation apps have many app level customizations. In order to triage and debug this issue we need a simple reproduction that **isolates the issue to the clarity component or style** that is causing it.

**Comment by dustwhirl** [comment] 2019-04-18 13:46
It is not doing it in the simple stackblitz I set up: https://stackblitz.com/edit/angular-wsj2dm

But it is in a prototype application (which is more customized like your web site and documentation apps): http://40.121.21.202/dev-cris-ang/submit/consultation scroll to step 4 in Chrome and hover over image.

Thanks

**Comment by hippee-lee** [comment] 2019-04-18 16:43
I'm not able to replicate the issue. 
The screen capture below was taken from the demo app running on a Windows 10 VM with Chrome `Version 73.0.3683.103 (Official Build) (64-bit)`

<img width="1033" alt="gh-3301-image-hover-issue" src="https://user-images.githubusercontent.com/433692/56376882-ecbc7e00-61bd-11e9-9840-a692edf70eb2.png">

Am I missing something here? Is it possible that you have a custom style sheet affecting your instance of Chrome? How can I re-create the issue as you are describing it?

**Comment by dustwhirl** [comment] 2019-04-22 19:01
I'll continue to investigate on my end. If you are not seeing it on the prototype app above, it may be some other issue. Thanks for taking a look.

**Comment by gnomeontherun** [comment] 2019-04-22 19:37
I also don't see anything, can you verify on your end with a different browser or computer?

**Comment by dustwhirl** [comment] 2019-04-22 21:00
![image](https://user-images.githubusercontent.com/1906611/56530090-d72db800-651f-11e9-94a3-14d8368a3d18.png)

and here is a screenshot with the double scrollbar after hovering over the image with the cursor:

![image](https://user-images.githubusercontent.com/1906611/56530241-0cd2a100-6520-11e9-80ca-d4cad91ebb14.png)

**Comment by gnomeontherun** [comment] 2019-04-22 21:31
Still cannot reproduce. Have you tried other browsers or computers please?

**Comment by dustwhirl** [comment] 2019-04-23 20:27
Yes, I've tried other browsers and computers. For me, this only occurs in Chrome, but it occurs in Chrome on every computer I try.

**Comment by hippee-lee** [comment] 2019-04-23 20:38
It seems like there is something different from the setups you have tested on vs the ones we have used. 

So far Ive tried Crome@latest on macOS and Chrome@latest on widows. 
I'm really sorry but without concrete steps for others to reliably re-create the issue its really hard to investigate. 

A couple of questions:
1. Does anyone else who accesses http://40.121.21.202/dev-cris-ang/submit/consultation also have this issue?
2. The other computers with Chrome were they also windows? 
3. Do you have any custom style sheets for CHrome? Could they be synced to any Chrom browser you are logged into? 

As I mentioned, I want to help here but I just don't seem to see how to diagnose the issue you are experiencing.

**Comment by dustwhirl** [comment] 2019-04-23 20:47
I appreciate the help and desire to figure this out. When I submitted this item, I assumed it was a consistent issue that could be seen in any Chrome browser. Since this isn't the case, I'm not sure how it can be resolved. I'm going to continue to investigate on my end and if I find anything, I'll let you know. I intend to migrate to 2.0 when released so if the issues persists, I can bring it up again.

**Comment by hippee-lee** [comment] 2019-04-23 20:48
Sounds good. I appreciate your patience and help investigating. I'm going to close this for now. Please feel free to re-open with new information.

**Closed by hippee-lee** 2019-04-23 20:48 UTC
Labels: Awaiting More Info

**Comment by dustwhirl** [comment] 2019-05-02 16:07
FYI - not sure if this issue is shown after it has been closed, but I solved the issue in Chrome by adding body { overflow: hidden; } to the Styles.scss file.

**Comment by hippee-lee** [comment] 2019-05-02 16:50
Thank you for the follow-up. I'm glad you found a solution. If you run into it again and can help us re-create it please open a new issue with the issue templates we provide.
