### ISSUE TITLE
Combobox popover not shown on first click

### ISSUE THREAD

**Issue by VladimirAnaniev** [vmware/clarity#5252] opened 2020-11-03 07:20 UTC
## Describe the bug

This issue caused a couple of our Protractor tests to fail after bumping Clarity from 4.0.2 to 4.0.5.
The issue occurs when filling a form with multiple fields, one of which is a Combobox. If the text in the form control before the Combobox is longer than the width of the input, then after clicking the Combobox arrow the options popover is not shown. The Combobox is focused, however.

## How to reproduce
https://stackblitz.com/edit/combobox-popover-not-shown?file=src%2Fapp%2Fapp.component.html

1.  Enter text with 20 characters in the Name field (Example: `12345678901234567890`)
2.  Click on the Combobox expand button
3.  Combobox is focused but options popover is not shown

## Expected behavior

Popover should be shown

## Versions

**App**

- Angular: 10.2.1
- Clarity: 4.0.5

**Device:**

- Type: MacBook
- OS: macOS Catalina
- Browser Chrome
- Version 86

## Additional notes

The 20 characters length seems arbitrary but it is the point at which the text content becomes longer than the input width. I was not able to reproduce it with a shorter text.

**Comment by bdryanovski** [comment] 2020-11-04 12:36
Thanks for reporting it,

It seems that this [issue](https://github.com/vmware/clarity/issues/5246) is also related to it, so we gonna try to combine and resolve both of them

**Comment by Jinnie** [comment] 2020-11-16 08:29
@bdryanovski it only reminds 5246 because it also talks about 20 chars, but actually, they are in the text field, not in the Combobox, so it's different.
Nevertheless, I am unable to reproduce it. The provided stackblitz works as expected for me.
I also tried calling the provided "reproduce()" method, or set it to a much larger string, but it's still okay.

**Comment by gnomeontherun** [comment] 2020-11-16 17:26
I do see the issue here on macOS Chrome 86. As soon as you hit 20 characters, the input is cleared and then the dropdown closes. The reproduce method calls the `name` and not the combobox field, so ignore it. The internal model on the input gets cleared for some reason.

**Comment by Jinnie** [comment] 2020-11-20 11:18
@gnomeontherun the description is about the "name" field, which is outside the combobox itself. 
what you're describing is the 5246 issue which happens inside the combobox input.
Btw, 5246 is fixed with https://github.com/vmware/clarity/pull/5320

**Comment by Jinnie** [comment] 2020-11-20 12:07
I examined the stackblitz more carefully.
You must have wrong expectations about what this statement will be doing:
```
*clrOptionItems="let value of [1, 2, 3]; field:'name'"
```
The `field` identifier will refer to a `name` property of the `value` variable, not on the form control.
In this specific case, it means that it tries to resolve 1.name, 2.name, 3.name

Although it is not connected to your currently reported problem, also keep in mind that `clrValue` should refer to the value object, too. It is expected to be typed as your dataset items.

**Closed as completed by Jinnie** 2020-11-20 12:07 UTC
Labels: resolution: no fix needed, @clr/angular, component: combobox

**Comment by VladimirAnaniev** [comment] 2020-11-20 18:49
Hi @Jinnie, thanks for looking at this.   
1. The problem is with the Combobox itself. The weird thing is that the way I was able to reproduce it is by entering text with a certain length in a text input and then trying to open the combobox. Let me try to clear up any confusion by demonstrating it visually.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19152501/99837438-40e4cc80-2b70-11eb-87b1-529347a5117b.gif)

To me, this seems different than #5246. Is this case handled with #5320 as well?

2. About the reproduce method, it is not relevant - I tried to provide a more automatic reproduction bat was unable to do so.  
3. Thanks for the clarification of the `name` property - seems like it is a copy-paste leftover from the combobox in our application :)

**Comment by Jinnie** [comment] 2020-11-23 09:42
I see it and I can guess why it may happen, but I still can not reproduce it locally.
The reason would be that the combobox is using the new smart popovers, which close on scroll.
And focusing out of the first input may trigger an inner scroll event, which may close the popover.
Now... the catch is that this inner scroll event should, in theory, be happening before the popover is opened, so it should not interfere. But depending on browser/OS, there may be some race condition that either the scroll or the popover-opening will happen 1st. Such a problem should be affecting all our implementations which use the smart popovers.
With the current implementation though, there's not much we can do to avoid it, as the scroll events are originating outside the combobox/popover components. I am testing with 87 version of Chrome on Mac and it looks okay. Is it possible that it was 86 only issue?

@hippee-lee FYI

**Comment by VladimirAnaniev** [comment] 2020-11-23 13:01
Just updated to chrome 87 and I am unable to reproduce it anymore. Seems to work fine on Safari and Firefox as well.

**Comment by Jinnie** [comment] 2020-11-23 13:08
Thanks Vladimir, 
I will keep it closed then, but it will be much helpful if we meet the problem again in future browser versions or in different context. 
As we don't have a viable approach, which does not include meddling with the Angular lifecycle, I prefer not to address it preemptively.
