### ISSUE TITLE
Design tokens (spacing)

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3303] opened 2019-04-17 21:30 UTC
Spacing tokens consist of a collection of pre-defined sizes that may be used when a semantic construction process is useful.

Usage: Spacing between 2 elements may be enabled and understood by a designer by using a padding element. Using such a component empowers designers to construct UI with fine control of layout and vertical rhythm. Should this be undesirable or impractical for some users, components will have built in default padding, Use of design token based padding will override defaults.

Example: $clr_padding_sm; 0.8 rem

The result (assuming a 10px rem system) is an 8px null spacing component. All such components are sized in balanced proportions to the overall proportional system.

Example for illustration purposes only, actual naming convention / sizes would need to be validated on several fronts.

2px - xxxs
4px - xs
8px - sm
12px - med
16px - l
24px - xl
32px - xxl
48px - xxxl

$clr_padding_0020
$clr_padding_0040
$clr_padding_0080
$clr_padding_0120
$clr_padding_0160
$clr_padding_0240
$clr_padding_0320
$clr_padding_0480

Reference:

https://blueprintcss.dev/docs/util-spacing
https://bits.24ways.org/docs/tokens
https://blog.prototypr.io/design-tokens-with-figma-aef25c42430f

example UI built with margin-less components and fine tuned for layout by a designer using spacing tokens:

**Comment by mathisscott** [comment] 2019-04-18 13:26
Note: To prevent this from being a breaking change, we should maintain our default spacing but allow for these utilities to force an override in the CSS. If we want to unify these utilities with the default spacing, we can use a combination of variables and mixins.

**Comment by coryrylan** [comment] 2019-04-18 17:36
The utility classes can be generated pretty easy with a mixin, the ones I built were attribute based but you could easily change to class based.

https://github.com/coryrylan/blueprint-css/blob/master/lib/src/_spacing.scss
https://github.com/coryrylan/blueprint-css/blob/master/lib/src/_config.scss

**Comment by colinreedmiller** [comment] 2019-07-12 20:39
Another reference:

https://gist.github.com/sebastiano-guerriero/7791857e7cb1f045e44494ba26b69586#file-spacing_13-scss

https://medium.com/codyhouse/create-your-design-system-part-4-spacing-895c9213e2b9

**Comment by mathisscott** [comment] 2020-02-05 21:21
@coryrylan 
This issue seems to have the sizing values you were asking about for #4116

**Comment by mathisscott** [comment] 2020-02-18 17:34
Closing for now as a duplicate of #4116

**Closed by mathisscott** 2020-02-18 17:34 UTC
Labels: Dev, type: enhancement
