### ISSUE TITLE
Datagrid column tooltip

### ISSUE THREAD

**Issue by antomor** [vmware/clarity#2891] opened 2018-11-28 13:26 UTC
## Summary

I would have the possibility to add a tooltip in column datagrid. At the moment, I can add a tooltip within the content, but if the column is sortable, all the content is rendered within a button, and this is a problem with Firefox, that doesn't render tooltips within buttons, [here](https://github.com/angular/material2/issues/6886) details.

My idea is to add a string property to the column, and if the property is set, render a tooltip before the content of the column.
All the remaining behavior can still be the same.
## Use case

```
 <clr-dg-column [tooltip] = "'My column description'" ...
```

## Implementation plan

Only [datagrid-column](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-column.ts) would be changed, by adding the string property and checking if the property is set in the template.

## Conclusion
If not possible, could you please tell me how can I extends the component? I have already tried, but there are some problem with DragDispatcher injection.

Thank you in advance

**Comment by antomor** [comment] 2018-11-28 16:00
Hi @mathisscott , thank you for your response.
[Here](https://stackblitz.com/edit/clarity-light-theme-v013-zpvwgq), you find a minimal example. 
You can have a look at the pokemon column; the tooltip doesn't appear on firefox, while it is visible on chrome.
The problem is that if the column is sortable, all the content is rendered within a button.
My proposal is to add a parameter tooltip to be rendered outside the button.

**Comment by youdz** [comment] 2018-11-28 16:06
This is a duplicate of #2294, as far as I can tell.

Note that we wouldn't receive a string property like you're suggesting, since it completely prevents using icons, emphasis or any other HTML in the tooltip's content.

**Closed by youdz** 2018-11-28 16:06 UTC
Labels: Awaiting More Info

**Comment by antomor** [comment] 2018-11-28 16:17
So, you are planning a different solution, I suppose.
Do you have an idea of the time necessary to implement it?
Sorry for the duplicate issue.

**Comment by youdz** [comment] 2018-11-28 16:32
The solution we have to go for is content projection. Because right now everything is projected in the button, we'll nee to offer different sub-component or sub-directives for the column, so the various pieces can go in different spot. And because it's only natural to target the title, it means we're probably facing a breaking change for this, asking everyone to add yet another Clarity component inside of their column header.

I don't think the implementation itself would be very long, the problem is mostly with the breaking change and the API implications, which are never simple for datagrid.

**Comment by antomor** [comment] 2018-11-28 16:40
Yep, I agree. At the moment I have tried to extend the datagrid-column component in order to change its template and adapt it to my needs, but I had some problem with dependency injection of DragDispatcher. Do you think it is a feasible solution or not? I am not very expert of ng, so any suggestion is welcome.
