### ISSUE TITLE
Bug with Header Example Code in clarity v12

### ISSUE THREAD

**Issue by Physium** [vmware/clarity#2464] opened 2018-07-15 10:12 UTC
**Select one ...** (check one with "x")

```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Expected behavior is as shown in the example of the clarity site.

![screen shot 2018-07-15 at 6 01 59 pm](https://user-images.githubusercontent.com/7604837/42732751-445366fe-8859-11e8-8af0-3b1395496a5a.png)

### Actual behavior

Sample code provided does not seem to work with the button showing up with missing CSS.

<img width="105" alt="screen shot 2018-07-15 at 12 09 37 am" src="https://user-images.githubusercontent.com/7604837/42732832-94d1d0c4-885a-11e8-8ea9-78470fd25595.png">

Below is the link where i reproduce the issue. 
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

https://stackblitz.com/edit/js-w3cxpe

### Environment details

* **Clarity version:** v12

* **OS and version:** Mac OS

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment] 2018-07-16 12:56
You are using the Angular component outside of Angular, this will not work. If you are trying to use just the Clarity styles, then do not use the Angular components and only use the components that support CSS directly. Closing as this is not a bug but implementation issue.

**Closed by gnomeontherun** 2018-07-16 12:56 UTC
