### ISSUE TITLE
New Feature: Searchable Select

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#148] opened 2016-11-23 20:06 UTC
```
[ ] bug
[X] feature request
[ ] enhancement
```

Similar to select2 (https://select2.github.io/), but built with Angular2. This would be a select dropdown that includes extended features such as an input for searching within the list, asynchronous data loading, templatable options for customized rendering, and tokenized items when selecting multiple options.

**Comment by jaffoneh** [comment] 2016-11-23 22:21
This is on the roadmap and being worked on in the design cycle. I am closing this as a duplicate of issue #90 which covers this use case as well. cc @reddolan

**Closed by jaffoneh** 2016-11-23 22:21 UTC
Labels: duplicate
