### ISSUE TITLE
API Docs for angular components?

### ISSUE THREAD

**Issue by maguitoon** [vmware/clarity#3236] opened 2019-03-24 20:02 UTC
How can i find component documentation?
https://clarity.design/documentation page only show some examples, but this docs is incomplete.
I can't find any doc when i wan't to do something different to examples or explore other component properties. Can we build api docs from code?

**Comment by hippee-lee** [comment] 2019-03-25 15:45
We request that _how to_ questions be asked on StackOverflow (tagged with `vmware-clarity`). 
It is also helpful to know some more information. e.g

1. What have you tried so far? A running [stackblitz](https://stackblitz.com/@clr-team) example is the best way for us to give you advice.
2. The examples in the docs are there to showcase the basic and specific use cases for each of the components and should be able to use as a starting point for copy/paste into a simple reproduction.
3. You can fork and clone the project and run the dev app, the website app or one of the several other apps in the repo. [package.json](https://github.com/vmware/clarity/blob/master/package.json) is your friend here. There is additional information on the website [here](https://github.com/vmware/clarity/wiki/Building-the-Website).

I'm closing this since it seems more like a _how to_ question and not an issue. Id you have implementation questions please post a question on StackOverflow and tag it with `vmware-clarity`.

**Closed by hippee-lee** 2019-03-25 15:45 UTC
Labels: Invalid

**Comment by gnomeontherun** [comment] 2019-03-25 16:15
If you are looking for an autogenerated API docs for Clarity, we don't have one published at this stage. We have found that the output shows a lot of things that make it confusing, and haven't put the effort into finding a way to clean it up with just the isolated things. It is on my radar as I'm thinking about some website changes, but for the time being we don't have it available. A good IDE like Webstorm can auto suggest a lot of the API for you based on our type files, so this might be a helpful guide in the interim. 

If we are missing specific documentation, please let us know though so we can add something.
