### ISSUE TITLE
Conditionally enable datagrid selection

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2118] opened 2018-03-29 08:56 UTC
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

You should be able to show and hide the selects for the datagrid (`[(clrDgSelected)]`) based on a condition.

### Actual behavior

Afaik this is currently not possible. You can either add the databinding attribute to the template or don't. Setting the input value to `null` or `false` leads to an error.

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.9

**Comment by youdz** [comment] 2018-10-18 19:21
Duplicate of #1790.

**Closed by youdz** 2018-10-18 19:21 UTC
Labels: Enhancement, Low, Needs Investigation, Watchlist
