### ISSUE TITLE
The datagrid is setting its column width too early when used inside an accordion panel.

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#3696] opened 2019-08-13 21:59 UTC
## Describe the bug

The datagrid component is setting its column width too eagerly when it's used inside the accordion panel.

## How to reproduce

https://stackblitz.com/edit/clr-basic-datagrid-luwtjk
If you open the accordion panel and check its datagrid column widths, all of them are set to 0.

## Expected behavior

The datagrid component should set proper column widths even if it's used inside the accordion panel.

## Additional notes

The workaround to this issue could be instantiating the Datagrid only after the accordion panel opens fully.

**Comment by Dedme** [comment] 2019-09-02 03:56
just wanted to say this is also happening for my grid not in an accordion.
the grid renders before the data loads into it, ignoring the column widths.
```html
<clr-dg-column _ngcontent-ufc-c11="" role="columnheader" class="datagrid-column ng-star-inserted" aria-sort="none" style="width: 0px;">
```
from 
```html
<clr-dg-column [style.width.px]="85">Size (MB)</clr-dg-column>
```

but if i load the page, via a different method when the data is ready.
```html
<clr-dg-column _ngcontent-ufc-c11="" role="columnheader" class="datagrid-column datagrid-fixed-width ng-star-inserted" aria-sort="none" style="width: 85px;">
```

**Comment by Dedme** [comment] 2019-09-02 05:22
this only happens when i first load a page straight onto a view with a datagrid. any navigation after are fine.
its almost like the first time clarity renders something it has not loaded something?
if i set a timeout on a variable *ngIf'ing the datagrid, it works - but the screen flashes.

calling resize() on the ClrDatagrid viewchild has a hardcoded 92px min-width!

on first load:
![image](https://user-images.githubusercontent.com/40647185/64091773-f4597980-cd90-11e9-83e4-8087487e4cbb.png)
after internal navigation:
![image](https://user-images.githubusercontent.com/40647185/64091759-e4da3080-cd90-11e9-88f7-6cb79fd6cc49.png)

**Comment by hippee-lee** [comment] 2019-09-03 21:08
@Dedme - datagrid columns have a `4rem min-width` on the [.datagrid-column]. Binding `[style.width.px]="85"` will not override that. But, you could add in `[style.min-width.px]="85"` and it _should_ override the styles delivered with the datagrid.

I don't think what you are describing is related to this issue. But to be sure, could you supply a stackblitz reproduction of the behavior you are seeing so we have working code to reference when investigating?

**Comment by rootix** [comment] 2019-09-27 07:45
We experience the same issue. Some of the fields get so small that the filter and sort icons are invisible (column "Objektnummer" in this example) and the drag line goes over the text of the second column when the accordion is initially closed.

![image](https://user-images.githubusercontent.com/874015/65751553-3022fd00-e10b-11e9-8030-e0ff8d90a7e5.png)

This does not happen if the accordion is open right away from the beginning. 

![image](https://user-images.githubusercontent.com/874015/65751662-79734c80-e10b-11e9-950a-b0e0445c1c51.png)

**Comment by hippee-lee** [comment] 2019-09-27 15:38
@rootix - can you provide a simple reproduction in [stackblitz](https://stackblitz.com/@clr-team)? It's hard to investigate without seeing the issue with working code.

**Comment by gnomeontherun** [comment] 2019-09-27 16:39
I believe one workaround would be to call the Datagrid.resize() method on open to force the Datagrid to recalculate sizes.

**Comment by rootix** [comment] 2019-09-29 19:50
@hippee-lee Sure, here it is: https://stackblitz.com/edit/clarity-light-theme-v2-cuusjx

- The issue happens only if there is not enough space for the columns
- It does not happen if the column titles can break

@gnomeontherun I tried this already in afterViewInit with no luck. The only temporary hack was to put the grid in another ng-container which *ngIf set to true after an delay of 1ms after the accordion open is true in Chrome (even 100ms was not enough in IE11 as the animation of the accordion went nuts). But with this "fix" you see a "stair" when opening the accordion as the content is loaded after the initial animation of the empty container.

**Comment by hippee-lee** [comment] 2019-09-30 19:00
@rootix - I was able to find a way to make resize work. 

I modified the example provided to use de-sugared syntax on the second row to grab the grid reference and call resize on it after the template has been rendered. I also used a separate grid because the reference needs to be distinct. If there are two templates with `#grid` rendered I'm not sure if it would call resize on the right one. 

```<clr-accordion-content clrIfExpanded (clrIfExpandedChange)="gridPanelChange($event)">```

The de-sugared syntax gives a hook to call the resize method after the view has been rendered by the `*clrIfExpanded` directive. 

I think something like this might work for you:  https://stackblitz.com/edit/clarity-light-theme-v2-o7ss2o

It seemed like there is an issue with the lifecycles of `*clrIfExpanded` used in conjunction with `ngTemplateOutlet`. The `ExpressionChangedAfterItHasBeenCheckedError` in the stackblitz example may be caused because is running before the template gets instantiated and rendered to the DOM via ngTemplateOutlet. 

I would recommend using separate datagrids for content that is displayed immediately vs content that user may expand later. And, for content in the first panel that is loaded as expanded I'm not sure `*clrIfExpanded` is needed there because `*clrIfExpanded` is an optimization directive that only renders its template to the DOM as needed. (if the accordion has hundreds of rows each with a datagrid the clrIfExpanded directive would prevent all of the datagrids from being instantiated until the user interacted with them).

**Comment by geyuqiu** [comment] 2020-03-02 23:32
> Binding `[style.width.px]="85"` will not override that

@hippee-lee is there a feature request to enable this in the future?

**Comment by hippee-lee** [comment] 2020-03-03 16:37
@geyuqiu - if i understand your question to be  "wiill Clarity provide an input for column width?" the answer is no. 

If you want to set a different min-width for a column the way to do that would be to add both the `[style.width]` and `[style.min-width]` attributes to the column.

**Comment by gnomeontherun** [comment] 2021-02-26 14:59
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-02-26 14:59 UTC
Labels: @clr/angular, component: datagrid, flag: has workaround, status: needs investigation, type: bug
