### ISSUE TITLE
New component Carousel

### ISSUE THREAD

**Issue by michelegoglio** [vmware/clarity#2252] opened 2018-05-09 15:03 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
Does Clarity consider creating a Carousel component ?

### Actual behavior
There's no Carousel component in Clarity. Is it a possible component for the future ?

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2018-05-09 15:19
Duplicate of #2174

**Closed by mathisscott** 2018-05-09 15:19 UTC
