### ISSUE TITLE
Tree recursion doesn't watch for model changes

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#3382] opened 2019-05-22 18:52 UTC
## Describe the bug

Using clrRecursiveFor doesn't watch for model changes after the tree has been initialized.

## How to reproduce

https://stackblitz.com/edit/clarity-tree-recursion-cant-push

Go to stackblitz above.
Click "Add new tree node" button.
Tree using ngFor updates when the model changes, tree using clrRecursiveFor does not

## Expected behavior

I expect the tree to update on model change.

**Comment by hippee-lee** [comment] 2019-05-22 19:32
`*clrRecursiveFor` uses `OnChanges` under the hood to determine when to update the nodes. 
_I believe_ `OnChanges` doesn't  detect the change because its not a new array so no change. 

If I create a new array, add an item and assign it to items the recursive tree updates. 
https://stackblitz.com/edit/clarity-tree-recursion-cant-push-uxr122

It seems that the issue is that *clrRecursiveFor* isn't detecting the change to an existing array.

**Comment by KANekT** [comment] 2020-02-27 11:50
@hippee-lee @gnomeontherun 

https://stackblitz.com/edit/clarity-tree-recursion-cant-push-4cyneh

Recursive - not select all after Expandable

if i expand Item 1 and select them - not selected Child 1A, Child 1B

**Comment by gnomeontherun** [comment] 2021-01-29 23:08
The Clarity Tree was rewritten in v2, so this seems like it might have been addressed. 

This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.

**Closed by gnomeontherun** 2021-01-29 23:08 UTC
Labels: flag: has workaround, status: needs investigation
