### ISSUE TITLE
Keyfilter directive feature

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#1999] opened 2018-02-18 14:44 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Can we get a keyfilter directive as one in PrimeNG?
This will be very helpful and handy for form inputs.
https://www.primefaces.org/primeng/#/keyfilter

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2018-02-21 16:29
This is a duplicate of #1259 

Closing this for now. Please subscribe to #1259 for updates. Thanks!

**Closed by mathisscott** 2018-02-21 16:29 UTC
