### ISSUE TITLE
Unable to overriding column width for checkboxes and radio buttons on horizontal layout

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4072] opened 2019-12-04 14:34 UTC
## Describe the bug

Unable to overriding column width for checkboxes and radio buttons on horizontal layout when using angular component.

we want to override the label and options as we do for input/select elements.
Irrespective of the col widths specified label. It is always adding "clr-col-md-10 clr-col-12" for the div and forcing the options to next line even we have lot of space
![image](https://user-images.githubusercontent.com/12848838/70150823-a37b5900-16d0-11ea-87b7-a6115553aea1.png)

If we delete these col widths on div added by angular component. It is working as expected.
![image](https://user-images.githubusercontent.com/12848838/70150941-df162300-16d0-11ea-814b-12cab0ee8180.png)

## How to reproduce

https://clarity-form-lmezj2.stackblitz.io

https://stackblitz.com/edit/clarity-form-lmezj2

## Expected behavior

We should be able to override the column width for radio and checkboxes for inline and horizontal forms.

## Versions

**App**

* Angular: 8.x
* Node:12.x
* Clarity: 2.3.2

**Device:**

* Type: [e.g. MacBook]
* OS: windows
* Browser chrome,firefox

## Additional notes

_Add any other notes about the problem here._

**Comment by shravansofts** [comment] 2019-12-08 07:13
Any update on this issue?

**Comment by hippee-lee** [comment] 2019-12-09 17:44
This is possible. Due to the design decisions for forms in Clarity 2+ it should be handled on the app side when necessary.

I modified the stackblitz to force one of the forms inputs to expand to the full column width: https://stackblitz.com/edit/clarity-form-lmezj2-mx8e9y

I'm going to close this as a question w/ an answer. Please update if I misunderstood what needs to be accomplished.

**Closed by hippee-lee** 2019-12-09 17:44 UTC

**Comment by shravansofts** [comment] 2019-12-11 03:52
@hippee-lee Question is about checkboxes and radio button to layout. Please go through the question once again.
Using angular component controller are always wrapping to next even we have of real estate available. There is no way to override this behavior.
Please reopen this issue.

**Comment by hippee-lee** [comment] 2019-12-11 05:32
Sorry, I guess I'm not clear on the expected behavior. 
In the example, how should Option 1 and Option 2 layout? 

I still think this is something that is overridable on the app side but if I can understand better I'll know how to evaluate the options.

**Comment by shravansofts** [comment] 2019-12-11 10:36
Please reopen the issue first.

It  should layout side by side
![image](https://user-images.githubusercontent.com/12848838/70613873-73333d80-1c2f-11ea-9e2c-43a2272084b6.png)

When we override the label cols the options are going to next line even  lot of space is available.
![image](https://user-images.githubusercontent.com/12848838/70614168-0cfaea80-1c30-11ea-92df-fe268acc8e6e.png)

**Comment by shravansofts** [comment] 2019-12-13 10:35
Any update on this?

**Comment by gnomeontherun** [comment] 2019-12-13 13:32
This is working as I see it using your demo, what you might be confused by is that at small screens it will wrap (the `clr-col-12` is the culprit for that) so that it better supports mobile layouts and narrow screens. 

See https://stackblitz.com/edit/clarity-form-lmezj2-rayhfy?file=src/app/app.component.html

**Comment by shravansofts** [comment] 2020-01-02 04:15
Thanks. This looks little odd syntax.
Please update the doc. It will help the library users a lot. :)
