### ISSUE TITLE
The actions buttons don't have unique names

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#4382] opened 2020-03-16 22:14 UTC
## Describe the bug

[Test URL]
https://clarity.design/documentation/timeline

[WCAG 2.1 Guideline]
Success Criterion 2.4.6 Headings and Labels
(Level AA)
https://www.w3.org/TR/WCAG21/#headings-and-labels
https://www.w3.org/WAI/WCAG21/Techniques/general/G131

[OS]
any

[User Agents/Assistive Technologies]
any

[Component]
Timeline

[Description]
The actions buttons don't have unique names

[User Impact]
When screen reader users read these buttons they do not hear a context specific name for what they do

[Steps to Reproduce]
- Go the Test URL
- Using a screen reader, read the action buttons and observe that the names are not context sensitive

[Recommendation]
Use contextual button names as seen below.

<button class="btn btn-sm">Add KMS</button>

<button class="btn btn-sm">Make Trust Center</button>

**Comment by gnomeontherun** [comment] 2020-03-30 21:57
This is an issue with the demo not the timeline, giving it a low priority for having sample buttons.

**Comment by gnomeontherun** [comment] 2021-02-01 22:49
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:49 UTC
Labels: @clr/angular, priority: 1 low, status: backlog, type: accessibility, type: website
