### ISSUE TITLE
Dropdown has wrong initial position

### ISSUE THREAD

**Issue by coldhamix** [vmware/clarity#1630] opened 2017-10-22 15:53 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Closed dropdown should not create extra space on the screen

### Actual behavior

Dropdown has wrong initial position when dropdown's content is longer than trigger width. It result in unneeded scrollbars.

![dd-location](https://user-images.githubusercontent.com/2734568/31863675-cfa11428-b761-11e7-958d-3594b7311cde.png)

When the dropdown is closed, the `clr-dropdown-menu` element has the following styles:
```position: absolute; top: 0px; bottom: auto; left: 0px; right: auto; visibility: hidden;```

Its parent `clr-dropdown` component has CSS class `.dropdown` which hangs `position: relative` to it. When we open the dropdown for the first time, the `clr-dropdown` component receives `style="position: static;"` which fixes the problem.

As a workaround one can explicitly add `style="position: sticky;" to the `clr-dropdown` component.

Why do we need setting `visibility: hidden` instead of `display: none`?

### Reproduction of behavior
https://plnkr.co/edit/wwBl4jNZ9zJAlVCyKPHm?p=preview

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:** 0.10.10

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment] 2017-10-23 02:06
@coldhamix: We recommend that you use the `*clrIfOpen` directive with `clr-dropdown-menu`. Please see this: https://plnkr.co/edit/PE4d6fLvckVn8MKvuS8D?p=preview When you use `*clrIfOpen`, the menu is not loaded be default and is positioned correctly.

I believe this issue is a duplicate of: https://github.com/vmware/clarity/issues/1474. Please subscribe to that issue for more updates or use the alternative that we suggested above. Closing the issue based on this.

**Closed by adityarb88** 2017-10-23 02:06 UTC

**Comment by adityarb88** [comment] 2017-10-23 13:42
Apologies. This is a duplicate of: https://github.com/vmware/clarity/issues/1262 Please subscribe to that issue for more updates.
