### ISSUE TITLE
Specify a default/initial sort column for datagrid

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#492] opened 2017-02-15 07:05 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior

It would be convenient to be able to specify a default/initial sort column for a datagrid directly in the definition. 

Simplistic approach:
<clr-dg-column [clrDgField]="'name'" [clrDgDefaultSort]="true">Name</clr-dg-column>

Having a parameter attached to <clr-datagrid> would be even better, but I'm not sure how to specify a particular column.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment] 2017-02-16 16:14
Duplicate of #355. We're working on it. 👍

**Closed by youdz** 2017-02-16 16:14 UTC
