### ISSUE TITLE
Notification / Toast messages / auto hide alerts

### ISSUE THREAD

**Issue by jaivardhanbhati** [vmware/clarity#1703] opened 2017-11-20 19:15 UTC
Title: Need a way to raise notifications/toast messages or a way to auto-hide alerts.

[ ] enhancement 
[ ] feature request
We use clarity .alert ( warnings and success ) heavily in our codebase as means of notifying the user about success/error/warning scenarios. But there is a need to hide the success and the warning messages after 8 seconds if not removed manually. This will be much like a toast message functionality.

### Expected behavior
1. Have a way to pass in an attribute with 'lifespan' / 'timeout' as part of the .alert / .alert-success OR
2. Implement the Toast message functionality 

Reference : https://www.npmjs.com/package/ng2-toastr

**Comment by adityarb88** [comment] 2017-11-20 19:19
@jaivardhanbhati: This looks like a duplicate of https://github.com/vmware/clarity/issues/365. Please subscribe to #365 for more updates.

**Comment by adityarb88** [comment] 2017-11-20 19:28
@jaivardhanbhati: Also you could use the `clrAlertClosed` input to make the alerts disappear after a few seconds. Please refer to this link: https://plnkr.co/edit/FtMhQxbIFX4wZo2tHTnC?p=preview

Closing the issue based on this.

**Closed by adityarb88** 2017-11-20 19:28 UTC
