### ISSUE TITLE
Wizzard Mobile View, remove side nav

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#1476] opened 2017-09-17 17:23 UTC
```
[x] bug
[x] feature request
```

### Expected behavior
Expect the wizzard side navigation to disappear or make room for the main wizzard content

### Actual behavior
Wizzard side navigation is fixed and the main content shrinks

### Reproduction of behavior

<img width="391" alt="screen shot 2017-09-17 at 19 21 30" src="https://user-images.githubusercontent.com/16038088/30523214-ab9e5954-9bdd-11e7-87f6-6a9482709bed.png">

<!-- Clarity Version:0.10.5

**Comment by mathisscott** [comment] 2017-09-18 15:28
This is a known issue with the Wizard. It was not designed to be used on phones.

Closing as a duplicate of #1379

**Closed by mathisscott** 2017-09-18 15:28 UTC
