### ISSUE TITLE
add type for ClrDatagridStateInterface.filters

### ISSUE THREAD

**Issue by geyuqiu** [vmware/clarity#4325] opened 2020-02-28 21:32 UTC
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
add type in ClrDatagridStateInterface, looks for me like: 
`filters?: Array<property: string, value: string, low?: number, high?: number>` instead of `filters?: any[]`
* Why should it go in Clarity?
strictly typed
or does it belong to DefinetelyTyped?
* Does this change impact existing behaviors? If so how?
no idea
* If this change introduces a new behavior, is this behavior accessible?
accessible via `@Output('clrDgRefresh') `

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by gnomeontherun** [comment] 2020-03-02 15:54
The problem is that each filter (string and numeric are built-in) may have a different interface, so adding strict typing would only provide one of the interfaces. You can also add custom filters, which is not available to Clarity except at runtime. Therefore, the typing would be incorrect no matter what we did other than `any[]`.

I'm going to close this as something we can't change. I understand the frustration, but filters are a runtime, plugin-like construct that prevents us from being able to type them accurately.

**Closed by gnomeontherun** 2020-03-02 15:54 UTC
