### ISSUE TITLE
Console error resulting the broken page when datagrid is used with clrIfActive

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#1363] opened 2017-08-24 06:58 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
We have two tabs and each tab contains a datagrid. There is an console error

```
ERROR TypeError: Cannot read property 'map' of undefined
```

after programmatically setting second tab to be active.

![screen shot 2017-08-24 at 2 54 31 pm](https://user-images.githubusercontent.com/6769465/29653455-66e77796-88dc-11e7-8168-26d38539450f.png)

### Actual behavior
The datagrid should render correctly.

### Reproduction of behavior
Working plunker:
https://plnkr.co/edit/nMgBt3dEIpQBM9u2j0X4

### Environment details

* **Angular version:** 4.x

* **Clarity version:** 0.10.1

* **OS and version:** 

* **Browser:** [ Chrome 60  ]

**Comment by youdz** [comment] 2017-08-24 13:00
Thanks for reporting this, apparently we still have an issue where the first tab is created and immediately destroyed when another tab is set as the default active. I thought we fixed it, but from the code I can see it's still there.

Thanks for reporting this.

CC @jeeyun on this one, so we can discuss it soon.

**Comment by mathisscott** [comment] 2017-09-13 14:20
@jeeyun + @youdz 
Any information out of this exploration/discussion?

**Comment by GEMI** [comment] 2017-12-12 21:24
Hi I am getting the same error when I do update of a structural directive which does `this.viewContainerRef.clear();`

```
TypeError: Cannot read property 'map' of undefined
    at DragDispatcher.destroy (VM9736 dstitan.js:85655)
    at DatagridColumnResizer.ngOnDestroy (VM9736 dstitan.js:86400)
    at callProviderLifecycles (VM9736 dstitan.js:11474)
    at callElementProvidersLifecycles (VM9736 dstitan.js:11443)
    at callLifecycleHooksChildrenFirst (VM9736 dstitan.js:11427)
    at destroyView (VM9736 dstitan.js:12768)
    at callWithDebugContext (VM9736 dstitan.js:13749)
    at Object.debugDestroyView [as destroyView] (VM9736 dstitan.js:13303)
    at ViewContainerRef_.clear (VM9736 dstitan.js:10289)
    at AuthDirective.update (VM9736 dstitan.js:192951)
```

**Comment by gnomeontherun** [comment] 2017-12-13 17:05
The original issue appears to be resolved, as the plunkr is working now. I believe it could have been fixed with https://github.com/vmware/clarity/commit/aa92fe8c7510e6030edbc9fcef2cfceaff31045b.

@GEMI you're on an outdated version of Clarity, have you tried to update to latest 0.10.x? If so, please provide a plunkr showing how to reproduce it because I don't know how to replicate this.

**Closed** 2017-12-13 17:21 UTC
Labels: bug, ClarityNG, duplicate
