### ISSUE TITLE
Is the size of margin between tabs fixed?

### ISSUE THREAD

**Issue by minjunsz** [vmware/clarity#4724] opened 2020-06-10 18:29 UTC
I'm trying to make tabs with zero margins. I tried the code below, but it doesn't work.

HTML
    <clr-tabs id="data-tab">
        <clr-tab *ngFor="let data of datas" class="no-margin">
          <button clrTabLink>{{data.title}}</button>
          <clr-tab-content *clrIfActive>
             {{data.content}}
          </clr-tab-content>
        </clr-tab>
      </clr-tabs>

SCSS
    #data-tab{
        .no-margin {
            margin: 0px;
        }
    }

**Comment by minjunsz** [comment] 2020-06-11 15:35
I made a simple code to reproduce my situation.
https://stackblitz.com/edit/clarity-v3-light-theme-4hpppc

I want to remove the margin between the tabs "title1" and "title2".
As I inspected, the gap comes from the "margin-right" of the li.nav-item tag.
In the app.component.css file, you can check my tries to override with "margin: 0px".

I can't even apply element style. I can't figure out what's going on by angular.

**Comment by mathisscott** [comment] 2020-06-11 16:51
@minjunsz 
The problem is that the styles are being applied to the `app.component.css`. Angular does a bit of work under the hood to "encapsulate" CSS applied to components. So your styles aren't making it across to the Clarity component library. Here's a screenshot of what I'm talking about.

<img width="856" alt="Screen Shot 2020-06-11 at 11 48 56 AM" src="https://user-images.githubusercontent.com/2728359/84416257-95efe000-abd9-11ea-93a8-5a330705faf1.png">

Do you see all those attr selectors like `[_ngcontent-bfx-c0]`? That is what is preventing your styles from being applied.

If you move your styles to a top level stylesheet (outside of your app component), it all works as expected. 

https://stackblitz.com/edit/clarity-v3-light-theme-q4binf?file=src/styles.css

I'm closing this as it is not an issue with Clarity.

**Closed by mathisscott** 2020-06-11 16:51 UTC
Labels: resolution: invalid, status: needs reproduction
