### ISSUE TITLE
Add information of when was introduced an icon

### ISSUE THREAD

**Issue by Crackroach** [vmware/clarity#3858] opened 2019-09-28 03:17 UTC
## Summary

The current documentation of the icons doesn't state when it was introduced, making it hard to know if it is available when using a certain version of `@clr/icons`.

Adding a simple

`Introduced in @clr/icons 1.3.1` would suffice when clicking on an icon.

Even better would be to filter them by availability per version

#### Current
![Current version](https://user-images.githubusercontent.com/5933612/65810783-1f12d400-e17d-11e9-9789-081400b4f7a4.png)

#### Updated
![Update](https://user-images.githubusercontent.com/5933612/65810813-82046b00-e17d-11e9-8dfb-74f45e89d453.png)

**Comment by gnomeontherun** [comment] 2019-09-29 22:24
This is a duplicate of #1808, which we have a design for but haven't prioritized yet. Follow #1808 to get updated.

**Closed by gnomeontherun** 2019-09-29 22:24 UTC
