### ISSUE TITLE
Datagrid Detail pane not rendering correctly when first column text is too long 

### ISSUE THREAD

**Issue by simonaen** [vmware/clarity#6429] opened 2021-10-22 10:04 UTC
## Describe the bug

_The Detail pane doesn't render left-side styles when one of the first column's inner text is longer than 1/3 of the datagrid._

_Screenshots from Stackblitz and official Clarity documentation._

_[Not Working Detail Pane](https://stackblitz.com/edit/clarity-light-theme-v5-bfzjlp?file=src/main.ts)_
![Screenshot 2021-10-22 at 12 53 42](https://user-images.githubusercontent.com/40393138/138434926-b9a072cf-85c5-4304-9e9b-754e9d6da0c2.png)

_[Working Detail Pane](https://stackblitz.com/edit/clarity-light-theme-v5-s53t7r?file=src/app/datagrid/datagrid.component.ts)_
![Screenshot 2021-10-22 at 13 01 45](https://user-images.githubusercontent.com/40393138/138435511-e6bdbb57-37c8-40ed-9ec9-1ee7e9508e00.png)

_[Clarity documentation](https://clarity.design/angular-components/datagrid/#detail-pane)_
![Screenshot 2021-10-22 at 12 53 54](https://user-images.githubusercontent.com/40393138/138434930-269c5ac0-2132-4206-92ad-0ef8d91c395e.png)

## How to reproduce

_[Stackblitz link](https://stackblitz.com/edit/clarity-light-theme-v5-bfzjlp?file=src/app/app.component.html)._

1.  Click on double right arrows to expand the Detail pane
2.  Observe left side of the Detail pane

## Expected behavior

_Left side border and triangle from trigger row to show regardless of the inner text of the rows._

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 12_

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version: 94.0.4606.81

**Comment by hippee-lee** [comment] 2021-10-27 22:36
Column widths and `_super_duper_extra_long_unbroken_lines_of_text` can be tricky in a datagrid cell. When combined with the detail pane which covers all but the first column when active it can be tricky. The best advice I can give is to use a combination of fixed width (set from the application side) for the column with long text and one of the css properties for managing the text behavior when it overflows its container. (e.g overflow-wrap, word-wrap  etc).

I [forked the stackblitz](https://stackblitz.com/edit/clarity-light-theme-v5-e8wdtj?file=src/app/datagrid/datagrid.component.html) and put a POC that handles it to demonstrate a workaround for the issue described with long, unbroken text in the first column and an active detail pane. FYI - the text issue also occurs with any other column and would need to be handled in a similar way with overflow-wrap if the column text can be very long. 

I am closing as works as intended but will also mark it as has workaround because there isn't anything we can fix on our end to address the issue described.

**Closed as completed by hippee-lee** 2021-10-27 22:36 UTC
Labels: resolution: wontfix, flag: has workaround, component: datagrid, @clr/angular
