### ISSUE TITLE
Datagrid toggle selection modes

### ISSUE THREAD

**Issue by alberthoekstra** [vmware/clarity#1720] opened 2017-11-27 15:46 UTC
Is it possible to enable/disable any type of selection (single/multi) with a two way binding property on a data grid?

By default my users need to be able to select one record. When they hit a certain button it should change the datagrid and be able to select multiple records.

I can't find other issues like this and I can't find it in documentation.

**Comment by alberthoekstra** [comment] 2017-12-15 12:25
Can you think of a workaround maybe? 

I'm thinking to make the grid multi select by default and limit the selection count in the events.

**Comment by mathisscott** [comment] 2017-12-18 14:36
@alberthoekstra 
Your plan to do a limited multi-select is about the best option available. There's no better option for a workaround, IMO.

**Comment by gnomeontherun** [comment] 2018-01-24 17:29
The main challenges as I see it are making sure when the selection mode changes that any already initialized renderers and providers are updated properly. There are some complexities in ensuring these items refresh properly and are fully tested to make this a larger task.

**Comment by youdz** [comment] 2018-10-18 19:22
Duplicate of #1790.

**Closed by youdz** 2018-10-18 19:22 UTC
Labels: Enhancement
