### ISSUE TITLE
>ng add @clr/angular fails

### ISSUE THREAD

**Issue by rahulpraj10** [vmware/clarity#4486] opened 2020-04-19 04:56 UTC
## Describe the bug
>ng add @clr/angular
| Installing packages...npm ERR! code ETARGET
npm ERR! notarget No matching version found for @clr/ui@NaN.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'OpEn3'
npm ERR! notarget

![1](https://user-images.githubusercontent.com/18599215/79679913-a746ec80-8227-11ea-90af-4e33eb31a02d.JPG)

Log :
[2020-04-19T04_41_46_556Z-debug.log](https://github.com/vmware/clarity/files/4498391/2020-04-19T04_41_46_556Z-debug.log)

## Versions

**App**

* Angular: 9.1.2
* Node: 12.16.1

**Device:**

* OS: Windows 10

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2020-04-20 18:18
Hi there, this is a duplicate of #4444 which is fixed but not yet released. The current workaround is to do `ng add @clr/angular@3.0.1`. Closing as duplicate.

**Closed by gnomeontherun** 2020-04-20 18:18 UTC
