### ISSUE TITLE
Website: broken link

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#4457] opened 2020-04-09 10:31 UTC
## Describe the bug
The Icon Sketch library on the website documentation is not dowloadable

## How to reproduce
Go to 'https://clarity.design/documentation/get-started#designResources'
Try downloading Sketch Design Files

## Expected
Dowloadable file
![2020-04-09_12h26_24](https://user-images.githubusercontent.com/311619/78886056-e625b700-7a5d-11ea-87b6-1928abe58806.png)

## Versions
current website version

**Comment by mathisscott** [comment] 2020-04-09 13:33
This is a duplicate of #4448 

Please subscribe to that issue to follow progress and access the working link at this time.

**Closed** 2020-04-09 13:33 UTC
Labels: resolution: duplicate
