### ISSUE TITLE
Multiple column sorting support in Datagrid

### ISSUE THREAD

**Issue by GoosvandenBekerom** [vmware/clarity#2774] opened 2018-10-23 15:03 UTC
## Summary

The Datagrid currently only supports single column sorting. Would it be interesting to add support for multiple column sorting?

* What is the change?
Sorting a datagrid by multiple columns. Each sorted column has a sort priority.
* Why should it go in Clarity?
I'm currently working on a project using server driven datagrid's and find myself in need of a feature like this. Not sure if more people would like this.
* Does this change impact existing behaviors? If so how?
Potentially the way sorting currently works, but it should not.
* If this change introduces a new behavior, is this behavior accessible?

## Use case

Display data that is sorted by multiple columns.

## Examples

For example when you order a SQL query by multiple columns.

## Workarounds

I don't think so.

**Comment by gnomeontherun** [comment] 2018-10-23 19:17
Closing as a duplicate of #1067, please follow that ticket for more details.

**Closed by gnomeontherun** 2018-10-23 19:17 UTC
Labels: Enhancement
