### ISSUE TITLE
Datagrid filter losing focus when more than 29 columns present

### ISSUE THREAD

**Issue by brianmmcgrath** [vmware/clarity#2979] opened 2019-01-02 14:14 UTC
Experiencing an issue (Chrome 71 and FF 63) whereby the grid filter does not function correctly in instances where more than 29 columns are present on the grid.  When attempting to filter, the text input loses focus after 1 or 2 characters have been entered and it needs to be clicked upon in order to return focus:

![filter-issue-column-limit](https://user-images.githubusercontent.com/5401335/50595538-a8200780-0e98-11e9-834f-2e5a7379080c.gif)

**Comment by hippee-lee** [comment] 2019-01-02 16:35
Hi @brianmmcgrath - can you provide a stackbliz reproduction so I can take a look at the issue s described? https://stackblitz.com/@clr-team

**Comment by brianmmcgrath** [comment] 2019-01-03 09:04
Hi @hippee-lee  stackblitz demo here:  https://clarity-light-theme-v1-0-36irup.stackblitz.io

Note, in this example, the filter stops functioning after 28 rows.  To reproduce:
1. Filter any column and start typing (input field will lose focus)
2. comment out a column and field cell in `app.component.html`
3. Filter any column for the text 'random',  delete two chars, ctrl + a to select all etc.,  (field should retain focus at all times)

**Comment by hippee-lee** [comment] 2019-01-03 16:23
Thank you for the stackblitz. It helps see the issue in a working application. Looks like this is a bug. 
fyi - here is a direct link to the StackBlitz editor: https://stackblitz.com/edit/clarity-light-theme-v1-0-36irup

**Comment by gnomeontherun** [comment] 2019-10-03 21:22
This appears to have been resolved with #2923 and perhaps also due to #3859. Closing as resolved from the demo.

**Closed by gnomeontherun** 2019-10-03 21:22 UTC
Labels: component: datagrid, status: needs investigation, type: bug
