### ISSUE TITLE
The action pop-up in the single row action data-grid is not positioned correctly

### ISSUE THREAD

**Issue by ipetrovaVm** [vmware/clarity#4472] opened 2020-04-14 12:00 UTC
## Describe the bug

The position of the action pop-up in single action data-grid is not calculated correctly when the height/width of the window changes. 
As a result the pop-up is not aligned to the selected grid element.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-owaezn

In a more complex application the issue is reproduced when different DOM elements show/hide after the window height/width is already calculated. In this cases when we try to open the action pop-up it is either not shown or it's shown in a wrong position.
In a simple app, the easiest way to reproduce is window resize.

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-owaezn -> single action data-grid
2.  Click on single selection menu in some of the grid rows
3.  Resize the window
4.  The pop-up is still visible, but it's not aligned to the selected row.

## Expected behavior
The pop-up should be aligned correctly to the selected grid row.

## Versions

**App**

Angular: [8.3.23]
Node: [e.g. 10.14.6]
Clarity: [2.3.5]

**Device:**

Type: [Windows]
OS: [Windows 10]
Browser [Firefox]
## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2020-04-17 16:30
This might be an area we can optimize, but the frequency of browser resizing is low (often developers testing). It also doesn't cause great angst as it will close if you click or scroll, so I'm marking this as a low priority feature enhancement.

**Comment by ipetrovaVm** [comment] 2020-04-22 19:11
Thanks for the response. 
The scenario with resizing is the easiest way to reproduce. The issue happens in cases after DOM elements are shown/hidden and the content height/width are changed without actual window resizing. In such cases the position of the action pop-up is not correctly calculated and when it is opened it is not aligned to the grid row. If the user reopen the action pop-up it is still not aligned properly. It might be very confusing when it appears aligned to another grid row.

**Comment by WhiteLord** [comment] 2020-07-30 07:11
This regression is not fixed in 3.1.4.
Currently the problem is reproducible not only by resizing the browser window, but by having a scrolltop as well. This affects button dropdown menus, as well as datagrid-action-overflow menus. The result is that menus are not positioned on their supposed places, but rather above the elements they're supposed to be adjacent to (I observed that the offset is equal to the scrolltop).

Please, do consider setting a higher priority.

**Comment by vmissue** [comment] 2020-10-09 10:56
In my team we gave up from datagrid's single action due to this issue. Had to deal with the UX in different manner.

**Comment by Jinnie** [comment] 2020-11-20 14:12
@WhiteLord is this issue still valid?
I am not able to reproduce it against v3 or v4.
The popover immediately closes on resize, or when a scroll event is emitted, which is the expected behavior.

**Comment by WhiteLord** [comment] 2020-11-21 21:48
This was still an issue on 3.11 as far as I can tell several weeks ago, but we switched to a new design. If this is no longer reproducible on your environment, feel free to close the bug.

**Comment by vmissue** [comment] 2020-11-22 13:44
@Jinnie yes, the issue still exists. That's, in fact, the only reason for us to give up with using single actions in the datagrid and switch to another design.

> The popover immediately closes on resize, or when a scroll event is emitted, which is the expected behavior.

That's good. However, the main issue with the single action menu was that it was initially shown with an offset. For example the menu was created outside of the viewport.

Here's the part of the issue description that referred to this behavior:
> In this cases when we try to open the action pop-up it is either not shown or it's shown in a wrong position.

**Comment by Jinnie** [comment] 2020-11-23 09:55
I mean, is it sill reproducible agains the lastest minor Clarity version released. Btw, 3.11 is not a valid version. 3.1.1? 3.1.11??
I will need Browser (with version), OS, Clarity version.
I see that the provided stackblitz just links to the v2 docs inside an Iframe in the same time we talk about v3.11. So a better defined reproduction scenario will also be helpful.

**Comment by gnomeontherun** [comment] 2021-02-05 21:27
The original concern here is that the popover positioning doesn't understand page resize events, but this is not a major flaw. If the issue is different, then we need updated details with a new reproduction.

This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.

**Closed by gnomeontherun** 2021-02-05 21:27 UTC
Labels: @clr/angular, priority: 1 low, status: needs info, type: enhancement
