### ISSUE TITLE
ARIA attributes for a datagrid component

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#2431] opened 2018-07-06 11:08 UTC
**Select one ...** (check one with "x")

```

[X ] feature request
[X ] enhancement
```

### Expected behavior
I would like to request ARIA roles, attributes and states for the clarity datagrid.
https://www.w3.org/TR/wai-aria-practices/#grid

The selected or expanded row is good to have appropriate attributes.
The cells to be map to the column and rows.
The expanded rows to have appropriate attributes. 
The datagrid to be recognizable by screen readers.

Environment details

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 11.0.18

* **OS and version:**

* **Browser:** all

**Comment by adityarb88** [comment] 2018-07-06 12:54
@dkanev: Thanks for filing the issue. We have a general issue open to add ARIA attributes to all our components here: https://github.com/vmware/clarity/issues/1190 Please subscribe to https://github.com/vmware/clarity/issues/1190 for more updates. 

@smathis: Can we close this issue as a duplicate of https://github.com/vmware/clarity/issues/1190 or do we want to track this separately?

**Comment by mathisscott** [comment] 2018-07-06 13:16
@adityarb88 
No, we are keeping these separate so we can prioritize them according to a need of a VMware product. Let's leave them atm. Thanks.

**Comment by hippee-lee** [comment] 2018-07-11 21:52
Recommendations for ARIA attributes on the `ClrDatagrid` component

## Easy Additions
- Add role="grid" to the `clr-datagrid` component
- Add role="row" to the `clr-dg-row` component
- Add role="columnheader" to the `clr-dg-column` component
- Add role="gridcell" to the `clr-dg-cell` component

## Complex Additions
- Add `aria-tabindex` to cells to enable arrow key navigation 
- Add `aria-rowindex` to the respective `clr-dg-row`'s 
- Add `aria-colindex` to the respective `clr-dg-column`'s and `clr-dg-cell`'s

## Others To Consider
- Add `aria-sort="ascending|descending|none" to `clr-dg-columns`
-  Expose an optional `@Input` for `aria-labelledby="grid1Label"` at the `clr-datagrid` level for users
- Add `aria-haspopup="true"` to the filters and hideable column toggler buttons
- Add `aria-rowcount="COUNT" to the `clr-datagrid` component
- Add `aria-colcount="COUNT"` to the `clr-datagrid-component

The complex additions seem easy but may have complexity due to the need to calculate each attribute value when a datagrid is created or rows are updated. Some, complexity when it comes to using arrow key navigation to update the `tab-index` ... I'm not sure if the browsers give us that for free or if we have to do it with code. Similar for the `Others To Consider` items.

@mathisscott: 
**Note:** This was my reference for the aria attributes: https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

**Comment by mathisscott** [comment] 2018-07-12 15:54
I've spent the morning with screenreaders and the easy additions above are sufficient to enable arrow-key up/down navigation in screenreaders as well as row and column counts.

I think this is sufficient (for now) to address concerns with datagrids and screenreaders.

It would be nice to break this item up into the easy additions and then putting the other two categories into another issue. If there are any in the `Others to consider` group that would not constitute a breaking change or add greatly to the level of effort, please consider adding them to the `Easy additions` ticket.

A lot of the hubbub we are receiving on these items are from people who have clearly never tried using a screenreader.

**Comment by youdz** [comment] 2018-07-12 17:39
I just read this, we also need to use the `rowgroup` role, and potentially the `aria-owns` attribute to link everything together. Thanks Matt for posting this. 👍

**Closed** 2018-07-31 16:56 UTC
Labels: Accepted, Accessibility, ClarityNG
