### ISSUE TITLE
Datagrid takes the height of items inside hidden columns

### ISSUE THREAD

**Issue by ajinkyac** [vmware/clarity#1114] opened 2017-06-27 09:02 UTC
Datagrid rows take the height of items inside hidden columns.

**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The grid should resize if the visibility of certain columns is toggled that have very long text.

### Actual behavior
The grid takes up height for text inside column(s) that is hidden.

### Reproduction of behavior
Use the Hide-show columns feature of datagrid, add very long text in one of the columns and hide that column.

PFA: GIF reproducing the issue.

### Environment details

* **Angular version:** 4.2.3

* **Clarity version:** 0.9.7

* **OS and version:** macOS Sierra

* **Browser:** [Chrome 58.0.3029.110 (64-bit) | Firefox 53.0.3 (64-bit)]
![datagrid_bug](https://user-images.githubusercontent.com/3681081/27579490-4f055ea0-5b45-11e7-8c6c-6cf26f37c738.gif)

**Comment by mathisscott** [comment] 2017-06-27 14:56
Hi @ajinkyac 
Could you provide a plunkr demonstrating the issue? It would help us triage it more quickly. The GIF is helpful but we have to do a lot of guesswork in repro'ing issues sent to us like this and if we can't reproduce it in our a plunkr we will close it.

For this reason, it's generally best to provide even a basic plunkr reproducing the issue since you know exactly what is leading to it.

https://plnkr.co/uNwwZe

**Comment by youdz** [comment] 2017-06-27 16:49
I'm not sure what we want to do here. Initially, the datagrid had pure "dynamic" height, which is what you want. But we got complaints that when the user moved from one page to another, the datagrid would resize and the whole app would move around. Especially on the last page, when it might not be full.

So we can't go back and forth between dynamic and static height and keep getting issues filed for the one we haven't chosen. In your case, the height difference is extreme, but some consumers _don't_ want the whole app layout moving up and down just because one of the datagrid cells in a hidden column has one extra line. 

I think at this point, we need a final UX decision on all the cases where the datagrid height might change (we don't have to pick the same solution for each, in some cases we might want to resize and in others we might not), and document the reasons for each choice.

**Comment by mathisscott** [comment] 2017-07-11 13:04
I can't think of a use case where we would want to dynamically size a datagrid. It doesn't mean there isn't one. But content jumping up and down the screen based on pagination, filtering, etc., is not a pattern we want to promote.

That said, the datagrid should not retain the size of hidden expandable rows as demonstrated above. The recommendation is that the datagrid have the static height of the visible non-expanded rows but allow for end users to change that height (once, declaratively) if they want or need more space for their datagrid.

It is expected that the datagrid will allow vertical scrolling when rows are expanded.

**Comment by mathisscott** [comment] 2017-09-13 14:37
The recommendation is to set a max-height or a strict height on the datagrid itself so that the rows will vertically scroll inside the datagrid and a reasonable height will be preserved across pages/filtering/hide-show.

**Closed by mathisscott** 2017-09-13 14:37 UTC
Labels: !!, bug, ClarityNG, UX Ready
