### ISSUE TITLE
AlertIconAndTypesService service breaks with 0.10.8 or 0.10.9

### ISSUE THREAD

**Issue by amolpowar** [vmware/clarity#1612] opened 2017-10-19 13:49 UTC
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Upgrading the Clarity framework from 0.10.7 to 0.10.8 or 0.10.9 should not break AlertIconAndTypesService service

### Actual behavior
Compilation fails with the following error

ERROR in ./src/app/main.nav.mod.ts
Module not found: Error: Can't resolve 'clarity-angular/emphasis/alert/providers/icon-and-types-service' in '/Users/<project>/src/app'
resolve 'clarity-angular/emphasis/alert/providers/icon-and-types-service' in '/Users/<project>/src/app'
  Parsed request is a module
  using description file: /Users/<project>/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/<project>/package.json (relative path: ./src/app)
    resolve as module

### Reproduction of behavior

In the main module import the following
import { AlertIconAndTypesService } from "clarity-angular/emphasis/alert/providers/icon-and-types-service";

set the provider

proividers:[AlertIconAndTypesService]

Note: Everything works fine with Clarity 0.10.7

### Environment details

* **Angular version:** 4.x.x

* **Clarity version: 0.10.8 or 0.10.9

* **OS and version: Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment] 2017-10-19 15:00
This issue is a duplicate of: https://github.com/vmware/clarity/issues/1574

More info here: https://stackoverflow.com/questions/46010942/getting-error-no-provider-for-alerticonandtypesservice

**Closed by adityarb88** 2017-10-19 15:00 UTC
