### ISSUE TITLE
Re-rendering of datagrid rows in case new  row items are added

### ISSUE THREAD

**Issue by pragesh** [vmware/clarity#3654] opened 2019-07-30 22:02 UTC
## Describe the bug

Is adding a new item to the data grid is resulting in re-rendering of all the rows even when trackBy function returns a unique identifier?

## How to reproduce

Here is the link to reproduce - https://stackblitz.com/edit/clarity-custom-theme-v1-0-7bndff
1. Open Chrome Inspect > Elements tab to observe the behavior.
2. Click on "Add Data" button which will add a new data item to the grid.
3. When a new item is added, already added "clr-dg-row" elements are highlighted (chrome behavior when a change is detected for DOM elements) as well.

## Expected behavior

Chrome "Elements" tab should not highlight elements that are already rendered in this case.

## Versions

**App**

* Angular: 8.1.0 and 7.2.15
* Node: 12.6.0
* Clarity: 2.0.2 and 1.1.5

**Device:**

* Type: MacBook
* OS: 10.13.6
* Browser Chrome
* Version 72.0.3626.121
--

## Additional notes

I observed it is working fine with an unordered list - https://stackblitz.com/edit/clarity-custom-theme-v1-0-aqh8hh

**Comment by gnomeontherun** [comment] 2019-07-31 15:51
This is an expected behavior because while we support trackBy in our custom iterator `clrDgItems` we also rebuild the current list of items each time for a few technical reasons. There could be an optimization some day to figure out how to reduce this, but we have to do calculations for size and end up always reassigning the new list of items in the process to trigger change detection in all the proper places. 

TrackBy in this case is primarily used to help us identify which rows are selected as you paginate, but we do internally reassign models which causes a redraw of each element. This isn't a bug IMO but rather a potential optimization (though I'm not certain this could be changed).

**Comment by pragesh** [comment] 2019-07-31 16:03
I am worried in case the model bound to Datagrid grows bigger this might lead to performance issues which would be bad.

Is there a workaround if I am using Datagrid? I noticed there is a similar problem if I use "ngFor" instead of "clrDgItems".

**Comment by gnomeontherun** [comment] 2019-07-31 17:45
There is no workaround, this is internal. The performance issue is only when you change the rows, which if that becomes too large we recommend using pagination. Regardless if you are changing the rows or contents of the datagrid quickly, I would wonder if you are using the right component for the job.

**Comment by pragesh** [comment] 2019-07-31 18:23
Okay, thanks for your response.

Is there any better component or guidelines from Clarity if the requirement is to add new rows as we fetch it from a backend? Just looking for suggestions.

**Comment by gnomeontherun** [comment] 2019-07-31 18:32
I would just profile your case and see if there is anything to worry about. You don't want 1000 rows on the page, you want a smaller number anyways because users can't make sense of that much content at once. Don't worry about premature optimization unless you are getting performance drag, and I suspect this won't be the source if you are having slow pages.

**Comment by gnomeontherun** [comment] 2021-02-01 21:45
Closing as I believe the question has been addressed and it is acting as expected.

**Closed by gnomeontherun** 2021-02-01 21:45 UTC
Labels: component: datagrid, priority: 1 low
