### ISSUE TITLE
Disabled buttons are broken in core ver 5.4.0

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#6080] opened 2021-06-16 16:13 UTC
## Describe the bug

Before 5.4.0 it was possible to use the `disabled` property on `<cds-button>`. With 5.4.0 this binding is no longer allowed and the alternative `attr.disabled` doesn't work correctly.

## How to reproduce

**Behaviour in 5.3.0**

Clicking the first button toggles the `disabled` property of the second button. The second button can be clicked when it's not disabled.

https://stackblitz.com/edit/clarit-angular-node-disabled-buttons

**Behaviour in 5.4.0**

Clicking the first button makes the second button disabled but it can never be re-enabled. (This example uses `[attr.disabled]` because the `[disabled]` binding is not valid.)

https://stackblitz.com/edit/clarit-angular-node-disabled-buttons-54?

## Expected behavior

Either the behaviour from 5.3.0 should continue or `[attr.disabled]` should work.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by mathisscott** [comment] 2021-06-16 21:33
It appears the `@cds/angular` package isn't removing the need for `CUSTOM_ELEMENTS_SCHEMA` as we'd hoped (at least in relation to this angular v12 app).

The workaround now is...

1. Add `import '@cds/core/button/register.js';` to your `app.component.ts`
2. Pull `CUSTOM_ELEMENTS_SCHEMA` from `@angular/core` into your `app.module.ts`
3. Make sure to import it into `@NgModule` by adding `schemas: [CUSTOM_ELEMENTS_SCHEMA]` to your imports in the module.
4. Get rid of `[attr.disabled]` in `app.component.html`. You don't need it. As the demo shows, `[disabled]` works fine.

[Link to working stackblitz](https://stackblitz.com/edit/clarit-angular-node-disabled-buttons-54-vh9jfl?file=src%2Fapp%2Fapp.component.html)

I'm closing this for now. I don't believe we have Angular 12 support yet. So my working assumption is that we will address the `CUSTOM_ELEMENTS_SCHEMA` problem by the time we've settled that.

CC: @Shijir @gnomeontherun

**Comment by grahamford** [comment] 2021-06-17 14:43
Thanks for looking at this Scott 👍 

For now, I'll stick with 5.3.0 until Angular 12 support is ready.

**Comment by gnomeontherun** [comment] 2021-06-17 15:50
@Shijir can you take a look at this, didn't we have a recent fix around this?

**Comment by Shijir** [comment] 2021-06-22 19:49
I've just detected that the `disabled` property is missing from the `custom-elements.json` file that we use to generate `cds-button` angular directive.

**Comment by grahamford** [comment] 2021-07-27 14:03
I've been holding off moving from 5.3.0 to avoid adding `CUSTOM_ELEMENTS_SCHEMA` to the various modules in our application. Are you able to give us an idea when a fix might get merged in for the missing `default` property on `cds-button`?

**Comment by bdryanovski** [comment] 2021-08-20 10:51
@grahamford I gonna need to do a little more investigation on the root cause of the issue and are there any other side-effects of it.

When it comes to the use of `[attr.disabled]` to make it work correctly you need to change it like that: 

`[attr.disabled]="someVar || null"`  -  the `null` part will remove the attribute `disabled` when needed 

Else you are generating `disabled="false"` that is equal to `disabled="disabled"` or `disabled`(only) that is making the browser think this mist be disabled. 

This is also valid for `readonly`, `checked` and almost all internal HTML attributes - by setting them to `null` Angular will remove them from the DOM structure.

**Closed as completed** 2021-08-30 17:39 UTC
Labels: flag: has workaround, Dependency Regression, @cds/angular
