### ISSUE TITLE
Nested tab links display in wrong position in 10.0.1

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#1345] opened 2017-08-22 03:17 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When we have nested tabs, it works as expected. In my case, it should be:

<img width="409" alt="screen shot 2017-08-22 at 10 36 19 am" src="https://user-images.githubusercontent.com/6769465/29546847-3bddb31c-8729-11e7-99fb-91d0b6ca12fd.png">

### Actual behavior
The nested tab links display in wrong position. They appears in their parent's position:
<img width="420" alt="screen shot 2017-08-22 at 10 38 12 am" src="https://user-images.githubusercontent.com/6769465/29546926-a2cee622-8729-11e7-8533-a100556c7c12.png">

### Reproduction of behavior
Working plunker:
https://plnkr.co/edit/ohidbkZD4wnofeauUpdC

Note that it was working well in 0.10.0. A recent change introduces the bug.

### Environment details

* **Angular version:** 4.3.4

* **Clarity version:** 0.10.1

* **OS and version:** Mac OS X 10.11.4

* **Browser:** [ Chrome 60 ]

**Comment by jeeyun** [comment] 2017-08-23 23:45
This only happens when we use `*clrIfActive` on `clr-tab-content`and the content is being created dynamically. In that scenario, looks like our contentChildren is grabbing all of the descendent links and projecting it incorrectly. 

@h657070128: for now, if you are ok with the tab content being created eagerly, your plunkr will work if you remove the `*clrIfActive` directive in your markup. We'll look into a possible fix for this so that this works correctly even when using the directive.

**Comment by h657070128** [comment] 2017-08-24 03:16
@jeeyun Thanks for your suggestion. But in my case I have to use `*clrIfActive` to programmatically set active tab. Is there a way to achieve this without using `*clrIfActive`? That is, I do not need lazy load tab contents, but I have to find a way to programmatically set active tab.

**Comment by gnomeontherun** [comment] 2018-01-24 17:37
I just tested the plunkr but using the latest 0.10.x and the bug does not appear any longer. The 0.10.1 does reproduce this once you view the private tab, but not 0.10.21. I'm going to mark this as resolved, unless there is an updated example to demonstrate the issue with later 0.10 releases.

**Closed by gnomeontherun** 2018-01-24 17:37 UTC
Labels: !!, ClarityNG, Investigation required, bug
