### ISSUE TITLE
Datagrid sliders are visible in dropdown content 

### ISSUE THREAD

**Issue by jokarmus** [vmware/clarity#2081] opened 2018-03-16 12:09 UTC
[x ] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Opened dropdown covers all content behind dropdown content.

### Actual behavior
Datagrid column sliders are visible in the content of opened dropdown.

### Reproduction of behavior
[reproduction](https://clarity-light-theme-v11-ws4u44.stackblitz.io/)

![sliders-dropdown](https://user-images.githubusercontent.com/37440709/37519757-9fd14f9e-291a-11e8-8475-11de9fc85ee1.png)

### Environment details
* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** Windows 10

* **Browser:** [all? | Chrome 64.0.3282.186 | Firefox 64.0.3282.186| IE 11.309.16.99.0| Mobile Chrome 65.0.335.109 |  iOS 11.2.6 Safari  ]

**Comment by adityarb88** [comment] 2018-03-16 13:35
@jokarmus: This looks like a duplicate of this issue: https://github.com/vmware/clarity/issues/1631

Please subscribe to #1631 for more updates. For now, would it be possible for you to place the dropdown outside of the datagrid? https://stackblitz.com/edit/clarity-light-theme-v11-qyt5ab?file=app/app.component.html

Closing this as duplicate.

**Closed by adityarb88** 2018-03-16 13:35 UTC
