### ISSUE TITLE
How to make dropdown list to overflow modal height?

### ISSUE THREAD

**Issue by Dead96** [vmware/clarity#2712] opened 2018-10-09 08:53 UTC
We can't figure out how to avoid modal's body to chop off the dropdown list, as in the picture below

![capture](https://user-images.githubusercontent.com/30490572/46657666-19f5f700-cbb1-11e8-81ac-207d445d6158.PNG)

the list has other 5 elements which are hidden behind the modal border, but they are reachable with the modal scrollbar (not the desired result)

How can we move the list on top of everything else? modifing dropdown z-index or its overflow doesn't change anything.

(the same thing happens with tooltips, but it's not as relevant at the moment)

**Comment by alberthoekstra** [comment] 2018-10-09 18:55
I think you have to make the height of your body (the element that's containing the input elements) larger, so your modal gets bigger and the popup has enough space to show.

Or maybe play with the [z-index](https://www.w3schools.com/cssref/pr_pos_z-index.asp) on the drop-down element. I'm not sure it will work tho.

**Comment by ildoc** [comment] 2018-10-10 08:18
I've the same problem

z-index doesn't change anything and I don't want to make the modal bigger because it will have too much unused blank space

**Comment by gnomeontherun** [comment] 2018-10-10 14:16
Modal content has an `overflow:hidden` styling that clips content like this, we have another issue which is essentially the same ticket #931.

Another possible culprit is using the old grid (`.row` and `.col` classes), which also clip. I recommend that you increase the min-height of the modal for now to accommodate the dropdown.

I'm going to close this as a duplicate of #931 but you can also use StackOverflow to ask questions about your specific implementation.

**Closed by gnomeontherun** 2018-10-10 14:16 UTC
