### ISSUE TITLE
Lazy Row Rendering in Data grid

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#4923] opened 2020-08-19 08:50 UTC
## Summary
Data grid support to render only rows that are visible to keep the DOM light and improve rendering performance.
This is a hybrid way similar to virtual scroll grids but with pagination support. 

- What is the change?
Rendering only the rows that are visible. Removing rows from DOM as they go out of the viewport.

- Why should it go in Clarity?
Clarity Data grids are used with large volume of data. With User interfaces growing complex, it is important to keep the DOM light. This is not something application specific and looks generic enough to be part of a library.

- Does this change impact existing behaviors? If so how?
1. DOM would only have rows that are visible/about to become visible.
2. This might make scroll to be little sluggish in some cases.

- If this change introduces a new behavior, is this behavior accessible?
Need investigation

## Use case
Clarity Data grid offers expand row feature, with a page size of 50 and detail section becoming complex (Too many components per row), the expand operation on multiple rows becomes slow from rendering perspective. Having virtual rendering would help initialize components lazily thus improving performance.
https://stackblitz.com/edit/clarity-scrollbar-expandall?file=src/app/app.component.html

## Examples
Not sure if people are doing pagination + virtual scroll. But virtual scroll typically include rendering only rows that are visible.

## Workarounds
Currently , less ideal workound is to  make the  _clr-row-detail_ render lazily from consumers by manually handling this.
In Angular, using a structural directive that renders a template only when another element (row) becomes visible.

This request extends the idea to have lazy rows which doesn't seem to have a workaround.

**Comment by bbogdanov** [comment] 2020-08-19 10:36
#41

**Comment by bbogdanov** [comment] 2020-08-19 13:06
#41

**Comment by hippee-lee** [comment] 2020-08-19 15:28
@bbogdanov - this seems a tiny bit different from infinite scrolling. The main difference I see here is that the ask is for the datagrid, with a large number of rows and overflow, to only render a set amount of rows in the DOM and re-use them for the row data as a user scrolls through the array if row items. I think thatvirtual scroll would re-use the existing dom nodes, like iOS does for  UITableViewController. I believe the ask here is to detect visible rows when datagrid has rows that overflow and only display data from the the visible rows. Is that correct @tarangkhandelwal ? 

We had done some POC work around infinite scrolling that investigated a virtual scroll utility but it was tied to the infinate scrolling pattern. E.g - new data is fetched when the scrolling reaches a specific height. Infinite scrolling has not been developed for several reasons, primarily because of accessibility issues. We have some notes on this because it regularly comes up as a request: https://github.com/vmware/clarity/wiki/Virtual-Scrolling

**Comment by tarangkhandelwal** [comment] 2020-08-19 18:55
@hippee-lee  Yes I think the understanding is correct. The idea was to have a mix of Pagination + Virtual rendering within a page. With clr-row-detail there could be few rows visible at  a time in the viewport. Datagrid can potentially render only the visible ones at start and as the user scrolls can start rendering the ones about to become visible ?

**Comment by gnomeontherun** [comment] 2020-08-19 20:52
While this is not a complete duplicate of #41, it does retain virtually (see what I did there?) all of the technical and accessibility concerns. What we would need to do here is build a prototype of this behavior, work with accessibility to ensure it can be done in a way that is accessible, and understand what tradeoffs have to be made to make it work. I understand its technically possible, but there are a lot of side effects and design questions that arise as well.

I've seen teams implement this hybrid approach in their own applications without the help of Clarity. We're not planning to make any significant changes like this to the Datagrid in the very near term, so I'll leave this open for context.

**Comment by gnomeontherun** [comment] 2021-02-03 20:31
Given the complexity of this ask and the availability of workarounds, I don't think we'll pursue this as part of Clarity Angular. Pagination is the recommendation for scaling large datagrids and anything beyond that going to require applications to handle it on their end in an accessible manner. I'm going to close this as something we won't deliver with Clarity Angular.

**Closed by gnomeontherun** 2021-02-03 20:31 UTC
Labels: @clr/angular, component: datagrid, flag: has workaround, status: under consideration, type: enhancement
