### ISSUE TITLE
Typeahead

### ISSUE THREAD

**Issue by tpronschinske** [vmware/clarity#2959] opened 2018-12-20 01:45 UTC
## Typeahead

I see you only have static select lists. Creating a dynamic drop down with filtering would be a great new feature.

**Comment by gnomeontherun** [comment] 2018-12-20 02:53
Thanks for the request. To help us out in the future please use our issue templates to fill in appropriate detail. 

I’m going to close this as a duplicate of #248 which describes the functionality you are seeking.

**Closed by gnomeontherun** 2018-12-20 02:53 UTC
