### ISSUE TITLE
Not possible to listen upon hidden changes on hideable column in datagrid

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#4227] opened 2020-01-24 10:08 UTC
## Describe the bug

Using `*clrDgHideableColumn` directive in a datagrid column, I can't detect changes with `(clrDgHiddenChange)`.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-ztzjys

## Additional notes

How can I properly detect changes upon show/hide columns? I know there is nothing in the Docs, but in the source code I could find the emitter: https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-hideable-column.ts#L78

Is there no official way to listen upon hidden changes?

**Comment by gnomeontherun** [comment] 2020-01-25 01:56
This seems like a duplicate of https://github.com/vmware/clarity/issues/2117, please follow it for updates.

**Closed by gnomeontherun** 2020-01-25 01:56 UTC

**Comment by ninodinatale** [comment] 2020-01-27 09:12
Actually, the `(clrDgHiddenChange)` is being triggered if used correctly:

```html
<clr-dg-column>
    <ng-template
            [clrDgHideableColumn]="{hidden: false}"
            (clrDgHiddenChange)="columnHiddenChange()">
          Column title
    </ng-template>
</clr-dg-column>
```

**Comment by namitabandal** [comment] 2020-05-25 07:37
I am using latest version (3.1.2) of clarity. and facing the same issue 
(clrDgHiddenChange)="columnHiddenChange()" is not getting trigger if we change the column display.
Can anyone please guide me exactly how to use it ?
Note: we need to use hide/show column property in this way *clrDgHideableColumn and not in [clrDgHideableColumn]. Otherwise hide/show is not working.

My HTML code:
<clr-dg-column>
          <ng-container 
                *clrDgHideableColumn="{hidden: false}"
                (clrDgHiddenChange)="clrDgHiddenChange($event)">
                Name
          </ng-container>
</clr-dg-column>

**Comment by Cryptonex7** [comment] 2020-08-18 07:29
> Actually, the `(clrDgHiddenChange)` is being triggered if used correctly:
> 
> ```
> <clr-dg-column>
>     <ng-template
>             [clrDgHideableColumn]="{hidden: false}"
>             (clrDgHiddenChange)="columnHiddenChange()">
>           Column title
>     </ng-template>
> </clr-dg-column>
> ```
> 
> Therefore I wouldn't say it's a duplicate of #2117.

I cannot get your code snippet working. Can you reproduce this in a code sandbox - maybe stackblitz?
