### ISSUE TITLE
Column resizer is broken in clr-data-grid

### ISSUE THREAD

**Issue by basalingayyakaramadi** [vmware/clarity#6288] opened 2021-08-24 04:43 UTC
## Describe the bug

Table column header is broken when we do resize of the column.  

## How to reproduce

1. Create table using clr-data-grid and add filters to column and have min 5 column
2. Add language translate to column header
3. Change the language from chrome setting for browser and run your application.
4. Try to resize the column and observe the behaviour.

## Expected behavior

Column header should not be broken when we do resize of column.

## Versions

**Clarity project:**

- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x

**Framework:**
- [ ] Angular

**Framework version:**
_ie: Angular 12_

**Device:**
Chrome
![resizer-issue](https://user-images.githubusercontent.com/36897446/130556916-e9418f4c-5f8d-47c8-bb4c-5441f5e08066.png)

## Additional notes

_Add any other notes about the problem here._

**Comment by bbogdanov** [comment] 2021-08-26 12:23
Hi @basalingayyakaramadi, 

Would you please provide us a stackblitz example? Thank you in advance.

https://stackblitz.com/@clr-team

**Comment by basalingayyakaramadi** [comment] 2021-08-27 05:21
@bbogdanov  Please find the stackblitz link. Let me know if you need few more info.
https://stackblitz.com/edit/clarity-light-theme-v5-y1x2cm?file=src%2Fapp%2Fapp.component.html

**Comment by basalingayyakaramadi** [comment] 2021-08-30 11:08
@bbogdanov let me know if you need any help.

**Comment by bbogdanov** [comment] 2021-08-30 12:07
Hi @basalingayyakaramadi,

From what I observe this behaviour only appears when the sorting is triggered and the icon of the sorting is shown. 

Our resize functionality is not triggered when the sorting is triggered and this leads to overlapping space between neighbour column headers.

Here is a workaround that will help in your scenario:

```
::ng-deep clr-dg-column[aria-sort='ascending'],
::ng-deep clr-dg-column[aria-sort='descending'] {
  width: auto !important; // We set `width` as a style attribute on resize so in this case `important` is needed
}
```

Demo: https://stackblitz.com/edit/clarity-light-theme-v5-67bc44?file=src%2Fapp%2Fapp.component.scss

**Comment by basalingayyakaramadi** [comment] 2021-08-30 12:35
Thanks @bbogdanov . I will try workaround.

**Comment by basalingayyakaramadi** [comment] 2021-08-30 14:40
@bbogdanov the problem with width: auto. is, once width is set and then its not able to resize column.

**Comment by bbogdanov** [comment] 2021-08-30 16:27
> @bbogdanov the problem with width: auto. is, once width is set and then its not able to resize column.

You are right. I'll take a deeper look to see if the we can do something on our side.

**Comment by basalingayyakaramadi** [comment] 2021-09-27 06:01
Hi @bbogdanov , Please let me know if there is any update on this.

**Comment by bbogdanov** [comment] 2021-10-04 11:14
After some investigation and discussion with the team.

This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritised. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases. The Datagrid in `@cds/core` is likely to be released in the end of the month and will resolve this issue by design.

**Closed as completed by bbogdanov** 2021-10-04 11:14 UTC
Labels: type: bug, component: datagrid, @clr/angular
