### ISSUE TITLE
Provide a possbility to listen to hideable change in columns in v2.0

### ISSUE THREAD

**Issue by spitfjre** [vmware/clarity#3427] opened 2019-06-07 11:57 UTC
## Summary

In v1.x you could listen to the hideable change in columns accessed via datagrid. This is now not possible anymore. Since the documentation is missing for that feature, what is the proposed way in v2.0? The ColumnsService could provide this functionality as far as i can see, but its not accessible.

Feedback or updating the docs is appreciated.

## Use case

Possibility to save hidden columns and persist them.

**Comment by gnomeontherun** [comment] 2019-06-07 17:37
This is a duplicate of https://github.com/vmware/clarity/issues/2117. Please follow that issue for a workaround. Also https://github.com/vmware/clarity/issues/2094 is probably how we'll solve this. You correctly identified the column service which is a refactoring that makes the above work easier to accomplish.

**Closed by gnomeontherun** 2019-06-07 17:37 UTC
Labels: Duplicate

**Comment by lolgans** [comment] 2019-09-06 09:07
Actually all workarounds are not feasible any more, because the `column.hidden` field was removed in version 2.0. Atm we workaround by injecting the columnsService directly in a really hacky way, like this: 
`private columnsService: ɵcs`. But this can not be the solution. Any hints on how to do it properly are highly appreciated.

**Comment by gnomeontherun** [comment] 2019-09-09 19:42
@lolgans you're right, that isn't a great solution. We refactored a lot internally that will capture the state of columns in one place (still a little work to do there), but we haven't exposed this. Another workaround could be to manually query the DOM to check the columns that are visible when you need to capture that state, hacky but unless we expose that input/output binding it is difficult to access.
