### ISSUE TITLE
use h5 element for timeline step titles of demo and doc for a11y purpose

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#4694] opened 2020-06-02 05:51 UTC
## Describe the bug

Use `h5` elements instead of the `span` elements for the demo and doc of timeline step titles.

## How to reproduce

For the v2-introduced timeline component, the step titles are enclosed in `span` elements in the demo and doc.

## Expected behavior

As the class and the doc desciption implies, they are titles of timeline steps. Is it better to use `h5` elements for a11y purpose?

## Versions

**App**

- Clarity: [v2 & v3]

**Comment by gnomeontherun** [comment] 2020-06-03 21:09
We can't set a header element by default, because we don't know the document outline. An application could do this on their end, though there might be slight font changes that might have to be adjusted. Our accessibility audit did not make this recommendation previously, and I don't believe that makes sense in many cases where the timeline is not really acting like a content heading.

Closing as works as intended but you could put a header element if your needs are different.

**Closed by gnomeontherun** 2020-06-03 21:09 UTC
