### ISSUE TITLE
Weird outline of focused button

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#5794] opened 2021-04-04 12:49 UTC
## Describe the bug
Outline of button has weird shape when focused inside button group

## How to reproduce

```html
<div class="btn-group">
  <button class="btn">First</button>
  <button class="btn">Second</button>
  <button class="btn">Third</button>
</div>
```

![image](https://user-images.githubusercontent.com/1386622/113509121-8375d700-955c-11eb-8791-386ebd368e9a.png)

You can reproduce in official page:
https://clarity.design/angular-components/button-group/

![image](https://user-images.githubusercontent.com/1386622/113509114-778a1500-955c-11eb-8df1-46b3e221d0cf.png)

## Expected behavior

Non weird consistent outline.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type:  MacBook
- OS: Big Sur 11.2.3
- Browser: chrome
- Version: 89.0.4389.114

**Comment by bbogdanov** [comment] 2021-04-05 15:04
Hi @ph55,

A community member last week merged a PR to solve this issue. Expect the fix to arrive with the next Clarity release.

I am going to close this issue as a duplicate of #5446

**Closed as completed by bbogdanov** 2021-04-05 15:04 UTC
Labels: resolution: duplicate, type: support
