### ISSUE TITLE
Table width calculation bug

### ISSUE THREAD

**Issue by jwangyangls** [vmware/clarity#4015] opened 2019-11-14 04:04 UTC
When I add a row in the datagrid by binding the data, one of the cell letter symbols is very long (beyond the cell that has been displayed at the moment), and the table is partially refreshed (for example, two rows before, now three rows) , but the resulting cell length has not changed, the excess content overflows. But if the entire page is refreshed, you get the perfect form.
![image](https://user-images.githubusercontent.com/29826789/68829440-dccd3400-06e3-11ea-8016-91467e5c6cf9.png)

![image](https://user-images.githubusercontent.com/29826789/68825884-c1a7f780-06d6-11ea-8de6-79ced388579f.png)

Angular: [8.2.0]
* Node: [16
* Clarity: [2.2]

**Comment by hippee-lee** [comment] 2019-11-14 16:51
Can you provide a reproduction so I can take a look at working code? 
We have had several issues raised in the past (1136, #1065, #815, #618) that might be related. But, without a reproduction it is hard to tell.

**Comment by jwangyangls** [comment] 2019-11-15 08:54
![image](https://user-images.githubusercontent.com/29826789/68929352-25115280-07c7-11ea-8ee9-7dbf1dfc9ad3.png)
![image](https://user-images.githubusercontent.com/29826789/68929851-18d9c500-07c8-11ea-8b52-d06bb7ae3de0.png)
![image](https://user-images.githubusercontent.com/29826789/68929981-67875f00-07c8-11ea-9a9c-723294769269.png)
![image](https://user-images.githubusercontent.com/29826789/68930095-a0273880-07c8-11ea-8b52-e44319c81e1f.png)

**Comment by hippee-lee** [comment] 2019-11-15 16:07
Thanks for the images but it is difficult to see what is actually going on. Can you please provide a reproduction on [stackblitz](https://stackblitz.com/@clr-team)? There are several features that could be affecting this and its hard to investigate with only an image.

**Comment by GaryHyland** [comment] 2019-11-17 23:05
I use the following in order to break these long strings (no spaces, hyphens etc to trigger a logical wrap) for cols that may contain such unusual long strings.

<clr-dg-cell style="word-wrap:break-word">

**Comment by jwangyangls** [comment] 2019-11-18 03:34
https://10.161.148.123
u:  yawang  p: Password123
![image](https://user-images.githubusercontent.com/29826789/69022717-30e35b80-09f7-11ea-8746-44b7265bfbea.png)
![image](https://user-images.githubusercontent.com/29826789/69022792-6e47e900-09f7-11ea-97d5-d8e1b206be22.png)

**Comment by hippee-lee** [comment] 2019-11-18 18:54
@jwangyangls -  Sorry but I'm hesitant to go to that url, the security certificate is not trusted by my computer's operating system. 

The reason for asking to see a simple reproduction in Stackblitz is that it enables me to investigate the code besides seeing it in the browser. I suspect that the issue you are having is related to the `word-wrap` vs `word-break` behavior that has already been discussed. But, without actually seeing code that demonstrates the behavior I can't be sure.

**Comment by jwangyangls** [comment] 2019-11-19 02:09
@hippee-lee  We are also a VMware project -- Harbor, deployed on a ubuntu virtual machine, using a self-signed certificate. You may not be able to access it because your Mac has been upgraded. If you need to see it, you can place a website certificate. Once you get the list of trusts, you can access them. I think the reason for this problem is what you think.

**Comment by hippee-lee** [comment] 2019-11-19 17:44
Ok, in that case it's up to the app to decide how to handle cell content like that (long unbroken strings) and override the default datagrid behavior. 

For the history of this please refer to the issues mentioned earlier (#1136, #1065, #815, #618)

What I believe the app will need is

```css
.datagrid-cell {
  word-break: break-all;
}
```

This will break the content but be aware that this will have a side effect on normal text if its appled to other content in the cells so you may want to target it to only the columns with text like this. The other option is to ellipsis the content in the datagrid-cell but please refer to the previous discussion for UX and technical issues related to that approach. 

I'm closing this as has a workaround. If you feel this is still an issue, please isolate and recreate the behavior in stackblitz so we can work with and discuss the application code.

**Closed by hippee-lee** 2019-11-19 17:44 UTC
Labels: status: needs reproduction
