### ISSUE TITLE
The ellipsis of 'clr-dg-action-overflow' and arrow of 'expand row' are NOT displayed in the datagrid view

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#886] opened 2017-05-11 05:59 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
ellipsis of 'clr-dg-action-overflow' and arrow of 'expand row' should appear in the datagrid view after datagrid loaded and initialized.
![2017-05-11 1 36 30](https://cloud.githubusercontent.com/assets/5753287/25934178/e115aae6-364e-11e7-9db0-fd27857d0e73.png)

### Actual behavior
The ellipsis of 'clr-dg-action-overflow' and arrow of 'expand row' are NOT displayed in the datagrid view.

See snapshot:
![2017-05-11 1 35 36](https://cloud.githubusercontent.com/assets/5753287/25934148/c36459f2-364e-11e7-9060-d3c5dd5c7070.png)

After click the datagrid view, the missing things will appear again.

A fun case is, the problem might be related with the data list used to render grid view. 
E.g:
  users: User[];

If uses is initialized with empty array and fill data later, the bug will reproduce.
users:User[] = [];

If the uses is initialized with at least item, the problem will be gone.
users:User[] = [{
  id: 1,
  name: "demo",
  ...
}];

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/jMCyX9

Please note that, not reproduce the bug in plnkr because the version of Angular is 2. We adopt 4.

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:**  Mac 10.11.4

* **Browser:** ALL

**Comment by youdz** [comment] 2017-05-11 14:59
A couple things: 
- The plunker correctly uses Angular 4, so I don't understand your comment saying you can't reproduce.
- Your components in the plunker try to load non-existing SCSS files, so nothing works. It just fails with the error `Failed to load app/grid.component.scss`. Please post a working plunker next time, or we can't investigate.

I think this is yet another duplicate of #744, so I'm going to close as such.

**Closed by youdz** 2017-05-11 14:59 UTC

**Comment by steven-zou** [comment] 2017-05-12 02:46
@youdz 

I saw the tag in plunker is 'Angular 2'.
The bug appear on my Chrome 51 browser with Angular 4 and Clarity 0.9. Still existing but really did not reproduce in the plunker demo.

Checked, it's duplicated with #744. I agree to close this issue but the problem should have a solution as it is a real existing issue.
