### ISSUE TITLE
Modal is incompatible with Firefox.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#739] opened 2017-04-18 03:40 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
Mask layer doesn't mask the whole background.
![image](https://cloud.githubusercontent.com/assets/5027302/25113513/a015ebfe-242a-11e7-86e7-47dee3e7f6a4.png)
[https://vmware.github.io/clarity/documentation/modals](https://vmware.github.io/clarity/documentation/modals)

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.0

* **OS and version:** macSierra

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-04-21 21:02
@wknet123 : My guess is this is a duplicate of #617. I'm closing this one as such.

**Closed by mathisscott** 2017-04-21 21:02 UTC
