### ISSUE TITLE
Clear Date Picker value on form reset using clrDate

### ISSUE THREAD

**Issue by rdvojmoc** [vmware/clarity#2724] opened 2018-10-12 07:59 UTC
What is a correct way to reset (placeholder is visible again) Date picker componet?

I'am setting component value like this:
`<input type="date" [(clrDate)]="date" autocomplete="off">`

In `reset` method  date is set as follows `this.date = null;`

Complete [example](https://stackblitz.com/edit/clarity-light-theme-v012-d5xivg?file=src%2Fapp%2Fapp.component.ts) on stackblitz.

**Comment by youdz** [comment] 2018-10-12 12:46
This seems to be a duplicate of #2474. This is a known bug in our date picker, and you reporting it actually raises its priority. :)

Please follow the linked issue for updates.

**Closed by youdz** 2018-10-12 12:46 UTC
