### ISSUE TITLE
Datagrid undesirably triples its height when changing the paginator's page size.

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1241] opened 2017-08-02 05:03 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The height of the grid is fixed to 100% equal to the height of the page. The page size of the paginator is currently set to 50. When you change the page size to 10, the height should be the same.

### Actual behavior

Changing the datagrid page size from 50 to 10 (or any page size) will expand the height of the data grid all the way to the bottom of the page which makes the paginator or bottom edge of the datagrid invisible.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Please see screen recording on this link: [https://drive.google.com/file/d/0B-aBfOkZhZJpcmdoZTVWV1ItQUk/view?usp=sharing](https://drive.google.com/file/d/0B-aBfOkZhZJpcmdoZTVWV1ItQUk/view?usp=sharing)
### Environment details

* **Angular version:** 4.0.X

* **Clarity version:**  0.0.10-alpha.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-08-02 13:24
Hi @whizkidwwe1217 
I know you don't really like to hear about [the plunkr thing](https://plnkr.co/uNwwZe). But without one, it makes it difficult for us to tell if this is an issue on our end or with custom sizing CSS/host component code on yours.

Oftentimes, when an issue shows up with a plunkr, you will see us able to either (a) identify the problem and offer a workaround or solution (even if it isn't an issue in Clarity) or (b) recognize the severity/impact of an issue and prioritize it accordingly. Frequently, this process takes minutes. And someone who is experiencing a problem can typically set up a plunkr in 30-45 minutes.

By contrast, issues that don't have a plunkr can languish for days or weeks as we go back and forth trying to figure out what the actual issue is. In some cases, we have tried on our own to create plunkrs for other people. Sometimes this works out. A lot of times it doesn't and becomes a complicated game of plunkr Battleship as we try to guess how people are doing something. Which again, takes days or weeks and consumes hours on our end of creating plunkr after plunkr after plunkr.

**Comment by whizkidwwe1217** [comment] 2017-08-02 14:08
@mathisscott It can be easily replicated using server side data grid. I even set the height of the datagrid with a fixed height of 200-400px. When I click the "Set Page size to 10", the grid stretches all the way to the bottom. Please take a look at this plunkr:  [https://plnkr.co/edit/VQIYST?p=preview](https://plnkr.co/edit/VQIYST?p=preview)

**Comment by adityarb88** [comment] 2017-08-16 13:39
Potential duplicate of #1084. @hippee-lee  please verify

**Comment by hippee-lee** [comment] 2017-08-16 18:14
Closing as duplicate of #1084. Please follow that issue for resolution.

**Closed by hippee-lee** 2017-08-16 18:14 UTC
Labels: bug, ClarityNG
