### ISSUE TITLE
clr-modal does not recreate/destroy children nodes when open/closed

### ISSUE THREAD

**Issue by coli** [vmware/clarity#215] opened 2016-12-09 20:27 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Generally you'd expect the dialog to be recreated when opened and destroyed when closed. Eg: init directive such as autofocus won't currently run when dialog is opened. Workaround is adding ngIf to the dialog.

### Actual behavior
Currently clr-modal open/close is shown/hidden.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment] 2017-05-17 20:36
This is a duplicate of the work described in #895

**Closed by mathisscott** 2017-05-17 20:36 UTC
Labels: ClarityNG, duplicate
