### ISSUE TITLE
Datagrid filter text input focus style inconsistency

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2114] opened 2018-03-28 09:40 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Text input focus should show the same styling across all browsers.
In firefox text input focus is showing double underlined which should be single underlined.

### Actual behavior
FireFox:(underline Issue) 
![image](https://user-images.githubusercontent.com/12848838/38021052-782f9f80-3299-11e8-9949-989f077a423c.png)
![image](https://user-images.githubusercontent.com/12848838/38021253-fc6dc858-3299-11e8-8912-fff6f214c113.png)

Chrome:
![image](https://user-images.githubusercontent.com/12848838/38021084-8f4fa304-3299-11e8-9975-05503a89ddf5.png)

 IE11:
![image](https://user-images.githubusercontent.com/12848838/38021130-aa14aaae-3299-11e8-81e7-31aab4f5449e.png)

### Reproduction of behavior
You can check in official documentation
https://vmware.github.io/clarity/documentation/v0.11/datagrid/full

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**0.11.x

* **OS and version:** windos

* **Browser:** Firefox 57.0.4

**Comment by adityarb88** [comment] 2018-03-28 15:38
@shravansofts: I am using the same version too but I dont see this issue:

![image](https://user-images.githubusercontent.com/1426805/38039931-60abf966-327c-11e8-8fe0-87c3a1ec74e9.png)

![image](https://user-images.githubusercontent.com/1426805/38039961-71109ba4-327c-11e8-8057-ab83b50a8f28.png)

**Comment by adityarb88** [comment] 2018-03-28 15:39
I do see it happening when I zoom to 150% though:

![image](https://user-images.githubusercontent.com/1426805/38040067-b4e467e8-327c-11e8-9256-d28d5bd88d94.png)

**Comment by adityarb88** [comment] 2018-03-28 15:42
BTW, this looks like a duplicate of this issue: https://github.com/vmware/clarity/issues/1672

Please subscribe to #1672 for more info. Closing this as duplicate.

**Closed by adityarb88** 2018-03-28 15:42 UTC
Labels: Needs Triage

**Comment by shravansofts** [comment] 2018-03-29 04:47
@adityarb88 For me it is the other way.
I don't have zoom-in on my firefox browser, this issue appears in normal mode. If I Zoom-in browser, it is showing single line only. Refer gif below:
![filter_style_issue](https://user-images.githubusercontent.com/12848838/38070594-622f7f38-333a-11e8-81c3-6ebac059b11b.gif)

Below is my Windows 10 display settings:
![image](https://user-images.githubusercontent.com/12848838/38070583-52ccddb0-333a-11e8-8222-3bffeb5dda8f.png)
