### ISSUE TITLE
selection.toggleAll removes the displayed items from Datagrid's list

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#4298] opened 2020-02-19 13:36 UTC
## Describe the bug

I am trying to introduce select all items functionality from all pages of the datagrid and possibly to update selectionChanged only once.
- Method 1: I use setSelected(item: T, selected: boolean): void; the selection works as expected but I want to avoid the multiple updates of selectionChanged.
- Method 2: I use updateCurrent(value: T[], emit: boolean): void; selectionChanged is updated once but the side effect is described below.

## How to reproduce

1.  Go to 'https://stackblitz.com/edit/clarity-light-theme-v2-2v2blj-datagrid-selectall-urdvgb'
2.  See the total number of datagrid items
3.  Click on 'select all - method2'
4.  Click on the checkbox which toggles the item selection on the current page
5.  See the total number of datagrid items

If you repeat step 3 and 4 multiple times it will continue to remove items from the datagrid.

## Expected behavior

datagrid items count should not be changed after trigger on selection.toggleAll

## Versions

**App**

* Angular: [8.2.0]
* Clarity: [2.1.0]

**Device:**

* Type: [PC]
* OS: [Windows 10]
* Browser [Chrome, Firefox]
* Version [79, 72]

## Additional notes

I also tried direct updates of datagrid.selected list instead of calling updateCurrent(value: T[], emit: boolean): void; but the result of removing items by selection.toggleAll remained the same.

**Comment by gnomeontherun** [comment] 2020-02-19 19:03
The issue is you are hitting some internals and that isn't the recommended way to manage the selection. The simplest way to do this, and the way that we expect, is to just set the `selected` binding so we capture the new selection and process it correctly.

Hitting internals like this skips some of the checkpoints that the bindings have in place to correctly manage the state, hence the buggy behaviors. 

See https://stackblitz.com/edit/clarity-light-theme-v2-2v2blj-datagrid-selectall-qk7bjn?file=src/app/app.component.html for a working demo. Closing as not a bug.

**Closed by gnomeontherun** 2020-02-19 19:03 UTC
