### ISSUE TITLE
Tree View acting slow for more than 1000 elements

### ISSUE THREAD

**Issue by ProgFroz** [vmware/clarity#3665] opened 2019-08-05 12:47 UTC
## The Problem

Currently I have a recursive Tree with about 5000 Elements. When expanding a node, the tree stutters and expands very slow. Here are some Screenshots of using the Firefox Profiling Tool. You can clearly see a lot of re-drawing and re-sizing over and over.

![NodeExpandingPerformance1](https://user-images.githubusercontent.com/14117860/62465015-3ee5d700-b78e-11e9-9767-a0591437c822.png)
![NodeExpandingPerformance2](https://user-images.githubusercontent.com/14117860/62465023-43aa8b00-b78e-11e9-9255-fc785cf255f8.png)

## How to reproduce

It is easily reproduced with the most basic recursive tree and about a thousand nodes with each having some children.

## Expected Behavior

I expect a clear and smooth animation when expanding a node.

## Versions

**App**

* Angular: 7.2.9
* Clarity: v2

**Device:**

* OS: Windows 10
* Browser: Edge, Firefox and Chrome

**Comment by hippee-lee** [comment] 2019-08-05 15:24
Is your tree leveraging `*clrIfExpanded` (lazy loading for the child nodes)? 
Can you post a stackblitz with minimal code to reproduce the results above?

**Comment by ProgFroz** [comment] 2019-08-06 07:59
I tried both lazy and non-lazy, it did not change anything.
I set up a StackBlitz, but it keeps throwing the error 'TypeError: Cannot read property 'model' of null'.
https://angular-zbwfwn.stackblitz.io/

**Comment by dorthrithil** [comment] 2020-02-21 10:53
I experienced the same problem with a tree of around 600 nodes. After using `*clrIfExpanded` everything worked smooth as butter.

**Comment by gnomeontherun** [comment] 2020-02-21 23:39
The Stackblitz had 100,000 items being loaded (1000 top level, each with 100 children), so I would expect it to be pretty slow or crash. Stackblitz has been slow for me today too. Is this still an issue though? Can we have a better reproduction?

**Comment by Shijir** [comment] 2020-02-22 00:33
If you load any interactive elements let alone angular components in a large number such as 1000s, it will take a while to render them. That's why we offer `*clrIfExpanded` to keep the collapsed node children to be removed from the DOM. Also, it's worth considering the UX side of projecting a TreeView with such a huge number of nodes.

**Comment by mdmarkova** [comment] 2020-10-07 14:05
We're hitting the same issue and I was about to log a new bug when I saw this one. The use case that we have is one root element that is expanded by default and its children are more than 6000. In that case *clrIfExpanded won't help at lll since the children of the parent (it is expanded) have to be rendered. I guess that having onPush mechanism on tree node might help.

Stackblitz: check here https://clr-tree-slow-rendering-new-options.stackblitz.io/

**Comment by NedyalkaD** [comment] 2020-11-26 21:34
Please, raise the priority for this issue. Clarity tree is a few times slower (definitely underperforming) compared to current component we use.

**Comment by Jinnie** [comment] 2020-11-30 15:17
We spent some time on this today, together with @bbogdanov.
Initial research shows that the biggest delay in the stackblitz provided by you, comes from the tree nodes animations. If we substitute BrowserAnimationsModule to NoopAnimationsModule in our tests, we can observe noticeable improvement. Further, the profiling shows some activity related to the rendering of the Clarity icons. 
In the next days we will do more comparative analyses, but we will take the animations and icons out of the testing scenarios.

**Comment by mdmarkova** [comment] 2020-11-30 15:33
> We spent some time on this today, together with @bbogdanov.
> Initial research shows that the biggest delay in the stackblitz provided by you, comes from the tree nodes animations. If we substitute BrowserAnimationsModule to NoopAnimationsModule in our tests, we can observe noticeable improvement. Further, the profiling shows some activity related to the rendering of the Clarity icons.
> In the next days we will do more comparative analyses, but we will take the animations and icons out of the testing scenarios.

I've also noticed that. If the tree does not have expandable nodes i.e. does not have any "arrow" icon the performance is better because no animation and rotation are done for all nodes.  Rotating the "arrow" icon for 6,000 items triggers angular digest cycle many time, recalculating the page layout and shifting the layout for every node which freeze the UI at some point. It might be helpful if there is a way to render the tree at chunks which will not freeze the UI and the user will see that something is rendering on the screen.

**Comment by Jinnie** [comment] 2020-11-30 15:42
And @gnomeontherun suggested a better way to locally disable animations on the host side without meddling with the animation providers
```
<clr-tree [clrLazy]="true" [@.disabled]="true">
   .......... 
```

**Comment by Jinnie** [comment] 2020-11-30 15:48
@mdmarkova though tempting, the partial rendering is a technique, which similarly to virtual loading, we don't plan to employ so far. Mainly for the same reasons - the accessibility and usability problems associated.

**Comment by mdmarkova** [comment] 2020-11-30 15:53
@Jinnie, I understand that, but my opinion is that it is not ok to wait everything to be calculated, shifted, animated and so on in order to render everything (a big amount of data at once) on the screen. For me, as a user, it's better to see items which fit on my screen quickly instead of waiting forever. I will try the approach you've suggested and compare the results with animations on.

**Comment by gnomeontherun** [comment] 2020-12-07 21:22
A major fix to help speed up performance has been added, and together with the ability to disable the animations on the app side when necessary, we expect this to be resolved. Closing as shipped in v3 and v4, and if issues remain please create additional examples with the latest versions to review.

**Closed by gnomeontherun** 2020-12-07 21:22 UTC
Labels: status: needs triage
