### ISSUE TITLE
User should be able to resize Clarity Data gird columns with keyboard 

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#3970] opened 2019-11-04 11:53 UTC
## Summary

Clarity grid provides ability to resize the width of the columns with the mouse.
User should be able to resize Clarity Data gird columns with keyboard  

* What is the change?
When user navigates to a column heading inside a data grid one should be able to resize the width of the column pressing left and right arrows.
 
* Why should it go in Clarity?
It is a basic requirement for accessibility compliance - https://www.w3.org/TR/WCAG20/#keyboard-operation
* Does this change impact existing behaviors? If so how?
No
* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case

I am keyboard only user and I want to resize the width of the data grid column

## Examples

could not find any

## Workarounds

no exact workaround, user can resize the column with the mouse

**Comment by gnomeontherun** [comment] 2019-11-04 12:56
This is a duplicate of #3372, so I'm going to close this in favor of the original report. Thanks for the report!

**Closed by gnomeontherun** 2019-11-04 12:56 UTC
