### ISSUE TITLE
Can't build the seed project as is

### ISSUE THREAD

**Issue by blackdust21** [vmware/clarity#562] opened 2017-03-06 18:13 UTC
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Getting an environment property error while building the app with ng-server command

### Actual behavior
When I download the seed project or install clarity on an angular cli project, I'm not able to build/serve it. It might be a version number issue. Please advise
It gives me this error:
$ ng serve
Environment configuration does not contain "environmentSource" entry.

### Reproduction of behavior
Download seed project from the github and try to serve it

### Environment details

* **Angular version:** 2.0.X
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

* **Clarity version:** 
Couldnt find how to get that

* **OS and version:** 
mac osx Yosemite

* **Browser:** [all ]

**Comment by Shijir** [comment] 2017-03-06 18:20
This is a duplicate of the error that is already notified by one of our users. And we have a fixing PR ready for it. 

https://github.com/vmware/clarity-seed/pull/40

**Closed by Shijir** 2017-03-06 18:20 UTC

**Comment by blackdust21** [comment] 2017-03-06 18:25
Thank you for the quick response. I'll make the change in my angular-cli.json file.

**Comment by blackdust21** [comment] 2017-03-06 18:25
It works.
