### ISSUE TITLE
[1.0] P4 font parameters doesn't match form label font

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2881] opened 2018-11-26 14:03 UTC
## Describe the bug

Form labels, when used together with input/select/password/textarea components, are different to what you'll get with `<label class="p4">Label</label>`.
P4 class has font-size of 0.5rem, whereas real form labels have bigger font.

## How to reproduce

[Example](https://stackblitz.com/edit/clarity-light-theme-v1-0-qdgr5m?file=src/app/app.component.html)

## Expected behavior

Based on a description in docs, p4 class should match form labels.

## Versions

**App**

* Angular: [e.g. 7]
* Clarity: [e.g. 1.0.0 beta 2]

**Device:**

* Type: [PC]
* OS: [Windows 10]
* Browser [Chrome]
* Version [70]

**Comment by gnomeontherun** [comment] 2018-11-26 18:48
This is a duplicate of #2540, so closing in favor of that one.

**Closed by gnomeontherun** 2018-11-26 18:48 UTC
