### ISSUE TITLE
[Accessibility enhancement] Arrow key navigation in tree view component

### ISSUE THREAD

**Issue by charpour** [vmware/clarity#2574] opened 2018-08-22 08:51 UTC
## Summary

Navigation using the arrow keys in a tree 

* What is the change?
**Enable arrow key navigation within a tree to enhance accessibility**
* Why should it go in Clarity?
**Better accessibility**
* Does this change impact existing behaviors? If so how?
**No, existing behavior shouldn't be affected**
* If this change introduces a new behavior, is this behavior accessible?
**N/A**

## Use case

**User selects a node from a big tree with many nodes, and upon selection another component displays some properties based on the selection. Without tree navigation using arrows, the user has to go through all of the remaining nodes in the tree using the Tab key, before getting a chance to focus on other components outside the tree (like the one that displays the properties of the selected node).** 

## Examples

**N/A**

## Workarounds

**N/A**

**Comment by gnomeontherun** [comment] 2019-07-02 21:15
Marking this as a duplicate of #3569

**Closed by gnomeontherun** 2019-07-02 21:15 UTC
Labels: Accessibility, Needs UX Input
