### ISSUE TITLE
Tabbing through clr-stack-view with improper change of content

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#5642] opened 2021-02-23 14:26 UTC
## Describe the bug

Tabbing through clr-stack-view is changing the content to be the next focus element within clr-stack-content without expanding the clr-stack-block.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-yfq2th?file=src%2Fapp%2Fapp.component.html

1.  Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-yfq2th?file=src%2Fapp%2Fapp.component.html'
2.  Click on 'Stackview Header'
3.  Press 'TAB' so you focus the first row '> Block label'
4.  Press 'TAB'
5.  Press 'TAB'
6.  Observe how the content changes

## Expected behavior

We should not access the clr-stack-content or at least expand clr-stack-block if an element within is focused.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10.2.4

**Device:**

- Type: [e.g. MacBook]
- OS: [mac os & win10]
- Browser [any]
- Version [any]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2021-02-23 18:57
This sounds like a duplicate of #4718.

**Comment by iivanovgit** [comment] 2021-02-24 09:38
> This sounds like a duplicate of #4718.

It looks like a duplicate but in #4718 you say that it will be fixed in the next minor of v4 since Jan and it is still not there. Also nothing related to stack-view in the patch notes

**Comment by Jinnie** [comment] 2021-02-25 09:15
CC @bbogdanov Bogdan, can you please check if this needs backporting: https://github.com/vmware/clarity/issues/4718

**Comment by Jinnie** [comment] 2021-02-25 10:06
It was confirmed to that https://github.com/vmware/clarity/issues/5615 has the same cause. Both issues may be closed with the same backport.

**Comment by Jinnie** [comment] 2021-02-25 17:11
It's backported now to v4.

**Closed as completed by Jinnie** 2021-02-25 17:12 UTC
Labels: resolution: fixed, component: stack view, @clr/angular
