### ISSUE TITLE
Horizontal and vertical scrollbars appear when dropdowns are used in header-actions

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [vmware/clarity#1317] opened 2017-08-17 10:57 UTC
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
When dropdowns are used in header-actions, horizontal and vertical scrollbars appear. These scrollbars disappear after clicking on the action button on the header.

### Expected behavior
These scrollbars should not appear.

### Reproduction of behavior
https://plnkr.co/edit/13kOG9?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.10.0

* **Browser:** [ Chrome  | Firefox ]

**Comment by adityarb88** [comment] 2017-08-17 14:17
@soumyakantiroychowdhury: Could you please try using the `*clrIfOpen` directive along with the `clr-dropdown-menu`. That should fix the issue. I will still keep this issue open because this is a bug with Clarity UI. We need to mark the dropdown menu as `display: none` instead of `visibility: hidden`

**Comment by youdz** [comment] 2017-08-17 15:57
`display: none` won't let the dropdown (or tooltips, which is a better use case) be read inline by screen readers.

What about just making sure `position: absolute` is always set on the dropdown menu, and keep `visibility: hidden`? The content would still be read inline by screenreaders, but the positioning would ensure the element is taken out of the flow of the page so we wouldn't have unwanted scrollbars anymore.

**Comment by soumyakantiroychowdhury** [comment] 2017-08-18 07:43
Thanks Aditya. Your suggestion worked.

**Comment by adityarb88** [comment] 2017-08-21 13:40
@youdz: `.dropdown-menu` already has `position: absolute` irrespective of whether its open or not. It still occupies that space as you can see in the screenshot below or if you inspect the plnkr in the issue description :-(

![image](https://user-images.githubusercontent.com/1426805/29521688-86763e56-8654-11e7-8fba-e5e9037e9521.png)

**Comment by adityarb88** [comment] 2017-08-22 18:28
Duplicate of #1232. Closing this issue. Please subscribe to #1232 for more updates.

**Closed by adityarb88** 2017-08-22 18:28 UTC
Labels: bug, ClarityUI
