### ISSUE TITLE
Ability to specify the initial/default sort column for a datagrid

### ISSUE THREAD

**Issue by BigBadaboom** [vmware/clarity#3833] opened 2019-09-18 17:18 UTC
This was requested a long time ago in issue #492, and later closed as a duplicate of #355.  However as far as I can see, that was a mistake, because that request was never implemented.

Currently, if you specify `clrDgSortBy` on multiple columns, there doesn't seem to be a way to tell the datagrid component which of those columns to use by default.  As far as I can see it is always the last (rightmost) `clrDgSortBy` or `clrDgField` that is used.

The only option seems to be to do the sorting yourself initially. Then let the datagrid take over.    But of course, if you do that, you won't get the ASC/DESC indicator on the column, until the first re-sort.

**Comment by gnomeontherun** [comment] 2019-10-03 14:29
We only support sorting by one column, so you should only set the one column you want to use by default or it uses the last one in the list. That is why those issues were closed because they work for a single column scenario. As far as a multi-column sorting that is captured in https://github.com/vmware/clarity/issues/1067 and I refer you to that issue since that is how you'd get the support you're requesting.

Closing this as a duplicate of https://github.com/vmware/clarity/issues/1067

**Closed by gnomeontherun** 2019-10-03 14:29 UTC
Labels: resolution: duplicate, type: enhancement
