### ISSUE TITLE
When using clrDgHideableColumn and clrDgColumnToggle, how do I get a list of the visible columns when you check a new column?

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#2514] opened 2018-08-03 04:32 UTC
**Select one ...** (check one with "x")

```
[ ] bug
[ X ] feature request
[ ] enhancement
```

### Expected behavior

When I select new columns to be displayed from the `clrDgColumnToggle`, it would expect an output to fire so that I can add that to my my list of columns that user wants to see next time they come to this screen

### Actual behavior

When a user selects a new column from the `clrDgColumnToggle`, the column appears in the UI. However, I need to be able to get an event with that new column so that I can add/remove it from the list of viewable columns that I save to the localStorage. 

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v012-2ifrlj

This shows the issue I am seeing. You can select a new column to show, but because of the way that I am painting the `clrDgCell`, I need an event telling me the that the column has been showed/hidden so that I can add/remove it from the UI. In addition, I want to save the selected columns to the localStorage so that the next time they come back, it can be like they left it. 

I am hoping that this already works, and you can just show me my blindness.

**Comment by aaronfrost** [comment] 2018-08-03 04:59
Even if we gotta get a change in to make this work, please help me work past it... please.

**Comment by aaronfrost** [comment] 2018-08-03 05:02
I found this where @youdz agrees that we should expose an output. https://www.bountysource.com/issues/60412553-usage-of-clrdghideablecolumn-with-server-driven-datagrid

**Comment by aaronfrost** [comment] 2018-08-03 05:09
I see that this may have already been entered as a feature. Feel free to close, if that is the case.

**Comment by gnomeontherun** [comment] 2018-08-03 13:55
You can also see https://github.com/vmware/clarity/issues/2117 for details and a workaround for now https://github.com/vmware/clarity/issues/2204#issuecomment-383210477

**Comment by gnomeontherun** [comment] 2018-08-03 14:06
Marking this as a duplicate of #2117

**Closed by gnomeontherun** 2018-08-03 14:06 UTC
Labels: Duplicate
