### ISSUE TITLE
Password clear text icon wrapping to newline inside a timeline

### ISSUE THREAD

**Issue by AlicePain** [vmware/clarity#5515] opened 2021-01-26 16:28 UTC
I posted this issue yesterday and was asked to create a stackblitz example. I can't figure out how to install Clarity 4 and when installing clarity 5 I get stackblitz errors.

Here's directions to reproduce in stackblitz. 
1) open this url https://stackblitz.com/edit/clarity-v3-dark-theme-r12emw?file=src%2Fapp%2Fapp.component.html
2) replace the app.component.html with the below code. 
3) the clear text eye icon wraps to a newline and is too large.

`<clr-timeline clrLayout="horizontal"> <clr-timeline-step clrState="success"> <clr-timeline-step-title><a routerLinkActive="disabled" routerLink="personal-info">Create your account</a></clr-timeline-step-title> <clr-timeline-step-description> <div class="clr-row"> <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-6"> <h3>Primary administrator</h3> Please enter information <clr-password-container> <label>Password *</label> <input clrPassword name="password" required /> </clr-password-container> <clr-password-container> <label>Confirm password *</label> <input clrPassword name="confirmpassword" required /> </clr-password-container> </div> </div> </clr-timeline-step-description> </clr-timeline-step> </clr-timeline>`

**Comment by AlicePain** [comment] 2021-01-26 17:36
I'm using Clarity v4, Angular 11. But this seems to happen in other version of Clarity and Angular as well.

**Comment by Jinnie** [comment] 2021-01-27 11:23
Thank you for providing a better reproduction and details.

I see where the problem is coming from. We need more specific css selectors in the component. And this _is_ a bug.
Trying to find the initial designs, I see that we already have this issue logged (https://github.com/vmware/clarity/issues/5366), so I'll link and close this one to avoid duplication.
Please, follow 5366 for updates.
Also, in your specific case, you want to add configuration steps to the timeline steps, which should work much better with the stepper component. We don't explicitly discourage what you want to do, but by design the timeline is more passive and informative, with only a limited set of action buttons in selected steps. In addition to our website, you can see the initial specs here:
https://github.com/vmware/clarity/issues/1633

**Closed as completed by Jinnie** 2021-01-27 11:23 UTC
