### ISSUE TITLE
How to apply multiple validation on single input?

### ISSUE THREAD

**Issue by theromie** [vmware/clarity#581] opened 2017-03-10 06:54 UTC
I want to apply multiple validation on single input. Ex. Like email with empty and pattern validation. 
```
<label for="emailname"
                        aria-haspopup="true"
                        role="tooltip"
                        class="tooltip tooltip-validation tooltip-md tooltip-top-left"
                        [class.invalid]="useremail.invalid && (useremail.dirty || useremail.touched)">                                                                
                        <input type="email" placeholder="Email Address" name="user_email" id="user_email" [(ngModel)]="user_email" #useremail="ngModel" required pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$">
                        <span class="tooltip-content">
                            Email is Required.
                        </span>
```
This working correct with both validation but how can i show different messages for each validation?

**Comment by Shijir** [comment] 2017-03-10 09:49
@theromie Angular has really a good comprehensive documentation on [Form Validation](https://angular.io/docs/ts/latest/cookbook/form-validation.html). The validation you want can be implemented without much effort as it looks like Angular provides [built-in validators](https://github.com/angular/angular/blob/38cb526f60f910ddbdb532639a03b57d9da378c5/modules/angular2/src/common/forms.ts#L36) for  `RequiredValidator`, `MinLengthValidator`, `MaxLengthValidator`, and `PatternValidator`.

**Comment by theromie** [comment] 2017-03-10 10:30
I know that but i want to do it clarity way.
`<span class="tooltip-content">
            Email is Required.
</span>`
content should be change
`<div class="form-block">
                                        <label for="vendorname"
                                            aria-haspopup="true"
                                            role="tooltip"
                                            class="tooltip tooltip-validation tooltip-md tooltip-top-left"
                                            [class.invalid]="vendoremail.invalid && (vendoremail.dirty || vendoremail.touched)">                                                                
                                            <input type="email" placeholder="Email Address" name="vendor_email" id="vendor_email" [(ngModel)]="vendor_email" #vendoremail="ngModel" size="50" required pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$">
                                            <span class="tooltip-content" [hidden]="!vendoremail.errors.required">
                                                Email is Required.
                                            </span>
                                            <span class="tooltip-content" [hidden]="!vendoremail.errors.pattern">
                                                Invalid Email.
                                            </span>
                                        </label>
                                    </div>`
this giving me error of required is not known property

**Comment by Shijir** [comment] 2017-03-10 17:24
@theromie you might need to have your validation messages in `*ngIf`.

**Comment by theromie** [comment] 2017-03-11 05:14
`
<div *ngIf="fullName.errors && (fullName.dirty || fullName.touched)">
                            <span class="tooltip-content" [hidden]="!fullName.errors.required">
                                Full Name is Required.
                            </span>
                            <span class="tooltip-content" [hidden]="!fullName.errors.pattern">
                                Only Alphabets allowed.
                            </span>
                        </div>
`
Cannot read property 'errors' of undefined

**Comment by Shijir** [comment] 2017-03-11 06:20
That means your template reference variable is wrong so it's not accessing the element or component. 

Also, as you are not asking Clarity related questions, but angular support questions, I am closing this issue.

**Closed by Shijir** 2017-03-11 06:20 UTC

**Comment by z3phyro** [comment] 2017-07-17 15:34
Hi @Shijir  ... i'm can't show multiple validations either... and it doesn't throw me any errors in developers console or else.... 

i tried many set-ups finnally this is the last variant I tried i just wanted to see if it added the text this is it when the input is required... and it didn't worked

`            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <label for="Email" aria-haspopup="true" role="tooltip" [class.invalid]="form.controls['Email'].touched && !form.controls['Email'].valid"
                    class="tooltip tooltip-validation tooltip-md">
                <input class="form-control" type="email" id="Email" placeholder="Email" size="45" [(ngModel)]="employee.Email" formControlName="Email">    
                <span class="tooltip-content">
                    <div>
                        <div *ngIf="form.controls['Email'].hasError('required')">
                            this doesn't works
                        </div>
                        Email is required or has an invalid format
                    </div>
                </span>
                </label>
            </div>`

**Comment by z3phyro** [comment] 2017-07-18 12:20
Hi I would really appreciate some feedback on this it appears that the "validation control" to call it some way.... is making a copy of the "initial state" of his content and then it doesn't vary depending on the input validation state.... So with the code I entered above it only shows the red popup rectangle. Completely empty.

**Comment by adityarb88** [comment] 2017-07-18 13:41
@z3phyro: Please file a separate issue with a plnkr and a clear description of the issue that you are facing. We have examples of how you can use Clarity validation with Angular here:
https://vmware.github.io/clarity/documentation/forms

![image](https://user-images.githubusercontent.com/1426805/28319839-041e77c4-6b9d-11e7-826a-8fa4de95e9c2.png)

If your validation is showing an empty red tooltip then it means that you are mostly not toggling the `.invalid` class correctly. But there is no way to confirm that without a working plnkr. You can use this plnkr template: https://plnkr.co/uNwwZe to replicate the issue.

**Comment by z3phyro** [comment] 2017-07-18 19:21
hey @adityarb88 thx for the advice to reproduce the error on plunker... doing it I manage to make it work... been honest I still don't know what I was doing wrong... but I'm new to Angular 2 so ... I'll left here the example that worked for me just in case there is another person with a similar problem. 

The code is irrelevant at least what I got wrong before was the html part. Here is the example that does works

```
 <label for="Email" aria-haspopup="true" role="tooltip" [class.invalid]="form.controls['Email'].touched && !form.controls['Email'].valid" class="tooltip tooltip-validation tooltip-md">
                <input tabindex="4" class="form-control" type="email" id="Email" placeholder="Email" size="45" formControlName="Email">
                <span class="tooltip-content">
                    <div *ngIf="form.controls['Email'].touched && form.controls['Email'].hasError('required')">
                        Email is required 
                    </div>
                    <div *ngIf="form.controls['Email'].touched && form.controls['Email'].hasError('email')">
                        Email  has an invalid format
                    </div>
                </span>
              </label>
```
