### ISSUE TITLE
display problem of date picker

### ISSUE THREAD

**Issue by liyang010813** [vmware/clarity#4429] opened 2020-03-30 12:10 UTC
create a new angular project to test this bug, please repair.
![微信图片_20200330200113](https://user-images.githubusercontent.com/31497640/77910875-70358900-72c2-11ea-87e8-f300a0350910.png)

**Comment by martinbrom** [comment] 2020-03-30 12:23
Could you please provide more details as to what is the expected behavior of the issue you are having? Without any details no one can possibly know what is the issue. It would also be helpful if you provided a StackBlitz or similar with the reproduction of your problem. You can use this StackBlitz: https://stackblitz.com/edit/clarity-v3-light-theme.

**Comment by gnomeontherun** [comment] 2020-03-30 16:02
@liyang010813 thanks for reporting. This is a duplicate of issue with #4272, so please watch it for a fix and workaround.

In the future when you submit a bug, we require an isolated demo using Stackblitz to confirm the behavior, otherwise it is often impossible to know what is wrong by just a screenshot. Please follow our bug report template and it will help us to address and triage bugs much faster for you.

Closing as duplicate.

**Closed by gnomeontherun** 2020-03-30 16:02 UTC

**Comment by liyang010813** [comment] 2020-03-31 01:53
@martinbrom @gnomeontherun Thank you for your response. Thank you
