### ISSUE TITLE
Date picker is shown behind datagrid filter

### ISSUE THREAD

**Issue by mrmokwa** [vmware/clarity#6001] opened 2021-05-26 18:16 UTC
## Describe the bug

Date picker inside Datagrid filter is always shown behind the filter.

![image](https://user-images.githubusercontent.com/12090931/119710636-f3a22a00-be34-11eb-9a3f-88d87d576c7f.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-xujszm?file=src/app/datagrid/datagrid.component.html

1.  Click on the shipping column filter
2.  Click on the calendar to open the date picker
3.  See error

## Expected behavior

Should be opened in front of the datagrid filter.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11.2.5

**Device:**

- Type: [e.g. Desktop]
- OS: [e.g. Windows 10]
- Browser [e.g. Chrome]
- Version [e.g. 90]

## Additional notes
The default `<input type="date"/>` from browsers (firefox/chrome) works as expected

**Comment by bdryanovski** [comment] 2021-05-27 09:13
@mrmokwa Thank you for reporting this.

**Comment by Jinnie** [comment] 2021-06-02 12:16
Duplicate of #4827

**Closed as completed by Jinnie** 2021-06-02 12:16 UTC
Labels: type: bug, @clr/angular, component: date-picker
