### ISSUE TITLE
How can I correctly set the predefined configurations to the Datagrid with a 'server side' mode

### ISSUE THREAD

**Issue by alpha1988** [vmware/clarity#3121] opened 2019-02-19 13:24 UTC
## Describe the bug

I can not correctly set all predefined or 'start' configurations to the datagrid table if I have some with using 'server-side' mode

## How to reproduce
I have Datagrid with pagination, filtration , sorting.
Also I have a such case: 
- I come to this page with some query params on the url that halps me to set all needed predefined configurations to the DataGrid.
- Also i have data from resolver that will displaying in this data grid, that was processed on the server with all needed params.

I set all that I can. That in result trigger 'on Refresh' event on the Datagrid.
On handler of this 'on Refresh' event I set a new queryParams and make re-route with new params to get new data with a 'fresh' filters on resolver at routing.

So HOW TO SET NEW START CONFIGS to the Datagrid without trigger onRefresh event because it's removes some of the previouse start configurations.

## Versions

**App**

* Angular: 6
* Node: 10.15.0
* Clarity:  0.13

**Comment by gnomeontherun** [comment] 2019-02-20 16:09
If you could provide a reproduction demonstration of this it would help us to prioritize looking into this issue. Generally we ask that questions are posted to StackOverflow, which this might apply here. However, there might be a bug but if you help us with a demo it will help us better understand.

**Comment by youdz** [comment] 2019-02-20 22:18
This looks like a duplicate of #2094 to me. Until we offer this single-point input, yes, the only solution right now is to manually set each piece. When you do this, I recommend ignore any `clrDgRefresh` output that happens _before_ your own component `ngAfterViewInit()`.

**Closed** 2019-02-20 22:18 UTC
Labels: Duplicate
