### ISSUE TITLE
How to iterate and display multiple column wise detail rows for an expanded row?

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2060] opened 2018-03-10 18:15 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[] feature request
[] enhancement
```

### Expected behavior
I want to show row(parent) and its related children in expanding row as shown below:
![image](https://user-images.githubusercontent.com/12848838/37250390-776f201e-2521-11e8-972a-70dc8094e264.png)

### Actual behavior
Using custom component and ngProjectAs="clr-dg-row-detail" syntax it is not possible to loop.

Issue link
https://stackblitz.com/edit/clarity-datagrid-row-expand-iterate-issue?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 5.2.x

* **Clarity version:** 0.11.x

* **OS and version:** all

* **Browser:** all

**Comment by gomesjj** [comment] 2018-03-11 19:20
@shravansofts  I am not sure how the "my-detail" component would generate a loop on its own, but an ng-template with ngFor works just fine. See [this](https://stackblitz.com/edit/clarity-datagrid-row-expand-iterate-issue-bnumse?embed=1&file=app/app.component.html).

Please correct me if I've got the wrong end of the stick…

Jose

**Comment by shravansofts** [comment] 2018-03-12 04:08
@gomesjj Thanks for the workaround.
my-detail component had the ngFor directive inside its .html file.

But how could we make it work using a custom component for the same?
Let's say I got the below usecase in future. I have to show some info after children as shown below:
![image](https://user-images.githubusercontent.com/12848838/37265297-80660c5c-25d8-11e8-8608-e706ec5f828d.png)
Which could be achieved as shown in below link. But going with a custom component will be a cleaner and better approach for extensibility in future.
https://stackblitz.com/edit/clarity-datagrid-row-expand-iterate-issue-query2?file=app/app.component.html

**Comment by gomesjj** [comment] 2018-03-12 07:25
@shravansofts I see what you mean now.

Somehow I missed the app.detail.component.html file… The only issue you had there was the wrong ngFor syntax used on an ng-template. [This](https://stackblitz.com/edit/clarity-datagrid-row-expand-iterate-issue-hnabrs?file=app%2Fapp.component.html) is what you need.

**Comment by adityarb88** [comment] 2018-03-12 14:04
@gomesjj: Thanks for taking the time to answer the debug the issue! We really appreciate it.

@shravansofts: I believe you could also use `ng-container` inside of the `my-detail` component:
```
<ng-container *ngFor="let child of children">
	<clr-dg-row-detail *clrIfExpanded>
		<clr-dg-cell>{{child.username}}</clr-dg-cell>
		<clr-dg-cell>{{child.fullName}}</clr-dg-cell>
		<clr-dg-cell>{{child.role}}</clr-dg-cell>
	</clr-dg-row-detail>
</ng-container>
```

Closing the issue based on the solution provided by @gomesjj. @shravansofts please feel free to reopen the issue if you have more questions. Also another good place to ask `how to` questions is on StackOverflow with the `vmware-clarity` tag. We monitor StackOverflow regularly and filing a question over there also helps other users in the community. Thanks!

**Closed by adityarb88** 2018-03-12 14:04 UTC

**Comment by shravansofts** [comment] 2018-03-12 15:42
@gomesjj Thanks a lot man!
@adityarb88 thanks for the tip on ng-container and stackoverflow. :+1:

**Comment by shravansofts** [comment] 2018-03-13 05:47
@adityarb88 We are using clarity for vCenter plugin development.
When we are using the inline/custom component syntax and doing a data refresh event.
This cannot be replicated in standalone mode(stackblitz). It is showing in vCenter plugin.
We are getting the following error. Can you have a look at actual clarity implementation for any null check missing?

![image](https://user-images.githubusercontent.com/12848838/37324505-c8c58f72-26af-11e8-9c25-eb6b58c41f31.png)

**Comment by youdz** [comment] 2018-03-13 14:17
@shravansofts: This error indicates you are somehow destroying the row before it even had time to initialize. In other words, you're creating a row, and then halfway through the initialization lifecycle, you destroy it immediately. That's something that should not happen, and reveals that there is a problem somewhere in your app.

We had a similar issue a while back, with someone wanting to add extra null checks to suppress an error they had, but it was decided against it because early fails like that help you debug before you hit issues that are impossibly hard to investigate. Here is the link if you're interested in the conversation: #151.

**Comment by shravansofts** [comment] 2018-03-16 06:49
@youdz Please find a sample angular project(based on plugin-seed 0.9.8 by [vmware](https://labs.vmware.com/flings/vsphere-html5-web-client?download_url=https%3A%2F%2Fdownload3.vmware.com%2Fsoftware%2Fvmw-tools%2Fvsphere_html_client%2FHTML+Client+SDK+Fling+Overview+and+Release+Notes-6094542.pdf#changelog)) that and implemented a sample Users Listing with datagrid row expand feature.
Now as a standalone webapp also it is throwning error while navigating to next page as shown below:
![image](https://user-images.githubusercontent.com/12848838/37507130-253dd902-2913-11e8-9c92-97c0ce33b67d.png)
This is a different error from the above one.

**Steps to run project:**
prerequisite: 
node.js version 6.9 or higher 
- npm install
- npm install -g json-server 

Run: 
1. start json-server to get mock data and load local message bundles(cmd terminal #1)
npm run json-server
2. run the plugin in dev mode and watches your files for live-reload (cmd terminal #2)
ng serve

Code Files path "testplugin-ui\src\app\users"

**Here is the project seed with code**
[testseed-ui.zip](https://github.com/vmware/clarity/files/1818159/testseed-ui.zip)

Please let me know what is wrong in this code/clarity code.

Thanks,
shravan

**Comment by youdz** [comment] 2018-03-16 15:19
@shravansofts: Both this error and the one before don't seem to be Clarity errors, they're due to an issue in the app's code. On top of that we can't download, install and build projects just to debug them, that would take way too much time.

Because of this, I recommend you ask your question on StackOverflow with the tag `vmware-clarity`, with a StackBlitz reproducing the issue. There is absolutely no reason for you to be able to reproduce the bug in a project but not in StackBlitz, and since this isn't a Clarity bug we shouldn't have this conversation here on GitHub.

**Comment by shravansofts** [comment] 2018-03-16 16:09
@youdz how do you say it is not clarity bug?
if I comment <user-row-detail [children]="user.child" ngProjectAs="clr-dg-row-detail"> line.
It's working fine.

As I need to have a rest api server, I had done as a standalone project.
I don't think it will take days of your time to download and run.

**Comment by gnomeontherun** [comment] 2018-03-16 16:27
The best way to report bugs is with a simple isolated StackBlitz. You don't need a server, replace that with static data. It took me 5 minutes to do, and I concur with @youdz that it is not an issue with Clarity but with your lifecycle management of your components. I'd start by reviewing your observables and any async behaviors.

https://stackblitz.com/edit/clarity-light-theme-v11-7e6mxm?file=app/app.component.html

**Comment by shravansofts** [comment] 2018-03-16 16:42
@gnomeontherun Thanks for looking into it. I had done the same thing without service call and in-build refresh mechanism(say a refresh button which fetches and updates data) which works fine as yours and the error occurs on click of next page.

This seed is given by VMware itself. I had followed the same way of observable how other components(monitorComponent) are there in seed project. Please let me know what is wrong in that.
This will be very helpful for us.

**Comment by gnomeontherun** [comment] 2018-03-16 17:59
The seed is most basic, it doesn't even have Observables https://github.com/vmware/clarity-seed/search?q=Observable&type=Code&utf8=%E2%9C%93 so I'm not sure what exactly you're pointing to. 

We cannot spend time triaging people's applications, but this error usually means you are changing the value of something twice, so look at your logic for refreshing the page contents for any place you might be setting a value more than once in a change detection cycle.

**Comment by shravansofts** [comment] 2018-03-16 18:06
I'm talking about vmware plugin seed.
https://labs.vmware.com/flings/vsphere-html5-web-client?download_url=https%3A%2F%2Fdownload3.vmware.com%2Fsoftware%2Fvmw-tools%2Fvsphere_html_client%2FHTML+Client+SDK+Fling+Overview+and+Release+Notes-6094542.pdf#changelog

**Comment by gomesjj** [comment] 2018-03-16 19:17
@gnomeontherun I am not disagreeing with your stance and I think that @shravansofts could have provided a better plunker for troubleshooting. But, to be fair, from my tests so far I have noticed that the errors only occur when pagination is enabled and the clr-dg-row-detail is part of a different component. That occurs whether the data is static or not...

I haven't been able to fully troubleshoot yet because I myself am not much experienced in Typescript and Angular. I will keep trying though, as it is a good learning exercise… :-)

**Comment by gomesjj** [comment] 2018-03-19 15:18
@shravansofts I have added an answer to your question on StackOveflow.

**Comment by shravansofts** [comment] 2018-03-20 03:51
Here is the stackover flow link for reference:
https://stackoverflow.com/questions/49325539/need-help-in-multiple-ui-issues-in-angular-project-with-clarity-framework/49331238#49331238
