### ISSUE TITLE
Issue with consistent state change for tree-view

### ISSUE THREAD

**Issue by harshabhat86** [vmware/clarity#1634] opened 2017-10-24 01:15 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Checking a top level node should check bottom level nodes till the leaf node even when the nodes are collapsed.

### Actual behavior

The clarity documentation has this bug already, so showing the gif from there.
 In the gif below, the states of READ, MODIFY, CREATE and DELETE should change when the checkbox "Authenticated Users" is clicked, even when the expanded state is false. 
![clarity_tree_view_bug](https://user-images.githubusercontent.com/5546493/31918287-c4a4c84e-b810-11e7-93af-51f430564227.gif)

### Reproduction of behavior

https://vmware.github.io/clarity/documentation/tree-view#examples
search for "Checkbox Tree"

### Environment details

* **Angular version:** 4.4.5

* **Clarity version:**
0.10.8

* **OS and version:** 
Mac - OSx ElCapitan 10.11.6
* **Browser:** All

**Comment by adityarb88** [comment] 2017-10-24 01:31
@harshabhat86: I believe this is a duplicate of: https://github.com/vmware/clarity/issues/1400. Please subscribe to https://github.com/vmware/clarity/issues/1400 for more updates.

Closing based on this.

**Closed by adityarb88** 2017-10-24 01:31 UTC

**Comment by harshabhat86** [comment] 2017-10-24 01:45
Thanks @adityarb88 !
