### ISSUE TITLE
Update  0.8.11 break wizard in Firefox 52.0

### ISSUE THREAD

**Issue by antitoine** [vmware/clarity#617] opened 2017-03-20 12:24 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When the wizard open, we can click (next, cancel, close) and fill the form.

### Actual behavior
Unable to click in the wizard. The problem seams to be present only with Firefox (52.0).

### Reproduction of behavior
https://plnkr.co/edit/IXW8pO try it with the full view and with Firefox 52.0

![capture du 2017-03-20 13-22-00](https://cloud.githubusercontent.com/assets/10686594/24099554/447191f2-0d70-11e7-95a3-cbde6ddfcf6d.png)

### Environment details

* **Angular version:** 2.4.0

* **Clarity version:** 0.8.11

* **OS and version:** Ubuntu 16.10

* **Browser:** Firefox 52

**Comment by Shijir** [comment] 2017-03-20 20:07
@antitoine Thanks for bringing this problem to our attention. I briefly investigated the problem. It looks like the issue is only reproducible in Plunkr environment, specifically in Plunkr's non-fullscreen window. In different environments, the wizard behaves just normally.

That being said, I won't close this issue for now as I believe we need to further investigate the cause of this problem and confirm whether the issue is on our end or Plunkr's. The following screenshots are what I see in the Firefox browser on my Ubuntu OS.

The wizard shows up normally in Plunkr's fullscreen window here:
<img width="1440" alt="screenshot 2017-03-20 12 53 51" src="https://cloud.githubusercontent.com/assets/3958008/24119268/d1b4bd30-0d6d-11e7-9957-f748bcc17b0b.png">

The wizard shows up at abnormal positions in Plunkr's non-fullscreen window here:
<img width="1440" alt="screenshot 2017-03-20 12 55 03" src="https://cloud.githubusercontent.com/assets/3958008/24119271/d1d3605a-0d6d-11e7-8b4b-36e67f3cef5e.png">

**Comment by podstava** [comment] 2017-05-04 09:14
also doesn`t work on FF 53.0 with clarity version 0.9.2

**Comment by mathisscott** [comment] 2017-05-04 13:02
@podstava 
Thanks for the update. This is still in our backlog and we are looking for a way to coordinate fixing it with our other priorities.

**Comment by mathisscott** [comment] 2017-05-17 20:32
I believe this to be fixed with the changes in #907

**Closed by mathisscott** 2017-05-17 20:32 UTC
