### ISSUE TITLE
Clarity Server Side Rendering 

### ISSUE THREAD

**Issue by MatthiasSkopek** [vmware/clarity#1664] opened 2017-11-01 09:49 UTC
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I have an Clarity Angular app and with ng serve it works great. But with server side rendering in Angular 4.3.6 it crashes. 
### Actual behavior

I get this error...
**node_modules/clarity-angular/utils/template-ref/template-ref-container.js:6
import { Component, TemplateRef, ViewChild } from "@angular/core";
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)**

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** "clarity-angular": "^0.10.4",
    "clarity-icons": "^0.10.11",
    "clarity-ui": "^0.10.4",

* **OS and version:** macOS 10.13.1 Beta 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jacobbutton** [comment] 2017-11-01 13:41
From my understanding Clarity does not support Server Side Rendering. At least, it didn't use to, and I don't remember that changing. You're most likely going to have to turn server side rendering off if you wan to continue using Clarity.

**Comment by mathisscott** [comment] 2017-11-01 14:15
@MatthiasSkopek 
My understanding is that we are working on server-side rendering for after the Angular 5 release. The problem we have is that there are some native elements in a few of our components that we need to place guards around. This won't be backported but I believe it will be viable within the 0.10.x releases.

Pinging @youdz and @gnomeontherun for more details. Please close if this is a duplicate of ongoing effort.

**Comment by gnomeontherun** [comment] 2017-11-01 14:18
I'm actually working on SSR with Clarity for our documentation, and I have not seen this issue. From what I can gather this sounds like a possible configuration issue with your compiling because it is complaining about `import`.

I'm working against Angular 5.0.0-rc.7 right now and the latest Clarity. There are some things that have to be ironed out so that pages can render properly (such as a few places where we use `document`), but I'd like to support it best we can.

**Comment by MatthiasSkopek** [comment] 2017-11-02 08:04
I follow the documentation for running SSR, so i dont‘t know... an other project without an Clarity worked just fine. Should I upgrade to Angular 5 and the newest Clarity version?

**Comment by MatthiasSkopek** [comment] 2017-11-02 09:08
When I leave out --prod and --aot than it works. But now there is this error 

ClarityIconElement.prototype = Object.create(HTMLElement.prototype, { constructor: { configurable: true, writable: true, value: ClarityIconElement } });
ReferenceError: HTMLElement is not defined

With Angular 5.0.0 and Clarity 0.10.11

**Comment by gnomeontherun** [comment] 2017-11-02 14:40
I'd need to have a look at your build and configuration, if you can create a sample repo with one that is giving you trouble? I'm finding that for SSR I was able to get icons working better if I included them in the index.html instead of .angular-cli.json. I'm still investigating this so your milage may vary.

**Comment by gnomeontherun** [comment] 2017-11-02 16:00
Are you running dynamic or static rendering? Dynamic seems to work better, but static rendering causes things like icons not to display (because they don't get added unless you have a `window` object).

**Closed** 2017-11-08 15:29 UTC
Labels: ClarityNG, has-workaround, invalid
