### ISSUE TITLE
Tree node does not propagate selected status on child items if not expanded

### ISSUE THREAD

**Issue by brinton-chand** [vmware/clarity#2542] opened 2018-08-14 03:01 UTC
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Tree node correctly propagates selection state regardless of expanded state through two-way binding.

### Actual behavior

It does not.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-dark-theme-v012-gvvsjp

### Environment details

* **Angular version:** 6.1.2

* **Clarity version:** 0.12.8

**Comment by hippee-lee** [comment] 2018-08-14 15:17
I believe this is a duplicate of this issue: https://github.com/vmware/clarity/issues/1400

I'm closing this issue based on that. Please let us know if that is not the case.

**Closed by hippee-lee** 2018-08-14 15:17 UTC
