### ISSUE TITLE
open modal from API

### ISSUE THREAD

**Issue by roeeovadia** [vmware/clarity#494] opened 2017-02-16 15:09 UTC
hey 
do you have and example how to open a modal from the TS ?

10x
Roee

**Comment by adityarb88** [comment] 2017-02-16 15:16
![image](https://cloud.githubusercontent.com/assets/1426805/23026964/bd442da0-f417-11e6-9e1c-606df167c84f.png)

![image](https://cloud.githubusercontent.com/assets/1426805/23026999/dcbfa31c-f417-11e6-90f6-e5ba36b9cbff.png)


We do. Check the examples section here: https://vmware.github.io/clarity/documentation/modals

Am closing this issue but feel free to reopen it if you still face an issue.

**Closed by adityarb88** 2017-02-16 15:16 UTC

**Comment by roeeovadia** [comment] 2017-02-16 15:22
I have somthing like this : `

import { Component, OnInit, Input } from '@angular/core';
 
@Component({
	selector: 'add-dashboard',
	templateUrl: 'add-dashboard.component.html'
})

export class AddDashboardComponent {
	@Input() isOpen: boolean;
	private isOpened: boolean = false;

	constructor() {

	}
	public ngOnInit() {
		 
	}
	ngOnChanges(isOpen: isOpen) {

I want to open it from here
	}


}
`

and the HTML is `<clr-modal id="AddDashboardModel" [(clrModalOpen)]="isOpened" [clrModalStaticBackdrop]="false">
    <h3 class="modal-title">No "x" in the top-right corner</h3>
    <div class="modal-body">
        <p>Clicking on the backdrop doesn't do anything.</p>

        {{isOpen}}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" (click)="isOpened = false">
            I'm the only way to close the modal!
        </button>
    </div>
</clr-modal>
`

10x
Roee

**Comment by adityarb88** [comment] 2017-02-16 15:24
@roeeovadia: Please use the Plunkr link: https://plnkr.co/8TwwdL to replicate the issue that you are facing. I am still not sure what the issue is. Thanks!

**Comment by roeeovadia** [comment] 2017-02-16 15:33
I can understand how I get the modal instance from TS code

**Comment by roeeovadia** [comment] 2017-02-16 15:38
![image](https://cloud.githubusercontent.com/assets/1067867/23027976/ae237fae-f46e-11e6-8558-2828570cf8ed.png)

**Comment by mathisscott** [comment] 2017-02-16 15:39
@roeeovadia 

Read this... https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ref-vars

**Comment by roeeovadia** [comment] 2017-02-16 15:41
https://plnkr.co/edit/UujK6VzeADSn0ecky8xS?p=preview

**Comment by mathisscott** [comment] 2017-02-16 15:49
@roeeovadia 

https://plnkr.co/edit/7vrkfrG683q4mXGNfIhW?p=preview

Please read the angular documentation. I would prefer not to use our github issues as a substitute for stackoverflow.

**Comment by roeeovadia** [comment] 2017-02-16 15:53
@adityarb88 
10x this make it clear :+1: 
I will use stackoverflow next time 
10x again 
Roee
