### ISSUE TITLE
clrTooltipTrigger directive adds role="button" attribute by default

### ISSUE THREAD

**Issue by amoghrane** [vmware/clarity#6251] opened 2021-08-12 09:29 UTC
## Describe the bug
clrTooltipTrigger directive adds role="button" attribute by default.
Need ability to set the role="text"

## How to reproduce
Markup used:
<clr-tooltip>
    <clr-icon clrTooltipTrigger shape="info-circle" size="24" aria-label="Uniq tooltip 4"></clr-icon>
    <clr-tooltip-content clrPosition="bottom-left" clrSize="lg" *clrIfOpen>
        <span>Lorem ipsum sit</span>
    </clr-tooltip-content>
</clr-tooltip>
Please check the screen shot of dom
<img width="1118" alt="Screenshot 2021-08-12 at 2 45 47 PM" src="https://user-images.githubusercontent.com/11397445/129172266-a146bd66-0525-4dd3-ad8f-0bf65399b9a7.png">

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._
Issue is reproducible on clarity documentation 
Issue is reproducible on clarity examples
https://v4.clarity.design/documentation/tooltips

## Expected behavior
Ask is to get ability the role as text for the trigger element.  Or if the role is set on the trigger element ignore adding the role button in trigger.
_A clear and concise description of what you expected to happen._

## Versions
v4
**Clarity project:**
Clarity Angular/UI
- [ x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**
v4.0.3
- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**
Angular
- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_
Angular 10
**Device:**
Macbook
- Type: [e.g. MacBook]
 Big Sur
 Chrome
Version 92.0.4515.131

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment] 2021-08-12 12:51
The `role="button"` is an accessibility requirement. Why would you want it removed versus, say, replacing your icon-as-tooltip-trigger with an icon button?

**Comment by bbogdanov** [comment] 2021-08-12 12:51
Duplicate of #4984

**Closed as completed** 2021-08-12 14:16 UTC
