### ISSUE TITLE
Icon-friendly button classes

### ISSUE THREAD

**Issue by gssjr** [vmware/clarity#137] opened 2016-11-22 20:44 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Clarity has no button styling ideal for icon buttons in toolbars or floating action buttons.

**Comment by youdz** [comment] 2016-11-23 04:44
I believe we have actionable icons triggering a dropdown.

Yes, just found the docs: https://vmware.github.io/clarity/documentation/dropdowns#clarity-icon-as-the-dropdown-toggle

Does this correspond to your use case? Or are you looking for a pure icon button, triggering a custom action immediately on click?

**Comment by gssjr** [comment] 2016-11-28 14:23
I was referring to creating something more like a toolbar like you'd find in a text-editor or a context sensitive toolbar that may pop up like in Photoshop. As far as floating action buttons: https://material.google.com/components/buttons-floating-action-button.html

**Comment by youdz** [comment] 2016-11-28 15:56
I see... This looks like a variant of actionable elements that we don't have a design for. I'm assigning to @jaffoneh to decide which way we're going with this, and probably assign to whoever on the UX team would look at it.

**Comment by yenmade** [comment] 2016-12-28 21:34
Will add this to the UX backlog for design explorations. @gssjr It would help greatly if you could post your specific use case(s) or examples, so that we take those into consideration when we tackle this. Thanks!

**Comment by reddolan** [comment] 2017-01-05 22:36
@gssjr I see that you are looking something similar to the Material Floating Action Button (FAB). Your other comment about "icon buttons in toolbars", is this similar to [Bootstraps Button Group](http://getbootstrap.com/components/#btn-groups)? Something where you would have icons grouped together for actions?

**Comment by reddolan** [comment] 2017-01-18 16:44
@gssjr wanted to circle back with you to see if you have had time to review the previous couple comments here. Your answers will help us understand your request better and make sure we are all on the same page.

**Comment by gssjr** [comment] 2017-01-18 19:19
Sorry about the delayed response.

Yes, @reddolan I was referring to something similar to Bootstrap Button Groups and/or FABs.

For my specific use case I'm creating a floating toolbar with contextual actions like "Edit", "Delete", "Zoom In", "Zoom Out", etc.

Another example would be creating buttons for a text editor: 
![image](https://cloud.githubusercontent.com/assets/2048811/22079235/1bb64940-dd89-11e6-8ed4-a5036e8dc937.png)

**Comment by jaffoneh** [comment] 2017-01-18 19:46
@gssjr would you say it is a duplicate of #240? I am trying to make sure we're on the same page about what we're looking for here.

**Comment by gssjr** [comment] 2017-01-18 19:53
@jaffoneh I'd say they're similar. Perhaps it can be broken into two parts: 1) button groups (generically i.e. supporting text/icons) and 2) icon styling that works well in these scenarios

**Comment by jaffoneh** [comment] 2017-01-18 20:03
@gssjr awesome, we're considering both for #240. Thanks for the quick response!

**Comment by reddolan** [comment] 2017-01-19 20:44
@gssjr we discussed this a bit further. We will have a new issue posted with the design specs for Button Group which will cover most of the use cases you mentioned here. Once that spec is posted, I will link it here as well. 

One the Floating Action Button use case, we believe that this would end up being a separate component as it behaves quite a bit differently than what we are spec'ing. We will also create a unique issue for the FAB request and link that here too.

**Comment by reddolan** [comment] 2017-01-20 20:55
We have merged your request into Button Groups #247. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you

**Closed by reddolan** 2017-01-20 20:55 UTC
Labels: ClarityUX, Component: New, needs-UX-input

**Comment by reddolan** [comment] 2017-01-20 21:05
@gssjr I also created a new issue for your request of the Floating Action Button (FAB) from Material Design. The issue is #393
