### ISSUE TITLE
[WEB,DOCS] Component pages like Wizards slow down when multiple demos are loaded at once.

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#858] opened 2017-05-08 18:54 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Component pages do not slow down due to the number of demos being loaded.

### Actual behavior

If a component page has more than 5-6 demos, for eg the wizards or icons page, the website starts to slow down. 

We tried a new layout with the datagrid page which works well as it displays only 1 demo at a time using child routes & pagination. We need to take this into consideration before moving all pages to the new layout (Badges/Buttons/Headers etc)

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/wizards on Firefox for eg.

### Environment details

* **Angular version:** NA

* **Clarity version:** NA

* **OS and version:** NA

* **Browser:** [all]

**Comment by reddolan** [comment] 2017-05-11 01:01
We might also want to look into other page IA's to see if there is something that works better for both performance and also usability/findability.

**Comment by reddolan** [comment] 2017-06-23 00:57
@adityarb88 is it possible to load demos on request? If we do that and several demos are loaded in the page will that still affect performance? If so, is there a way to do some garbage clean up? Maybe kill previous demos when a new one is requested.

**Comment by mathisscott** [comment] 2017-06-23 01:00
@reddolan
This is more of an IA issue. How do we present pages with many demos?

Right now, we do something a little different on datagrid. But I don't think that's a long term solution.

**Comment by reddolan** [comment] 2017-06-23 01:12
@mathisscott yeah, but in this case the technical means are what's driving the need to change things. The better I understand what can and can't be done, the more viable a solution we can come up with

**Comment by adityarb88** [comment] 2017-06-23 19:15
@reddolan and I discussed a few approaches we could do to resolve this. I will try to research more on what we discussed and see if those approaches are feasible and comment more on the issue in a few days.

**Comment by colinreedmiller** [comment] 2019-02-25 23:29
I need an example of the issue. The Wizards page referenced above is missing (404). I looked at icons and could not locate / recreate the issue.

**Comment by reddolan** [comment] 2019-02-26 23:04
@colinreedmiller when multiple large-component instances are loaded on a page, the page will slow down. Datagrid is another example of this issue. We ended up having to create the workaround in Datagrid to cut the performance issue

**Comment by gnomeontherun** [comment] 2019-02-27 00:04
The real design request here is more about how could we organize the content on the website docs in a way that would limit the total number of components on the page for performance reasons.

**Comment by colinreedmiller** [comment] 2019-02-28 17:44
Proposal: Add a tertiary level of hierarchy in the side nav and use this to organize the site into sub-types of components.

Some visual design is needed for display of location status e.g. Components | Button Group | Overflow --- The likely solution to this would be Button Group (bold) and Overflow (selected cell colored fill). We will also want to consider the page title - in the example case it is showing the path in an abbreviated breadcrumb fashion: Button Group | Overflow.

Illustration of solution for discussion - not a design:

![tertiary-nav-site](https://user-images.githubusercontent.com/44213553/53585909-dbe77880-3b3b-11e9-9bd9-abe2cb32b59a.png)

The other direct solution would be tabs at the top of the content, however, the Design Guidelines | Code & Examples Tabs work nicely and confounding the design here will be less usable, as well as un-discoverable for the user navigating in the sidenav, only surfacing in the content area when a selection is made. The only concern I see offhand from a design perspective is the potential for long strings to test the width of the sidenav. I tested Datagrid  |  Custom Cell Rendering and there is plenty of space.

**Comment by colinreedmiller** [comment] 2019-08-06 19:50
Systematically breaking this down into viable solutions we have a small number of choices:
1. Tertiary left navigation as in the suggestion above. This is the most clear and usable of the available alternatives. Research confirms that very long pages with most of the content below the fold are common and less desirable re: usability.
2. An in-page list of sub-items such as in datagrid - somewhat less usable but acceptable.
3. Change the site design / IA to organize the information and demos in a way that prevents this issue from occurring. An example would be to present demos in an inspector type component allowing the user to load and view only the demo they prefer.

Unless the intent is to table this issue until a larger assessment / redesign of the entire site which includes eliminating this issue by design, the preferable solutions with less resource requirements are:
(1) tertiary navigation - preferred
(2) in page list linking to subsets of a component.

Any solution will require a survey of the pages where demos have a performance impact. This may suggest a preference for one solution or the other, or perhaps a hybrid.

note: Wizard (cited as an example above) already is using the datagrid solution (2) in the Clarity sandbox. Cannot reproduce the issue in icons (other example cited).

**Comment by gnomeontherun** [comment] 2020-10-29 20:31
No longer an issue or resolved in the upcoming website work. Closing as resolved.

**Closed by gnomeontherun** 2020-10-29 20:31 UTC
Labels: needs: design, type: website
