### ISSUE TITLE
Datagrid: Truncate long cell content with instead of going multi-lines

### ISSUE THREAD

**Issue by halachliyskid** [vmware/clarity#1136] opened 2017-06-30 12:05 UTC
[ ] bug
[x ] feature request
[ ] enhancement
```

Currently, if the content of a cell is very long, it goes on multiple lines. This means that the row height increases and in some cases this may degrade the user experience.

We need the option to stay on a single line - long content will be truncated with "..." and the full content will be visible in a tooltip on hover.

**Comment by youdz** [comment] 2017-06-30 12:54
Duplicate of #1065, #815, #618. The discussion on `overflow: hidden` for datagrid cells is in these issues, feel free to check them out.

**Closed by youdz** 2017-06-30 12:54 UTC
