### ISSUE TITLE
Datagrid: columns are not aligned properly for dynamically loaded data

### ISSUE THREAD

**Issue by sivaah** [vmware/clarity#622] opened 2017-03-21 06:35 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
columns in each row to be aligned with same width

### Actual behavior
Columns are taking different width results in wrong alignment
![screen shot 2017-03-21 at 12 02 08 pm](https://cloud.githubusercontent.com/assets/6573919/24135167/8c519b20-0e2e-11e7-9b79-b19ed6951ab4.png)

### Reproduction of behavior
https://plnkr.co/edit/j6gdA0?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.11

* **OS and version:** 

* **Browser:** [Chrome 57.0.2987.110 (64-bit) ]

**Comment by youdz** [comment] 2017-03-21 14:04
Surprising, this case was actually tested. We'll investigate and publish a fix as soon as we can. It will not impact any integration.

**Comment by youdz** [comment] 2017-03-21 14:10
Duplicate of #623, the latter is slightly more detailed.

**Closed by youdz** 2017-03-21 14:10 UTC
Labels: bug, ClarityNG
