### ISSUE TITLE
Date Picker (clrDate directive): Introduce popup position relative to the date input

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#2717] opened 2018-10-10 13:37 UTC
Feature request for the Clarity Date Picker directive

Current behavior: 
Currently, the Date Picker popup appears under the input.

Desired behavior: 
Ability to choose the position of the Date Picker popup relative to the date input, similar to Clarity tooltips (top, bottom, etc.).

The current behavior can be observed at the date picker clarity page (https://vmware.github.io/clarity/documentation/v0.13/datepicker as of the time of writing).

**Comment by gnomeontherun** [comment] 2018-10-10 14:07
This is a duplicate of #2331, follow that ticket for updates.

**Closed by gnomeontherun** 2018-10-10 14:07 UTC
Labels: Duplicate
