### ISSUE TITLE
Schematic(s) for Application Layout

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#3461] opened 2019-06-14 11:37 UTC
## Summary

Add schematics for the Application Layout and Navigation schemas listed [here](https://clarity.design/documentation/navigation).

You could add a single schematics (the simplest one) or one per each of the 5 examples provided in the Navigation documentation

* What is the change? add schematics for the main component template
* Why should it go in Clarity? starting a new app will be a way faster
* Does this change impact existing behaviors? No 
* If this change introduces a new behavior, is this behavior accessible? N/A

## Use case

Starting a new App will be a way faster and with schematics you could enforce guidelines for Application Layout and Navigation

## Examples

Look at the [Angular Material Schematics](https://material.angular.io/guide/schematics)

## Workarounds

No

**Comment by gnomeontherun** [comment] 2019-06-14 16:02
This is a duplicate of https://github.com/vmware/clarity/issues/2337, follow that ticket for updates as we go forward. This is tricky to understand what files to write this template into.

**Closed by gnomeontherun** 2019-06-14 16:02 UTC
