### ISSUE TITLE
clr-tree-nodes dont overflow if bound by a bounding container

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#1149] opened 2017-07-05 08:08 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If the tree is very large and we want it to be should in a restricted space (a container which has fixed bounds of height and width and overflow set to auto), the tree should navigatable with scrolls on the container

### Actual behavior
The tree can be scrolled vertically but not horizontally

### Reproduction of behavior
https://plnkr.co/edit/37qhI0?p=preview

### Environment details

* **Angular version:** Not applicable

* **Clarity version:** 0.10.0-alpha.3

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by envyN** [comment] 2017-07-05 11:45
I kind of have this fixed for my requirements though but would be better if the fix came from clarity

[https://plnkr.co/edit/IQDp32?p=preview](https://plnkr.co/edit/IQDp32?p=preview)

check the app.component.css for the fix

**Comment by youdz** [comment] 2018-07-19 00:22
The workaround doesn't work anymore, and that's a pretty tough fix as far as I can see. Marking as more complex than expected for now, we'll have to investigate more when we start working on it.

The problem is that the overall width changes when nodes are expanded or collapsed, but I think it's doable.

**Comment by gnomeontherun** [comment] 2019-10-03 19:30
I tested this against latest master and don't see this problem if you put the tree view inside a container. It was rewritten in v2 and seems to be resolved. Closing as fixed unless we can get an updated demo.

**Closed by gnomeontherun** 2019-10-03 19:30 UTC
Labels: Dev, status: needs investigation, type: enhancement
