### ISSUE TITLE
[Icon Request] Paperclip Icon

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#1377] opened 2017-08-28 01:53 UTC
Is there any icon we can use to represent "attachments"? It would be better to have a paperclip icon.
Thanks in advance!

**Comment by youdz** [comment] 2017-08-28 12:34
Duplicate of #1334. It's funny how requests for the same icon come roughly at the same time. 😄

**Closed by youdz** 2017-08-28 12:34 UTC
