### ISSUE TITLE
Best Practices for self styling

### ISSUE THREAD

**Issue by joshvanal** [vmware/clarity#439] opened 2017-02-01 19:53 UTC
[ ] bug
[ ] feature request
[x] enhancement

We really enjoy the components provided by you guys but we are trying to figure out the best practices for styling the components. Can you provide some documentation?

**Comment by mathisscott** [comment] 2017-02-01 22:46
Hi @joshvanal:

This is something we've been talking about for a while. It's never made it out of the concept stage yet. It's possible to do this but we would need to go through and document how.

Thanks for filing this github issue. We'll add it to our backlog.

**Comment by vkpavan26** [comment] 2017-02-06 05:14
Hi @joshvanal:

Thanks for adding this.We have similar requirement to change the style of Clarity components with  NGC theming if we have some best practices we would love to hear that.

**Comment by jaffoneh** [comment] 2017-02-08 18:06
Marking this as a duplicate of #268

**Closed by jaffoneh** 2017-02-08 18:06 UTC
Labels: ClarityUI, Docs, enhancement, WEB
