### ISSUE TITLE
Accessibility Issue found on "Datagrid - Select All" using Voice Over on Mac

### ISSUE THREAD

**Issue by firehole3** [vmware/clarity#4505] opened 2020-04-23 10:30 UTC
## Describe the bug

Accessibility Issue found on "Datagrid - Select All" using Voice Over on Mac
Refer to video for detail: 
https://www.dropbox.com/s/sbwm7izewxk9rw0/Datagrid-SelectAll-AccessibilityIssue.mp4?dl=0

## How to reproduce

https://clarity.design/documentation/datagrid/full

1.  Go to 'https://clarity.design/documentation/datagrid/full'
2.  On Mac, turn on "Voice Over"
3.  Press "Tab" key till "Apply" button
4.  Press "Tab" key again which should focus on "Select All" of Datagrid

## Expected behavior

Voice over should read out "Select All".

## Versions

**App**

* Angular: 9.0.0
* Node: v12.16.2
* Clarity: 3.1.0

**Device:**

* Type: MacBook
* OS: OS X
* Browser: chrome
* Version: 81.0.4044.122 (Official Build) (64-bit)

## Additional notes

This issue is not reproducible on Windows Narrator

**Comment by gnomeontherun** [comment] 2021-02-01 22:43
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-02-01 22:43 UTC
Labels: needs: accessibility input, type: accessibility
