### ISSUE TITLE
Performance issue in the action-overflow of datagrid if no pagination enabled

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#913] opened 2017-05-12 07:35 UTC
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Should smooth popup action overflow

### Actual behavior
Popup too slowly and cause CPU and memory too high.
<img width="343" alt="2017-05-12 3 28 20" src="https://cloud.githubusercontent.com/assets/5753287/25987824/2ac205b6-3728-11e7-8a81-63ae08bcdcd2.png">

### Reproduction of behavior

No pagination enabled and a large scale of data items. E.g: 300-500.
The implementation of action-overflow or datagrid may have issues.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
 

https://plnkr.co/edit/rdEsR7

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.x

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment] 2017-05-12 13:35
@steven-zou: Please make sure that your plunkrs are working. We will not be able to investigate the issue otherwise

![image](https://cloud.githubusercontent.com/assets/1426805/26000224/fa215eca-36dc-11e7-9e2c-5d5f4146e323.png)

Plunkr links:
Clarity Version: [Latest - 0.9.x](https://plnkr.co/uNwwZe)
Clarity Version: [Legacy - 0.8.15](https://plnkr.co/8TwwdL)

**Comment by steven-zou** [comment] 2017-05-12 14:25
Weird, the changes I did are not effective.
Update demo, please try again. @adityarb88 

The reproduce way is simple, just not enable pagination and load a large scale items to the datagrid with action overflow. Then click the ellipsis to open the popup menus.

**Comment by steven-zou** [comment] 2017-05-12 14:28
Use *ngFor still found exception in console.

<img width="1440" alt="2017-05-12 10 26 47" src="https://cloud.githubusercontent.com/assets/5753287/26002467/4920be0a-3762-11e7-8115-3e863418a273.png">

**Comment by jeeyun** [comment] 2017-05-16 19:03
It seems that having 500 onClick handlers for the action-overflow in the non-paginated case is causing the delay. Do we consider this an acceptable use case that we should support (non-paginated datagrid with 500 rows)? I don't recall if our UX guideline has a recommended maximum number of rows a datagrid should display.

**Comment by mathisscott** [comment] 2017-05-16 19:04
Good question for @reddolan and the UX team.

**Comment by mathisscott** [comment] 2017-06-26 21:47
Duplicate of #1111 per @youdz

**Closed by mathisscott** 2017-06-26 21:47 UTC
Labels: duplicate
