### ISSUE TITLE
Make date-picker more versatile by date filtering

### ISSUE THREAD

**Issue by spitfjre** [vmware/clarity#4274] opened 2020-02-14 09:09 UTC
## Summary

* What is the change?
* Why should it go in Clarity?
In order to make the date picker more versatile it would be nice to have the ability to filter selectable dates beyond the scope of `min` and `max` option (as present in other datepickers like material and ng-pick-datetime).

* Does this change impact existing behaviors? If so how?
No

* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case
Having the possibility to only select "working days" (as in no Saturdays, no Sundays, no public holidays).

## Workarounds
Currently the you have to validate the selected date after selection, which is not nice.

**Comment by gnomeontherun** [comment] 2020-02-14 16:35
Thanks @spitfjre we actually designed the current `min/max` internals to support expanding this support. This would be something we can get help on to prioritize, but I'll put it into our backlog and list of anticipated form improvements.

**Comment by gnomeontherun** [comment] 2021-02-05 19:56
This is a duplicate of #3009 and closing with same resolution.

**Closed by gnomeontherun** 2021-02-05 19:56 UTC
Labels: Help Wanted, component: date-picker, status: in progress, type: enhancement
