### ISSUE TITLE
Datagrid detail pane: Empty column is shown if first column is hidden

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5920] opened 2021-04-29 08:30 UTC
## Describe the bug

The first column of the datagrid is shown when the detail view is active. However when the first column is hidden, the datagrid displays an empty column.

![Screenshot 2021-04-29 at 10 24 28](https://user-images.githubusercontent.com/3655915/116522417-79ce5d80-a8d5-11eb-9d17-0d31f50fa830.png)
![Screenshot 2021-04-29 at 10 24 33](https://user-images.githubusercontent.com/3655915/116522423-7a66f400-a8d5-11eb-81c8-94f55da6675a.png)

## How to reproduce

[https://stackblitz.com/edit/clarity-light-theme-v5-bbsgbm?file=src/app/app.component.html](https://stackblitz.com/edit/clarity-light-theme-v5-bbsgbm?file=src/app/app.component.html
)

1.  Activate the detail pane

## Expected behavior

The first **visible** column is shown.

## Versions

**Clarity project:**

- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.x

**Framework:**

- [x] Angular

**Comment by gnomeontherun** [comment] 2021-04-29 13:33
This is actually a limitation, you should not allow the first column to show/hide. Its mentioned in the docs, maybe not as clear as it should be, but it is a known limitation. https://clarity.design/angular-components/datagrid/#detail-pane

Closing as works as intended, though I understand the confusion. Don't define the first column as hidable is the solution so the grid can properly understand what to show.

**Closed as completed by gnomeontherun** 2021-04-29 13:33 UTC
Labels: type: bug, resolution: wontfix, component: datagrid, @clr/angular
