### ISSUE TITLE
a broken icon

### ISSUE THREAD

**Issue by Stela-Stamenkova** [vmware/clarity#4133] opened 2019-12-19 08:55 UTC
Hi guys,

I can't download the "tape-drive" icon from here: https://clarity.design/icons#core-shapes  "tape-drive", I receive this instead.
[tape-drive-line (1).svg.zip](https://github.com/vmware/clarity/files/3982584/tape-drive-line.1.svg.zip)

Can you please help!
Thanks!
Stela

**Comment by martinbrom** [comment] 2019-12-19 09:46
The "wrong" SVG file contains "404 Not Found" for those who don't want to open it.

**Comment by mathisscott** [comment] 2019-12-19 19:33
I believe I've found what the issue is. I think I can get it fixed today or tomorrow.

**Comment by mathisscott** [comment] 2019-12-19 20:04
This should now be fixed by https://github.com/vmware/clarity-assets/commit/a6693b6af2ffc92e11bd02f41e3b5fef09b7c198

**Closed by mathisscott** 2019-12-19 20:04 UTC
Labels: @clr/icons, component: icons, resolution: fixed, type: bug, type: build, type: task
