### ISSUE TITLE
Modal opened in user-defined component placed in ClrDatagridActionBar has wrong background overlay and placement

### ISSUE THREAD

**Issue by jokarmus** [vmware/clarity#2082] opened 2018-03-16 13:19 UTC
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Opened modal in the middle of app with all page background overlay.

### Actual behavior
Modal opened in the middle of ClrDatagridActionBar with bagkround overlay only in ClrDatagridActionBar.

### Reproduction of behavior
[reproduction](https://clarity-light-theme-v11-iz8gc3.stackblitz.io/)

![modal-overlay](https://user-images.githubusercontent.com/37440709/37522666-e50ec67c-2924-11e8-99e3-94d0dfaf3807.png)

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** Windows 10

* **Browser:** 
[all? | Chrome 64.0.3282.186 | Firefox 64.0.3282.186| IE 11.309.16.99.0| Mobile Chrome 65.0.335.109 | iOS 11.2.6 Safari ]

**Comment by adityarb88** [comment] 2018-03-16 13:45
@jokarmus: This one too looks like a duplicate of this issue: #1631. Please subscribe to #1631 for more updates.

**Closed by adityarb88** 2018-03-16 13:45 UTC

**Comment by jokarmus** [comment] 2018-03-16 13:51
@adityarb88 
It is not a problem with visible items in front of the modal, this is a problem with **placement** and **background overlay** in ClrDatagridActionBar.  It is not a duplicate of #1631. Please reopen the issue.

**Comment by adityarb88** [comment] 2018-03-16 14:02
@jokarmus: I can definitely reopen the issue but I think the source of this issue is within `clr-dg-action-bar`. This issue is linked to #1631, and when we start to work on that, we will test both the dropdown and the modal use case you provided to us. If one the dropdown is fixed and this is not, then I will reopen this issue so that we can resolve this too.
