### ISSUE TITLE
Checkbox doesn't respect stopPropagation in click handler

### ISSUE THREAD

**Issue by cado1982** [vmware/clarity#3520] opened 2019-06-26 09:52 UTC
## Describe the bug

When I add clrCheckbox to a checkbox input element and then call stopPropagation in the click handler, the event still propagates up the DOM.

## How to reproduce

https://stackblitz.com/edit/angular-tbvv73

1. Open the console while running the stackblitz project
2. Click on the red div and confirm that Click Parent appears in the console
3. Click on the regular input checkbox and confirm that Click Child appears in the console
4. Click on the Clarity checkbox and confirm that both Click Child and Click Parent appears in the console

## Expected behavior

Because event.stopPropagation is called in the clickChild handler, the click event shouldn't make it to the parent.

## Versions

**App**

* Angular: 8
* Clarity: 2.0.1

**Device:**

* Type: MacBook
* OS: 10.14.5 Mojave
* Browser: Chrome
* Version: 74.0.3729.169

**Comment by gnomeontherun** [comment] 2019-06-26 16:39
Since checkboxes are wrapped in a label (we do this dynamically if you don't provide one and you actually are clicking the label) the click event is propagating up from the label. If you need to prevent propagation, you need to define a label and stop the event there.

```
<div (click)="clickParent()" style="width: 200px; height: 200px; background-color: red">
  <!-- This works because you have no label so it does stop the click event -->
  <input type="checkbox" (click)="clickChild($event)">
  <!-- This will trigger the parent click event due to the label we apply around the checkbox -->
  <input clrCheckbox type="checkbox" (click)="clickChild($event)">
  <!-- This will also trigger the parent click event -->
  <label><input type="checkbox" (click)="clickChild($event)"></label>
  <!-- This will stop the event -->  
  <label (click)="$event.stopPropagation()"><input clrCheckbox type="checkbox" (click)="clickChild($event)"></label>
</div>
```

You should always use a label to add meaningful labels so this is the expected behavior based on how click events propagate through the DOM. 

Closing as not an issue, with the solution provided.

**Closed by gnomeontherun** 2019-06-26 16:39 UTC
