### ISSUE TITLE
Datepicker date format to allow DD MMM YY

### ISSUE THREAD

**Issue by blomm** [vmware/clarity#3877] opened 2019-10-04 12:20 UTC
Can we have the option to display dates in DD MMM YY (or YYYY) please.
So 20 Mar 19 for example

**Comment by gnomeontherun** [comment] 2019-10-07 21:18
Thanks, what is the use case here? We depend upon the locale and browser defaults for setting these formats, so this is a non-trival change to make it work properly.

**Comment by blomm** [comment] 2019-10-08 06:19
hey there, thanks for getting back.  I've got an international currency trading app I'm building and I'd like to be as clear as possible with the date between North America and Europe.

**Comment by blomm** [comment] 2019-10-08 13:38
20 Mar 2019 would be fine btw

**Comment by gnomeontherun** [comment] 2019-12-17 16:30
This is a duplicate of #2056 closing in favor of it.

**Closed** 2019-12-21 01:52 UTC
Labels: @clr/angular, component: date-picker, resolution: duplicate, type: enhancement
