### ISSUE TITLE
Identifier 'collapsed' is not defined ... in documentation for vertical nav

### ISSUE THREAD

**Issue by corganfuzz** [vmware/clarity#4285] opened 2020-02-18 01:29 UTC
While trying to implement a collapsible vertical nav.  In the documentation page [here](https://v2.clarity.design/vertical-nav/collapsible-nav/normal), the following line does not work

(this is under *Collapsible Vertical Nav*)

```html
<clr-vertical-nav [clrVerticalNavCollapsible]="true" [(clrVerticalNavCollapsed)]="collapsed">
</clr-vertical-nav>
```
On top of that, vscode gives me the following error:

**Identifier 'collapsed' is not defined. The component declaration, template variable declarations, and element references do not contain such a member**

The correct code should be: ( you can switch between true and false). This indeed work, please change

```html
<clr-vertical-nav [clrVerticalNavCollapsible]="true" [clrVerticalNavCollapsed]="false">
</clr-vertical-nav>
```

## How to reproduce

Copy and paste this code in a brand new angular app
```
<clr-vertical-nav [clrVerticalNavCollapsible]="true" [(clrVerticalNavCollapsed)]="collapsed">
    <a clrVerticalNavLink routerLink="./normal" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="user"></clr-icon>
        Normal
    </a>
    <a clrVerticalNavLink routerLink="./electric" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="bolt"></clr-icon>
        Electric
    </a>
    <a clrVerticalNavLink routerLink="./poison" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="sad-face"></clr-icon>
        Poison
    </a>
    <a clrVerticalNavLink routerLink="./grass" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="bug"></clr-icon>
        Grass
    </a>
    <a clrVerticalNavLink routerLink="./fighting" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="shield"></clr-icon>
        Fighting
    </a>
    <a clrVerticalNavLink routerLink="./credit" routerLinkActive="active">
        <clr-icon clrVerticalNavIcon shape="certificate"></clr-icon>
        Credit
    </a>
</clr-vertical-nav>
```

## Expected behavior

to collapse or not

## Versions

**App**

* Angular: 8.3.x
* Node: 12.3.x
* Clarity: 2.3.7

**Comment by hippee-lee** [comment] 2020-02-18 21:54
Hi There, I copied and pasted the markup from the documentation into our stackblitz starter here: https://stackblitz.com/edit/clarity-light-theme-v2-avyudk

This seems to be working fine. Please fork the stackblitz and recreate your issue so that we can look at a running application that reproduces the reported issue. 

Closing for now, please re-open with the stackblitz reproduction.

**Closed by hippee-lee** 2020-02-18 21:54 UTC
Labels: status: needs reproduction, type: support
