### ISSUE TITLE
Error when adding the new forms with angular reactive forms

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2448] opened 2018-07-11 08:31 UTC
**Select one ...** (check one with "x")

```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

![image](https://user-images.githubusercontent.com/1977391/42559825-d026e104-8527-11e8-9f7e-d161c876ed1a.png)

### Reproduction of behavior

[https://stackblitz.com/edit/clarity-light-theme-v11-x5hujx](https://stackblitz.com/edit/clarity-light-theme-v11-x5hujx)

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**0.12.3-patch.2

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment] 2018-07-11 12:44
This is a duplicate of #2438, please follow that issue for updates.

**Closed by youdz** 2018-07-11 12:44 UTC
