### ISSUE TITLE
Cannot build clarity

### ISSUE THREAD

**Issue by deanchalk** [vmware/clarity#1689] opened 2017-11-13 07:05 UTC
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
after installing all of the tools and dependencies, I would be able to run the build command 'npm run build' without failure. I am trying to build the main clarity repository on my local clone

### Actual behavior
When I run the build I get an obscure error:

del: command not found

### Reproduction of behavior
Templates:
Clarity Version: latest (just installed from website)

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** build from github

* **OS and version:**  OSX - High Sierra

* **Browser:** chrome

**Comment by adityarb88** [comment] 2017-11-13 15:53
@hippee-lee: Could you please take a look at this?

**Comment by hippee-lee** [comment] 2017-11-15 19:48
Hi @deanchalk - are you building on windows perchance?

We have an issue (https://github.com/vmware/clarity/issues/1582 ) that sounds similar to this one as well as a PR (that is in the works). 

If you are using windows, can you tell me a little more about your setup?
- What's a common way to install node for windows devs?
- Do you use the command prompt, powershell, a bash equivalent or something else when you work on the command line
- Are there any typical issues a windows dev would be aware of that I might not know about wrt doing node/angular development on a windows box? 

I'm not a windows native but do have a Surface Pro 4 that I was using to test the options for making the build more windows friendly. Any info / tips you can pass along are appreciated.

**Comment by deanchalk** [comment] 2017-11-16 13:27
Im am not on Windows, but on Mac OSX (High Sierra)
The issue looks similar to #1582, but can you confirm that your proposed fix also fixes the same issue on Mac

Thanks

**Comment by hippee-lee** [comment] 2017-11-16 16:14
Hmmm. I'm not having any issues building and do most of the work on a OSX (High Sierra)

Is there any way you can share your fork with me so I can take a look and see the error?

**Comment by hippee-lee** [comment] 2017-11-16 16:26
Also, I'm sure you have already run `npm install` to install the dev-dependencies and dependencies. Can you check the node modules folder to see if `del` is installed? It should be here: `<clarity-root>/node_modules/del` Perhaps something went astray with the install.

**Comment by deanchalk** [comment] 2017-11-16 16:47
1) I have only cloned the repository - no changes to the source code at all
2) I have run npm install successfully
3) the del folder exists in node_modules

I've tried this on a windows machine, and I get the same error
Here is the build log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle clarity-all@0.10.13~prebuild: clarity-all@0.10.13
6 silly lifecycle clarity-all@0.10.13~prebuild: no script for prebuild, continuing
7 info lifecycle clarity-all@0.10.13~build: clarity-all@0.10.13
8 verbose lifecycle clarity-all@0.10.13~build: unsafe-perm in lifecycle true
9 verbose lifecycle clarity-all@0.10.13~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Projects\clarity\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\chd8f5\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\chd8f5\AppData\Local\Microsoft\WindowsApps;C:\Users\chd8f5\AppData\Roaming\npm;C:\Users\chd8f5\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\3.4\bin;
10 verbose lifecycle clarity-all@0.10.13~build: CWD: C:\Projects\clarity
11 silly lifecycle clarity-all@0.10.13~build: Args: [ '/d /s /c',
11 silly lifecycle   'npm-run-all clean build:angular webpack build:icons' ]
12 silly lifecycle clarity-all@0.10.13~build: Returned: code: 1  signal: null
13 info lifecycle clarity-all@0.10.13~build: Failed to exec build script
14 verbose stack Error: clarity-all@0.10.13 build: `npm-run-all clean build:angular webpack build:icons`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid clarity-all@0.10.13
16 verbose cwd C:\Projects\clarity
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error clarity-all@0.10.13 build: `npm-run-all clean build:angular webpack build:icons`
22 error Exit status 1
23 error Failed at the clarity-all@0.10.13 build script 'npm-run-all clean build:angular webpack build:icons'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the clarity-all package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all clean build:angular webpack build:icons
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs clarity-all
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls clarity-all
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hippee-lee** [comment] 2017-11-16 17:08
Yeah, I am aware of the issues on windows, the `del node_package` isn't a windows compatible command. That's what we are trying to fix for the other issue i referenced above. 

Since you use OSX to develop let's focus on that.
`del` is installed and working fine for me on my dev computer. (OSX Sierra 10.12.6). Its part of the `clean` task that removes the `dis/` directory before building. I just published Clarity `v0.10.14` this morning and del worked as expected. 

Can you give me any clues for how to reproduce the error you see? Alternatively, can you do a fresh clone/install and run just the clean task `npm run clean` to see if you still get the error?

**Comment by hippee-lee** [comment] 2017-11-16 18:49
Another follow question for you @deanchalk - what version of `node` is installed?

**Comment by deanchalk** [comment] 2017-11-17 14:02
OK, we've solved one problem, but now there's another (minor) problem

Doing a clean clone of the current github repository and doing 'npm i' followed by 'npm run clean' works now. And 'npm run build' actually builds and I have build output in the dist directory - perfect.

However, when I navigate to the ks-app subdirectory and build that it fails - because its expecting the file dist/clarity-angular/clarity-angular-0.10.12,tgz' but the build is creating a file of a different version. I can fix this for myself locally, but I thought I'd make you aware

**Comment by hippee-lee** [comment] 2017-11-17 16:36
Thanks for the follow-up.

Yes, I am aware of this `ks-app` issue you ran into. Sorry about that - it was a change that came in during our migration to webpack and is on my list of things to investigate for developer happiness. 

I'm closing this issue based on your feedback that you can clean and build. Feel free to reopein it if `del` gives you more problems.

**Closed by hippee-lee** 2017-11-17 16:36 UTC
Labels: ClarityCore, |>
