### ISSUE TITLE
Improve intuitiveness of Combobox autocomplete behavior

### ISSUE THREAD

**Issue by syndesis** [vmware/clarity#5508] opened 2021-01-26 00:42 UTC
## Summary

Change the behavior of autocomplete for the Combobox component

- What is the change?

1. Create a Combobox with option list `OPTION LIST`
2. Type into the Combobox input such that a filtered list of options which match the input is displayed: `VISIBLE LIST`
3. The first item from `VISIBLE LIST` is automatically selected
4. Use key (enter, tab) or mouse to alter focus while keeping that first item from `VISIBLE LIST` selected

- Why should it go in Clarity?

It is confusing to filter out options and then have an option which doesn't match your filter be selected when you hit enter.  The combobox input wrapper is created with `aria-autocomplete="list"` which should implement the requested behavior but the `ComboboxFocusHandler.handleTextInput` method overrides it.

- Does this change impact existing behaviors? If so how?

Current behavior:
1. Create a Combobox with option list `OPTION LIST`
2. Type into the Combobox input such that a filtered list of options which match the input is displayed: `VISIBLE LIST`
3. No options are selected
3. Hit enter
4. The first item from `OPTION LIST` is selected (or an option which was previously selected)

- If this change introduces a new behavior, is this behavior accessible?

Yes, it is a recommended pattern for ARIA

## Use case

As a form user, I would like for the first option of a combobox list to be automatically selected after I apply a filter so that items that don't match my filter are not selected accidentally

## Examples

1. Create a combobox with options: `['bird', 'dog', 'cat', 'elephant', 'donkey']`
2. Type "ele" into the input
3. Hit Enter

Currently, that would select "bird."  Feature request is that it should select "elephant"

_Are there any examples in other projects that demonstrate this feature or enhancement?_

https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
Example 2: List Autocomplete with Automatic Selection

### List autocomplete with automatic selection means that:

1. When the listbox popup is displayed, it contains suggested values that complete or logically correspond to the characters typed in the textbox. In this implementation, the values in the listbox have names that start with the characters typed in the textbox.
2. The first suggestion is automatically highlighted as selected.
3. The automatically selected suggestion becomes the value of the textbox when the combobox loses focus unless the user chooses a different suggestion or changes the character string in the textbox.

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

The user can use arrow keys or mouse to select a list option

**Comment by Jinnie** [comment] 2021-01-26 14:26
Our implementation is based on the Manual Selection scenario (Example 1 from the examples page provided in the bug description). It's been one of the choices we've made. It's not been intended to cover all possible scenarios.
In my personal opinion, it would be more confusing to have a component which would automatically select in single-selection scenario and will need manual selection in multi-select (it can't be automatic with multiselect)
Some A11Y feedback won't hurt, though:
@chlane is there a reason to prefer automatic completion over manual, given the request in this issue, and my comparison of single vs multiselection experience?

**Comment by syndesis** [comment] 2021-01-26 15:30
In example 1 of that scenario, hitting "Enter" without using arrow keys to move to a list item does not make a selection - it does nothing.  I think that would be better than selecting an item that's not even displayed.  That said, it would be nice to have functionality like the second example as an option, at least for single selection.

**Comment by chlane** [comment] 2021-01-26 18:39
Now tracking this issue internally as an accessibility issue.

**Comment by chlane** [comment] 2021-01-26 19:03
As long as we follow the ARIA Working Group's example mentioned in the description it can be done IMO.

https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
Example 2: List Autocomplete with Automatic Selection.

**Comment by Jinnie** [comment] 2021-02-03 10:05
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which, as noticed by Chris, has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed as completed by Jinnie** 2021-02-03 10:05 UTC
Labels: type: accessibility, resolution: tracked by a11y
