### ISSUE TITLE
Date Piker - Disable future dates

### ISSUE THREAD

**Issue by enoquemoises** [vmware/clarity#2742] opened 2018-10-17 11:52 UTC
## Summary

_Can future dates be disabled from the Date Piker? If not can we have this feature in the future?_

**Comment by youdz** [comment] 2018-10-17 13:02
Closing this as duplicate of #1984. We are not working on it at the moment, but you can follow the linked issue for updates.

**Closed by youdz** 2018-10-17 13:02 UTC
