### ISSUE TITLE
Datagrid component feature - sticky columns

### ISSUE THREAD

**Issue by brankoleone** [vmware/clarity#1307] opened 2017-08-15 14:21 UTC
```
[ ] bug
[x] feature request
[x] enhancement
```

### Questions

I have some questions concerning the Datagrid component?
Do you plan adding sticky header (row) and scroll?

**Example**:
We have hundred rows (without pagination) but we want to limit the viewport of the datagrid to show let's say 20 at once. We would like to scroll down and still have the header (or some sticky row) on top.

We think it would be great to have these features. Do you plan adding them?

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.10.0

* **Browser:** [all]

**Comment by adityarb88** [comment] 2017-08-15 14:28
@brankoleone: Are you looking for restricting the height of the datagrid? If yes, you can do that using CSS. Please refer to this Plnkr: https://plnkr.co/edit/4CY7AObItGIqt5puJuQe?p=preview

**Comment by brankoleone** [comment] 2017-08-15 15:00
This works great, 10x for the tip Aditya.
As we keep the conversation, do you have any clue how we can have a sticky column.

**Example:**
We would like to have the first two columns sticky, but to have a scroll for the remaing ones.

This feature would be great in the contenxt when we hawe axpandable rows!

Thanks for the answers!

**Comment by reddolan** [comment] 2017-09-01 22:57
@brankoleone I am confused. Do you want
- a sticky column header like you mention in the initial description? (horizontal sticky)
- or sticky columns like you mention in the latest comment? (vertical sticky)

**Comment by reddolan** [comment] 2017-09-01 23:13
Just trying to figure out if this is a duplicate request of #619

**Comment by brankoleone** [comment] 2017-09-04 13:53
It's exactly as described in #619 but it's different from showing / hiding columns like in #401.
We would like to be able to pin some of the columns so they stay pinned on the left, and the rest is scrollable.

This [UI Grid](http://ui-grid.info/docs/#/tutorial/203_pinning) demo component does exactly this, as mentioned in the comments of #619.

I managed to achieve similar result with two separated Clarity datagrids on this [plunker demo](https://plnkr.co/edit/4NytnI?p=preview), but there are still inconveniences from the **scrolling and sorting** stand point.

Thank you for your feedback!

**Comment by reddolan** [comment] 2017-09-06 20:00
@brankoleone for clarifying that. Seeing as this appears to be a duplicate of issue #619, I will mark this one as a duplicate. 

Please subscribe to #619 and leave a comment regarding the need to freeze two columns.

**Closed by reddolan** 2017-09-06 20:00 UTC
Labels: !!, duplicate, FR: Review Needed, needs-UX-input, |>
