### ISSUE TITLE
When datagrid body is an object whose keys are not known.

### ISSUE THREAD

**Issue by Mshardul** [vmware/clarity#4363] opened 2020-03-12 09:40 UTC
## Summary

Datagrid is easy to create when the object keys are known to the developer(ie are static).
However, it might be possible that the object keys are not known till run-time.

## Use case

Generating a data-grid even when object keys are not known.
## Examples

Let's say we receive 2 lists from backend
* header: list of column names. eg. [id, name, marks1, marks2]
* body: list of objects, each object corresponding to a single row. eg. [{id: 1, name: abc, marks1: 5, marks2: 7}, {id: 2, name: bcd, marks1: 9, marks2: 6}]

## Something like.....

```
<clr-datagrid style="min-height: 480px;">
 <clr-dg-column *ngFor="let th of header">{{th}}</clr-dg-column>
  <clr-dg-row *clrDgItems="let row of body" [clrDgItem]='row'>
   <clr-dg-cell *ngFor="let th of tHead">{{row[th]}}</clr-dg-cell>
  </clr-dg-row>
</clr-datagrid>
```

**Comment by hippee-lee** [comment] 2020-03-12 17:31
In a case like this I would merge the two backend lists into one unified modal for the app to work with. Since this is an implementation question ad not a bug/feature issue I'm going to close the issue. 

Feel free to create a simple demo that mocks the data sources you are working with using one of our stackblitz starter apps: https://stackblitz.com/@clr-team and post a question on Stackoverflow with the `vmware-clarity` tag: https://stackoverflow.com/questions/tagge/vmware-clarity

**Closed by hippee-lee** 2020-03-12 17:31 UTC
Labels: component: datagrid, type: support
