### ISSUE TITLE
btn-group overflow his container

### ISSUE THREAD

**Issue by jromerob** [vmware/clarity#1975] opened 2018-02-09 07:51 UTC
![image](https://user-images.githubusercontent.com/11867464/36016954-d22f9b82-0d75-11e8-9a15-be819c992bc0.png)

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Buttons inside btn-group must adapt to parents container width

### Actual behavior
Buttons in button group  don't shrink and overflow the container

## Reproduction of behavior
See  Clarity examples 
https://vmware.github.io/clarity/documentation/v0.11/button-group#examples

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://vmware.github.io/clarity/documentation/v0.11/button-group#examples

### Environment details
 

* **Browser:** [ all ]

**Comment by adityarb88** [comment] 2018-02-09 13:44
@jromerob:  Our UX team recommends that each button have a `min-width` on it for accessibility reasons. If the `.btn-group` container width is smaller than the widths of the button in it, the the buttons will overflow. We do provide a button group overflow menu for these cases. I would recommend to use the overflow menu if the buttons are moving off the screen. The reason that we cannot do that dynamically for you is because browsers don't support container queries as of now. So you will have to make sure that you adjust the button groups for the screen sizes you support using browser width and render the overflowing buttons in the overflow menu.

Let me know if this helps. I am closing the issue as this is the expected behavior until we can start using container queries. Please feel free to reopen the issue if you have any more questions. Thanks!

**Closed by adityarb88** 2018-02-09 13:44 UTC
