### ISSUE TITLE
Datagrid shows an extra row if there is only one row

### ISSUE THREAD

**Issue by ssanghavi** [vmware/clarity#1100] opened 2017-06-23 10:24 UTC
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
If datagrid has only one row it shows an extra row, this happens even in case we filter a huge datagrid to single row.

### Reproduction of behavior
plnkr - https://plnkr.co/edit/ekqYbq8AQO5PJDW69qIr?p=preview

### Environment details

* **Angular version:** 4.1.2

* **Clarity version: 0.9.10

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment] 2017-06-23 11:22
Duplicate of #1010.

Long story short, datagrids have a min-height because they look even weirder when empty or with a single row. We're looking at other compromises since it seems to bother consumers.

**Closed by youdz** 2017-06-23 11:22 UTC
Labels: ClarityNG, duplicate
