### ISSUE TITLE
Datagrid: Single row action is not visible when data is loaded asynchronously

### ISSUE THREAD

**Issue by pchoi** [vmware/clarity#1173] opened 2017-07-12 22:07 UTC
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When the data for the Datagrid is loaded asynchronously (i.e. Observable), single row action should be visible on each row

### Actual behavior

When the data for the Datagrid is loaded asynchronously (i.e. Observable), single row action is hidden on each row (action column is not rendered).
When you click on any of the Datagrid column header, then the single row action is rendered for each row.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

You can reproduce the behavior here:
https://plnkr.co/edit/Lb2VilKWu08GEZ6r4B2k?p=preview
(Note: it's reproducible on Safari ; on Chrome, the Datagrid content does not render)

### Environment details

* **Angular version:** 4.x

* **Clarity version:** 0.9.12

* **OS and version:** 

* **Browser:** Chrome 59 | Safari 10.1.1

**Comment by youdz** [comment] 2017-07-12 23:01
Duplicate of #744, the fix is coming in any time now!

**Closed by youdz** 2017-07-12 23:01 UTC
