### ISSUE TITLE
Class "required" for clr-input-container label

### ISSUE THREAD

**Issue by ibuler** [vmware/clarity#2847] opened 2018-11-15 10:56 UTC
### Label in clr-input-container class `required` not work 

```
<clr-input-container style="padding-left: 10px">
        <label for="username" class="required">Username: </label>
        <input clrInput type="text" id="username" [(ngModel)]="username"
</crl-input-container>
```
![image](https://user-images.githubusercontent.com/17382885/48548465-f8063780-e907-11e8-87ec-165c6b01e092.png)

### But in Form group worked fine
```
<div class="form-group" style="padding-left: 135px;">
          <label for="username" class="col-md-3 form-group-label-override required">Name: </label>
...
</div>
```
![image](https://user-images.githubusercontent.com/17382885/48548489-05bbbd00-e908-11e8-87ea-57aab7f4e712.png)

## Versions

**App**

* Angular:  7.0.2
* Node: 10.0.0
* Clarity: 0.13.8

**Device:**

* Type: MacBook
* Browser: chrome

**Comment by gnomeontherun** [comment] 2018-11-15 16:02
There is no longer support for `required` in the new forms fields. This is a design decision, because forms should be assumed to be required and fields marked as optional using text. Also, while * is a convention used in many places it is also not very accessible or clear to many users, so it was removed. Closing as working as intended.

**Closed by gnomeontherun** 2018-11-15 16:02 UTC

**Comment by navneetkarnani** [comment] 2018-12-13 07:05
@gnomeontherun Shouldn't there, then, be an "optional" style to handle this case ?
