### ISSUE TITLE
Improve "required" validation in order to support "select" elements

### ISSUE THREAD

**Issue by kaleksandrov** [vmware/clarity#1571] opened 2017-10-11 08:23 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Currently the "required" validation works only on input fields. It would be great if it works on "select" fields as well.

### Actual behavior
If the "required" mechanism is used over "select" fields, the info icon is shown over the dropdown icon.

### Reproduction of behavior
https://embed.plnkr.co/g3WmMI/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** all

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment] 2017-10-11 13:10
@kaleksandrov 
This is a duplicate of the work currently being done on #1118 

That work is currently in the design phase. Please subscribe to that issue or one of the issues related to it to track progress.

Thanks.

**Closed by mathisscott** 2017-10-11 13:10 UTC

**Comment by kaleksandrov** [comment] 2017-10-11 13:37
Hi @mathisscott 

Thanks for the fast reply! I don't think this is a duplicate as #1118 is related to "optiona" parameters. The current issue is about extending its support to other DOM elements like "select" which currently is not supported.

Do you still think this is a duplicate?

There is no information about the state of this enhancement in #1118 - can you share a little bit more? When could we expect it to be shipped?

Thanks,
Kiril

**Comment by mathisscott** [comment] 2017-10-11 14:53
@kaleksandrov 
It's in design/research at the moment, so it is still a ways off.

I was wrong to point you to #1118, however. Because it is just one part of #932 <- which is what I should have directed you to.

Sorry for the confusion.
