### ISSUE TITLE
Datagrid Hide/Show overlaps with headers

### ISSUE THREAD

**Issue by gauranirudh** [vmware/clarity#3113] opened 2019-02-14 10:47 UTC
## Describe the bug

If Datagrid has few rows, then hide/show overlaps with the Headers and gets hidden behind the Headers.

## How to reproduce

![hide show](https://user-images.githubusercontent.com/34673679/52780493-8c3c8380-304a-11e9-923c-dfbbed4234de.png)

How to reproduce:
      

      <clr-datagrid id="activity-datagrid" (clrDgRefresh)="onRefresh($event)" [clrDgLoading]="loading">
      <clr-dg-action-bar>
      </clr-dg-action-bar>
      <clr-dg-column >
        <ng-container *clrDgHideableColumn="{hidden: false}">
          Title, Action
        </ng-container>
      </clr-dg-column>
      <clr-dg-column >
          <ng-container *clrDgHideableColumn="{hidden: false}">
            Type
        </ng-container>
      </clr-dg-column>
      <clr-dg-column >
        <ng-container *clrDgHideableColumn="{hidden: false}">
          Date, Time
        </ng-container>
      </clr-dg-column>
      <clr-dg-row *ngFor="let activity of activityResults.searchResults">
        <clr-dg-cell class="text-ellipsis">
          {{activity.title}}
        </clr-dg-cell>
        <clr-dg-cell class="text-ellipsis">
            <clr-icon shape="calendar"></clr-icon>
        </clr-dg-cell>
        <clr-dg-cell class="text-ellipsis">
          {{activity.startDate}}
        </clr-dg-cell>
      </clr-dg-row>
      <clr-dg-footer>
        <clr-dg-column-toggle>
          <clr-dg-column-toggle-title>Show/Hide Columns!</clr-dg-column-toggle-title>
          <clr-dg-column-toggle-button>Select all!</clr-dg-column-toggle-button>
        </clr-dg-column-toggle>
      </clr-dg-footer>
    </clr-datagrid>

## Expected behavior

Hide/Show should be visible on top of Headers in case of overlap.

## Versions
**App**

* Angular: 7
* Clarity: [1.0]

**Device:**

* Type: [e.g. Lenovo]
* OS: [Windows]
* Browser [Chrome ]
* Version [71.0.3578.98]

**Comment by hippee-lee** [comment] 2019-02-14 18:45
This is a duplicate of #2683. Please subscribe to that for updates. FYI - I am actively working on a fix for these issues.

**Closed by hippee-lee** 2019-02-14 18:45 UTC
