### ISSUE TITLE
Visual focus indication is lost in Safari

### ISSUE THREAD

**Issue by clane** [vmware/clarity#4085] opened 2019-12-04 21:42 UTC
## Describe the bug

[Test URL]
https://clarity-light-theme-v2-a6ykys.stackblitz.io

[WCAG 2.1 Guideline]
2.4.7 Focus Visible
(Level AA)

[Screen Reader/Browser]
Safari Version 13.0.3 (15608.3.10.1.4)

[Description]
Visual focus indication is lost when you tab to the cancel or next buttons using Safari.

[User Impact]
Sighted keyboard-only users using Safari will not be able to tell which element has focus.

[Recommendation]
Needs further investigation.

## How to reproduce

[Steps to Reproduce]
1.  Using Safari and the keyboard alone, go to the Test URL
2.  Tab to the close button
3.  Tab 3 more times
4.  Observe that focus is on the cancel button but you do not see a visual indication of focus

## Expected behavior
Visual focus indication should persist in Safari

## Versions

?**App**

* Angular: Uknown
* Node: : Uknown
* Clarity: : Uknown

**Device:**

* Type: Any
* OS: Any
* Browser: Any
* Version: Any

## Additional notes
NA

**Comment by gnomeontherun** [comment] 2019-12-20 22:17
This appears to be a duplicate of #4084 so closing this in favor of that one.

**Closed by gnomeontherun** 2019-12-20 22:17 UTC
Labels: @clr/angular, browser: safari, component: wizard, status: needs investigation, type: accessibility
