### ISSUE TITLE
Column control cannot be removed

### ISSUE THREAD

**Issue by ellitsaHristova** [vmware/clarity#2283] opened 2018-05-16 14:21 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The column control shows up on first click and can be closed

### Actual behavior
The column control does not show up on first click and cannot be closed

### Reproduction of behavior
1. Open 1 or more column filters.
2. Click the button for showing the column control.
3. Observe that the column control does not show up. So click the button again.
4. Observe that the column control cannot be closed.

https://stackblitz.com/edit/angular-gekk5z

### Environment details

* **Browser:** all

**Comment by youdz** [comment] 2018-05-16 14:38
Duplicate of #1183.

**Closed by youdz** 2018-05-16 14:38 UTC
