### ISSUE TITLE
[TAB] Tabs content caching when custom tab navigate is required.

### ISSUE THREAD

**Issue by Gesh4o** [vmware/clarity#2289] opened 2018-05-17 12:54 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```
### Description

I have the following scenario - several clarity tabs one of which **initially** should be **open** based on a url parameter (after that clarity handles tab selection).

In order to achieve that I am using the `*clrIfActive` structural directive. The issue that I am having is when the user is switching between tabs the closed tab gets **destroyed** and when this tab is opened again is **recreated** once more. 

I want to be able to set which tab should be **initially** **opened** and preserve closed tab's **state** because:
 - it will make transition between tabs more optimized **performance** wise (data won't be requested every time I reselect closed tab)
 - it will provide better **UX**  in my opinion since preserving the old tab's state won't actually lose any data (like selected value in a dropdown or grid). **Note** that switching between the tabs in my (real) case is not used for data comparison.

### Reproduction of behavior
In this [demo](https://stackblitz.com/edit/clarity-light-theme-v11-mmqdwh) you can navigate between two tabs. The second tab contains state which will be lost after navigating out of it.

If such logic is can be implemented already I will appreciate your advice!

Thank you!

**Comment by adityarb88** [comment] 2018-05-17 13:07
@Gesh4o: This looks like a duplicate of https://github.com/vmware/clarity/issues/2112. Please subscribe to #2112 for more information.

Closing this based on the above info. Please feel free to reopen the issue if you have more questions/feedback.

**Closed by adityarb88** 2018-05-17 13:07 UTC
