### ISSUE TITLE
Advanced keyboard navigation for the step/page progress component in the wizard

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#2359] opened 2018-06-13 12:54 UTC
[X ] feature request
[X ] enhancement

### Expected behavior

I would like to request ARIA attributes for the step/page progress component in the wizard (the component in the left pane).
The active state information is indicated using color only we would like to have ARIA attribute for the active state (selected step).

Also probably is good to have ability to move to the next page by clicking or pressing some keyboard key on the next step in the step/page progress list. 

### Environment details

Angular version: 4.x.x

Clarity version: 11.0.1

OS and version:**

Browser:all

**Comment by adityarb88** [comment] 2018-07-13 13:28
@dkanev: I believe the ARIA attributes were already added by @mathisscott when he wrote the component.

Wizard Step:
![image](https://user-images.githubusercontent.com/1426805/42693981-d825b4f4-867e-11e8-9f87-b33653b92bb3.png)

![image](https://user-images.githubusercontent.com/1426805/42694023-f1f30aa8-867e-11e8-8ef2-42978770bac4.png)

Wizard Page:
![image](https://user-images.githubusercontent.com/1426805/42694051-0a8699a4-867f-11e8-8665-3fbc5373aafb.png)

I will check with UX as to what they recommend for the keyboard navigation part.

cc: @reddolan @mathisscott

**Comment by bashibozuk** [comment] 2020-05-05 12:15
Are you guys planning to invest efforts on this issue any time soon ?

**Comment by hippee-lee** [comment] 2020-05-05 15:14
Hi @bashibozuk - this issue is in the backlog but has not been prioritized for someone on the team to pick up at this time.

**Comment by gnomeontherun** [comment] 2021-01-29 19:19
Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed by gnomeontherun** 2021-01-29 19:19 UTC
Labels: Dev, flag: has workaround, priority: 1 low, type: accessibility, type: enhancement
