### ISSUE TITLE
Datagrid - output clrDgHiddenChange is not called when showing/hiding columns

### ISSUE THREAD

**Issue by josephaVMW** [vmware/clarity#5123] opened 2020-10-06 18:35 UTC
## Describe the bug

Within a datagrid in Clarity v4, the output clrDgHiddenChange is not called when a user hides or shows columns using the dialog inside the datagrid footer.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-datagrid-column-hide?devtoolsheight=33&file=src/app/app.component.html

1.  Toggle the Show/Hide columns dialog in the left side of the footer
2.  Show or hide any columns
3.  Note that an alert and console logging are not generated

## Expected behavior

The _notify_ function should be called whenever columns are shown or hidden.

## Versions

**App**

- Angular CLI: 10.1.3
- Node: 12.18.4
- OS: win32 x64
- Clarity: ^4.0.2

**Device:**

- Type: Dell Laptop
- OS: win32 x64 (Windows 10)
- Browser: Brave v1.14.81 (Chromium v85.0.4183.102), Firefox v80.0.1

## Additional notes

Discussed in thread https://vmware.slack.com/archives/C0JF5M52Q/p1601666865028900

**Comment by mcirillo-sw** [comment] 2021-09-17 18:46
Hi, are there any news on this issue? I'm still reproducing it with Angular CLI 12.1.0, Clarity 5.4.1 and Node 14.17.3

**Comment by Jinnie** [comment] 2021-09-23 11:30
This has been discussed in the past:
https://github.com/vmware/clarity/issues/2117
You can find several different workarounds in the above issue.
Our final statement has been that we won't be fixing it for Clairty Angular, as there are workarounds and upcoming fix in Clarity Core.
See @gnomeontherun's last comment for more details.

Closing as duplicate of #2117.

**Closed by Jinnie** 2021-09-23 11:30 UTC
Labels: type: bug, flag: regression, component: datagrid, @clr/angular
