### ISSUE TITLE
Modals are losing focus when user presses tab 

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#2396] opened 2018-06-27 08:04 UTC
**Select one ...** (check one with "x")

```
[x] bug
[x] enhancement
```

### Expected behavior
I would like to request the following functionality:  
when I open a Clarity Modal and navigatе with the Tab button in it and when I focus out the last element in the modal the first focusable element of the modal should be focused like this example shows https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

### Actual behavior
When I focus out the last element of the modal the address bar is focused

EDIT by @youdz: I'm copy-pasting your detailed explanation here, because you nailed it and I want this to be visible immediately without reading all the comments. 😄 The important part for reproduction is that the modal or wizard needs to be **the last element in the page**.

> According to my observations if the wizard is the last focusable element in the DOM it happens all the time. This is a bug in the focus trap directive which you are using to keep the focus in the wizard. This is what happens according to my observations:
>
>1. When you press tab on the last button of the wizard the focus goes away from the wizard
>2. The browser tries to focus the next focusable element in the DOM, but since there is no such element the focus goes to the first in the browser , which is the address bar
>3. The focus trap directive does not catch the situation, because it listens the DOM three for focusin event which does not happen because the address bar is outside the DOM. on the next tab , when the focus enters inside the DOM(which may not be exactly the next one, if there are more controls on the browser), the focus trap catches the event.

### Reproduction of behavior
Go to https://clarity-light-theme-v11-9rttaf.stackblitz.io/ and click the Open Modal button
A modal will show
Start pressing tab button. After focus is removed from the OK button, the address bar of the browser is focused

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.11.21

* **OS and version:** OSX 10.12.6 | Windows 10

* **Browser:** [Chrome 67.0.3396.99 | Firefox 60.0.2 | IE 11 ]

**Comment by mathisscott** [comment] 2018-07-06 15:56
@bashibozuk 
We need more info on this. We cannot reproduce this issue on http://clarity-ks.surge.sh/modals

I see it in your stackblitz but only in that stackblitz. Do you know why that might be?

**Comment by bashibozuk** [comment] 2018-07-09 12:45
According to my observations if the wizard is the last focusable element  in the DOM it happens all the time. This is a bug in the focus trap directive which you are using to keep the focus in the wizard. This is what happens according to my observations: 
1) When you press tab on the last button of the wizard the focus goes away from the wizard 
2) The browser tries to focus the next focusable element in the DOM, but since there is no such element the focus goes to the first in the browser , which is the address bar
3) The focus trap directive does not catch the situation, because it listens the DOM three for focusin event which does not happen because the address bar is outside the DOM. on the next tab , when the focus enters inside the DOM the focus trap catches the event.

**Comment by mathisscott** [comment] 2018-07-09 14:08
@bashibozuk 
So this is an issue with the wizard? The description and title only say modal.

**Comment by bashibozuk** [comment] 2018-07-09 14:31
@mathisscott the issue actually is the focus trap which is used to keep the focus inside the clarity modals. Since the wizard uses clr-modal internally I think that the issue affects both the wizard and the modal. Here is an example which I think illustrates the issue better https://clarity-light-theme-v11-bwyf5c.stackblitz.io/. In my opinion you should employ the `window.blur` event to detect when when focus goes out of the DOM to return it back to the wizard.

**Comment by mathisscott** [comment] 2018-07-09 14:32
Yes, @bashibozuk 

But as I pointed out earlier, we couldn't reproduce this with the modal. I'll ask the team to look at it with the wizard.

Thanks!

**Comment by bashibozuk** [comment] 2018-07-09 14:45
Hi @mathisscott , would you please take a look at this example https://clarity-light-theme-v11-bwyf5c.stackblitz.io/. The issue is 100% reproducible here. Just open the link, press the button and start pressing TAB.  Please let me know if you have any problems with reproducing the issue, I could record a video if the behavior if it is it is necessary.

**Comment by bashibozuk** [comment] 2018-07-09 14:59
Attaching a recording 

[clarity-focus-trap-issue.mov.zip](https://github.com/vmware/clarity/files/2176726/clarity-focus-trap-issue.mov.zip)

**Comment by mathisscott** [comment] 2018-07-11 16:55
Hi @bashibozuk 

Sorry this has taken me a bit to get back to you. This week we've had a dozen fires and I'm only one fireman.

I've reviewed your video and see what you're describing. The problem is that we don't know if this is a bug introduced by stackblitz or not. We have to look into it. Again, see fires vs. firemen.

I'm attaching a video of the modal in our kitchen sink app. It doesn't show the behavior that the modal in the stackblitz does. 

I'm happy to discuss further.

[clarityModalsTabbing.mov.zip](https://github.com/vmware/clarity/files/2185455/clarityModalsTabbing.mov.zip)

**Comment by gnomeontherun** [comment] 2018-07-11 21:12
The workaround for this is to not allow the modal to be the last content of the page, instead put it at the top of the page. The issue only happens when the modal is the last element of the page that can be tabbed into, and our focus trap doesn't kick in here. The wizard should work find with the same workaround.

This is related to #2400 and could be fixed in the same basic way. Since we only catch the focus trap when the `focusin` event tries to focus on another element _after_ the modal content, it works on our site and docs. However, if it is the last tabbable item in the page, there is no final `focusin` event fired before it hops to the browser chrome.

**Closed** 2018-08-07 16:50 UTC
Labels: Accepted, Bug, ClarityNG, Has Workaround, In Review
