### ISSUE TITLE
Stack View Doesn't work with Safari and Edge

### ISSUE THREAD

**Issue by jkjha** [vmware/clarity#3646] opened 2019-07-25 12:36 UTC
## Describe the bug

Stack View not working in Safari and IE with Clarity verion 1.1.0. 
## How to reproduce

Check the link with v1.1.0: https://stackblitz.com/edit/clarity-light-theme-v1-0-h3mowx?file=package.json

1.  Go to  above stackblitz in safari or Edge.
2.  Try to expand the row.

## Expected behavior

It should expand the row and show the data. 

## Versions

**App**

* Angular: ^7.2.0
* Node: NA
* Clarity: ^1.1.0

**Device:**

* Type: Macbook, Windows
* OS: Win, Mac
* Browser Safari, Edge
* Version Latest

## Additional notes

This issue seems similar to this, but due to inactivity there, Opening a new one.

https://github.com/vmware/clarity/issues/3308

**Comment by mattmutt** [comment] 2019-07-25 15:20
Am prescribing angular/animations 7.2.7 exactly as that application's dependency.

**Comment by gnomeontherun** [comment] 2019-07-29 21:52
For some reason, the `display: none` style is left on the content, if I clear that attribute then it displays and collapses again.

**Comment by dennitsa** [comment] 2019-07-30 10:18
I had the same issue, it is fixed in Clarity 2.1 with https://github.com/vmware/clarity/pull/3470
p.s. In 2.0 it is also not working.

**Comment by mattmutt** [comment] 2019-07-31 19:04
stick to the exact 7.2.7 release of the animation and all will be well. There is nothing Clarity should attempt to patch without getting into the thick details of how sequenced animations are ordered during transitions.

**Comment by gnomeontherun** [comment] 2019-07-31 21:17
Thanks @mattmutt I found this open issue on Angular side, so this sounds like a dependency regression. We suggest the workaround to pin your version and we might also port the fix from #3470 to v1 to also fix this.

https://github.com/angular/angular/issues/30314

**Comment by gnomeontherun** [comment] 2020-10-29 22:37
Closing due to being isolated to an unsupported version of Clarity or has been fixed in more recent versions.

**Closed** 2021-02-01 21:30 UTC
Labels: Dependency Regression, flag: has workaround, status: needs investigation, type: bug, v1
