### ISSUE TITLE
clarity-angular version bump from 0.10.7 to 0.10.9 results in angular-cli build module resolution error

### ISSUE THREAD

**Issue by williamhallatt** [vmware/clarity#1592] opened 2017-10-14 09:07 UTC
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
ng build/serve should compile without errors

### Actual behavior
Angular CLI based project fails with, what seems to be, a webpack error (field 'browser' doesn't contain a valid alias configuration). Complete error output follows.

```
ERROR in ./src/app/private/layout/header/header.component.ts
Module not found: Error: Can't resolve 'clarity-angular/layout/nav/clrResponsiveNavigationService' in 'D:\code\testapp\src\app\private\layout\header'
resolve 'clarity-angular/layout/nav/clrResponsiveNavigationService' in 'D:\code\testapp\src\app\private\layout\header'
  Parsed request is a module
  using description file: D:\code\testapp\package.json (relative path: ./src/app/private/layout/header)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\code\testapp\package.json (relative path: ./src/app/private/layout/header)
    resolve as module
      D:\code\testapp\src\app\private\layout\header\node_modules doesn't exist or is not a directory
      D:\code\testapp\src\app\private\layout\node_modules doesn't exist or is not a directory
      D:\code\testapp\src\app\private\node_modules doesn't exist or is not a directory
      D:\code\testapp\src\app\node_modules doesn't exist or is not a directory
      D:\code\testapp\src\node_modules doesn't exist or is not a directory
      D:\code\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\code\testapp\node_modules
        using description file: D:\code\testapp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\code\testapp\package.json (relative path: ./node_modules)
          using description file: D:\code\testapp\node_modules\clarity-angular\package.json (relative path: ./layout/nav/clrResponsiveNavigationService)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.js doesn't exist
            as directory
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
      looking for modules in D:\code\testapp\node_modules
        using description file: D:\code\testapp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\code\testapp\package.json (relative path: ./node_modules)
          using description file: D:\code\testapp\node_modules\clarity-angular\package.json (relative path: ./layout/nav/clrResponsiveNavigationService)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.js doesn't exist
            as directory
              D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
      looking for modules in D:\code\testapp\src
        using description file: D:\code\testapp\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\code\testapp\package.json (relative path: ./src)
          using description file: D:\code\testapp\package.json (relative path: ./src/clarity-angular/layout/nav/clrResponsiveNavigationService)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.js doesn't exist
            as directory
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
      looking for modules in D:\code\testapp\src
        using description file: D:\code\testapp\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\code\testapp\package.json (relative path: ./src)
          using description file: D:\code\testapp\package.json (relative path: ./src/clarity-angular/layout/nav/clrResponsiveNavigationService)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.js doesn't exist
            as directory
              D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService doesn't exist
[D:\code\testapp\src\app\private\layout\header\node_modules]
[D:\code\testapp\src\app\private\layout\node_modules]
[D:\code\testapp\src\app\private\node_modules]
[D:\code\testapp\src\app\node_modules]
[D:\code\testapp\src\node_modules]
[D:\code\node_modules]
[D:\node_modules]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.ts]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.js]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.ts]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService.js]
[D:\code\testapp\node_modules\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.ts]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.js]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.ts]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService.js]
[D:\code\testapp\src\clarity-angular\layout\nav\clrResponsiveNavigationService]
 @ ./src/app/private/layout/header/header.component.ts 20:0-107
 @ ./src/app/private/private.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Reproduction of behavior
package.json content is as below, changing the clarity-angular version from 0.10.7 to 0.10.9 as mentioned results in the failure above.

```
{
  "name": "testapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build.test": "ng build --target=production --environment=test",
    "build.prod": "ng build --target=production --environment=prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.1",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/platform-browser": "^4.4.5",
    "@angular/platform-browser-dynamic": "^4.4.5",
    "@angular/router": "^4.4.5",
    "@angular/upgrade": "^4.4.5",
    "@webcomponents/custom-elements": "1.0.4",
    "bootstrap": "4.0.0-beta",
    "chart.js": "^2.7.0",
    "clarity-angular": "0.10.7",
    "clarity-icons": "^0.10.9",
    "clarity-ui": "^0.10.9",
    "core-js": "^2.5.1",
    "d3": "^4.11.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ng2-toasty": "^4.0.3",
    "popper.js": "^1.12.5",
    "rxjs": "^5.4.2",
    "ts-helpers": "1.1.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.7",
    "@angular/compiler-cli": "^4.4.5",
    "@types/d3": "^4.11.0",
    "@types/jasmine": "^2.6.0",
    "@types/node": "^8.0.34",
    "codelyzer": "^3.2.1",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "^4.2.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "node-sass": "^4.5.3",
    "protractor": "5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "ts-node": "^3.3.0",
    "tslint": "^5.7.0",
    "typescript": ">=2.1.0 <2.4.0"
  }
}
```

### Environment details

* **Angular version:** 4.x.x
See above.

* **Clarity version:**
See above.

* **Windows 10, but using Git bash**

**Comment by mathisscott** [comment] 2017-10-16 15:40
@hippee-lee and @jeeyun : Could one of you check this out?

**Comment by rokobasilisk** [comment] 2017-10-24 12:53
Also experiencing this issue.

**Comment by adityarb88** [comment] 2017-10-24 13:07
@williamhallatt @rokobasilisk: Clarity website is built on top of Angular CLI too and we didn't face this issue. Could you give us more information to reproduce this? Can this be replicated on a Plnkr? https://embed.plnkr.co/AuJuo5/ If not then can you share a git repo which reproduces this?

**Comment by williamhallatt** [comment] 2017-10-25 06:40
@adityarb88 Here we go mate: [clarity-break-minimal](https://github.com/williamhallatt/clarity-break-minimal)

If you grab that repo 'as-is', it will build ("clarity-angular": "0.10.7"), as soon as you (nuke your node_modules), update the package.json to 0.10.9, 'yarn install' (I doubt it matters how you pull your packages, npm or otherwise, but included this bit for the sake of completeness) and 'ng build', you'll get the failure described above.

I savagely ripped apart an existing product to produce this franken-app, so I hope this is enough to work with :)

**Comment by rokobasilisk** [comment] 2017-10-25 12:17
@adityarb88 it turns out we were referencing a clarity object 'Page' in a unit test which was causing the error as Clarity seems to have started using Declaration files in the node_modules. We fixed our unit tests by changing an import from `import { Page } from 'clarity-angular/data/datagrid/providers/page';` to `import { ɵz as Page } from 'clarity-angular'; `.

Then we also had to pass in a StateDebouncer to the Page object but that was unrelated.

**Comment by adityarb88** [comment] 2017-10-25 13:43
@williamhallatt, @rokobasilisk: It looks to me that this issue is happening when you try to access the internal API. @williamhallatt In the repo your linked above I see this:

```
import { ClrResponsiveNavCodes } from 'clarity-angular/layout/nav/clrResponsiveNavCodes';
import { ClrResponsiveNavigationService } from 'clarity-angular/layout/nav/clrResponsiveNavigationService';
```

Could you please tell me why you need access to the nav service and the nav codes. We do not export these and accessing them is going to cause breakages.

Same applies for `Page` @rokobasilisk 

cc: @hippee-lee

**Comment by rokobasilisk** [comment] 2017-10-25 13:59
@adityarb88 we needed a greater level of customisation, and also as I previously mentioned for more thorough unit testing.

We understand the risks involved but thought our solution might help someone down the line and was worth posting!

**Comment by showlong** [comment] 2017-10-25 15:02
We also face the same issue in our customized checkbox tree view that meets our product need after upgrading to 0.10.9. It seems we cannot customize clarity-angular widgets anymore.

**Comment by adityarb88** [comment] 2017-10-25 15:36
@rokobasilisk: I am failing to understand why you need `Page` for testing components on your side. Could you please post an example and elaborate more on that?

@showlong: We need more details to understand the issue.

> It seems we cannot customize clarity-angular widgets anymore.

I don't believe this is true. What exactly are you trying to customize? What were you trying to access before that you cannot access now? If you provide us with more details and the use case for doing that, we can consider providing what you need or recommend an alternative solution.

I would recommend that you file a separate issue for your customized tree view use case so that we can review and provide feedback.

Thanks!

**Comment by showlong** [comment] 2017-10-25 22:56
I simply just want to +1 to report this issue.
In my case it seems the following 3 internal API are not exposed from your webpack build now but are available from previous angular cli build. It is simple question that if your webpack build block the internal APIs.

import {Expand} from 'clarity-angular/utils/expand/providers/expand';
import {TreeSelectionService} from 'clarity-angular/data/tree-view/providers/tree-selection.service';
import {clrTreeSelectionProviderFactory} from 'clarity-angular/data/tree-view/providers/tree-selection.provider';

**Comment by gnomeontherun** [comment] 2017-10-26 00:53
I believe our bundles are now correctly isolating private APIs, and I don't believe we want to be supporting internal APIs that aren't meant for external consumption. 

I'm not entirely sure what the use cases are for them here. If you are accessing internal APIs of Clarity, then you are likely unit testing Clarity and not your components, and the recommendation is to test using the public APIs.

**Comment by williamhallatt** [comment] 2017-10-26 11:32
@adityarb88 

"Could you please tell me why you need access to the nav service and the nav codes. We do not export these and accessing them is going to cause breakages."

That explains a lot, I did not actually implement those bits, will find out and confirm whether or not there was a logical use-case or if it is learning curve related.

Thanks for the investigation and feedback!

**Comment by steveland83** [comment] 2017-10-26 23:02
@adityarb88 In relation to your question to @williamhallatt  above - we're using the ResponsiveNavService because the responsive menu's hamburger toggle actions dont seem to fire automatically - at least in our implementation.

I've forked the example @williamhallatt created to demonstrate the issue - to see this behaviour, pull down and serve this app: https://github.com/steveland83/clarity-break-minimal
In this fork I've commented out the calls to ResponsiveNavService. Clicking the menu hamburger trigger no longer toggles the responsive menu. If you revert the commit I made, you'll see that the menu triggers.
**Note that the Burger will only be visible when the browser is resized to a mobile screen size.

I adapted this code from here:
https://github.com/vmware/clarity/blob/6d3e670d8b386df45e9dd201e3b026e67be03a34/src/clarity-angular/layout/nav/header.ts

I'm assuming that we must have an issue in our implementation which is the root cause - but I'm unable to find it based on the examples available. 
The documentation for sidenav (https://vmware.github.io/clarity/documentation/sidenav) doesnt mention of this functionality or provide an applicable example, so any pointers you can offer would be most appreciated :)

**Comment by steveland83** [comment] 2017-10-27 06:37
Update to the above - I've just found https://vmware.github.io/clarity/documentation/navigation
This section does describe the usage for responsive nav - we just didnt think to look under patterns before.

I've tested with this - and it certainly does work if used as described (`<clr-header>` tag directly within `<clr-main-container>`). In our case we insert this code based on the route (we have public & private menus) - its also in a child component a few levels down - and this seems to break it.

**Comment by adityarb88** [comment] 2017-10-27 13:59
@steveland83: Could you replicate your issue on a Plnkr https://embed.plnkr.co/AuJuo5/ and file a new issue. Once you do that we can figure out whats going on.

**Comment by adityarb88** [comment] 2017-10-27 14:09
I am going to close this issue. For more details please read @youdz's response here: https://github.com/vmware/clarity/issues/1649#issuecomment-339968863

I would recommend that you submit a separate issue for each of your use cases which break after upgrading from 0.10.7 to the latest version. Please provide details on why you need to access the internal API and we can give more feedback on how your issue can be resolved. If you are trying to do something that has a valid use case and is not present currently, we wouldn't mind providing that feature to you through our public API. But to do that we need to know more details about what you are trying to do and the use case for doing that. Thanks again! Please feel free to reach out to use if you have any more questions.

**Closed by adityarb88** 2017-10-27 14:09 UTC
Labels: ClarityCore, needs-triage

**Comment by steveland83** [comment] 2017-10-27 22:22
Thanks @adityarb88 - we do not need access to the internal API.
Our problems with Responsive Nav were the result of incorrect classes on the nav element - which were resolved after comparing to the example at https://vmware.github.io/clarity/documentation/navigation
