### ISSUE TITLE
Will pagination be an independent component ?

### ISSUE THREAD

**Issue by ThinkontrolSY** [vmware/clarity#1376] opened 2017-08-27 01:21 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

pagination is now only available in data-grid.
Will pagination be an independent component so that other list data can be paginated ?

**Comment by mathisscott** [comment] 2017-08-29 13:48
@ThinkontrolSY 
We have an existing issue open for a pagination component ( #538 ). We haven't made a decision yet whether or not we are going to design and build a generic pagination component.

I'm closing this as a duplicate of #538. Please subscribe to that issue to track progress and participate in conversations re: pagination. Thanks!

**Closed by mathisscott** 2017-08-29 13:48 UTC
