### ISSUE TITLE
Setting datagrid selection reactively results in infinite loop

### ISSUE THREAD

**Issue by mfp22** [vmware/clarity#2613] opened 2018-08-31 23:51 UTC
## Describe the bug

We want to store the selection in `ngrx/store`. In our component we're using a server-driven data grid. We are using `changeDetection: ChangeDetectionStrategy.OnPush,` and we're binding to `clrDgSelected` using the `async` pipe like so:
```
<clr-datagrid [clrDgSelected]="selected$ | async"
    (clrDgSelectedChange)="changeSelection($event)"
    [clrDgLoading]="loading$ | async" 
    (clrDgRefresh)="changeFilters($event)">
    
  <clr-dg-column *ngFor="let col of columns$ | async; trackBy: getKey" [clrFilterValue]="col.filterValue" [clrDgField]="col.key">
      {{col.title}}
  </clr-dg-column>
  <clr-dg-column></clr-dg-column>

  <clr-dg-row *ngFor="let item of items$ | async" [clrDgItem]="item">
      <clr-dg-cell>
        {{item.value}}
      </clr-dg-cell>
      <clr-dg-cell></clr-dg-cell>
  </clr-dg-row>
  
  <clr-dg-footer>
      {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
      of {{count$ | async}} items
      <clr-dg-pagination #pagination [clrDgTotalItems]="count$ | async"></clr-dg-pagination>
  </clr-dg-footer>
</clr-datagrid>
```

The app goes into an infinite loop on initialization. 

## How to reproduce

https://stackblitz.com/edit/angular-clarity-reactive

1.  Uncomment the code under this line: `// Uncomment the following and infinite loop occurs:`
2. Refresh the app

I've created a sort of mock ngrx/store, but it works the same. The important part is `selected$` and `items$` emitting new arrays every so often. 

## Expected behavior

No infinite loop occurs. At any time, the state in the store can change, and `selected$` will emit a new array and the checkboxes should reflect that state.

## Versions

**App**

* Angular: 5.0.0
* Node: StackBlitz
* Clarity: 0.12.11

**Device:**

* Type: MacBook
* Browser: Chrome

## Additional notes

`OnPush` and `| async` are encouraged by the Angular team because they are efficient and reactive.

**Comment by mathisscott** [comment] 2018-09-04 13:31
Thanks for filing this issue, @mfp22 

We will need to dive into this StackBlitz to see what's happening here.

**Comment by gnomeontherun** [comment] 2018-09-04 15:46
It would help us out if you could provide any additional anecdotal and observational details you have, as there are so many things in play right here. For example, does it seem to happen due to using async with selection only, or all things together? It would help us narrow down the field of potential places to review and speed up our investigation. Thanks.

**Comment by mfp22** [comment] 2018-09-04 18:01
I can't remember much since I have only touched this every once in a while, but I do remember selection being really sensitive to the async pipe in the past. 

Before I created this issue I peaked around at the source code and saw this line https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/selection.ts#L225 which emits a change whenever a new value from the outside is inputted. In general I have found that Angular has liked me more when I only emit outputs in response to user events. So instead of taking data into a component, processing, and then outputting the result, I provide a service with the component for any data processing that the outside would care about, then the processing can happen as the data trickles down the services/components tree instead of inside the component. 

So I assumed that this was the ultimate source of this bug. Whenever a change emits from `clrDgSelectedChange`, I update my items in ngrx/store for which ones are `checked`. Certain items are going to come back from the server as pre-`checked`, so I always need to calculate the `selected` array from the `items` in the store, so then `items.filter` always creates a new reference that pops out of the `async` pipe into `[clrDgSelected]`. This in turn triggers `this.emitChange();` which updates items in the store, and the cycle repeats. Maybe there is more to it though.

I tried a few ways to "ignore" the extra onDgSelected outputs, but I couldn't figure anything out. If you can think of a way to do this, I could really use it.

**Comment by youdz** [comment] 2018-09-06 00:02
This example is nowhere near minimal. Filters have nothing to do with this, half of your store features are irrelevant (`distinctUntilChanged()` uses reference equality so it is useless in your example, `shareReplay(1)` on a BehaviorSubject doesn't do anything that BehaviorSubject didn't do in the first place, etc). The way to implement a minimal reproduction is to start from scratch and add features until the bug appear, not the other way round.

In your case, I can't possibly detail everything that is wrong with your StackBlitz, but I can easily tell you that you are generating brand new arrays and objects all the time but you are not using `trackBy` on your items' `*ngFor`. Doing so prevents your infinite loop from happening.

I'll leave this open in case because I can't be sure this is what you meant given your StackBlitz, but feel free to close the issue if it's solved for you.

**Comment by mfp22** [comment] 2018-09-06 19:03
My apologies. I was re-using a previous StackBlitz I had set up to illustrate a bug with filters for which I ended up discovering a workaround. I didn't realize that about BehaviorSubject, thank you for pointing that out. `.map(...).distinctUntilChanged()` was to replicate the `select` operator of ngrx; I didn't care what it did, I just wanted it to be the same as ngrx without bothering with setting up an actual store. In the future, whenever I see an issue with Clarity, I'll have to allot enough time to set up the StackBlitz more carefully.

Unfortunately, when I add `; trackBy: getValue` ... `getValue = item => item.value`, the infinite loop goes away, but selection breaks in other major ways. The initial state is this:
![image](https://user-images.githubusercontent.com/13700926/45178383-c0c22e80-b1d2-11e8-866c-8e0f92e47911.png)
After I select all fields, I get this:
![image](https://user-images.githubusercontent.com/13700926/45178436-e5b6a180-b1d2-11e8-8d10-c6c9f98822c1.png)

The infinite loop is just one possibility in the set of troubles I've encountered when trying to push new select states into `[clrDgSelected]`. The code in `data/datagrid/providers/selection.ts` is very imperative as opposed to reactive, making inconsistent state the default result when any new behavior is added. Those states in the screenshots would be impossible if it were more reactive. 

My recommendation is to refactor the code in `selection.ts` to be more reactive, but my team would like a more short-term fix for this specific use case so we don't have to move to our backup design, which isn't as simple.

**Comment by youdz** [comment] 2018-09-07 18:19
I apologize if my first answer seemed harsh, here comes a much more detailed and helpful one.

>In the future, whenever I see an issue with Clarity, I'll have to allot enough time to set up the StackBlitz more carefully.

We are a small team of 4 devs and 1 tech lead, and we get daily requests from hundreds of teams just within VMware, not counting the ones from our open source consumers. That means we have extremely limited time to allocate to investigating issues. By submitting an obfuscated example, you're making it so that we will always prioritize issues with a clean reproduction before yours because it's a more efficient way to spend what little time we have. Your issue could sit there for months with no answer and just the "Needs Investigation" label. 

If you don't have time to set up a minimal reproduction, we understand and you can go ahead and submit what you have, but please accept that we also have limited resources and can't compensate for the time you couldn't spend.

Now, let's get to your particular issue.

### The minimal reproduction

I took the time to write a much shorter and clean example of the issue you have: https://stackblitz.com/edit/reactive-datagrid-selection-minimal?file=app/app.component.ts

I removed filters, sorting, pagination, data refresh, etc. The only things I needed to reproduce the issue was observable-based state (to mimic ngrx) and tracking selection with a property on the items themselves. Note that I added a counter to break the infinite loop if it ever happens, so experimentating is safe and the browser won't just freeze.

If you play with the running example a little bit you'll instantly see it's broken, it keeps reaching impossible states.

### The explanation

What you have here is a hidden "Expression has changed after it was checked" error. Hidden because you use `ChangeDetectionStrategy.OnPush` so it doesn't raise an actual error, but it's exactly the problem you have here. Here is the exact same example without `OnPush`: https://stackblitz.com/edit/reactive-datagrid-selection-no-onpush?file=app/app.component.ts

As you can see you now have the aforementioned error, and your infinite loop is even back.
The reason this happens has been discussed over and over, so I won't go into details here but I highly recommend checking out these links:
- https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4
- https://github.com/angular/angular/issues/17572
- https://github.com/angular/angular/issues/6005
- https://github.com/angular/angular/issues/18129#issuecomment-326801192

It's extremely common with ngrx in particular, due to the fact that synchronous state changes used in bindings with the `async` pipe will trigger it almost every time.
In your particular case, what's happening is that during the datagrid's change detection we emit an output for selection changed. Your listener to that output reacts synchronously, rewriting the entire array of items and the items themselves to preserve immutability (which is what you want, I assume). Since this array is used in a binding on the datagrid, it would need another change detection run to stabilize, hence the error. With `OnPush` the error wasn't thrown, but you still had this changed binding that wasn't taken into account, leading to an inconsistent UI.


### First tentative fix

Let's try the typical fix for these errors, that you'll see mentioned 1000 times in the above links: making the change asynchronous so that it happens in the next change detection cycle. This can easily be done by adding `.delay(0)` to our observables: https://stackblitz.com/edit/reactive-datagrid-selection-delay?file=app/app.component.ts

No more big red error, but the infinite loop is still happening. That's because the observables fire a brand new array of brand new objects every time, and it never stabilizes. 

### The better fix

You kind of had the right intuition with `distinctUntilChanged` that you put to copy ngrx, but `distinctUntilChanged` uses reference equality by default so it is completely useless on immutable arrays and objects like the ones you use. Your ngrx store doesn't know that the new array is the same as the old one every time so the observables fire constantly, and Clarity doesn't know their the same either. In other words, you can't expect Clarity to be smarter about your data than even your own ngrx store is. This is the general idea of `trackBy`, but in this case there is no easy `trackBy` to just use directly with Angular.

Rather than ask Clarity to perform deep comparison of arrays and objects for the datagrid, which simply cannot be done for performance reasons, you should make sure your ngrx store doesn't fire state changes when the state hasn't actually changed. 

Let's put back the `OnPush` so that we reproduce your own example more accurately, and add a comparison function to `distinctUntilChanged` so that the observables fire only if the state actually changed: https://stackblitz.com/edit/reactive-datagrid-selection-fix?file=app/app.component.ts

It now works perfectly, and you can see from the logs that we're down to a single "Selection changed" log for each user action, as you would expect.

### Conclusion

This is not an issue with Clarity's datagrid selection not being implemented in a "reactive way". For what it's worth, the entire Datagrid architecture is based on a chain of Observable to update the view and emit outputs, which is reactive.

The problem is that the combination of ngrx, immutable states, async pipes and synchronous state changes creates numerous issues with Angular, which as you can see from the links above have raised hundreds and hundreds of comments on GitHub. You would hit the same issue with any component offering two bindings that are tied together, and output a change when the other changes.

**Comment by youdz** [comment] 2018-09-07 18:30
I'm going to go ahead an close this as not a Clarity issue, but feel free to answer here if you have additional comments on this, we'll get a notification.

**Comment by mfp22** [comment] 2018-09-07 20:53
Thanks for the explanation. That was awesome.

I'm still seeing a couple of issues though, even with the changes you made in stackblitz.com/edit/reactive-datagrid-selection-fix?file=app/app.component.ts . When I change all items to `true`:
![image](https://user-images.githubusercontent.com/13700926/45241341-53cd9800-b2a9-11e8-9015-0f70be3e8377.png)

It shows this initially:
![image](https://user-images.githubusercontent.com/13700926/45241359-6a73ef00-b2a9-11e8-8852-deeaa0d15301.png)

I click the top box and get this:
![image](https://user-images.githubusercontent.com/13700926/45241453-cb9bc280-b2a9-11e8-955c-88d8fb5026a3.png)

And then after about 20 clicks, it logs `Infinite loop detected` in the console. I can't figure out the pattern to reproduce it, but it always happens around 10-20 clicks I think.

**Comment by mfp22** [comment] 2018-09-11 02:02
Working around this is very difficult. Nothing else I tried worked, so now I'm manipulating the DOM directly from outside the datagrid and it still isn't working. Random events fire from the datagrid without any user input. I have to be careful about `setTimeout` because the datagrid mutates the objects passed into it.

**Comment by youdz** [comment] 2018-09-11 12:40
Sorry that was my bad, I forgot the order of trackBy arguments so I used
```typescript
trackByValue = item => item.value;
```
instead of 
```typescript
trackByValue = (index, item) => item.value;
```

I updated all plunkers, it works fine now.

**Closed by youdz** 2018-09-11 12:40 UTC
Labels: Invalid

**Comment by mfp22** [comment] 2018-09-11 15:56
Oh man! Looks like I need to learn Angular! Thanks for the update!

There are still some issues with this though, unfortunately. The all checkboxes checkbox doesn't update without another click somewhere, so it's a change detection issue at first. Here's what that looks like:
![image](https://user-images.githubusercontent.com/13700926/45371232-53821500-b5a7-11e8-8a48-a972472392f9.png)

![image](https://user-images.githubusercontent.com/13700926/45371274-685ea880-b5a7-11e8-9bbb-3207fd03f49a.png)

But this is a relatively easy problem to fix. 

The bigger problem is that it still falls into an infinite loop after 20 or so clicks:
![image](https://user-images.githubusercontent.com/13700926/45371847-c17b0c00-b5a8-11e8-949a-c0328c0fb726.png)

**Comment by gnomeontherun** [comment] 2018-09-11 16:39
It does not fall into an infinite loop, look around line 53 of the app component. 20 selection changes will trigger this message and is there to detect if one click triggers an infinite loop or not. 

As far as the Select All button, there does seem to be a little issue there with OnPush, turning it off works fine. I'll log a new ticket to investigate that further, but that is a minor issue I think.

**Comment by mfp22** [comment] 2018-09-11 16:42
Oh, I see. Yes, that's relatively minor. Thanks for your help.

**Comment by alonbez** [comment] 2018-11-26 11:42
> Oh, I see. Yes, that's relatively minor. Thanks for your help.

How you solved this?
I can't find an elegant way without going to that loop again.

**Comment by mfp22** [comment] 2018-11-26 15:48
@alonbez I could never figure it out for my actual component. Some random feature of the datagrid actually was influencing this so that I could figure it out in isolation on StackBlitz, but not with my actual component. I didn't have the time to drill down and figure out exactly what it was.

I also had so many places I wanted to use the datagrid and I didn't want to turn on change detection for the entire app. So I kept using my function that directly talked to the DOM.
