### ISSUE TITLE
Static tree view node and clrRecursiveFor

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#5613] opened 2021-02-16 20:29 UTC
## Describe the bug

Adding a *clrRecursiveFor clr-tree-node under a static template clr-tree-node does not make the *clrRecursiveFor clr-tree-node a child.

![image](https://user-images.githubusercontent.com/4148643/108117857-cc052e00-709d-11eb-8dbd-bddd97cd9f05.png)

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-jbcxnb?file=src/app/app.component.html

## Expected behavior

The *clrRecursiveFor clr-tree-node should be a child of the outer clr-tree-node.

![image](https://user-images.githubusercontent.com/4148643/108117773-abd56f00-709d-11eb-90ad-ef3d630383fc.png)

## Versions

**Clarity project:**

- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.0.1

**Framework:**

- [x] Angular

**Framework version:**
- [x] Angular 11.1

**Device:**

- Type: [Windows]
- OS: [Windows 10]
- Browser [Chrome]
- Version [88]

**Comment by Jinnie** [comment] 2021-02-22 14:04
I see your point and it would have been useful if we could mix static and recursive tree nodes.
But the current implementation will not allow it. It's easy to achieve the same, working on the model level, though, by implicitly adding the desired "static" root node. See this sample stackblitz:
https://stackblitz.com/edit/clarity-static-root-recursive-tree?file=src%2Fapp%2Fapp.component.ts
Based on the above workaround and the fact that our future feature focus is aimed at Clarity Core, which will be less restrictive by design, I'm going to close this issue. Please follow our Clarity Core development, where your case may have a more natural approach once the Tree component gets released.

**Closed as completed by Jinnie** 2021-02-22 14:04 UTC
Labels: resolution: wontfix, flag: has workaround, resolution: best with core
