### ISSUE TITLE
Datagrid filters no longer appear in front of the grid

### ISSUE THREAD

**Issue by BramMeerten** [vmware/clarity#3001] opened 2019-01-08 06:59 UTC
### Describe the bug
Custom and string filters are hidden when you have a small grid (or a big filter).
This screenshot is taken from the Clarity documentation (v1.0):
![now](https://user-images.githubusercontent.com/1921407/50773466-32011380-1291-11e9-9ea9-b3059490245a.PNG)

This is how it looks in the documentation of the previous version (v0.13):
![before](https://user-images.githubusercontent.com/1921407/50773536-6248b200-1291-11e9-8c2d-94af6cb7ec6a.PNG)

### How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v1-0-6zat36?file=src/app/app.component.ts

* Click the filter icon of the last column. It's not completely visible

### Expected behavior
The filter area should be in front of the grid (as is the case in older clarity versions).

### Versions
Angular version 7.0.0
Clarity version 1.0.3-patch
Google Chrome 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)

**Comment by youdz** [comment] 2019-01-08 13:12
Duplicate of #2683, please subscribe to that issue for future updates.

**Closed by youdz** 2019-01-08 13:12 UTC
