### ISSUE TITLE
Modal does not have hide animation when it has been created as angular component

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1888] opened 2018-01-26 13:57 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Modal has the same show and hide animation regardless of how it has been created: as static or as angular component.

### Actual behavior
If modal has been created as angular component it does not have hide animation.

### Reproduction of behavior
https://clarity-light-theme-v10-d5xkbh.stackblitz.io

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.10.15

* **OS and version:** Windows 10

* **Browser:** Chrome 63.0.3239.132

**Comment by adityarb88** [comment] 2018-01-26 14:17
@belyan: Thanks for filing the issue. This looks like a duplicate of #1148. Please subscribe to #1148 for future updates.

**Comment by adityarb88** [comment] 2018-01-26 14:19
Closing this as duplicate. Please feel free to reopen the issue if you feel this is different from #1148.

**Closed by adityarb88** 2018-01-26 14:19 UTC
Labels: duplicate

**Comment by belyan** [comment] 2018-01-26 14:22
Okay, sorry for the duplicate.

**Comment by adityarb88** [comment] 2018-01-26 14:23
No worries!
