### ISSUE TITLE
Dropdown with filter input

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2000] opened 2018-02-18 15:45 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

![image](https://user-images.githubusercontent.com/12848838/36353163-a02cc2fc-14e8-11e8-92f5-0ea7c8ecd118.png)
This will be helpful when there are many items in the list

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment] 2018-02-20 14:21
@shravansofts: This looks like a duplicate of https://github.com/vmware/clarity/issues/248. Please subscribe to #248 for more updates.

Closing this based on the above info.

**Closed by adityarb88** 2018-02-20 14:21 UTC
