### ISSUE TITLE
Would like to have icon "action button"

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#489] opened 2017-02-14 22:19 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ x] feature request
[ ] enhancement
```

### Expected behavior

I have a data table, and I'd like to have some icon buttons to perform actions on a given row. I can simulate what I want by using `<button class="close"><clr-icon ...`, but this also picks up other .close behavior, like float left. Would be nice to have a button class for icons that have a nice hover effect and maybe a click effect on an icon (no text).

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment] 2017-02-14 22:35
@rongery are you looking for a button group style for icons? Is this a duplicate of #247?

**Comment by rongery** [comment] 2017-02-14 23:03
Yes! Flat icon buttons as described near the bottom. Doed that already
exist today? I couldn't find reference to it in the docs.

Ron

**Comment by jaffoneh** [comment] 2017-02-14 23:06
Yes it's currently in development at the moment. #247 will have updates so closing this as a duplicate in the meantime.

**Closed by jaffoneh** 2017-02-14 23:06 UTC
