### ISSUE TITLE
Error:  @clr/ui@NaN with Angular 9 / Clr 3 new project

### ISSUE THREAD

**Issue by adumesny** [vmware/clarity#4494] opened 2020-04-21 22:12 UTC
## Describe the bug
trying to convert flyingdragon lib to support clr3, I created a new angular 9 project but getting error on the clarity part

## How to reproduce
following new projects setup, using latest angular cli 9.1.2 globally installed I did in a new folder:
```cmd
ng new test
cd test
ng add @clr/angular
```
gives this. Note the @clr/ui@NaN
``` cmd
UPDATE src/app/app.module.ts (488 bytes)
\ Installing packages...npm ERR! code ETARGET
npm ERR! notarget No matching version found for @clr/ui@NaN.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'test'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adumesny\AppData\Roaming\npm-cache\_logs\2020-04-21T22_10_03_976Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.
```
## Expected behavior

add clarity to new project. 
**Note** I was able to see issue in generated package.json and fix it there before continuing

## Versions
> ng version
Angular CLI: 9.1.2
Node: 10.19.0
OS: win32 x64

while `package.json` had
"@angular/core": "~9.1.2"
"@clr/angular": "^3.0.1",
"@clr/core": "**NaN**",
"@clr/icons": "**NaN**",
"@clr/ui": "**NaN**",

**Comment by gnomeontherun** [comment] 2020-04-21 22:49
Hi Alain, this is a duplicate of #4444 and is resolved. It will go out with this week's release, and in the interim #4444 has some workarounds for the time being.

Closing as a duplicate.

**Closed by gnomeontherun** 2020-04-21 22:49 UTC

**Comment by adumesny** [comment] 2020-04-21 22:57
Agrrr... I looked for "@clr/ui@NaN"  but didn't find any **open** bugs. You guys are closing things too fast :)
that was a waste of time... thanks
