### ISSUE TITLE
Pagination shrinks the datagrid on selection in IE 11

### ISSUE THREAD

**Issue by ickobombata** [vmware/clarity#4330] opened 2020-03-02 13:16 UTC
## Describe the bug

When the clarity datagrid is used together with the pagination functionallity the datagrid shrinks when the datagrid selection changes.

## How to reproduce

Stackblitz does not work under IE 11, thus to reproduce this I have used a locally created project.
If needed I can host this simple project sample somewhere for download.
Video of the reproduction:  https://www.dropbox.com/s/ze77d358he969ms/datagrid-shrink.mp4?dl=0

Code snippet: 
app.component.html
```
<clr-datagrid [(clrDgSelected)]="selectedItem">
    <clr-dg-column>Name</clr-dg-column>
     <clr-dg-row *clrDgItems="let item of items" [clrDgItem]="item">
       <clr-dg-cell>
          {{item.name}}
       </clr-dg-cell>
    </clr-dg-row>
    <clr-dg-footer>
       <clr-dg-pagination #pagination [clrDgPageSize]="numberOf"></clr-dg-pagination>
    </clr-dg-footer>
 </clr-datagrid>
```
app.component.ts
```javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  selectedItem: any[] = [];
  items: any[] = [{name: "Foo"}, {name: "Bar"}];
  numberOf: number = 5;
}
```

## Expected behavior

When items are selected in the datagrid,there should be no shrinking and expanding.

## Versions

**App**

* Angular: 9
* Node: 10
* Clarity: 3.0.0-rc.1

**Device:**

* Type: PC
* OS: Windows
* Browser IE
* Version 11

**Comment by gnomeontherun** [comment] 2020-03-02 15:37
Hi @ickobombata it would help greatly to have the same reproduction (as a github repo or stackblitz) to give us the ability to see your exact setup.

**Comment by ickobombata** [comment] 2020-03-04 09:45
Here is a stackblitz with the reproduction code:
https://stackblitz.com/edit/clarity-light-theme-v2-v5rv96

As stated above stackblitz does not work under IE due to a bug.

**Comment by ickobombata** [comment] 2020-03-05 12:12
There is an additional issue when the pagination footer is added, namely 
a scroller appears when an item is selected in the datagrid.

**Comment by gnomeontherun** [comment] 2020-04-01 01:17
Hi @ickobombata, I reviewed this and the issue is related to having nothing inside of the footer. We expect that you'll project some content inside of it, so the solution is to project something like 

```
<clr-dg-footer>
    <clr-dg-pagination #pagination [clrDgPageSize]="10">
        <clr-dg-page-size [clrPageSizeOptions]="[10,20,50,100]">Users per page</clr-dg-page-size>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{pagination.totalItems}} users
    </clr-dg-pagination>
</clr-dg-footer>
```

Closing as its expected you'll have content, even a `&nbsp;` will suffice to project something.

**Closed by gnomeontherun** 2020-04-01 01:17 UTC
Labels: browser: ie11, component: datagrid, status: needs reproduction, type: bug
