### ISSUE TITLE
datagrid-table width is fixed and not changing

### ISSUE THREAD

**Issue by 281team29** [vmware/clarity#2865] opened 2018-11-20 19:22 UTC
## Describe the bug

I am using datagrid from clarity 1.0.0 -beta2. there is an element style being added to the .datagrid-table which is fixed and does not change even when the container size changes.
this is causing the data grid to be causing weird space at the end. 
this did not happen with previous releases of clarity
node: 8.11.3
angular 7
clarity 1.0.0-beta2

![datagrid](https://user-images.githubusercontent.com/10069350/48797575-90b60200-ecd0-11e8-812d-fedc8ad84ddb.PNG)

**Comment by gnomeontherun** [comment] 2018-11-20 20:09
Hello, please provide details per our bug template the in future. We ask for a reproduction using StackBlitz to help us see what you are seeing.

In this case, the datagrid gets a size because of updates for the rendering engine to help better manage the size and calculations. We don't know about changes to any containers, so you'll have to tell the Datagrid about those. You can do this by telling the datagrid to resize and it will recalculate itself. 

```
@ViewChild(ClrDatagrid) datagrid;

myMethodToResizeContainer() {
  // ...do whatever that changes container size
  this.datagrid.resize();
};```

I believe this should resolve your issue so I'll close this.

cc @hippee-lee

**Closed by gnomeontherun** 2018-11-20 20:09 UTC
