### ISSUE TITLE
[UI] Datagrid pagination page values incorrect

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#518] opened 2017-02-22 15:13 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When the datagrid is empty, and pagination is activated, as on the documentation page, a string like "0 - 0 of 0 parameters" is expected in the footer

### Actual behavior
The actual string is "1 - 8 of 0 parameters"

<img width="610" alt="screen shot 2017-02-22 at 5 01 51 pm" src="https://cloud.githubusercontent.com/assets/1798828/23217497/1cdb00cc-f922-11e6-80a0-ab75856233eb.png">

### Reproduction of behavior
I tried creating a plunker with this behaviour, but the result is even worse. No pagination at all, plus incorrect values.
https://plnkr.co/mEjMJMtRSUH7AqdEEc4c

### Environment details

* **Angular version: 2.4.8**

* **Clarity version: 0.8.7** 
 
* **OS and version: OS X El Capitan** 

* **Browser: Tested with Chrome and Firefox**

**Comment by youdz** [comment] 2017-02-22 23:07
The reason the plunker didn't work is because you used `*ngFor*` instead of `*clrDgItems`. You need to use the smart iterator if you want us to handle pagination fully.
And to showcase your example, the easiest is to have an empty user array. 😉 
Here is the plunker you posted showing the actual error you screenshoted: https://plnkr.co/edit/HxNtbXKKxz998SAZmirI?p=preview

Thanks for the report, this shouldn't be too hard to fix. Not a big priority, but definitely something we want to fix sometime.

**Comment by Jinnie** [comment] 2017-02-23 08:51
I felt I may be missing something simple. I had gone through this before, but forgot about it in this case. 
I will provide the fix for the pagination issue if I find some time today.
Thanks for checking the plunker,
Ivan

**Comment by Jinnie** [comment] 2017-03-09 07:53
I closed the related pull request. Some valuable discussions remain there, please check them if you attend this issue in future.
Workarounds for me were either using conditional footers, or pluralization directive in the footer.
Feel free to close the issue too, or keep it open if you think it may be attended in future.

**Comment by pratheekhegde** [comment] 2017-05-04 11:44
I see the problem still persists. This is the Full Datagrid demo from the docs.

![clarity](https://cloud.githubusercontent.com/assets/11031124/25701368/bed1bf20-30e9-11e7-9c30-28bfbd205ceb.gif)

I don't feel this is a bug because it is something we write in `<clr-dg-footer>` and not part of the ` <clr-dg-pagination>`
```
{{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} of {{total}} users
```
The simple fix is by hiding `{{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} of ` when total count is 0.

**Comment by Jinnie** [comment] 2017-05-04 13:49
Hi @pratheekhegde
You are right that it's not a "component problem", but pagination.firstItem and pagination.lastItem are sort of public API functions, and if they are returning erroneous values, then this should be a bug.

🤔

**Comment by pratheekhegde** [comment] 2017-05-04 14:10
You are correct @Jinnie. But I was referring to the bug which shows **1 - 10 of users** when there are no records.

**Comment by Shijir** [comment] 2018-12-13 23:03
With our new Datagrid pagination, users have full control over how to present their pagination numbers however they want with no efforts. Hence, closing the issue as the problem is no longer relevant.

**Closed by Shijir** 2018-12-13 23:03 UTC
Labels: Bug
