### ISSUE TITLE
Clarity 1.0.0 Show/Hide function z-index bug

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2936] opened 2018-12-12 22:23 UTC
## Describe the bug

Column toggle popover z-index is less than grid header z-index. (popover is overlapped by grid header)

## How to reproduce

1.  Go to https://stackblitz.com/edit/show-hide-ng7
2.  Click on column toggle button
4.  See the UI bug

## Expected behavior

Popover should be over grid header.

## Versions

**App**

Angular CLI: 7.1.3
Node: 8.11.2
Clarity: 1.0.0

Device:
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Chrome - Version: 69.0.3497.92 (Official Build) (64-bit)

**Comment by Jinnie** [comment] 2018-12-13 09:10
Duplicate of #2915.
Already resolved for 1.0.

**Closed by Jinnie** 2018-12-13 09:10 UTC
Labels: Bug, Dev, Regression
