### ISSUE TITLE
Clarity datagrid does not word-wrap or show ellipsis on fields with underscore.

### ISSUE THREAD

**Issue by SandeshSomashekar** [vmware/clarity#1146] opened 2017-07-03 19:18 UTC
Clarity datagrid does not word-wrap or show ellipsis on fields with underscore.

```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Ideally, columns with text longer than the available column width must either wrap or show ellipsis with mouse over for the whole text.

### Actual behavior
Text containing underscores overlaps with the text on the next column.

### Reproduction of behavior
Have a clarity column text with data containing several underscore characters and see how it is displayed. Attaching a screenshot.

Clarity Version: [Latest - 0.9.2]

### Environment details

* **Angular version:** 4.2.4

* **Clarity version: 0.9.2 

* **OS and version: OSX 10.12.5

* **Browser:** Chrome Version 58.0.3029.110 (64-bit)
<img width="955" alt="screen shot 2017-07-03 at 12 03 12 pm" src="https://user-images.githubusercontent.com/1157190/27805434-7b691b96-5fe9-11e7-8f8b-d9f956be0da6.png">

**Comment by SandeshSomashekar** [comment] 2017-07-03 19:47
For now I am overriding datagrid-cell style with the following to temporarily fix this -

.datagrid-cell {
   word-break: break-all;
}

**Comment by youdz** [comment] 2017-07-05 13:37
Two things:
1) Please post a plunker reproducing this, because Datagrid actually sizes columns smartly and will allocate enough space for them, even if it means adding a horizontal scroll.
2) Feel free to follow #1065 for a potential helper class if it is really needed. See #815 and #618 for discussion of why we will not truncate text by default. Note that the `word-break: break-all` solution is not something we'd implement by default either, since it leads to terrible word breaking on normal text. I'm closing this as duplicate, we can reopen if you do have a plunker that shows a different use case as the mentioned issues.

**Closed** 2017-07-05 13:38 UTC
Labels: ClarityNG, ClarityUI, duplicate, enhancement, has-workaround
