### ISSUE TITLE
Single action options are wrongly highlighted

### ISSUE THREAD

**Issue by mostafaabdulraouf** [vmware/clarity#4202] opened 2020-01-14 09:28 UTC
## Describe the bug
Single action options are wrongly highlighted
when a single action menu in a datagrid is clicked,the first option is highlighted by default,when hovering the other options all options become highlighted as well

## How to reproduce

1.  Go to 'https://v2.clarity.design/datagrid/single-action'
2.  Click on 'single action menu'
3.  Hover the options in the single action menu
![image](https://user-images.githubusercontent.com/59867308/72331597-bd895d80-36b8-11ea-94e8-d2ae9fd18415.png)

## Expected behavior

none of the options in the single action men should be highlighted

## Versions

**App**

* Clarity: [2.3]

**Device:**

* Type: [windows]
* Browser [Chrome]

## Additional notes

_Add any other notes about the problem here._

**Comment by martinbrom** [comment] 2020-01-14 09:41
I think the first option is highlighted because it has autofocus so you can immediately navigate to the link using your keyboard, and when you hover over the second one it gets highlighted because you are hovering over it. This to me seems like the expected behavior.

**Comment by hippee-lee** [comment] 2020-01-14 18:00
Thanks @martinbrom, you are correct. This behaves as intended. 

This behavior is needed to support screen readers and make the row action popover content accessible.
I'm closing as works as intended.

**Closed by hippee-lee** 2020-01-14 18:00 UTC
