### ISSUE TITLE
Datagrid. Export option.

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#1041] opened 2017-06-13 08:25 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ X] feature request
[ ] enhancement
```

Export option if fairly common in datatables / datagrids and often requested in CRM alike systems.
Think its pretty 'must have' feature.

Few examples in well known alternatives: 
[DataTables Export](https://datatables.net/extensions/buttons/examples/initialisation/export.html)
[PrimeNG Export](https://www.primefaces.org/primeng/#/datatable/export)

**Comment by youdz** [comment] 2017-06-13 13:06
This is a duplicate of #147. See the discussion over there for the explanation of why we don't think this feature should be implemented.

For the TL;DR, the general idea is that since we're using a declarative API that lets you display anything you want in the cells, we'd have to ask for a function on what to export for each column (which can be different from what you're displaying on the page).

**Closed by youdz** 2017-06-13 13:06 UTC
