### ISSUE TITLE
Clarity not working with Angular V6

### ISSUE THREAD

**Issue by kgidwani** [vmware/clarity#2243] opened 2018-05-06 19:38 UTC
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Application should come up when i run ng serve

### Actual behavior

The build fails with error below

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

1. create a new project using angular cli (version 6)
ng new navigator-clarity --style=scss --routing 

2. go to project directory 
cd  navigator-clarity

3. Add Clarity 

"ng add @clr/angular@next "

4. Run npm install
5. Run ng serve
ng serve gives error

ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'C:\Users\54960
3\Desktop\Workspace\navigator-clarity\node_modules\@clr\angular\
esm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\549603\Deskto
p\Workspace\navigator-clarity\node_modules\@clr\angular\esm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/operator/first' in 'C:\Users\549603
\Desktop\Workspace\navigator-clarity\node_modules\@clr\angular\e
sm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/operators/map' in 'C:\Users\549603\
Desktop\Workspace\navigator-clarity\node_modules\@clr\angular\es
m5'

### Environment details

* **Angular version:** 4.x.x
Angular v 6 

* **Clarity version:**
"^0.11.15"

* **OS and version:** 
Windows 7 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any

**Comment by Shijir** [comment] 2018-05-06 19:47
This is a duplicate of https://github.com/vmware/clarity/issues/2239 and https://github.com/vmware/clarity/issues/2242. Please take a look at the solutions specified in those issues.

**Closed by Shijir** 2018-05-06 19:47 UTC

**Comment by kgidwani** [comment] 2018-05-06 20:04
Thanks.. It solved my problem.
