### ISSUE TITLE
Datagrid within Form does not render correctly when row selection mode is enabled

### ISSUE THREAD

**Issue by davidrourke** [vmware/clarity#4226] opened 2020-01-23 20:58 UTC
## Describe the bug

When you enable row selection mode (i.e. [clrDgRowSelection]="true") on a datagrid within a form the datagrid does not render correctly.

<img width="865" alt="Screen Shot 2020-01-23 at 3 50 25 PM" src="https://user-images.githubusercontent.com/25104184/73022737-262eb380-3df8-11ea-96d0-adc2e2b7243a.png">

## How to reproduce

1.  Go to https://clarity-light-theme-v2-vuyeah.stackblitz.io/
2.  Click on 'Show Modal'

## Expected behavior

The datagrid header and rows should render without formatting issues.

## Versions

**App**

* Angular: 8.0
* Node: 10.0
* Clarity: 2.12 and higher

**Device:**

* Type: MacBook Pro
* OS: macOS Catalina
* Browser Chrome
* Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by hippee-lee** [comment] 2020-01-23 21:28
Thanks for the stackblitz. It is hard to be sure what you mean by formatting issues. Can you be more specific about what you see or where in the datagrid the formatting is wrong? I hae an idea what the issue is but am not sure if it is the same thing that is being reported. More details would help isolate the reported issue in case there are multiple things going on here.

**Comment by davidrourke** [comment] 2020-01-24 00:21
Sorry, I thought the image I posted and the stackblitz example would provide enough details.

1. In the header you will see that the divider between the checkbox and the first column header is not aligned correctly.
2. The height of the rows is larger than needed to display the data.  As you can see there is no wrapped text that would force the height of the row to be that large.

If you remove [clrDgRowSelection]="true", the height of the rows of the datagrid render correctly.  However, the header still has the issue I stated in item #1 above.

**Comment by hippee-lee** [comment] 2020-01-24 00:37
Thanks for confirming what you saw. I suspect there may be a style conflict with the button inside the modal. We will have to investigate a bit more.

**Comment by mathisscott** [comment] 2020-02-04 21:45
This looks like there are a couple of possible issues. One is that the form styles are affecting labels inside of the datagrid. The other is that the datagrid is showing up with a minimum height and the rows are distributing the space evenly with flexbox even though there aren't enough rows to fill the space.

**Comment by gnomeontherun** [comment] 2020-02-21 17:56
The row selection is deprecated, and we recommend not using it for accessibility reasons (nested click targets). There must be a conflict in the CSS, and the first item is dupliated in #4289. This ticket should then focus on the row height issue, but the workaround is to not use `clrDgRowSelection`.

**Comment by gnomeontherun** [comment] 2021-02-26 18:53
Closing as this uses whole row selection which is not considered accessible with nested elements. The solutions and workarounds might also help you but we don't plan to support this combination of features.

**Closed by gnomeontherun** 2021-02-26 18:53 UTC
Labels: @clr/angular, component: datagrid, component: forms, priority: 1 low, status: backlog, type: bug
