### ISSUE TITLE
Inconsistent stacking of datagrid cell content

### ISSUE THREAD

**Issue by xucito** [vmware/clarity#2007] opened 2018-02-21 21:22 UTC
[ x] bug
[ ] feature request
[ ] enhancement

### Expected behavior

Body cell content of data grid is consistently stacking when a single row action is present.

### Actual behavior

Maybe root cause/related to issue #1986 

Header Cells:
If single row actions are not included, the header row stacks.
If there is a single row action, header does not stack.

![datagrid_issue_header](https://user-images.githubusercontent.com/36687889/36505809-14465072-176e-11e8-9ee3-58ab8821fadc.png)

Body Cells:

If single row actions are included without *clrDgItems, content of cells stacks, 
If there is no single row action or has a single action row but uses *clrDgItems the cell content does not stack.

![datagrid_issue](https://user-images.githubusercontent.com/36687889/36505373-b7d5a9e2-176c-11e8-8d2e-cb7e622af9ac.png)

### Reproduction of behavior

https://plnkr.co/edit/wx89GcoHb1ZA27E0RlkP?p=preview

### Environment 

Angular version: 4.x.x

Clarity version: 0.10.x

OS and version: [Win10]

Browser: [all]

**Comment by mathisscott** [comment] 2018-02-22 23:11
@hippee-lee : Could you get back with @xucito on this?

**Comment by hippee-lee** [comment] 2018-02-23 00:58
@xucito - thanks for reporting this. It looks like a duplicate of #1986 that was recently reported. I'm closing this based on that. Please subscribe to that issue for updates.

**Closed by hippee-lee** 2018-02-23 00:58 UTC
