### ISSUE TITLE
Text input in dropdown loses focus

### ISSUE THREAD

**Issue by sylvaingirardbe** [vmware/clarity#3794] opened 2019-09-09 05:51 UTC
## Describe the bug

I have a text input in a dropdown menu that is used to filter the entries in the dropdown menu. When the user starts typing text, the text is applied as a filter on the dropdown list items starting from the 3rd character entered. When the list with dropdown items is refreshed, focus on the text input is lost so the user has to click the text input to get it to focus again to enter another character, just to have it lose focus again. It seems that clr-input-container is getting the focus instead of the actual input.

This used to work in version 1.0.5 but I'm not sure when it stopped working.

## How to reproduce

It is reproduced in https://clarity-dark-theme-v2-rqelud.stackblitz.io/.

1.  Open the stackblitz repro
2.  Click on 'Source' header in the grid
3.  Type 'ANT-S' in the text input
4.  Focus is lost

## Expected behavior

Focus should remain on the text input and not the clr-input-container element.

## Versions

**App**

* Angular: 8+
* Node: 
* Clarity: 2+

**Device:**

* Type: Laptop
* OS: Windows 10
* Browser Chrome 
* Version 76.0.3809.132

**Comment by florin-borceanu** [comment] 2019-09-09 12:39
I investigated this issue and I found out that the `clrDropdownItem` directive from the div inside the `clr-dropdown-menu` cause this odd behavior. If you remove it, the style got changed, but the issue is solved. I don't know the context where you use this directive, can you test this fix and tell me if something is not going the way it should? (beside the style)

**Comment by gnomeontherun** [comment] 2019-09-09 15:17
We've seen several reports of this because people have turned the dropdown into a combobox, which is not a use case we ever intended to support. See https://github.com/vmware/clarity/issues/3729#issuecomment-523917087 for a more detailed explanation. The best thing to do is wait for combobox, though a workaround is to copy the old dropdown menu, rename it and use that instead of ours or use the static version of dropdown until combobox is ready. There is also a datalist component in HTML that we've got on our backlog which does much of what you want too, and you could style that instead.

Closing as a duplicate.

**Closed by gnomeontherun** 2019-09-09 15:17 UTC

**Comment by sylvaingirardbe** [comment] 2019-09-10 06:07
> I investigated this issue and I found out that the `clrDropdownItem` directive from the div inside the `clr-dropdown-menu` cause this odd behavior. If you remove it, the style got changed, but the issue is solved. I don't know the context where you use this directive, can you test this fix and tell me if something is not going the way it should? (beside the style)

Thanks, works a treat!
