### ISSUE TITLE
Stack-view animation bug

### ISSUE THREAD

**Issue by taivu** [vmware/clarity#3350] opened 2019-05-09 18:54 UTC
## Describe the bug

stack-view opens without animation. 

## How to reproduce

1.  Go to `https://clarity.design/documentation/stack-view`
2.  scroll down to angular component
3.  click to open.
4.  See error

this has the error --> https://clarity.design/documentation/stack-view
this doesnt -->https://v1.clarity.design/stack-view

however, it is happening to me in `v1.1.13`

## Expected behavior

animates smoothly, open and close. like this: --> https://v1.clarity.design/stack-view

the weird thing is that this error is happening to me in `v1.1.13`.

## Versions

**App**

* Angular: 7.2.15
* Clarity: 1.1.3

**Device:**

* Type: imac
* OS: OSX Mojave
* Browser: chrome/firefox
* Version: latest versions as of 05-09-2019

## Additional notes

the inline animations are garbled: `style="height:0px;display:none;0:height;1:display;display:none;height:0px;"`

not sure if this is an angular issue since its animations, or clarity. its weird that the v1 docs dont exhibit this error, but i am running v1.1.3 with it. weirder that v2 docs *does* exhibit this error.

**Comment by Jinnie** [comment] 2019-05-17 12:22
Hi, I am not able to reproduce it neither on the website, nor in stackblitz with 1.1.3 (1.1.13 is not a valid Clarity version).
Please verify if it still fails for you and provide more information, a screenshot and a stack trace at least.
Thanks.

**Comment by taivu** [comment] 2019-05-17 17:58
heres a gif screen capture of the issue on clarity docs: http://www.giphy.com/gifs/MFlosM2n54syXaHgEX

**Comment by Jinnie** [comment] 2019-05-22 07:11
I confirm it's reproducible on the website. I also reproduced it in stackblitz with 1.1.3
I am unable to reproduce it in my dev environment. I didn't find any recent changes in the component that may lead to this, so it may be Angular version specific.
Assigning to the backlog for now, so it can get picked for more extensive research when possible.

**Comment by diogojesus95** [comment] 2019-06-12 15:43
Having the same error. We just updated from version 0.11 to the most recent stable one (v 1.3.1) and we're also having this issue.

The worse isn't the lack of animation but the fact that it doesn't work at all on iPhone. 
This is a GIF from iPhone XS

![60562131_2318737751711107_3224947035392180224_n](https://user-images.githubusercontent.com/26788642/59365882-a1e06200-8d39-11e9-82af-9c0b03548d19.gif)

**Comment by diogojesus95** [comment] 2019-06-13 09:45
Update: After rolling back to version 1.0.0 problem persisted, so I guess it's an angular problem as we were using angular 5 before the update and now we went to angular 8

**Comment by Jinnie** [comment] 2019-06-14 16:43
Note to myself: test in Safari.

**Closed** 2019-06-17 15:11 UTC
Labels: Bug, Regression

**Comment by epicStudio** [comment] 2019-06-22 10:32
Hi @Jinnie 

I've noticed some strange behaviour with Angular and the stack-view as well.
Please have a look here https://stackoverflow.com/questions/56563439/clarity-stack-view-does-not-work-with-angular-ngtemplateoutlet

Let me know if  should open a new issue for this problem on Github.

**Comment by Jinnie** [comment] 2019-06-24 11:04
Thanks for the update, @epicStudio  - answered on stackoverflow.
