### ISSUE TITLE
Different height for items in Vertical Nav Group

### ISSUE THREAD

**Issue by biziosan** [vmware/clarity#4136] opened 2019-12-20 16:14 UTC
## Summary

Would it be possible or appropriate to have items in a vertical nav group to use a height different from the one specified in the main vertical nav body.

## Use case

The vertical nav menu in my app is a bit too uniform. At first glance, it is hard to recognize what is in the main nav and what is in the groups. 
It would look much more clearer to have either color, item height, or font size (or all the above) differences between the main body items and the group items.

**Comment by mathisscott** [comment] 2019-12-20 16:24
This seems related to work we were doing with #4116 and #3303 which was largely concerned with cleaning up spacing and hierarchy.

I don't have much to report on these efforts as we're a bit at odds internally about adoption.

However, the design "tokens" should be released in the near(?) future independent of the hierarchy updates and those would allow you to adjust spacing and font-weight to meet your needs.

Closing as a duplicate of those efforts.

Adding @colinreedmiller if I've missed anything.

**Closed by mathisscott** 2019-12-20 16:24 UTC

**Comment by colinreedmiller** [comment] 2019-12-20 16:51
Using a design token based system for such adjustments needs to be handled carefully - while theming and use case specific adjustments are important and extremely useful, they can also be at odds with one of the central values of a design system namely creating consistency and repeatability both from the design/dev side and in the experience of the end user. Remaining consistent is a foundational principle. The team will release / document / support this when we arrive upon a solution that emphasizes benefits and mitigates liabilities.
