### ISSUE TITLE
Improve SEO for our website

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#1369] opened 2017-08-25 15:52 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

We need proper SEO on the website. This would probably be some form of partial server-side rendering (some of our demos are _not_ server-side renderable) that would happen during build-time, the resulting files would be committed to the gh-pages branch, and we would publish that. Hopefully it will work with routes, so component documentation can be indexed too.

### Actual behavior

Our website is currently not crawlable at all because it's full Angular that dynamically creates everything on the client side.

**Comment by mathisscott** [comment] 2017-09-20 14:14
Marking as a duplicate of #1485 because that ticket is more detailed re: what needs to be done.

**Closed by mathisscott** 2017-09-20 14:14 UTC
Labels: ClarityCore, enhancement, WEB
