### ISSUE TITLE
ClrModal emits multiple changes for one closing event

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#3385] opened 2019-05-23 16:08 UTC
## Describe the bug

As a consumer when I listen to `(clrModalOpenChange)="onModalClose($event)"` I see two events triggering the onModalClose function. 

## How to reproduce

https://stackblitz.com/edit/gh-modal-close-multiple-change-emits

1.  Open the console for observation
2.  Open the modal by clicking on the button
3.  Close the modal in one of two ways:
    - press the escape button
    - click the `X` button in hte modal header
4.  Observe two false values in the console for each diescrete close action

## Expected behavior

The expected behavior will only emit one close change event.

## Versions

**App**

* Angular: 7.2.15
* Node: n/a
* Clarity: 1.1.3

**Device:**

* Type: n/a
* OS: n/a
* Browser n/a
* Version n/a
## Additional notes

_Add any other notes about the problem here._
`ClrModal` emits `this._openChanged.emit(true);` from the close method.
It also emits `this._openChanged.emit(false);` from the fadeDone method (when its going to the void state). 

TODO: revisit the discussion on this issue: https://github.com/angular/angular/issues/15798 and determine when to properly emit closing state for modals.

**Comment by gnomeontherun** [comment] 2019-06-05 14:45
Duplicate of #3149

**Closed by gnomeontherun** 2019-06-05 14:45 UTC
Labels: Bug, Duplicate
