### ISSUE TITLE
ClrPopoverContent rootNodes of undefined

### ISSUE THREAD

**Issue by mykah89** [vmware/clarity#4267] opened 2020-02-11 22:08 UTC
## Describe the bug

Using the smartToggleService to toggle the open flag is causing an issue with an undefined reference.

ERROR TypeError: Cannot read property 'rootNodes' of undefined
`        this.checkCollector.pipe(Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_4__["debounceTime"])(0)).subscribe(() => {
            this.alignContent();
            this.shouldRealign = false;
            this.renderer.setStyle(this.view.rootNodes[0], 'opacity', '1');
        }));`

## How to reproduce

Mousing quickly over the item which changes visibility state, or rapidly changing the visibility state of the item seems to cause this error.  Noticed first in the button group menu items popover, and then in a custom component i created.

Clicking the icon to toggle the popover menu very quickly while pressing the enter key with the button in focus to allow for a faster change rate will produce the error.

https://stackblitz.com/edit/clarity-light-theme-v3-next-4qjkr8

## Versions

**App**

* Angular: 9
* Node: 12.11.1
* Clarity: 3.0.0-next.8

**Comment by hippee-lee** [comment] 2020-02-11 22:56
Hi @mykah89 can you supply a simple stackblitz reproduction? I updated one to use 3.0.0-next.8 and Angular 9 here: https://stackblitz.com/edit/clarity-light-theme-v3-next

**Comment by mykah89** [comment] 2020-02-12 13:53
Thanks for the updated stackblitz.

Here is a link to the reproducible issue, as a side note, it also seems to expose a bug in the button group which opens the in menu items when clicking any button.

It was difficult to reproduce in the stackblitz environment, i'm guessing it has some sort of speed/timing element to it.

I had to continuously click the cog icon as fast as i could while simultaneously pressing the enter key quickly. It was much easier to reproduce in my application

https://stackblitz.com/edit/clarity-light-theme-v3-next-4qjkr8

**Comment by gnomeontherun** [comment] 2020-02-14 16:38
Moving to backlog for investigation.

**Comment by gnomeontherun** [comment] 2020-02-14 22:43
The button group issue has been identified, but we need a better reproduction for rootNodes. I'm not clear, are you creating your own popover implementation or seeing this error when using a Clarity component?

**Comment by mykah89** [comment] 2020-02-14 23:21
I have a notification component that opens a popover on hover using the ClrPopoverToggleService to toggle the open property.

In my application even slowly hovering back and forth over the component will cause the error at some point.

Using the stackblitz i was unable to reproduce in this fashion, i assume its because the stackblitz executes faster, which is why i used the button as an example.  Even in my application toggling the button slower causes the issue.

I have updated the stackblitz with a toggle button that seems to consistently provide the same error.
https://stackblitz.com/edit/clarity-light-theme-v3-next-4qjkr8

Please let me know if there is anything additional i can provide to help here since this error prevents me from updating my production application to angular 9 with clarity.

**Closed** 2020-02-24 16:30 UTC
Labels: @clr/angular, component: button, flag: regression, resolution: fixed, type: bug

**Comment by mykah89** [comment] 2020-02-29 16:20
While the button overflow issue seems to be resolved, this underlying issue is still not resolved, toggling the popover with the ClrPopoverToggleService as per the stackblitz still causes an error while referencing the rootNodes.

**Comment by gnomeontherun** [comment] 2020-03-02 15:52
You are trying to toggle with an internal service (which has to be public unfortunately), which isn't clear to me why you are trying to do this. However, the issue is that you should use the `toggleWithEvent($event)` method instead and pass in the click/keyboard event. Setting the open state directly is causing the issue for you, since this is an event based toggle example.

This is not really a supported use case and could change in the future. I don't know the context by which you want to do this, but a better long term solution would be to request an input binding to toggle the state of the overflow menu (currently not available).

**Comment by mykah89** [comment] 2020-03-02 18:39
Thanks for the feedback, i have a notifications component utilizing the popover service.. this button example was just the easiest way i could display it at the time.

Here is an updated stack blitz with my implementation, also using the toggleWithEvent as you outlined.

The error does not occur all of the time, hovering quickly over and off of the notifications indicator will eventually result in the console error i have described, again this occurs fairly quickly in my larger application, it seems to occur less often in the faster running stackblitz but it does occur.

ERROR
Error: Cannot read property 'rootNodes' of undefined

https://stackblitz.com/edit/clarity-light-theme-v3-next-bpxtfg
