### ISSUE TITLE
Need to create a buttonbar in clarity

### ISSUE THREAD

**Issue by snagar78** [vmware/clarity#240] opened 2016-12-13 20:48 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

Need to implement a toolbar with clarity buttons, something very similar to 
https://v4-alpha.getbootstrap.com/components/button-group/

### Actual behavior

No Component at present exists to create button bar.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hrantbagdasarian** [comment] 2016-12-14 21:43
A buttongroup using checkbox/radio button would also be a nice feature.
[https://v4-alpha.getbootstrap.com/components/buttons/#button-plugin](https://v4-alpha.getbootstrap.com/components/buttons/#button-plugin)

**Comment by reddolan** [comment] 2017-01-17 21:41
We are currently working on design documentation for this. We will be posting it soon

**Comment by dudanogueira** [comment] 2017-01-18 20:31
first of all, congrants on this awesome project. I am really enjoying using it and hope to help with what I can. 
I am also interested on a button group class. 

I am basically experimenting migrating a webapp from bootstrap + angular1 to clarity + angular2, and I have this use case with kind of a radio button with an action button attached.

![exemplo-button-group-clarity](https://cloud.githubusercontent.com/assets/1761174/22081796/3533e968-ddac-11e6-8f62-ea51da80f918.png)

when you click on the blue button, it becomes selected (checkbox) and you can add some options o this. You can also add a new number. With a button group, one would be able to combine a button and a dropdown button to accomplish this.

Thanks!!

**Comment by reddolan** [comment] 2017-01-18 21:52
@dudanogueira we will be including a feature that supports your need into Button Groups. I hope to have the documentation posted in the next few days. I will notify watchers on this issue once it is live

**Comment by yenmade** [comment] 2017-01-20 21:40
Closing this as a duplicate of #247

**Closed by yenmade** 2017-01-20 21:40 UTC
Labels: ClarityUI, ClarityUX, Component: New

**Comment by vkpavan26** [comment] 2017-01-24 10:41
Hi Team,

Do we have a screenshot of the proposal/implementation.

Regards,
Pavan

**Comment by jaffoneh** [comment] 2017-01-24 14:42
@vkpavan26 yeah. All the details are available in #247 including the design spec.
