### ISSUE TITLE
Datagrid keeps horizontal scrollbar visible, even if there is nothing to scroll

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2799] opened 2018-10-31 08:34 UTC
## Describe the bug

Clarity datagrid with particular setups handles the horizontal scrollbar wrongly. This issue presents in half of our datagrids (2 works properly, 2 not). There is no difference with the layout, just the number of columns.

## How to reproduce

https://stackblitz.com/edit/clr-datagrid-scrollbar-bug

1.  Go to https://stackblitz.com/edit/clr-datagrid-scrollbar-bug
2.  Observe datagrid
3.  2 columns are visible and horizontal scrollbar presents, even if there is enough space for all columns, scrolling is not necessarry. 
4. Go to column toggle, hide more columns, scrollbar is still visible.
5. If you select all columns, scrollbar disappears.

## Expected behavior

Scrollbar should only be visible when, scroling is necessary.

## Versions

App

Angular CLI: 6.1.9
Node: 8.11.2
Clarity: 0.13.7
Device:
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Chrome - Version: 69.0.3497.92 (Official Build) (64-bit)

**Comment by youdz** [comment] 2018-11-07 18:02
Known issue, closing as duplicate of #1248.

**Closed by youdz** 2018-11-07 18:02 UTC
