### ISSUE TITLE
Error when removing items with Datagrid

### ISSUE THREAD

**Issue by bokzor** [vmware/clarity#1346] opened 2017-08-22 11:09 UTC
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The datagrid should displayed correctly the items. When I add or remove items to be displayed

### Actual behavior
I have this error.
ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### Environment details

* **Angular version:** 4.x

* **Clarity version:**  0.10.1

* **OS and version:** 

* **Browser:** all

**Comment by bokzor** [comment] 2017-08-22 11:15
Problem solved if I removed 

<clr-dg-action-overflow>
</clr-dg-action-overflow>

**Comment by youdz** [comment] 2017-08-22 13:52
Duplicate of #1215, we already have a PR out for it (#1333).

**Closed by youdz** 2017-08-22 13:52 UTC
