### ISSUE TITLE
Provide custom svg shapes into Clarity Icons

### ISSUE THREAD

**Issue by koninos** [vmware/clarity#6028] opened 2021-06-07 14:22 UTC
## Describe the bug

I am trying to add a custom icon into Clarity.
First of all the docs make an import `import { ClarityIcons, userIcon } from '@cds/core/icon';` and then add your custom name along with the svg `ClarityIcons.add({ 'my-custom-icon': '<svg ... >[your SVG code goes here]</svg>' });`.
The compiler complains `Property 'addIcon' does not exist on type 'typeof ClarityIcons'. Did you mean 'addIcons'?` so the icon does not really appear when using `<cds-icon shape="my-custom-shape"></cds-icon>`

## How to reproduce

Follow the docs on how to [add custom icon](https://clarity.design/foundation/icons/#customize)

## Expected behavior

My custom icon should appear

## Versions

**Clarity project:**

- Clarity Core 5.3.0
- Clarity Angular/UI 5.3.0

**Clarity version:**
5.3.0

**Framework:**

-  Angular

**Framework version:**
 Angular 11.2.13

**Device:**

- OS: Windows 10
- Browser Chrome 91.0.4472.77

**Comment by hippee-lee** [comment] 2021-06-07 16:09
@koninos As described in the [Icon docs](https://clarity.design/foundation/icons/#customize), are you calling `ClarityIcons.add({ 'my-custom-icon': '<svg ... >[your SVG code goes here]</svg>' });`? If so and you still have the error can you post the code you are trying as an isolated reproduction for your issue? I'll be able to take a look and see whats going on for you. We keep starter apps on [stackblitz](https://stackblitz.com/edit/clarity-light-theme-v5) for just this purpose.

**Comment by koninos** [comment] 2021-06-08 06:34
The thing is that `ClarityIcons` class does not have an `add` method, so why the docs say to call a method that doesn't exist?

Check on [stackblitz](https://clarity-light-theme-v5-dawrac.stackblitz.io)

**Comment by bdryanovski** [comment] 2021-06-08 09:59
It seems that our documentation requires some updating 

```ts
import { ClarityIcons } from '@cds/core/icon';

ClarityIcons.addIcons([
  // Icon/Shape name
  'my-custom-icon',

  // SVG content for the Bell icon 
  '<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M32.51,27.83A14.4,14.4,0,0,1,30,24.9a12.63,12.63,0,0,1-1.35-4.81V15.15A10.81,10.81,0,0,0,19.21,4.4V3.11a1.33,1.33,0,1,0-2.67,0V4.42A10.81,10.81,0,0,0,7.21,15.15v4.94A12.63,12.63,0,0,1,5.86,24.9a14.4,14.4,0,0,1-2.47,2.93,1,1,0,0,0-.34.75v1.36a1,1,0,0,0,1,1h27.8a1,1,0,0,0,1-1V28.58A1,1,0,0,0,32.51,27.83ZM5.13,28.94a16.17,16.17,0,0,0,2.44-3,14.24,14.24,0,0,0,1.65-5.85V15.15a8.74,8.74,0,1,1,17.47,0v4.94a14.24,14.24,0,0,0,1.65,5.85,16.17,16.17,0,0,0,2.44,3Z"></path><path d="M18,34.28A2.67,2.67,0,0,0,20.58,32H15.32A2.67,2.67,0,0,0,18,34.28Z"></path></svg>'
]);
```

To use it later on 

```html
<cds-icon shape="my-custom-icon"></cds-icon>
```

**Comment by koninos** [comment] 2021-06-08 10:37
Thanks @bdryanovski, this one is working.

**Comment by mathisscott** [comment] 2021-06-08 12:45
@koninos 
The `ClarityIcons.add()` method that was being used was the old call signature for `@clr/icons`. I don't know why that wound up on the website docs for `@cds/core`. Different packages. But it looks like @bdryanovski updated the docs in [this PR](https://github.com/vmware/clarity/pull/6032) so it should be corrected soon. I'm sorry for the confusion.

**Comment by hippee-lee** [comment] 2021-06-08 17:35
Closing this as resolved. @koninos - please update here if that is not the case.

**Closed as completed by hippee-lee** 2021-06-08 17:35 UTC
Labels: flag: has workaround, Documentation
