### ISSUE TITLE
Wizard with Asynchronous Completion not complete

### ISSUE THREAD

**Issue by ThinkontrolSY** [vmware/clarity#996] opened 2017-05-31 13:43 UTC
## URL
```
https://vmware.github.io/clarity/documentation/wizards
```

**Comment by mathisscott** [comment] 2017-05-31 14:11
@ThinkontrolSY 
Thanks for the feedback. Can you provide us with any more details? What do you think is missing?

**Comment by ThinkontrolSY** [comment] 2017-06-01 00:46
```typescript
@Component({
    ...
})
export class WizardAsyncCompletion {
    @ViewChild("wizard") wizard: Wizard;
    @ViewChild("myForm") formData: any;
    @ViewChild("myFinishPage") finishPage: WizardPage;

    loadingFlag: boolean = false;
    errorFlag: boolean = false;
    checked = false;
    finished = false;
    open: boolean = false;
    answer: number = null;

    // have to define doCancel because page will prevent doCancel from working
    // if the page had a previous button, you would need to call
    // this.wizard.previous() manually as well...
    doCancel(): void {
        this.wizard.close();
    }

    get showCongrats(): boolean {
      return !this.errorFlag && this.checked;
    }

    resetFinalPage(): void {
      this.loadingFlag = false;
      this.errorFlag = false;
      this.checked = false;
    }

    goBack(): void {
      this.wizard.previous();
    }

    doFinish(): void {
      this.wizard.forceFinish();
      this.resetFinalPage();
    }

    onCommit(): void {
        let value: any = this.formData.value;
        this.loadingFlag = true;
        this.errorFlag = false;

        if (this.finished) {
          this.doFinish();
          return;
        }

        setTimeout(() => {
            if (value.answer === "42") {
              this.finished = true;
            } else {
                this.finishPage.completed = false;
                this.errorFlag = true;
            }
            this.checked = true;
            this.loadingFlag = false;
        }, 1000);
    }
}
```
```html
<clr-wizard #wizard [(clrWizardOpen)]="open">
    <clr-wizard-title>Async validation</clr-wizard-title>

    <clr-wizard-button [type]="'cancel'">Cancel</clr-wizard-button>
    <clr-wizard-button [type]="'previous'">Back</clr-wizard-button>
    <clr-wizard-button [type]="'next'">Next</clr-wizard-button>
    <clr-wizard-button [type]="'finish'">Finish</clr-wizard-button>

    <clr-wizard-page
        clrWizardPagePreventDefault="true"
        (clrWizardPageOnCommit)="onCommit()"
        (clrWizardPageOnCancel)="doCancel()">
        <ng-template clrPageTitle>Form with async validation</ng-template>

        <div class="spinner" *ngIf="loadingFlag">
            Loading...
        </div>
        <clr-alert [clrAlertType]="'alert-info'" [clrAlertClosable]="false">
            <div class="alert-item">
                This&nbsp;<a
                    href="https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker.27s_Guide_to_the_Galaxy"
                    target="_blank">wiki article</a>&nbsp;might help you answer the question.
            </div>
        </clr-alert>
        <clr-alert *ngIf="errorFlag" [clrAlertType]="'alert-danger'">
            <div class="alert-item">
                Your answer is incorrect.
            </div>
        </clr-alert>
        <form #myForm="ngForm" [class.hide]="loadingFlag">
            <section class="form-block">
                <div class="form-group">
                    <label for="fourtyTwoInput">The answer to life, the universe and everything</label>
                    <input type="text" id="fourtyTwoInput" [(ngModel)]="answer" name="answer">
                </div>
            </section>
        </form>
    </clr-wizard-page>
    <clr-wizard-page>
        ...
    </clr-wizard-page>
</clr-wizard>
```

Hi, the code & examples for Wizard with Asynchronous Completion
The html code seems just the same with code in Wizard with Asynchronous Validation section.
Am I misunderstood on this?

**Comment by mathisscott** [comment] 2017-06-01 00:58
I see what you are saying now, @ThinkontrolSY

The issue is that the HTML in the demo hasn't been updated.

Until we can make that update to the website, you can see a working example here. 

https://github.com/vmware/clarity/blob/new-website/src/app/documentation/demos/wizard/wizard-async-completion.demo.html

**Comment by mathisscott** [comment] 2017-06-01 01:00
@adityarb88 
Could you move this into the backlog with an estimate of 1?

All that needs to be done is the demo needs to be updated with the HTML I referenced. 

The HTML example is wrong.

**Comment by adityarb88** [comment] 2017-06-01 14:57
This should be fixed now.

**Closed** 2017-06-01 14:57 UTC
Labels: bug, WEB
