### ISSUE TITLE
[Bug] Selection (clrDgSelected ) gets cleared after pagination

### ISSUE THREAD

**Issue by MRMokwa** [vmware/clarity#646] opened 2017-03-23 18:09 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Keep the selected itens after changing the page in the datagrid.

### Actual behavior
After changing the page of datagrid, the selected itens are cleared.

### Reproduction of behavior
This can be reproduced in the documentation of the datagrid with the Full Datagrid demo.
https://vmware.github.io/clarity/documentation/datagrid

### Environment details

* **Clarity version:** Latest

**Comment by youdz** [comment] 2017-03-23 18:34
Duplicate of #484.

**Closed by youdz** 2017-03-23 18:34 UTC
