### ISSUE TITLE
Allow Date Picker to behave more like a input type date

### ISSUE THREAD

**Issue by mxab** [vmware/clarity#4348] opened 2020-03-07 14:09 UTC
## Summary

The desktop version of the datepicker with`type="date"` changes the type to text and therefore writing the "formatted" value into the form control.
```
{
  "date": "03/14/2020"
}
```

Even though this behaviour is documented in the examples, this is highly confusing since the expected format of type="date" input value is yyyy-mm-dd

This issue makes it even more complicated as the behaviour is inconsistent when using the datepicker with a mobile browser, where the native type="date" is used and therefore the value in the form control is:

```
{
  "date": "2020-03-14"
}
```

This forces the developer todo special device handling.

## Use case

Further the formatted date behaviour makes it hard to implement a simple dynamic min/max handling:

```
<clr-date-container>
          <input name="from" clrDate #from [max]="to.value" type="date" >
</clr-date-container>
<clr-date-container>
          <input name="to"  clrDate #to [min]="from.value" type="date" >
 </clr-date-container>
```
Since min/max expect the ISO8601 but the value is in the correct format this needs extra care

**Comment by gnomeontherun** [comment] 2020-03-09 16:03
This sounds like a duplicate of https://github.com/vmware/clarity/issues/2056 where depending on if you bind to ngModel or clrDate you get a different format (which was initially intentional but now seems to be buggy).

**Comment by gnomeontherun** [comment] 2021-02-26 17:40
This is also changed if you want to use the Clarity Core date control which adheres more directly to HTML spec. Closing as something we have already.

**Closed by gnomeontherun** 2021-02-26 17:40 UTC
Labels: component: date-picker
