### ISSUE TITLE
Data arrangement in datagrid is messed up using with tabs

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#1362] opened 2017-08-24 06:41 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The data in datagrid should display correctly in large screen, after switching to the second tab

### Actual behavior
The data is in a mess in datagrid in large screen after I switch to the second tab:
![screen shot 2017-08-24 at 2 36 36 pm](https://user-images.githubusercontent.com/6769465/29652822-d2d53e50-88d9-11e7-9285-250aabefc5b8.png)

### Reproduction of behavior
Working plunker: (you have to run the code in full screen mode to reproduce the bug)
https://plnkr.co/edit/s1MbZUtRhEVMxYdhPgwS

### Environment details

* **Angular version:** 4.x

* **Clarity version:** 0.10.1

* **Browser:** [ Chrome 60 ]

**Comment by youdz** [comment] 2017-08-24 13:04
When using such a heavy component like Datagrid, you should always use `*clrIfActive` on the tab content. You don't want a fully instantiated datagrid in memory just to not display it. 
Just adding `*clrIfActive` on the tab contents fixes the issue, as you can see: https://plnkr.co/edit/xcJwfTOMUQvt2YNmGHft?p=preview

You then might run into the other issue you opened (#1363) when you want to initialize displaying a different tab than the first one, but that is an actual separate bug that we are going to fix.

So I'm closing this as a duplicate of #1363.

**Comment by h657070128** [comment] 2017-08-25 06:38
Hi @youdz , thanks for your quick response. I tried the one with `*clrIfActive`, it still shows a mess, exactly the same with the one without `*clrIfActive`. Any ideas?

**Comment by youdz** [comment] 2017-08-25 12:57
My bad, there is still a bug in here. Sorry about that. I'm reopening and tagging correctly.

**Comment by gnomeontherun** [comment] 2021-01-29 15:34
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.

**Closed by gnomeontherun** 2021-01-29 15:34 UTC
Labels: component: datagrid, type: bug
