### ISSUE TITLE
Tab overflow drop-down creates a horizontal scroll

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1623] opened 2017-10-20 13:56 UTC
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tab overflow drop-down does not create a horizontal scroll.

### Actual behavior
Tab overflow drop-down creates a horizontal scroll when it is in a hidden state and has not been initialized.

### Reproduction of behavior
https://embed.plnkr.co/3rEVkZRBDvtyYmjuUrf2/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** Latest

* **OS and version:** Windows 10

* **Browser:** Chrome 61.0.3163.100

**Comment by adityarb88** [comment] 2017-10-20 16:04
@belyan: Will take a look and get back to you.

**Comment by coldhamix** [comment] 2017-10-22 16:08
It looks to me to be the same bug as #1630

**Comment by belyan** [comment] 2017-10-22 16:12
@coldhamix I agree with you.

**Comment by adityarb88** [comment] 2017-10-23 13:28
Closing this as a duplicate of #1474. Please subscribe to that issue for more updates.

**Comment by adityarb88** [comment] 2017-10-26 17:50
duplicate of #1232. Please subscribe to #1232 for more updates.

**Closed by adityarb88** 2017-10-26 17:50 UTC
Labels: !!, bug, ClarityNG, ClarityUI
