### ISSUE TITLE
Can not shrink datagrid columns on Chrome

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#1666] opened 2017-11-02 13:28 UTC
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I am creating clarity datagrid columns by iterate column definitions with *ngFor.
I expect the created clarity datagrid columns to be shrinkable.
### Actual behavior
When create clarity datagrid columns (clr-dg-column elements)  with *ngFor, they can't be shrink on Chrome.
The shrink of the datagrid columns work on FF and IE. 

### Reproduction of behavior
https://plnkr.co/edit/UGgTYUNIQMOm19pxgbXp?p=preview

### Environment details

* **Angular version:4.x.x** 

* **Clarity version:10.06**

* **OS and version: Windows** 

* **Browser:** Chrome 62.0.3202.75

**Comment by adityarb88** [comment] 2017-11-02 13:30
@dkanev: Thanks for reporting this. We will take a look and get back to you.

@Shijir: Would you mind taking a look at this.

**Comment by Shijir** [comment] 2017-11-03 17:44
This is the duplicate of https://github.com/vmware/clarity/issues/1537.

**Comment by Shijir** [comment] 2017-11-09 17:16
I've opened this issue again as it reproduces the same problem in a different way.

**Closed** 2017-11-14 17:05 UTC
Labels: !!, needs-triage, |>
