### ISSUE TITLE
CSS Import syntax is wrong on website

### ISSUE THREAD

**Issue by ad9999** [vmware/clarity#5707] opened 2021-03-09 22:02 UTC
## Describe the bug

The description provided on clarity website says you need to do / add following on your root JS file at the top

```
@import '~normalize.css/normalize.css'; // css reset
@import '~@cds/core/global.min'; // clarity global styles
@import '~@cds/core/styles/module.shims.min'; // non-evergreen browser shims
@import '~@cds/city/css/bundles/default.min'; // load base font
```

How-ever that resulted in lot of compile errors. Some of them

```
ERROR in ./src/app/index.ts
Module not found: Error: Can't resolve '~@cds/city/css/bundles/default.min' in '/Users/elonmusk/Documents/workspace/uhana_dashboard/ui/src/app'
 @ ./src/app/index.ts 5:0-44
 @ ./src/index.tsx
 @ multi webpack-dev-server/client?http://0.0.0.0:8090 ./src/index.tsx

ERROR in ./src/app/index.ts
Module not found: Error: Can't resolve '~@cds/core/global.min' in '/Users/elonmusk/Documents/workspace/uhana_dashboard/ui/src/app'
 @ ./src/app/index.ts 3:0-31
 @ ./src/index.tsx
 @ multi webpack-dev-server/client?http://0.0.0.0:8090 ./src/index.tsx

ERROR in ./src/app/index.ts
Module not found: Error: Can't resolve '~@cds/core/styles/module.shims.min' in '/Users/elonmusk/Documents/workspace/uhana_dashboard/ui/src/app'
 @ ./src/app/index.ts 4:0-44
 @ ./src/index.tsx
 @ multi webpack-dev-server/client?http://0.0.0.0:8090 ./src/index.tsx

ERROR in ./src/app/index.ts
Module not found: Error: Can't resolve '~normalize.css/normalize.css' in '/Users/elonmusk/Documents/workspace/uhana_dashboard/ui/src/app'
 @ ./src/app/index.ts 2:0-38
 @ ./src/index.tsx
 @ multi webpack-dev-server/client?http://0.0.0.0:8090 ./src/index.tsx
ℹ ｢wdm｣: Failed to compile.
```

## How to reproduce

1. 
2. 

1.  Install `cds`  package using following commands as provided through clarity website 
`npm install @cds/core @cds/city --save`
2.  Add following on top of your index.js
```
@import '~normalize.css/normalize.css'; // css reset
@import '~@cds/core/global.min'; // clarity global styles
@import '~@cds/core/styles/module.shims.min'; // non-evergreen browser shims
@import '~@cds/city/css/bundles/default.min'; // load base font
```

## Expected behavior

Code compiled successfully

## Versions

**Clarity project:**

- [ ] @cds/core@^5.0.3
- [ ] @cds/city@^1.1.0

**Framework:**
- [ ] Other:

**Device:**

- Type: [MacBook]
- OS: [ iOS]
- Browser [N/A]
- Version [N/A]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment] 2021-03-10 16:21
The import paths may depend on project configurations. When you use React like this example, you may have to reconfigure the imports depending on your tooling. The CSS import syntax is not written for JavaScript but to be used in CSS files, so that is the confusion here by using the import in the wrong place or not updating to match target syntax. Closing as working as intended and not having a clear reproduction.

**Closed as completed by gnomeontherun** 2021-03-10 16:21 UTC
Labels: status: needs reproduction
