### ISSUE TITLE
How to add suffix in when using "clrInput" label?

### ISSUE THREAD

**Issue by yandong01** [vmware/clarity#4496] opened 2020-04-22 08:35 UTC
Is there a way to add a suffix or prefix when using "clrInput"?

just like below:
<div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="Your Email">
    <div class="input-group-append">
      <span class="input-group-text">@vmware.com</span>
  </div>

I tried to add a 'span' in <clr-input-container>, but it doesn't work!

**Comment by gnomeontherun** [comment] 2020-04-27 17:40
This is a duplicate of https://github.com/vmware/clarity/issues/3778 which is being worked on currently.

Closing as duplicate.

**Closed by gnomeontherun** 2020-04-27 17:40 UTC
