### ISSUE TITLE
CSS Font Error - Showing 24px font

### ISSUE THREAD

**Issue by sandeep540** [vmware/clarity#3291] opened 2019-04-12 16:11 UTC
## Describe the bug
For some reason, when I use the css class using the clarity css

![clarity error](https://user-images.githubusercontent.com/741952/56051282-b42b2900-5d13-11e9-91e7-f5301b8b0ac5.png)

## Expected behavior
Font should be smaller - may be 12px or so

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: 7.0.3
* Node: 10
* Clarity: 1.1.2

**Device:**

* Type: Windows 10 laptop
* OS: Windows
* Browser : chrome
* Version : 73

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment] 2019-04-12 16:38
Hi @sandeep540 

I can't diagnose what's happening here based on that screenshot alone. Could you reproduce this [in one of the stackblitzes we offer](https://stackblitz.com/@clr-team)?

At a glance, it looks like some styles in your application are overriding the clarity styles. But I can't say for sure.

Thanks!

**Comment by sandeep540** [comment] 2019-04-20 16:05
Sorry for the late reply, here you go

https://stackblitz.com/edit/angular-ivtjoz

https://angular-ivtjoz.stackblitz.io/

**Comment by gnomeontherun** [comment] 2019-04-22 14:17
You have `<html>` tags in your app.component.html, which should not be there. Those belong in the index.html file only. Removing those makes the styles correct. Closing as not-an issue, but feel free to update with additional information if I missed something.

**Closed by gnomeontherun** 2019-04-22 14:17 UTC
Labels: Awaiting More Info, Needs Investigation

**Comment by sandeep540** [comment] 2019-04-22 16:54
Apologies, my bad, it fixed it
