### ISSUE TITLE
Implement single selection in DataGrid by clicking anywhere in the row and without radio button

### ISSUE THREAD

**Issue by bstoicov** [vmware/clarity#629] opened 2017-03-22 15:32 UTC
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Datagrid should allow making single selection not only with radio button on each row but by clicking anywhere in the row as well. This may be configurable, so the user  of the component can decide which works best for the specific use case. 
This is specifically requested for cases where we use master - details pattern in our views. In such use cases selecting with a radio button seems odd. For other occasions like selecting an option from a list in a wizard/dialog selection with radio button seems more natural, hence the request for supporting 2 modes of single selection. 

### Actual behavior
Currently the built in option for single selection in the Datagrid is using radio button on each row for making the selection. Clicking anywhere else in the row does not select the row. 

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.11

* **OS and version:** All

* **Browser:** All

**Comment by youdz** [comment] 2017-03-22 15:42
Duplicate of #17 and #476.

Please read the comments in issue #17 to understand the ins and outs of doing this, and the reasons why we are postponing it so far.

**Closed** 2017-03-22 15:42 UTC
Labels: ClarityNG, duplicate
