### ISSUE TITLE
Invalid ARIA markup in clr-combobox

### ISSUE THREAD

**Issue by dangrussell** [vmware/clarity#5997] opened 2021-05-25 17:25 UTC
## Describe the bug

The clr-combobox component has invalid ARIA markup https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/forms/combobox/combobox.html

Attribute "aria-multiline" is not valid for role "combobox": https://www.w3.org/TR/wai-aria-1.1/#combobox

Role of combobox should own a textbox, which could have a aria-multiline attribute, but it's not set up that way currently.

Currently causes warnings on Lighthouse and Axe validation checks.

## How to reproduce

Quick demo: https://clarity-light-theme-v5-zbb1qj.stackblitz.io

Accessibility report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fclarity-light-theme-v5-zbb1qj.stackblitz.io#accessibility

## Expected behavior

Clean accessibility audit

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
ie: Angular 12

**Device:**

- Type: PC
- OS: Windows
- Browser: Edge, Chrome
- Version: Latest

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment] 2021-06-02 14:09
@scroniser we may need to track this internally with your team

**Comment by scroniser** [comment] 2021-06-03 00:53
@Jinnie Agreed. I'll touch base with you on this.

**Comment by scroniser** [comment] 2021-06-09 20:21
Created issue within our internal reporting tool.

**Comment by hippee-lee** [comment] 2021-06-10 15:21
Thanks @scroniser - I'll close this as it has been triaged and is being tracked with the other a11y issues. 

Clarity cares deeply about accessibility, and we work with our accessibility team to identify and triage issues. We have an internal tracking system to identify and verify accessibility issues, which has captured this already. Some issues with Clarity Angular are difficult to solve without causing side effects or breaking changes, and we have to balance concerns with fixing issues and breaking changes. As we build out Clarity Core, we are able to address these root cause accessibility issues and recommend adopting the Clarity Core implementations as they become available. We are closing this issue as we have the issues tracked internally. Please follow our development and releases to see when we release relevant Clarity Core components to make this possible.

**Closed as completed by hippee-lee** 2021-06-10 15:21 UTC
Labels: type: bug, type: accessibility, @clr/angular, component: combobox
