### ISSUE TITLE
clr-tooltip component shows "info-circle" in Firefox browser. 

### ISSUE THREAD

**Issue by lf-collins** [vmware/clarity#839] opened 2017-05-04 03:11 UTC
[ ] bug
[ ] feature request
[x] enhancement

### Expected behavior
When the mouse hovers over the clr-tooltip component in all browsers, the "info-circle" won't show. 

### Actual behavior
When the mouse hovers over the clr-tooltip component in Firefox browser, then the "info-circle" will show. The "info-circle" string won't show in Chrome browser.
<img width="396" alt="screen shot 2017-05-04 at 10 41 42 am" src="https://cloud.githubusercontent.com/assets/26111301/25689352/e846bb88-30b9-11e7-82ea-1c255049968a.png">
<img width="382" alt="screen shot 2017-05-04 at 10 42 11 am" src="https://cloud.githubusercontent.com/assets/26111301/25689355/eb3aba1a-30b9-11e7-9223-623c40b52a6a.png">

### Reproduction of behavior
`<clr-tooltip [clrTooltipDirection]="'bottom-right'" [clrTooltipSize]="'lg'">
    <clr-icon shape="info-circle"></clr-icon>
    <clr-tooltip-content>
          <span>Clarity Tootip</span>
    </clr-tooltip-content>
</clr-tooltip>
`
### Environment details

Angular version:2.3.1

Clarity version:0.8.14

OS and version: mac os x, version: 10.11.6

Browser:Chrome latest | Firefox latest

**Comment by mathisscott** [comment] 2017-05-04 03:27
Hi @lf-collins 
This looks like a duplicate of https://github.com/vmware/clarity/issues/734

Closing as such.

**Closed by mathisscott** 2017-05-04 03:27 UTC
