### ISSUE TITLE
Request: Inline validation for select box

### ISSUE THREAD

**Issue by abbey24** [vmware/clarity#1753] opened 2017-12-06 23:29 UTC
**Select one ...**  (check one with "x")

[ ] bug
[x] feature request
[ ] enhancement

### Expected behavior
Clarity has inline validation for input field, which is very handy and users can quickly locate the error. Select box should have similar behavior too. When user selects the wrong item from the list or they forget to make selection, the select box show have inline validation, maybe the line become red and an error icon is shown by its side. 

### Actual behavior
No inline validation available for select box now.
Example of input field showing error inline while for select box error we can only use error alert, which takes a few seconds to locate the error.

**Comment by mathisscott** [comment] 2017-12-07 16:15
This is a duplicate of #46 – which is still in design phase.

**Closed** 2017-12-07 16:15 UTC

**Comment by abbey24** [comment] 2017-12-19 18:07
Forgot to reply earlier. Thanks Scott!
