### ISSUE TITLE
clr-icon in a non-primary button has a higher order and overlaps everything

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3638] opened 2019-07-21 05:58 UTC
## Describe the bug

An icon inside a link button sits on top of everything.

![image](https://user-images.githubusercontent.com/1977391/61587578-45d1ee80-abbf-11e9-8ead-685836327782.png)

![image](https://user-images.githubusercontent.com/1977391/61587583-5b471880-abbf-11e9-9225-51a06a95ff00.png)

It only looks okay when the button is a primary button, a danger or a success button.

![image](https://user-images.githubusercontent.com/1977391/61587626-212a4680-abc0-11e9-8a63-9ee36c0d0326.png)

![image](https://user-images.githubusercontent.com/1977391/61587628-2a1b1800-abc0-11e9-852d-42e06f7e18cb.png)

## How to reproduce

Here's a StackBlitz link:
https://stackblitz.com/edit/clarity-light-theme-v2-w4uyt4

## Expected behavior

Should have the same z-index with the link button.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment] 2019-07-22 06:24
For the primary button it's also above the popover body. It's just white on white, but can be detected by cursor change on hover.

**Comment by wendellestradairely** [comment] 2019-07-25 11:16
The transform property of the clr-icon creates a new stacking context so it overlaps the popover body. I have to set the z-index of the popover body to a positive value to correct the order of elements.

![image](https://user-images.githubusercontent.com/50942719/61870325-69bf6800-af10-11e9-8e01-8fc414172b3a.png)

**Comment by AlexMarcuBytex** [comment] 2019-09-05 11:30
@hippee-lee Hi! Are smart popover changes solving this issue? ( im referring to changes from #3374 ) Let me know if this still require investigations.

**Comment by hippee-lee** [comment] 2019-09-05 15:58
This issue is not using any Clarity popovers so the new utility isn't applicable in this context. This will still need investigation.

**Comment by AlexMarcuBytex** [comment] 2019-09-06 08:41
Oh, you re right! The popover is just for the example here. Sorry for this confusion! Im trying to figure what would be the solution here..

**Comment by hippee-lee** [comment] 2019-09-06 15:51
Hey @AlexMarcuBytex I would start with the [layers](https://github.com/vmware/clarity/blob/master/src/clr-angular/utils/_layers.clarity.scss) we already have. Looking at the demo it seems like `btn-primary, btn-success and btn-danger` classes handle the icon correctly wrt layering. I would look at what is different between those classes and the `btn-link & btn-outline` classes. 

I'm guessing here but I think the link and outline classes are missing the proper layer for clr-icon's inside them.

**Comment by AlexMarcuBytex** [comment] 2019-09-10 09:40
`btn-primary, btn-success and btn-danger ` have the same bug as `btn-link & btn-outline`. in that example those buttons are just using a white icon so you wont see that something is wrong with the layers. The problem is clearly caused by the transform property as @wendellestradairely presented above. I think that if you want to solve this, you must get rid of the transform. I see this is used to center the icon together with the text inside the button. Maybe we can find another solution to make it look like it should.

**Comment by gnomeontherun** [comment] 2019-09-11 22:09
A transform causes an element to play by 3d rules, and doesn't play by the flat rules properly causing stacking issues here. We're basically nudging the icon up 2px (.083333rem) to align it more nicely. The line-height of button text and icon sizes are off by 4px, so we push up. 

It might be ok to use `margin-top: -0.0833333rem` instead of the transform, but we really need to validate this across the demos carefully.

**Comment by gnomeontherun** [comment] 2021-02-01 21:41
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

**Closed by gnomeontherun** 2021-02-01 21:41 UTC
Labels: Dev, status: needs triage, type: bug
